Repository Chia-Network/chia-blockchain, pull requests merged in 2022-09, with the labels that each got.

#13271 checkpoint: into main from release/1.6.0 @ 8051a91fa2e9ad944289f0fee9e4c8997bb380ec
  tests/core/data_layer/config.py
Labels: ready_to_merge

#13253 treehash optimization for DID wallet
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/did_wallet/did_wallet_puzzles.py
Labels: ready_to_merge

#13301 Puzzle solution benchmark
  tests/core/large_block.py
  tests/core/test_cost_calculation.py
Labels: ready_to_merge

#13236 tighten the expected timing for the offer parsing benchmark
  tests/wallet/test_offer_parsing_performance.py
Labels: ready_to_merge

#13229 minor fixes for Serialized program
  chia/full_node/mempool_check_conditions.py
  chia/types/blockchain_format/program.py
  chia/wallet/puzzles/rom_bootstrap_generator.py
  mypy.ini
Labels: ready_to_merge

#13195 Fix small bug in commands refactor & move all imports
  chia/cmds/cmds_util.py
  chia/cmds/farm_funcs.py
  chia/cmds/plotnft.py
  chia/cmds/wallet.py
Labels: ready_to_merge, 1.6.0

#12925 fix flakey test
  tests/core/full_node/full_sync/test_full_sync.py
Labels: ready_to_merge

#13314 Ms.mempool simplify
  benchmarks/mempool.py
  chia/clvm/spend_sim.py
  chia/full_node/full_node.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/full_node/pending_tx_cache.py
  chia/types/mempool_item.py
  mypy.ini
  tests/core/full_node/test_mempool.py
  tests/wallet/test_wallet_retry.py
Labels: ready_to_merge

#13332 Fix bug in remove_plot_directory
  chia/plotting/util.py
Labels: ready_to_merge

#13196 Remove "Total iterations since start" from chia show -s
  chia/cmds/show_funcs.py
Labels: ready_to_merge

#13315 use get_puzzle_and_solution_for_coin() from chia_rs
  chia/clvm/spend_sim.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool_check_conditions.py
  setup.py
  tests/core/test_cost_calculation.py
Labels: ready_to_merge

#13347 The poor CI machine cannot go fast enough
  tests/core/data_layer/test_data_rpc.py
  tests/wallet/test_wallet.py
Labels: ready_to_merge

#13366 Fix test race condition with reorged txs
  tests/pools/test_pool_rpc.py
Labels: ready_to_merge

#13320 Ms.mypy enable
  benchmarks/block_ref.py
  benchmarks/block_store.py
  benchmarks/coin_store.py
  chia/consensus/blockchain.py
  chia/data_layer/data_layer_api.py
  chia/full_node/block_height_map.py
  chia/full_node/block_store.py
  chia/full_node/bundle_tools.py
  chia/full_node/coin_store.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/full_node_store.py
  chia/full_node/generator.py
  chia/full_node/hint_store.py
  chia/full_node/lock_queue.py
  chia/full_node/mempool_manager.py
  chia/full_node/sync_store.py
  chia/full_node/weight_proof.py
  chia/rpc/full_node_rpc_api.py
  chia/seeder/crawler.py
  chia/seeder/crawler_api.py
  chia/server/node_discovery.py
  chia/server/ws_connection.py
  chia/simulator/full_node_simulator.py
  chia/util/api_decorators.py
  chia/util/cached_bls.py
  chia/util/lru_cache.py
  chia/util/streamable.py
  chia/wallet/util/peer_request_cache.py
  chia/wallet/wallet_state_manager.py
  chia/wallet/wallet_sync_store.py
  mypy.ini
  tests/core/full_node/ram_db.py
  tests/core/full_node/stores/test_block_store.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/stores/test_hint_store.py
  tests/core/full_node/test_mempool.py
  tests/core/test_db_conversion.py
  tests/core/test_db_validation.py
  tests/util/blockchain.py
  tests/util/test_network_protocol_files.py
  tests/wallet/test_wallet.py
Labels: ready_to_merge

#13070 github: Drop incorrect/leftover statement in `test.yml`
  .github/workflows/test.yml
Labels: ready_to_merge

#13238 fix run_block
  tools/run_block.py
Labels: ready_to_merge

#13386 reduce log noise
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge

#13390 Update test_nft_wallet.py
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: ready_to_merge

#13385 Wait for sync after making wallet
  tests/pools/test_pool_rpc.py
Labels: ready_to_merge

#13387 ensure coin is a valid DID coin before adding it, otherwise skip
  chia/wallet/did_wallet/did_wallet.py
Labels: ready_to_merge

#13432 pools: Add default for `PoolWallet._update_pool_config_after_sync_task`
  chia/pools/pool_wallet.py
Labels: 1.6.0

#12389 cmds: Implement `chia beta`
  chia/cmds/beta.py
  chia/cmds/beta_funcs.py
  chia/cmds/chia.py
  chia/cmds/start.py
  chia/cmds/stop.py
  chia/daemon/server.py
  chia/plotters/bladebit.py
  chia/plotters/madmax.py
  chia/plotters/plotters_util.py
  chia/seeder/start_crawler.py
  chia/server/start_farmer.py
  chia/server/start_full_node.py
  chia/server/start_harvester.py
  chia/server/start_introducer.py
  chia/server/start_timelord.py
  chia/server/start_wallet.py
  chia/util/chia_logging.py
  chia/util/errors.py
  chia/util/initial-config.yaml
  chia/util/misc.py
  tests/core/cmds/test_beta.py
  tests/util/test_misc.py
Labels: ready_to_merge

#13430 Lots of blocks are being synced, extend the timeouts
  tests/wallet/sync/test_wallet_sync.py
Labels: ready_to_merge

#13405 run expensive API requests in separate thread
  chia/full_node/full_node_api.py
  setup.py
Labels: ready_to_merge

#12672 util: Introduce `FileKeyringContent`
  chia/util/dump_keyring.py
  chia/util/file_keyring.py
Labels: ready_to_merge

#13298 Add `running_services` command to list all running services
  chia/daemon/server.py
  tests/core/daemon/test_daemon.py
Labels: ready_to_merge

#12491 daemon: Implement system metrics logger based on beta config
  chia/cmds/beta.py
  chia/cmds/beta_funcs.py
  chia/daemon/server.py
  chia/util/beta_metrics.py
  setup.py
  tests/core/cmds/test_beta.py
Labels: ready_to_merge

#13437 make a WalletProtocol, defining the shared API of all wallets
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_protocol.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge

#13461 util: Remove the assigned label if a key gets removed
  chia/util/keychain.py
  tests/core/util/test_keychain.py
Labels: ready_to_merge

#11701 zstd==1.5.2.6 for wheels on PyPI
  setup.py
Labels: ready_to_merge

#13399 Heap profiler
  chia/full_node/full_node.py
  chia/util/initial-config.yaml
  chia/util/memory_profiler.py
  chia/util/task_timing.py
  chia/wallet/wallet_node.py
Labels: ready_to_merge

#13426 pools: Make `PoolWallet` a `dataclass`
  chia/pools/pool_wallet.py
  tests/pools/test_pool_wallet.py
Labels: ready_to_merge

#13445 plotters: Only produce beta logs if `beta: true`, not if it just exists
  chia/plotters/plotters_util.py
Labels: ready_to_merge

#13447 cmds: Remove the beta program link from the warning
  chia/cmds/beta_funcs.py
Labels: ready_to_merge

#13463 plot_sync: Change log level to `INFO` in `Receiver.reset`
  chia/plot_sync/receiver.py
Labels: ready_to_merge

#13476 Suppress debug log
  chia/plotting/create_plots.py
Labels: ready_to_merge

#13261 On chain wallet notifications
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/util/initial-config.yaml
  chia/wallet/notification_manager.py
  chia/wallet/notification_store.py
  chia/wallet/puzzles/notification.clvm
  chia/wallet/puzzles/notification.clvm.hex
  chia/wallet/puzzles/notification.clvm.hex.sha256tree
  chia/wallet/util/compute_memos.py
  chia/wallet/util/notifications.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_notifications.py
Labels: ready_to_merge

#12604 handle errors during shutdown
  chia/daemon/server.py
  chia/wallet/wallet_node.py
Labels: ready_to_merge

#13442 remove --enable-data-server from chia configure cli
  chia/cmds/configure.py
Labels: CLI, data

#13481 Add __tracebackhide__ to time_out_assert_not_none()
  chia/simulator/time_out_assert.py
Labels: PR

#13487 mypy: Fix some `asyncio.Task` related ignores
  chia/plot_sync/sender.py
  chia/rpc/rpc_server.py
  chia/util/beta_metrics.py
Labels: ready_to_merge, PR

#13501 Changing conditional of start-release
  .github/workflows/start-release.yml
Labels: ready_to_merge, PR

#13505 increase datalayer test timeout to 40 minutes
  tests/core/data_layer/config.py
Labels: ready_to_merge, PR, data

#13506 increase mempool wait timeout for test_data_rpc::test_get_owned_stores
  tests/core/data_layer/test_data_rpc.py
Labels: PR

#11187 Cmj.bladebit
  chia/daemon/server.py
  chia/plotters/bladebit.py
  chia/plotters/madmax.py
  chia/plotters/plotters.py
  chia/plotters/plotters_util.py
Labels: ready_to_merge

#13306 Add root hash to CLI.
  chia/cmds/data.py
  chia/cmds/data_funcs.py
  chia/data_layer/data_layer.py
  chia/rpc/data_layer_rpc_api.py
  chia/rpc/data_layer_rpc_client.py
Labels: data

#13493 Update 1.6.0 Modified changelog section to Changed for consistency
  CHANGELOG.md
Labels: PR

#13495 Remove unreleased section from changelog
  CHANGELOG.md
Labels: PR

#13526 Added support for `--no-t1-direct` and `--no-t2-direct`
  chia/daemon/server.py
  chia/plotters/bladebit.py
  chia/plotters/plotters.py
Labels: ready_to_merge

#11837 Refactor away from post init for UPnP
  chia/data_layer/data_layer_server.py
  chia/server/start_service.py
  chia/server/upnp.py
Labels: stale-pr

#13478 only compile clvm for developers
  .pre-commit-config.yaml
  chia/clvm/singleton.py
  chia/full_node/generator.py
  chia/pools/pool_puzzles.py
  chia/wallet/db_wallet/db_wallet_puzzles.py
  chia/wallet/did_wallet/did_wallet_puzzles.py
  chia/wallet/nft_wallet/metadata_outer_puzzle.py
  chia/wallet/nft_wallet/nft_info.py
  chia/wallet/nft_wallet/nft_puzzles.py
  chia/wallet/nft_wallet/ownership_outer_puzzle.py
  chia/wallet/nft_wallet/transfer_program_puzzle.py
  chia/wallet/nft_wallet/uncurry_nft.py
  chia/wallet/puzzles/cat_loader.py
  chia/wallet/puzzles/load_clvm.py
  chia/wallet/puzzles/p2_conditions.py
  chia/wallet/puzzles/p2_delegated_conditions.py
  chia/wallet/puzzles/p2_delegated_puzzle.py
  chia/wallet/puzzles/p2_delegated_puzzle_or_hidden_puzzle.py
  chia/wallet/puzzles/p2_m_of_n_delegate_direct.py
  chia/wallet/puzzles/p2_puzzle_hash.py
  chia/wallet/puzzles/singleton_top_layer.py
  chia/wallet/puzzles/singleton_top_layer_v1_1.py
  chia/wallet/puzzles/tails.py
  chia/wallet/trade_manager.py
  chia/wallet/trading/offer.py
  chia/wallet/util/puzzle_compression.py
  tools/manage_clvm.py
Labels: ready_to_merge, PR

#13491 Add Signing message APIs
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/test_wallet.py
Labels: PR

#13376 Recompress generators
  tools/analyze-chain.py
Labels: ready_to_merge

#13564 format path properly depending on os in simulator block-tools
  chia/simulator/block_tools.py
Labels: ready_to_merge

#13508 harvester: Some log updates
  chia/harvester/harvester.py
  chia/harvester/harvester_api.py
  chia/plotting/cache.py
  chia/plotting/manager.py
Labels: harvester, PR

#13554 minor comment typo, hinting, and fixture cleanup
  chia/full_node/mempool_manager.py
  tests/conftest.py
Labels: PR

#13458 Better proof to singleton mapping
  chia/data_layer/data_layer_wallet.py
  tests/core/data_layer/test_data_rpc.py
  tests/wallet/db_wallet/test_dl_offers.py
Labels: PR, data

#13468 add a transactional reader as `DBWrapper2.reader()`
  chia/util/db_wrapper.py
  tests/db/test_db_wrapper.py
Labels: PR

#13513 server: Drop some `ChiaServer` attributes
  chia/server/server.py
Labels: PR

#13535 add test_miniupnpc_imports_successfully()
  tests/core/server/test_upnp.py
Labels: PR

#13515 util|rpc: Refactor `RpcEnvironment` -> `WebServer`
  chia/rpc/rpc_server.py
  chia/util/network.py
  tests/wallet/nft_wallet/test_nft_bulk_mint.py
Labels: PR

#13542 more explicit and complete handling of api decorator data
  chia/server/server.py
  chia/server/ws_connection.py
  chia/util/api_decorators.py
Labels: PR

#13551 Fixed a crash that happens when plot directory config is empty
  chia/plotting/util.py
Labels: PR

#13569 util: Set log levels per handler / Fix the log level in beta mode
  chia/util/chia_logging.py
Labels: PR

#13570 minimal fixup for daemon signal handling regression
  chia/daemon/server.py
Labels: PR
