Repository Chia-Network/chia-blockchain, pull requests merged in 2022-08, with the labels that each got.

#12704 make flake8 5 happy
  chia/cmds/passphrase.py
Labels: ready_to_merge

#12654 move wallet functions to cmds_util.py for further refactoring
  chia/cmds/cmds_util.py
  chia/cmds/plotnft.py
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
Labels: ready_to_merge

#12711 Replace NFT_HRP and DID_HRP with AddressType
  chia/rpc/wallet_rpc_api.py
  chia/wallet/did_wallet/did_info.py
  chia/wallet/nft_wallet/nft_info.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge

#12690 Mark workspace safe in pre-commit workflow
  .github/workflows/pre-commit.yml
Labels: ready_to_merge

#12581 Fix NFT > CAT Royalty splitting bug.
  chia/cmds/wallet_funcs.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
  chia/wallet/trading/offer.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
Labels: ready_to_merge

#12563 remove soft fork logic at height 2300000
  chia/consensus/block_body_validation.py
  chia/consensus/blockchain.py
  chia/consensus/constants.py
  chia/consensus/default_constants.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
  chia/full_node/mempool_check_conditions.py
  tests/blockchain/test_blockchain.py
  tests/blockchain/test_blockchain_transactions.py
  tests/conftest.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/test_mempool.py
  tests/core/test_cost_calculation.py
  tests/generator/test_rom.py
  tests/util/generator_tools_testing.py
  tools/run_block.py
  tools/test_full_sync.py
Labels: ready_to_merge

#12462 Set a minimum for initial_num_public_keys and change the default, to …
  chia/util/initial-config.yaml
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge

#12590 remove redundant tuple conversions
  chia/full_node/block_store.py
  tests/core/full_node/stores/test_block_store.py
Labels: ready_to_merge

#12682 Add small coin selection improvements
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/coin_selection.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/wallet.py
  tests/wallet/test_coin_selection.py
Labels: ready_to_merge

#12684 Update test with pytest.raises
  tests/wallet/cat_wallet/test_cat_outer_puzzle.py
Labels: ready_to_merge

#12727 Fixed `mint_nft`
  chia/rpc/wallet_rpc_client.py
Labels: ready_to_merge

#12741 optimize get_coins_to_check()
  chia/wallet/wallet_coin_store.py
  chia/wallet/wallet_node.py
  tests/wallet/test_wallet_coin_store.py
Labels: ready_to_merge

#12742 parse the puzzle reveal once, instead of 3 times
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge

#12745 Increase timeouts to reduce flakiness
  tests/core/full_node/test_performance.py
  tests/core/full_node/test_transactions.py
  tests/plot_sync/test_plot_sync.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_wallet.py
Labels: ready_to_merge

#12761 Fix more flaky tests, and optimize `test_pool_rpc` and NFT tests (signed)
  chia/timelord/timelord_launcher.py
  chia/wallet/wallet_blockchain.py
  tests/conftest.py
  tests/core/full_node/test_full_node.py
  tests/pools/test_pool_rpc.py
  tests/setup_services.py
  tests/util/wallet_is_synced.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_retry.py
Labels: ready_to_merge

#12541 util: Unify lockfile handling
  chia/daemon/server.py
  chia/server/start_service.py
  chia/util/config.py
  chia/util/dump_keyring.py
  chia/util/file_keyring.py
  chia/util/lock.py
  chia/wallet/puzzles/load_clvm.py
  setup.py
  tests/core/util/test_file_keyring_synchronization.py
  tests/core/util/test_lockfile.py
  tests/setup_services.py
  tests/simulation/test_start_simulator.py
Labels: ready_to_merge

#12661 harvester: Log the plot refresh parameter on start
  chia/harvester/harvester.py
Labels: ready_to_merge

#12737 log blockchain database file used along with schema version on startup
  chia/full_node/full_node.py
Labels: ready_to_merge

#12427 Add bulk cancel API
  chia/rpc/wallet_rpc_api.py
  chia/wallet/trade_manager.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
Labels: ready_to_merge, 1.5.1

#12691 rename testnet constants to default constants, because they are the base for all networks
  chia/consensus/default_constants.py
Labels: ready_to_merge

#12666 show which processes get closed on daemon termination
  chia/cmds/stop.py
  chia/daemon/server.py
Labels: ready_to_merge

#12782 Fix no keys loaded error by making KeychainProxy automatically reconnect when a connection is lost
  chia/daemon/client.py
  chia/daemon/keychain_proxy.py
  chia/plotting/create_plots.py
  chia/simulator/block_tools.py
  chia/util/keychain.py
  mypy.ini
Labels: ready_to_merge

#12683 New test files with CAT2 coins
  tests/tools/1315537.json
  tests/tools/1315544.json
  tests/tools/1315630.json
  tests/tools/149988.json
  tests/tools/392111.json
  tests/tools/396963.json
  tests/tools/test_run_block.py
Labels: ready_to_merge

#12781 uncurry the puzzle once instead of 3 times
  chia/rpc/wallet_rpc_api.py
  chia/wallet/cat_wallet/cat_outer_puzzle.py
  chia/wallet/cat_wallet/cat_utils.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/did_wallet/did_wallet_puzzles.py
  chia/wallet/nft_wallet/nft_puzzles.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/nft_wallet/uncurry_nft.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/nft_wallet/test_nft_puzzles.py
  tools/run_block.py
Labels: ready_to_merge

#12703 Simulator Final touches
  chia/full_node/full_node.py
  chia/rpc/full_node_rpc_api.py
  chia/simulator/block_tools.py
  chia/simulator/full_node_simulator.py
  chia/simulator/simulator_full_node_rpc_api.py
  chia/simulator/simulator_full_node_rpc_client.py
  chia/simulator/simulator_protocol.py
  chia/simulator/start_simulator.py
  chia/util/initial-config.yaml
  chia/wallet/wallet_node_api.py
  chia/wallet/wallet_state_manager.py
  tests/core/test_full_node_rpc.py
  tests/pools/test_pool_rpc.py
  tests/simulation/test_simulation.py
  tests/simulation/test_start_simulator.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tests/wallet/test_wallet.py
Labels: ready_to_merge

#12756 util: Move all keychain related errors into `chia.util.error`
  chia/cmds/chia.py
  chia/cmds/start_funcs.py
  chia/daemon/keychain_proxy.py
  chia/daemon/server.py
  chia/farmer/farmer.py
  chia/rpc/wallet_rpc_api.py
  chia/util/errors.py
  chia/util/keychain.py
  chia/util/keyring_wrapper.py
  chia/wallet/wallet_node.py
Labels: ready_to_merge

#12797 Fixed a CI issue where it tried to remove a win cert file which does not exist
  .github/workflows/build-windows-installer.yml
Labels: ready_to_merge

#12665 Nft reorg
  chia/rpc/wallet_rpc_api.py
  chia/wallet/nft_wallet/nft_info.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet_nft_store.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/test_nft_store.py
Labels: ready_to_merge, 1.5.1

#12779 Remove unused ping/pong code
  chia/rpc/rpc_server.py
  tests/core/daemon/test_daemon.py
Labels: ready_to_merge

#12759 Move simulator tests over to new file, to allow other programs to use it
  chia/simulator/simulator_test_tools.py
  tests/simulation/test_start_simulator.py
Labels: ready_to_merge, 1.5.1

#12783 No network type
  chia/consensus/constants.py
  chia/consensus/default_constants.py
  chia/consensus/network_type.py
  chia/farmer/farmer_api.py
  chia/simulator/block_tools.py
  chia/util/initial-config.yaml
  tests/conftest.py
  tests/tools/test_run_block.py
Labels: ready_to_merge

#12808 fix ci
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: ready_to_merge

#12768 rpc: Improve RPC server start/stop
  chia/rpc/rpc_server.py
  chia/server/start_service.py
  tests/core/test_farmer_harvester_rpc.py
  tests/core/test_full_node_rpc.py
  tests/pools/test_pool_rpc.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge

#12748 util: Drop partially implemented BIP39 passphrase support
  chia/cmds/keys_funcs.py
  chia/daemon/keychain_proxy.py
  chia/daemon/keychain_server.py
  chia/rpc/wallet_rpc_api.py
  chia/simulator/block_tools.py
  chia/simulator/simulator_test_tools.py
  chia/util/keychain.py
  tests/core/cmds/test_keys.py
  tests/core/daemon/test_daemon.py
  tests/core/util/test_keychain.py
  tests/farmer_harvester/test_farmer_harvester.py
  tests/setup_services.py
  tests/util/bip39_test_vectors.json
  tests/wallet/test_wallet_node.py
Labels: ready_to_merge

#12818 fix a few instances of coin name logging
  chia/pools/pool_wallet.py
  chia/wallet/cat_wallet/cat_wallet.py
Labels: ready_to_merge

#12817 Fix a migration bug of NFT table change
  chia/wallet/wallet_nft_store.py
Labels: 1.5.1

#12801 util: Force keyring migration / Deprecate legacy keyring support
  chia/cmds/chia.py
  chia/cmds/keys.py
  chia/cmds/keys_funcs.py
  chia/cmds/passphrase.py
  chia/cmds/start.py
  chia/cmds/wallet.py
  chia/daemon/server.py
  chia/util/keychain.py
  chia/util/keyring_wrapper.py
  tests/core/cmds/test_keys.py
Labels: 1.5.1

#12769 tests: Drop redundant `RpcServer` instances
  tests/conftest.py
  tests/core/test_farmer_harvester_rpc.py
  tests/core/test_full_node_rpc.py
  tests/pools/test_pool_rpc.py
  tests/setup_nodes.py
  tests/setup_services.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge

#12847 increased timeouts for less NFT test flakiness
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: ready_to_merge

#12735 Swap intel installer to 10.14 runners
  .github/workflows/build-macos-installer.yml
  build_scripts/npm_macos/package-lock.json
  build_scripts/npm_macos/package.json
  build_scripts/npm_macos_m1/package-lock.json
  build_scripts/npm_macos_m1/package.json
Labels: ready_to_merge

#12864 Update the arm64 deb installer to also use the 1804 builder container
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
Labels: ready_to_merge

#12702 Few additional sets of test SSL certs/keys for CI
  chia/simulator/block_tools.py
  chia/simulator/simulator_test_tools.py
  chia/simulator/ssl_certs.py
  chia/simulator/ssl_certs_10.py
  chia/simulator/ssl_certs_8.py
  chia/simulator/ssl_certs_9.py
Labels: ready_to_merge

#12750 util: Simplify key deletion in `Keychain`
  chia/util/keychain.py
Labels: ready_to_merge

#12775 pre-commit: Reorder hooks by runtime
  .pre-commit-config.yaml
Labels: ready_to_merge

#12822 pre-commit: Fix a venv activation issue on linux
  activated.py
  activated.sh
Labels: ready_to_merge

#12812 Adding Chia-Network/required-reviewers as CODEOWNERS
  .github/CODEOWNERS
Labels: ready_to_merge

#12780 add benchmark for MempoolManager.add_spendbundle
  benchmarks/mempool.py
  chia/full_node/mempool_manager.py
Labels: ready_to_merge

#12751 util: Simplify public key getters in `Keychain`
  chia/util/keychain.py
Labels: ready_to_merge

#12747 util: Raise in `Keychain.add_private_key` if the key already exists
  chia/cmds/keys_funcs.py
  chia/util/errors.py
  chia/util/keychain.py
  tests/core/daemon/test_daemon.py
  tests/core/util/test_keychain.py
Labels: ready_to_merge

#12310 wallet code reuse
  chia/full_node/weight_proof.py
  chia/wallet/util/peer_request_cache.py
  chia/wallet/wallet_blockchain.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
  chia/wallet/wallet_weight_proof_handler.py
  tests/wallet/test_wallet_blockchain.py
Labels: ready_to_merge

#12862 server|tests: Delay the harvester -> farmer connection in some tests
  chia/server/start_harvester.py
  chia/server/start_service.py
  tests/farmer_harvester/test_farmer_harvester.py
  tests/plot_sync/test_plot_sync.py
  tests/plot_sync/test_sync_simulated.py
  tests/plot_sync/util.py
  tests/setup_nodes.py
  tests/setup_services.py
Labels: ready_to_merge

#12877 Early return from olivernyc
  chia/wallet/wallet_node.py
Labels: ready_to_merge

#12357 cmds: Drop unused `chia_minor_release_number`
  chia/cmds/init_funcs.py
Labels: ready_to_merge

#12771 Add REMARK to `ConditionOpcodes`
  chia/types/condition_opcodes.py
Labels: ready_to_merge

#12890 Combine m1 and intel mac installers to a single workflow
  .github/workflows/build-macos-installer.yml
  .github/workflows/build-macos-installers.yml
  build_scripts/build_macos-2-installer.sh
  build_scripts/build_macos_m1-1-gui.sh
  build_scripts/build_macos_m1-2-installer.sh
  build_scripts/npm_macos/package-lock.json
  build_scripts/npm_macos/package.json
  build_scripts/npm_macos_m1/__init__.py
  build_scripts/npm_macos_m1/package-lock.json
  build_scripts/npm_macos_m1/package.json
Labels: ready_to_merge

#12875 Ms.wlt node unsynced
  chia/protocols/protocol_state_machine.py
  chia/wallet/util/wallet_sync_utils.py
  chia/wallet/wallet_node.py
Labels: ready_to_merge, 1.5.1

#12913 Decrease default number of public keys from 750 to 425
  chia/util/initial-config.yaml
  chia/wallet/wallet_state_manager.py
Labels: 1.5.1

#12911 cmds|daemon: Improve legacy keyring migration enforcement
  chia/cmds/keys.py
  chia/cmds/keys_funcs.py
  chia/cmds/passphrase.py
  chia/cmds/start.py
  chia/cmds/start_funcs.py
  chia/cmds/wallet.py
  chia/daemon/server.py
  chia/util/keychain.py
  chia/util/keyring_wrapper.py
  tests/core/cmds/test_keys.py
Labels: 1.5.1

#12910 return to use awaitable in WP
  chia/full_node/weight_proof.py
Labels: ready_to_merge, 1.5.1

#12904 renaming series -> editions (full deprecation)
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/wallet/nft_wallet/nft_info.py
  chia/wallet/nft_wallet/nft_puzzles.py
  chia/wallet/nft_wallet/uncurry_nft.py
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: ready_to_merge

#12901 Fix chia farm summary if using a remote full node
  chia/cmds/farm_funcs.py
Labels: ready_to_merge

#12928 Bring-in Mariano's Remove accidentally added debugging logs
  chia/wallet/util/wallet_sync_utils.py
Labels: ready_to_merge

#12798 optimize simple_solution_generator()
  chia/full_node/bundle_tools.py
Labels: ready_to_merge

#12951 add catch for 100% royalties as the offers for them are broken
  chia/rpc/wallet_rpc_api.py
Labels: ready_to_merge

#12950 Couple of small key migration changes to speed up launching
  chia/cmds/chia.py
  chia/cmds/keys_funcs.py
  chia/cmds/wallet.py
Labels: ready_to_merge

#12919 Bump chia_rs dependency
  chia/full_node/mempool_check_conditions.py
  chia/types/blockchain_format/program.py
  chia/util/streamable.py
  setup.py
Labels: ready_to_merge

#12961 no traceback for unknown wallet id request to nft_get_nfts
  chia/rpc/wallet_rpc_api.py
Labels: ready_to_merge

#12923 rust tree_hash()
  chia/types/blockchain_format/program.py
  chia/wallet/did_wallet/did_wallet_puzzles.py
  chia/wallet/puzzles/singleton_top_layer.py
  chia/wallet/trading/offer.py
Labels: ready_to_merge

#12403 plotters: Move `install_plotter` into `plotters`
  .isort.cfg
  chia/plotters/install_plotter.py
  chia/plotters/plotters.py
  mypy.ini
Labels: ready_to_merge

#12316 streamable: More custom exceptions
  chia/util/streamable.py
  tests/core/util/test_streamable.py
Labels: ready_to_merge

#12398 tests: Drop redundant `expected_state` parameter of `run_sync_step`
  tests/plot_sync/test_receiver.py
Labels: ready_to_merge

#12990 Fix NFT wallet naming issue
  chia/rpc/wallet_rpc_api.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: 1.5.1

#12895 Update the version for flake8 in the pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: ready_to_merge

#12831 Move DB test to new directory
  tests/db/__init__.py
  tests/db/test_db_wrapper.py
Labels: ready_to_merge

#12896 Update the version of pre-commit-hooks in the pre-commit-config.yaml …
  .pre-commit-config.yaml
Labels: ready_to_merge

#12924 revert change to change OR REPLACE -> OR FAIL in wallet_coin_store
  chia/wallet/wallet_coin_store.py
  tests/wallet/test_wallet_coin_store.py
Labels: ready_to_merge

#13008 Update package for installer
  build_scripts/npm_macos/package-lock.json
  build_scripts/npm_macos/package.json
Labels: ready_to_merge

#13000 Fix the DBWrapper test
  tests/db/test_db_wrapper.py
Labels: ready_to_merge

#12850 util: Simplify `unlocks_keyring` and move it with `obtain_current_passphrase` into `cmds`
  chia/cmds/keys_funcs.py
  chia/cmds/passphrase_funcs.py
  chia/util/file_keyring.py
  chia/util/keychain.py
Labels: ready_to_merge

#12891 Change the pattern for running pre-commit. Previously, this was using…
  .github/workflows/pre-commit.yml
Labels: ready_to_merge

#12988 streamable: Fix the message of `ParameterMissingError` + Test custom error messages
  chia/util/streamable.py
  tests/core/util/test_streamable.py
Labels: ready_to_merge

#12998 cat_wallet mypy fixes
  chia/wallet/cat_wallet/cat_outer_puzzle.py
  chia/wallet/cat_wallet/cat_utils.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/cat_wallet/lineage_store.py
  chia/wallet/puzzles/tails.py
  chia/wallet/wallet_state_manager.py
  mypy.ini
  tests/clvm/test_puzzle_compression.py
  tests/wallet/cat_wallet/test_cat_lifecycle.py
  tests/wallet/cat_wallet/test_cat_outer_puzzle.py
  tests/wallet/cat_wallet/test_offer_lifecycle.py
Labels: ready_to_merge

#13007 Remove unnecessary split when starting daemon,
  chia/cmds/start_funcs.py
Labels: ready_to_merge

#13010 Allow developers to easily use standard chia clvm puzzles and libraries
  chia/wallet/puzzles/load_clvm.py
Labels: ready_to_merge

#13016 No traceback for OSError 113 in WSChiaConnection.outbound_handler()
  chia/server/ws_connection.py
Labels: ready_to_merge

#10087 Adds handling for daemon not sending `initial_target_state` (#10058)
  chia/rpc/wallet_rpc_api.py
Labels: ready_to_merge

#12810 fix slight issue with simulator loading, this only really could affect tests
  chia/simulator/start_simulator.py
Labels: ready_to_merge

#12999 enable mypy for NFT wallet
  chia/rpc/wallet_rpc_api.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trading/offer.py
  chia/wallet/util/debug_spend_bundle.py
  mypy.ini
Labels: ready_to_merge

#13029 skip validating GTElement in mempool
  chia/full_node/mempool_manager.py
  setup.py
Labels: ready_to_merge

#13015 Remove the wallet action store and adapt what depended on it
  chia/wallet/wallet_action_store.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_node_api.py
  chia/wallet/wallet_state_manager.py
  mypy.ini
Labels: ready_to_merge

#12993 cleanup keychain proxy
  chia/daemon/client.py
  chia/daemon/keychain_proxy.py
  chia/util/errors.py
Labels: ready_to_merge

#12956 configurable ci test job duplicates
  tests/build-job-matrix.py
Labels: ready_to_merge

#12926 Reduce flakiness (saw 281 in a test)
  chia/wallet/coin_selection.py
  tests/wallet/test_coin_selection.py
Labels: ready_to_merge

#12796 add delayed pool config update feature
  chia/pools/pool_wallet.py
Labels: ready_to_merge

#12934 Rust coin state
  chia/protocols/wallet_protocol.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/util/peer_request_cache.py
  chia/wallet/util/wallet_sync_utils.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
  setup.py
  tests/util/test_network_protocol_test.py
Labels: ready_to_merge

#13037 cmds: Don't `exit` in `migrate_legacy_keyring_interactive`
  chia/cmds/keys_funcs.py
  chia/util/keyring_wrapper.py
Labels: 1.5.1

#13048 build_scripts: cherry-pick dependency updates into `release/1.5.1`
  build_scripts/npm_linux_deb/package-lock.json
  build_scripts/npm_linux_deb/package.json
  build_scripts/npm_linux_rpm/package-lock.json
  build_scripts/npm_linux_rpm/package.json
  build_scripts/npm_macos/package-lock.json
  build_scripts/npm_macos/package.json
  build_scripts/npm_windows/package-lock.json
  build_scripts/npm_windows/package.json
Labels: 1.5.1

#12669 util: Some cleanups in `file_keyring.py`
  chia/util/dump_keyring.py
  chia/util/file_keyring.py
  chia/util/keyring_wrapper.py
  tests/core/util/test_keyring_wrapper.py
Labels: ready_to_merge

#12752 util: Introduce `KeyData` and `_get_pk_and_entropy` -> `_get_key_data`
  chia/util/errors.py
  chia/util/keychain.py
  tests/core/util/test_keychain.py
Labels: ready_to_merge

#13089 Disable some tests
  tests/core/test_merkle_set.py
  tests/util/test_full_block_utils.py
Labels: ready_to_merge

#12945 Generalize NFT offers
  chia/wallet/nft_wallet/nft_wallet.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
Labels: ready_to_merge

#13118 fix locking of mainthread in validate_weight_proof_inner
  chia/full_node/weight_proof.py
Labels: ready_to_merge

#13135 release/1.5.1 into main
  CHANGELOG.md
Labels: ready_to_merge

#13133 Fix several bugs with untrusted sync, and correct sync status
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/util/new_peak_queue.py
  chia/wallet/wallet_blockchain.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
  tests/core/full_node/test_mempool_performance.py
  tests/pools/test_pool_rpc.py
  tests/util/wallet_is_synced.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_blockchain.py
Labels: 1.6.0

#12778 Change all commands to use one client generator function & Add chia peer command
  chia/cmds/chia.py
  chia/cmds/cmds_util.py
  chia/cmds/farm_funcs.py
  chia/cmds/netspace_funcs.py
  chia/cmds/peer.py
  chia/cmds/peer_funcs.py
  chia/cmds/plotnft_funcs.py
  chia/cmds/show.py
  chia/cmds/show_funcs.py
  chia/cmds/wallet_funcs.py
  chia/rpc/rpc_client.py
Labels: ready_to_merge

#13154 We did not await the async function
  chia/pools/pool_wallet.py
Labels: ready_to_merge, 1.6.0

#13137 tweak output from task-profiler
  chia/util/task_timing.py
Labels: ready_to_merge

#13157 update _peak_height after committing the block to the DB
  chia/consensus/blockchain.py
Labels: 1.6.0

#13142 lookup the coin records in bulk
  chia/wallet/wallet_coin_store.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/test_wallet_coin_store.py
Labels: ready_to_merge

#13145 Revert "remove DBWrapper"
  chia/util/db_wrapper.py
  tests/util/db_connection.py
Labels: ready_to_merge

#13146 Fix comments in initial config where puzzle hash should be receive address
  chia/util/initial-config.yaml
Labels: ready_to_merge

#13129 add royalty calculation method and RPC
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/nft_wallet/nft_wallet.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge

#13159 remove all_puzzle_hashes from wallet_puzzle_store
  chia/wallet/wallet_puzzle_store.py
  tests/wallet/test_puzzle_store.py
Labels: ready_to_merge

#13144 simplify WalletStateManager.coin_added()
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge

#13185 enable mypy for a some wallet files
  chia/types/blockchain_format/coin.py
  chia/types/spend_bundle.py
  chia/wallet/trade_manager.py
  chia/wallet/trading/offer.py
  mypy.ini
Labels: ready_to_merge

#13155 remember last derivation path
  chia/wallet/wallet_puzzle_store.py
Labels: ready_to_merge

#13183 introduce a Protocol for puzzle drivers, for increased type checking
  chia/wallet/driver_protocol.py
  chia/wallet/outer_puzzles.py
Labels: ready_to_merge

#13205 don't run the get_offered_coins post-init check
  chia/wallet/trading/offer.py
Labels: ready_to_merge

#13213 fix performance issue in wallet with offers
  chia/wallet/trade_manager.py
Labels: ready_to_merge

#13204 implement a more efficient Program.uncurry()
  chia/types/blockchain_format/program.py
  tests/clvm/test_program.py
Labels: ready_to_merge

#13218 Debug get tree hash
  chia/wallet/nft_wallet/nft_puzzles.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trading/offer.py
Labels: ready_to_merge

#12883 util: Implement key label support for `Keychain` and `KeychainServer`
  chia/daemon/keychain_server.py
  chia/util/keychain.py
  tests/core/daemon/test_daemon.py
  tests/core/util/test_keychain.py
Labels: ready_to_merge

#13203 use rust parser for Program.from_bytes()
  chia/types/blockchain_format/program.py
Labels: ready_to_merge

#13212 benchmark for parsing Offer
  tests/wallet/test_offer_parsing_performance.py
Labels: ready_to_merge

#13190 Puzzle driver type annotations
  chia/wallet/cat_wallet/cat_outer_puzzle.py
  chia/wallet/nft_wallet/metadata_outer_puzzle.py
  chia/wallet/nft_wallet/ownership_outer_puzzle.py
  chia/wallet/nft_wallet/singleton_outer_puzzle.py
  chia/wallet/nft_wallet/transfer_program_puzzle.py
  chia/wallet/outer_puzzles.py
  chia/wallet/puzzle_drivers.py
  tests/wallet/cat_wallet/test_cat_outer_puzzle.py
  tests/wallet/nft_wallet/test_ownership_outer_puzzle.py
Labels: ready_to_merge

#13200 Fix missing wallet `state_changed` events
  chia/rpc/wallet_rpc_api.py
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge, 1.6.0

#13211 introduce an UncurriedPuzzle class
  chia/wallet/cat_wallet/cat_outer_puzzle.py
  chia/wallet/cat_wallet/cat_utils.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/driver_protocol.py
  chia/wallet/nft_wallet/metadata_outer_puzzle.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/nft_wallet/ownership_outer_puzzle.py
  chia/wallet/nft_wallet/singleton_outer_puzzle.py
  chia/wallet/nft_wallet/transfer_program_puzzle.py
  chia/wallet/outer_puzzles.py
  chia/wallet/puzzles/singleton_top_layer_v1_1.py
  chia/wallet/trading/offer.py
  chia/wallet/uncurried_puzzle.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/cat_wallet/test_cat_outer_puzzle.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/nft_wallet/test_nft_puzzles.py
  tests/wallet/nft_wallet/test_ownership_outer_puzzle.py
  tools/run_block.py
Labels: ready_to_merge

#13237 Implement generator_for_single_coin() in python instead of clvm
  chia/clvm/spend_sim.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool_check_conditions.py
  chia/rpc/full_node_rpc_api.py
  chia/wallet/puzzles/generator_for_single_coin.clvm
  chia/wallet/puzzles/generator_for_single_coin.clvm.hex
  chia/wallet/puzzles/generator_for_single_coin.clvm.hex.sha256tree
  chia/wallet/puzzles/generator_loader.py
  tests/clvm/test_clvm_compilation.py
  tests/core/test_cost_calculation.py
  tests/generator/test_compression.py
Labels: ready_to_merge

#13044 coin interest optimization for trade records
  chia/wallet/trade_manager.py
  chia/wallet/trading/trade_store.py
  chia/wallet/wallet_node.py
  tests/wallet/test_wallet_trade_store.py
Labels: ready_to_merge

#13156 Get minter DID for offer
  chia/rpc/wallet_rpc_api.py
  chia/wallet/nft_wallet/nft_info.py
  chia/wallet/nft_wallet/nft_puzzles.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet_nft_store.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/test_nft_store.py
Labels: ready_to_merge
