Repository Chia-Network/chia-blockchain, pull requests merged in 2022-05, with the labels that each got.

#11388 Add Windows to wheel check matrix
  .github/workflows/check_wheel_availability.yaml
Labels: ready_to_merge

#11364 farmer|rpc: Add `plot_count` to `get_pool_state` RPC endpoint
  chia/rpc/farmer_rpc_api.py
  tests/core/test_farmer_harvester_rpc.py
Labels: 1.3.5-cherrypick

#11324 Fix race condition, blockchain can change between two calls to get_peak
  chia/full_node/full_node_api.py
Labels: ready_to_merge

#11400 Update plotters installation to include an `apt update`
  chia/plotters/bladebit.py
  chia/plotters/madmax.py
Labels: ready_to_merge

#11408 test: Give `setup_farmer` and `setup_harvester` a separate chia root
  tests/core/ssl/test_ssl.py
  tests/core/test_farmer_harvester_rpc.py
  tests/farmer_harvester/test_farmer_harvester.py
  tests/plot_sync/test_plot_sync.py
  tests/setup_nodes.py
  tests/setup_services.py
Labels: 1.3.5-cherrypick

#11416 simplify merkle set
  chia/util/merkle_set.py
  tests/core/test_merkle_set.py
Labels: ready_to_merge

#11421 optimize hash_coin_list()
  .github/workflows/build-test-macos-core.yml
  .github/workflows/build-test-ubuntu-core.yml
  chia/consensus/block_creation.py
  chia/consensus/block_root_validation.py
  chia/full_node/full_node_api.py
  chia/types/blockchain_format/coin.py
  chia/wallet/util/wallet_sync_utils.py
  tests/block_tools.py
  tests/core/test_coins.py
Labels: ready_to_merge

#11414 cmds: Use the new `plot_count` of `get_pool_state` in `plotnft show`
  chia/cmds/plotnft_funcs.py
Labels: ready_to_merge

#11412 tests: Use `lock_and_load_config` in `setup_services.py`
  tests/setup_services.py
Labels: ready_to_merge

#11406 Add libgmp-dev to Bladebit installation
  chia/plotters/bladebit.py
Labels: ready_to_merge

#11393 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: ready_to_merge

#11385 Remove outdated 3.8 upgrade comment
  .github/workflows/build-windows-installer.yml
Labels: ready_to_merge

#11222 Ms.hint refactor
  .github/workflows/build-test-macos-core-full_node.yml
  .github/workflows/build-test-ubuntu-core-full_node.yml
  chia/clvm/spend_sim.py
  chia/consensus/blockchain.py
  chia/full_node/full_node.py
  chia/full_node/hint_management.py
  chia/full_node/hint_store.py
  chia/full_node/mempool_manager.py
  tests/blockchain/blockchain_test_utils.py
  tests/blockchain/test_blockchain.py
  tests/core/full_node/stores/test_hint_store.py
  tests/core/full_node/test_generator_tools.py
  tests/core/full_node/test_hint_management.py
  tests/core/test_db_conversion.py
  tests/core/test_db_validation.py
  tools/test_full_sync.py
Labels: ready_to_merge

#11148 tests: Improve `test_wallet_rpc.py`
  .isort.cfg
  chia/rpc/wallet_rpc_client.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge

#11445 flag lgtm issues in test and benchmark code
  lgtm.yml
Labels: ready_to_merge

#11468 harvester: Introduce `recursive_plot_scan`
  chia/plotting/util.py
  chia/util/initial-config.yaml
  tests/plotting/test_plot_manager.py
Labels: ready_to_merge

#11467 Use context manager for locking clvm files
  chia/util/lock.py
  chia/wallet/puzzles/load_clvm.py
Labels: ready_to_merge, example

#11432 Replace MerkleSet with the rust implementation
  chia/consensus/block_creation.py
  chia/consensus/block_root_validation.py
  chia/wallet/util/wallet_sync_utils.py
  setup.py
  tests/block_tools.py
  tests/core/test_merkle_set.py
Labels: ready_to_merge

#11453 fix some LGTM issues
  chia/wallet/wallet_node.py
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/full_node/test_mempool.py
  tests/core/test_db_conversion.py
  tests/core/util/test_db_wrapper.py
  tests/core/util/test_streamable.py
  tests/util/db_connection.py
  tests/wallet/sync/test_wallet_sync.py
  tests/weight_proof/test_weight_proof.py
  tools/test_full_sync.py
Labels: ready_to_merge

#11403 Ms.mypy consensus
  benchmarks/block_ref.py
  chia/consensus/block_body_validation.py
  chia/consensus/block_creation.py
  chia/consensus/block_header_validation.py
  chia/consensus/block_record.py
  chia/consensus/block_root_validation.py
  chia/consensus/blockchain.py
  chia/consensus/blockchain_interface.py
  chia/consensus/coinbase.py
  chia/consensus/constants.py
  chia/consensus/difficulty_adjustment.py
  chia/consensus/get_block_challenge.py
  chia/consensus/multiprocess_validation.py
  chia/consensus/pos_quality.py
  chia/consensus/vdf_info_computation.py
  chia/full_node/block_height_map.py
  mypy.ini
Labels: ready_to_merge

#11167 Resend transactions
  .github/workflows/build-test-macos-wallet.yml
  .github/workflows/build-test-ubuntu-wallet.yml
  chia/util/config.py
  chia/util/initial-config.yaml
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
  chia/wallet/wallet_transaction_store.py
  tests/block_tools.py
  tests/conftest.py
  tests/pools/test_pool_rpc.py
  tests/setup_nodes.py
  tests/wallet/test_wallet_retry.py
Labels: ready_to_merge

#10219 less except -> false
  chia/server/server.py
  chia/server/ws_connection.py
  tests/connection_utils.py
  tests/core/ssl/test_ssl.py
Labels: ready_to_merge

#11429 simplify SizedBytes and StructStream
  chia/util/byte_types.py
  chia/util/ints.py
  chia/util/struct_stream.py
  mypy.ini
  tests/core/util/test_streamable.py
  tests/util/test_struct_stream.py
Labels: ready_to_merge

#11516 Allow services to set a non-default max request body size limit
  chia/rpc/rpc_server.py
  chia/server/start_service.py
Labels: ready_to_merge

#11530 reduce the redundant computations of coin_ids in block_body_validation
  chia/consensus/block_body_validation.py
  chia/consensus/block_root_validation.py
Labels: ready_to_merge

#11527 add test for streamable -> json conversion
  .github/workflows/build-test-macos-core-util.yml
  .github/workflows/build-test-ubuntu-core-util.yml
  tests/core/util/test_jsonify.py
Labels: ready_to_merge

#9975 Coin Selection Refactor With CAT Coin Selection Refactor
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/coin_selection.py
  chia/wallet/wallet.py
  tests/pools/test_pool_rpc.py
  tests/wallet/test_coin_selection.py
Labels: ready_to_merge

#11541 hints and strict type checking for test_wallet
  chia/wallet/wallet.py
  mypy.ini
  tests/wallet/test_wallet.py
Labels: ready_to_merge

#11507 disable pytest-monitor by default
  .github/workflows/build-test-ubuntu-blockchain.yml
  .github/workflows/build-test-ubuntu-clvm.yml
  .github/workflows/build-test-ubuntu-core-cmds.yml
  .github/workflows/build-test-ubuntu-core-consensus.yml
  .github/workflows/build-test-ubuntu-core-custom_types.yml
  .github/workflows/build-test-ubuntu-core-daemon.yml
  .github/workflows/build-test-ubuntu-core-full_node-full_sync.yml
  .github/workflows/build-test-ubuntu-core-full_node-stores.yml
  .github/workflows/build-test-ubuntu-core-full_node.yml
  .github/workflows/build-test-ubuntu-core-server.yml
  .github/workflows/build-test-ubuntu-core-ssl.yml
  .github/workflows/build-test-ubuntu-core-util.yml
  .github/workflows/build-test-ubuntu-core.yml
  .github/workflows/build-test-ubuntu-farmer_harvester.yml
  .github/workflows/build-test-ubuntu-generator.yml
  .github/workflows/build-test-ubuntu-plot_sync.yml
  .github/workflows/build-test-ubuntu-plotting.yml
  .github/workflows/build-test-ubuntu-pools.yml
  .github/workflows/build-test-ubuntu-simulation.yml
  .github/workflows/build-test-ubuntu-tools.yml
  .github/workflows/build-test-ubuntu-util.yml
  .github/workflows/build-test-ubuntu-wallet-cat_wallet.yml
  .github/workflows/build-test-ubuntu-wallet-did_wallet.yml
  .github/workflows/build-test-ubuntu-wallet-rl_wallet.yml
  .github/workflows/build-test-ubuntu-wallet-rpc.yml
  .github/workflows/build-test-ubuntu-wallet-simple_sync.yml
  .github/workflows/build-test-ubuntu-wallet-sync.yml
  .github/workflows/build-test-ubuntu-wallet.yml
  .github/workflows/build-test-ubuntu-weight_proof.yml
  pytest.ini
  tests/build-workflows.py
  tests/runner_templates/build-test-ubuntu
Labels: ready_to_merge

#11552 tests: Split up and improve `test_wallet_rpc.py`
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge

#11575 Remove unneeded uint64() intermediate in CAT wallet
  chia/wallet/cat_wallet/cat_wallet.py
Labels: ready_to_merge

#11576 Fix several flaky tests
  tests/core/full_node/test_full_node.py
  tests/core/full_node/test_mempool.py
  tests/core/server/test_rate_limits.py
  tests/pools/test_pool_rpc.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_retry.py
Labels: ready_to_merge

#11597 Fix a few additional flaky tests
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/full_node/test_conditions.py
  tests/wallet/test_singleton_lifecycle.py
Labels: ready_to_merge

#11568 restore missing hints being stored as None (instead of 0-length bytes)
  chia/full_node/hint_management.py
  chia/types/blockchain_format/program.py
  chia/types/spend_bundle_conditions.py
  tests/core/full_node/test_mempool.py
  tests/generator/test_rom.py
Labels: ready_to_merge

#11567 Coin simplification
  chia/rpc/wallet_rpc_api.py
  chia/types/blockchain_format/coin.py
  chia/wallet/cat_wallet/cat_utils.py
  chia/wallet/trade_manager.py
  chia/wallet/trading/offer.py
  tests/core/custom_types/test_coin.py
Labels: ready_to_merge

#11589 add tests.util.misc.assert_maximum_duration for benchmark assertions
  tests/core/full_node/test_mempool.py
  tests/core/full_node/test_mempool_performance.py
  tests/core/full_node/test_node_load.py
  tests/core/full_node/test_performance.py
  tests/core/test_cost_calculation.py
  tests/util/misc.py
Labels: ready_to_merge

#11594 early return from _set_spent function
  chia/full_node/coin_store.py
Labels: ready_to_merge

#11582 remove redundant condition
  chia/full_node/coin_store.py
Labels: ready_to_merge

#11590 fix built-in profiler to work for mac
  chia/util/profiler.py
Labels: ready_to_merge

#11558 tests: Some adjustments in `test_offer_endpoints`
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge

#11612 async sleep and require connection reset error for DoS test
  tests/core/server/test_dos.py
Labels: ready_to_merge

#11566 log full errors when run_as_generator() throws
  chia/full_node/mempool_check_conditions.py
Labels: ready_to_merge

#11620 Skip `plot_sync_callback` if `delta` is `None`, hint `Harvester.server`
  chia/harvester/harvester.py
  chia/plot_sync/receiver.py
  chia/plot_sync/sender.py
  chia/plotting/manager.py
  tests/plot_sync/test_plot_sync.py
  tests/plot_sync/util.py
Labels: ready_to_merge

#11625 harvester: Validate the path in `add_plot_directory`
  chia/cmds/plots.py
  chia/daemon/server.py
  chia/plotters/chiapos.py
  chia/plotting/util.py
  tests/core/test_farmer_harvester_rpc.py
  tests/plot_sync/test_plot_sync.py
Labels: ready_to_merge

#10561 streamable: Cache convert functions from `dataclass_from_dict`
  chia/util/streamable.py
  tests/core/util/test_streamable.py
Labels: ready_to_merge

#11619 Generally hint with Awaitable not Coroutine
  chia/rpc/rpc_server.py
Labels: ready_to_merge

#11596 allow bigger chunks of bind variables per SQL statement
  chia/full_node/coin_store.py
  chia/util/db_wrapper.py
Labels: ready_to_merge

#11595 Clean up and Refactor "chia show" command
  chia/cmds/show.py
  chia/cmds/wallet_funcs.py
Labels: ready_to_merge

#11591 increment the dirty counter when setting height-to-hash map entries
  chia/consensus/blockchain.py
  chia/full_node/block_height_map.py
Labels: ready_to_merge

#11587 plotting|util: `plotting.cache.DiskCache` -> `util.misc.VersionedBlob`
  chia/plotting/cache.py
  chia/util/misc.py
Labels: ready_to_merge

#11569 Remove is not None and length assertion in select_coins()
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/wallet.py
Labels: ready_to_merge

#11517 log error for failed service start
  chia/rpc/rpc_server.py
Labels: ready_to_merge

#11474 farmer: Improve logging in `plot_sync.{receiver|delta}`
  chia/plot_sync/delta.py
  chia/plot_sync/receiver.py
Labels: ready_to_merge

#11415 cmds: Improve `chia farm summary`
  chia/cmds/farm_funcs.py
Labels: ready_to_merge

#11549 Optimize std_hash in coin.py
  chia/types/blockchain_format/coin.py
  chia/util/hash.py
Labels: ready_to_merge

#11513 tests: Consolidate farmer/harvester fixtures
  tests/conftest.py
  tests/core/ssl/test_ssl.py
  tests/core/test_farmer_harvester_rpc.py
  tests/farmer_harvester/test_farmer_harvester.py
  tests/plot_sync/test_plot_sync.py
  tests/plot_sync/test_sync_simulated.py
  tests/setup_nodes.py
Labels: ready_to_merge

#11629 fix jsonify bool
  chia/util/streamable.py
  tests/core/util/test_jsonify.py
Labels: ready_to_merge

#11638 tests: Avoid using `match` of `pytest.raises` together with paths
  tests/core/test_farmer_harvester_rpc.py
  tests/util/misc.py
Labels: ready_to_merge

#11645 Merge release/1.4.0's 46ebed3 into main
  chia/util/streamable.py
  tests/core/util/test_jsonify.py
Labels: checkpoint_merge

#11565 Quexington's Offer generalization bringup
  .github/workflows/build-test-macos-clvm.yml
  .github/workflows/build-test-ubuntu-clvm.yml
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/cat_wallet/cat_outer_puzzle.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/outer_puzzles.py
  chia/wallet/puzzle_drivers.py
  chia/wallet/trade_manager.py
  chia/wallet/trade_record.py
  chia/wallet/trading/offer.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
  tests/clvm/test_puzzle_drivers.py
  tests/wallet/cat_wallet/test_offer_lifecycle.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge

#9692 tests: Some renaming in plot manager tests to avoid `pytest` conflicts
  tests/plot_sync/test_plot_sync.py
  tests/plotting/test_plot_manager.py
Labels: ready_to_merge

#10300 changed column selection: table `derivation_paths`
  chia/wallet/wallet_puzzle_store.py
Labels: ready_to_merge

#11601 Show test output in benchmarks workflow
  .github/workflows/benchmarks.yml
Labels: ready_to_merge

#11630 remove big_ints list
  chia/util/streamable.py
Labels: ready_to_merge
