Repository Chia-Network/chia-blockchain, pull requests merged in 2022-12, with the labels that each got.

#13992 Skip only the item that doesn't satisfy the inclusion filter
  chia/full_node/mempool_manager.py
Labels: ready_to_merge, Fixed, Tests

#13720 Add bulk set NFT DID API
  chia/rpc/wallet_rpc_api.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: Added, 1.7.0-b1

#14042 Stop creating unecessary index in notification store
  chia/wallet/notification_store.py
Labels: Fixed

#14031 Check wheel availability on macOS 10.14
  .github/workflows/check_wheel_availability.yaml
Labels: Changed, CI

#14013 bump chia_rs version to 0.1.16
  chia/types/spend_bundle_conditions.py
  setup.py
  tests/core/full_node/test_generator_tools.py
  tests/core/full_node/test_hint_management.py
  tests/core/full_node/test_mempool.py
  tests/generator/test_rom.py
Labels: ready_to_merge, Changed, Cleanup

#13947 tools: Implement and test `tools/legacy_keyring.py`
  .github/actions/install/action.yml
  .github/workflows/benchmarks.yml
  .github/workflows/test-single.yml
  install.sh
  setup.py
  tests/build-job-matrix.py
  tests/tools/config.py
  tests/tools/test_legacy_keyring.py
  tools/legacy_keyring.py
Labels: Added

#14018 isort: Remove all `tests` exceptions and sort the related files
  .isort.cfg
  tests/blockchain/test_blockchain.py
  tests/blockchain/test_blockchain_transactions.py
  tests/build-init-files.py
  tests/clvm/benchmark_costs.py
  tests/clvm/coin_store.py
  tests/clvm/test_chialisp_deserialization.py
  tests/clvm/test_program.py
  tests/clvm/test_puzzle_compression.py
  tests/clvm/test_serialized_program.py
  tests/clvm/test_singletons.py
  tests/clvm/test_spend_sim.py
  tests/conftest.py
  tests/generator/test_compression.py
  tests/generator/test_generator_types.py
  tests/generator/test_list_to_batches.py
  tests/generator/test_rom.py
  tests/generator/test_scan.py
  tests/pools/test_pool_cmdline.py
  tests/pools/test_pool_config.py
  tests/pools/test_pool_puzzles_lifecycle.py
  tests/pools/test_pool_rpc.py
  tests/pools/test_wallet_pool_store.py
  tests/simulation/test_simulation.py
  tests/util/benchmark_cost.py
  tests/util/blockchain.py
  tests/util/build_network_protocol_files.py
  tests/util/db_connection.py
  tests/util/key_tool.py
  tests/util/network_protocol_data.py
  tests/util/test_lock_queue.py
  tests/util/test_misc.py
  tests/util/test_network.py
  tests/util/test_network_protocol_files.py
  tests/util/test_struct_stream.py
  tests/weight_proof/test_weight_proof.py
Labels: Changed, Cleanup

#14051 server: Fix invalid attribute accesses in `WSChiaConnection`
  chia/server/server.py
  chia/server/ws_connection.py
  tests/core/server/test_server.py
Labels: Fixed

#14049 also upload the `-cli` `.deb` and `.rpm` packages to GitHub releases
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
Labels: Fixed, CI

#14061 fixup test_did.test_get_info() and .test_update_metadata()
  tests/wallet/did_wallet/test_did.py
Labels: Fixed, Tests

#13887 add new, optimized tx queue
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/tx_processing_queue.py
  tests/core/full_node/test_tx_processing_queue.py
Labels: Added

#14075 fixup test_did.test_get_info() and .test_update_metadata() (#14061)
  tests/wallet/did_wallet/test_did.py
Labels: Fixed, Tests

#14073 checkpoint: into main from release/1.7.0 @ 15e657723a4fce5a754c57afc17b24d476fcbfbd
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
Labels: checkpoint_merge, Changed

#13908 fix coin selection cli decimal handling & splitting issue
  chia/cmds/coin_funcs.py
  chia/cmds/coins.py
  chia/cmds/wallet_funcs.py
Labels: Fixed

#14072 Make `--number-of-coins` required for the `chia coins split` CLI
  chia/cmds/coins.py
Labels: Fixed

#13944 fix warning log in header validation
  chia/full_node/full_node.py
Labels: ready_to_merge, Fixed

#13967 dont wait for timeout on None response
  chia/protocols/protocol_message_types.py
  chia/protocols/shared_protocol.py
  chia/server/server.py
  chia/server/ws_connection.py
  tests/core/full_node/full_sync/test_full_sync.py
Labels: Changed

#14039 server: Some adjustments related to `WSChiaConnection.close_event`
  chia/server/server.py
  chia/server/ws_connection.py
Labels: Changed, Cleanup

#14041 in profile analysis, treat GetQueuedCompletionStatus() as idle state
  chia/util/profiler.py
Labels: ready_to_merge, Changed, Tests

#14056 move mempool tests from full_node to mempool directory
  mypy.ini
  tests/conftest.py
  tests/core/full_node/test_full_node.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_fee_protocol.py
  tests/core/mempool/test_mempool_performance.py
Labels: ready_to_merge, Changed, Tests

#14045 Cleanup: Add specific error if derivation missing
  chia/wallet/wallet_state_manager.py
Labels: Changed, Cleanup

#14035 Remove redundant checks in validate_spend_bundle()
  chia/full_node/mempool_manager.py
  tests/core/mempool/test_mempool_manager.py
Labels: ready_to_merge, Changed

#14067 tests: Use the `self_hostname` fixture in more places
  tests/core/data_layer/test_data_rpc.py
  tests/simulation/test_simulation.py
  tests/wallet/db_wallet/test_dl_wallet.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_bulk_mint.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/rpc/test_dl_wallet_rpc.py
  tests/wallet/test_notifications.py
Labels: Changed, Cleanup

#14088 Type check mempool_item.py
  mypy.ini
Labels: Changed

#14090 revert delayed pool config handling (#12795, #13154)
  chia/pools/pool_wallet.py
Labels: Fixed

#14092 Ensure bladebit is always included when installers are built for mac
  .github/workflows/build-macos-installers.yml
Labels: Added, CI

#14030 Add WalletStateManager.get_wallet() to centralize wallet type checking
  chia/rpc/wallet_rpc_api.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Changed, CI

#14008 server: Move api call processing into `WSChiaConnection`
  chia/server/server.py
  chia/server/ws_connection.py
  chia/simulator/time_out_assert.py
  tests/connection_utils.py
  tests/core/full_node/test_full_node.py
  tests/core/ssl/test_ssl.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
Labels: Changed, Cleanup

#14058 add typehints to MempoolManager members
  chia/full_node/mempool_manager.py
Labels: ready_to_merge, Changed, Cleanup

#14093 handle incoming unknown capabilities
  chia/server/capabilities.py
  chia/server/ws_connection.py
  tests/core/full_node/test_full_node.py
  tests/core/server/test_capabilities.py
Labels: Fixed

#14100 fix for short option collision
  chia/cmds/wallet.py
Labels: Fixed, Cleanup

#14089 replacing transactions in the mempool is normal behavior, not a warning
  chia/full_node/mempool_manager.py
Labels: ready_to_merge, Fixed

#14059 Add Arch Linux to install-gui.sh script
  install-gui.sh
Labels: Added

#14096 remove (redundant) OR FAIL from UPDATE sql statements
  chia/full_node/block_store.py
  chia/full_node/coin_store.py
Labels: Fixed, Cleanup

#14091 checkpoint: into main from release/1.7.0 @ 998ef392d9fd4b42f36eb919c6a158c2159ac02d
  chia/cmds/coin_funcs.py
  chia/cmds/coins.py
  chia/cmds/wallet_funcs.py
Labels: checkpoint_merge, Changed

#14097 account for asyncio.wait_for returning early for timeout
  tests/core/full_node/full_sync/test_full_sync.py
Labels: Fixed, Tests

#14109 Avoid calling spend_bundle.name() twice
  benchmarks/mempool.py
  chia/clvm/spend_sim.py
Labels: ready_to_merge, Clean: caught up to main, PR, Changed, Cleanup

#13981 Opt for a function instead of the broke from inner loop pattern
  chia/full_node/mempool_manager.py
Labels: ready_to_merge, Changed, Cleanup

#14052 server: Replace `WSChiaConnection.__getattr__` with `call_api`
  chia/farmer/farmer_api.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/seeder/crawler.py
  chia/server/ws_connection.py
  chia/util/api_decorators.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/util/wallet_sync_utils.py
  chia/wallet/wallet_node.py
  tests/core/full_node/full_sync/test_full_sync.py
  tests/plot_sync/test_receiver.py
Labels: Changed, Cleanup

#14108 don't throw unnecessary exception on peer connect
  chia/cmds/peer_funcs.py
  chia/rpc/rpc_server.py
  chia/server/server.py
Labels: bug, Fixed

#14068 util: Rework `get_host_addr`
  chia/server/reconnect_task.py
  chia/server/start_service.py
  chia/simulator/setup_services.py
  chia/timelord/timelord_launcher.py
  chia/util/network.py
  tests/util/test_network.py
Labels: Changed, Cleanup

#14123 server: Drop redundant `VettedPeer.__init__`
  chia/server/introducer_peers.py
Labels: Changed, Cleanup

#14127 Fees should always be in XCH mojos units
  chia/cmds/wallet_funcs.py
Labels: Fixed, Cleanup

#14114 create_bundle_from_mempool() doesn't need to be async
  benchmarks/mempool.py
  chia/clvm/spend_sim.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool_manager.py
  chia/simulator/full_node_simulator.py
  tests/blockchain/test_blockchain_transactions.py
  tests/core/full_node/test_performance.py
Labels: Changed, Cleanup

#14132 Remove wallet coins list/split/combine options
  chia/cmds/wallet.py
Labels: Changed, Cleanup

#14129 checkpoint: into main from release/1.7.0 @ 9d423d1516f5b3900fab282db5d7d93acfa5ae72
  chia/pools/pool_wallet.py
Labels: checkpoint_merge, Changed

#14101 Return existing CAT wallet instead of raising
  chia/rpc/wallet_rpc_api.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
Labels: Fixed

#14138 checkpoint: into main from release/1.6.2 @ 618f93b4c42b176659cc74c02a4dd711adc62052
  chia/server/capabilities.py
  chia/server/ws_connection.py
  tests/core/full_node/test_full_node.py
  tests/core/server/test_capabilities.py
Labels: checkpoint_merge, Changed

#14069 server: Resolve config peers earlier
  chia/server/reconnect_task.py
  chia/server/start_farmer.py
  chia/server/start_service.py
  chia/server/start_wallet.py
Labels: Changed

#14136 Wrap `Union[IPv4Address, IPv6Address]` in the class `IPAddress`
  chia/util/network.py
  tests/util/test_network.py
Labels: Changed, Cleanup

#14153 checkpoint: into main from release/1.6.2 @ 81965c6dd57944294bb030e95f59ee0c8c9e94c4
  chia/cmds/wallet.py
Labels: checkpoint_merge, Changed

#14161 server: Resolve peers in harvester and timelord startup also
  chia/server/start_harvester.py
  chia/server/start_timelord.py
Labels: Fixed

#14111 Rename confusing variables. 'c_id' suggests coin IDs, but these values are actually SpendBundle IDs.
  chia/full_node/mempool_manager.py
Labels: Clean: caught up to main, PR, Changed, Cleanup

#14169 checkpoint: into main from release/1.6.2 @ 29590b86a5d41b5ea6da0f45f4b80bceb916e7b9
  chia/cmds/coin_funcs.py
  chia/cmds/coins.py
Labels: checkpoint_merge, Changed

#14166 types: `PeerInfo` doesn't need to be streamable
  chia/types/peer_info.py
Labels: Changed, Cleanup

#14171 checkpoint: into main from release/1.6.2 @ 69501ae22a2aeddc705633b9997a909971799f8a
  chia/cmds/wallet_funcs.py
Labels: checkpoint_merge, Changed

#14173 Create logger object in module instead of passing it in
  chia/full_node/bitcoin_fee_estimator.py
  chia/full_node/fee_tracker.py
  chia/full_node/mempool.py
  tests/core/mempool/test_mempool_fee_estimator.py
  tests/fee_estimation/test_fee_estimation_unit_tests.py
Labels: PR, Changed, Cleanup

#14168 Rename Mempool.removals, which is actually a map from coin_id to a list of SpendBundleIDs
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
Labels: Clean: caught up to main, PR, Changed, Cleanup

#14174 Don't rely on noticing self.limit_factor, instead do the block limit calculation once.
  chia/full_node/mempool_manager.py
Labels: bug, ready_to_merge, Clean: caught up to main, PR, Fixed

#14180 reorder gui install command instructions in install.sh/ps1
  Install.ps1
  install.sh
Labels: Fixed, Cleanup

#14181 bump default bladebit version to 2.0.1 in install-plotter.sh
  install-plotter.sh
Labels: ready_to_merge, Fixed

#14179 checkpoint: into main from release/1.6.2 @ 30b9173eb205db5476b72bba8ef61dd2c3d34645
  chia/cmds/wallet.py
Labels: checkpoint_merge, Changed

#11535 Block and transaction processing helpers
  chia/simulator/full_node_simulator.py
  setup.py
  tests/conftest.py
  tests/core/data_layer/test_data_rpc.py
  tests/simulation/test_simulation.py
  tests/simulation/test_simulator.py
  tests/wallet/db_wallet/test_dl_wallet.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/test_wallet.py
Labels: Changed, Tests

#13995 TechDebt: add get_name to WalletProtocol
  chia/cmds/wallet_funcs.py
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_protocol.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: tech-debt, Changed, Cleanup

#14197 hint RpcClient.create() return type
  chia/rpc/rpc_client.py
  chia/wallet/puzzles/prefarm/spend_prefarm.py
  tests/wallet/rpc/test_dl_wallet_rpc.py
Labels: Fixed, Tests, Cleanup

#14055 Updating PR template & adding exclusion tags
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release.yml
Labels: Changed, Exclude_Notes

#14159 Add py310 to the black target version
  pyproject.toml
Labels: Fixed, Cleanup

#14195 Remove redundant check for duplicate outputs
  chia/full_node/mempool_manager.py
  tests/core/mempool/test_mempool_manager.py
Labels: Changed

#14198 improve adjusted_timeout() to handle floats and None
  chia/simulator/time_out_assert.py
  tests/core/test_services.py
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: Fixed, Tests

#14200 make wallet rpc client wallet id parameters accept int, not str
  chia/cmds/coin_funcs.py
  chia/cmds/plotnft_funcs.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_client.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Fixed, Cleanup

#14202 wait for wallet sync in test_wallet_coinbase_reorg() and test_wallet_tx_reorg()
  tests/wallet/test_wallet.py
Labels: Fixed, Tests

#14193 Fixes the case when a fee estimation request is made before the FullNode has initialized a peak
  chia/rpc/full_node_rpc_api.py
  tests/conftest.py
  tests/fee_estimation/test_fee_estimation_rpc.py
Labels: Clean: caught up to main, PR, Fixed

#14199 check_removals() doesn't need to be async
  chia/full_node/mempool_manager.py
Labels: Changed

#14204 fully hint test_pool_rpc
  chia/simulator/block_tools.py
  mypy.ini
  tests/pools/test_pool_rpc.py
Labels: Changed, Tests

#14212 Remove redundant check for maximum block CLVM cost
  chia/full_node/mempool_manager.py
  tests/core/mempool/test_mempool_manager.py
Labels: Changed

#14214 use default_factory= for SpendableCAT mutable defaults
  chia/wallet/cat_wallet/cat_utils.py
Labels: Fixed, Cleanup

#14215 allow more sqlite thread safety than the minimum we require
  tests/core/full_node/stores/test_block_store.py
Labels: Fixed, Cleanup

#14221 use adjusted_timeout() for simulator helpers
  chia/simulator/full_node_simulator.py
Labels: Fixed, Tests
