Repository Chia-Network/chia-blockchain, pull requests merged in 2022-07, with the labels that each got.

#12160 Fix some more flakiness
  tests/core/server/test_rate_limits.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_wallet.py
Labels: ready_to_merge

#12177 checkpoint: into datalayer-sim from release/1.4.0 @ d2dbb1244846305985fbdd741799f242917a4687
  chia/rpc/wallet_rpc_api.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge

#12171 WalletTransactionStore unit test
  chia/wallet/transaction_record.py
  chia/wallet/transaction_sorting.py
  chia/wallet/wallet_transaction_store.py
  tests/wallet/test_transaction_store.py
Labels: ready_to_merge

#11763 streamable: Turn `dataclass_from_dict` into `streamable_from_dict`
  chia/types/spend_bundle.py
  chia/util/streamable.py
  tests/core/util/test_streamable.py
Labels: ready_to_merge

#12172 replace service `running_new_process=` parameter by `.setup_process_global_state()` method
  chia/server/start_service.py
  tests/setup_services.py
Labels: ready_to_merge

#12182 El.dependabot/node fetch combined
  build_scripts/npm_linux_deb/package-lock.json
  build_scripts/npm_macos/package-lock.json
  build_scripts/npm_macos_m1/package-lock.json
Labels: dependencies, javascript, ready_to_merge

#12183 El.dependabot/minimist 1.2.6
  build_scripts/npm_linux_deb/package-lock.json
  build_scripts/npm_linux_rpm/package-lock.json
  build_scripts/npm_macos_m1/package-lock.json
  build_scripts/npm_windows/package-lock.json
Labels: dependencies, javascript, ready_to_merge

#12196 Make start_crawler.py consistent with start_*.py
  chia/seeder/start_crawler.py
Labels: ready_to_merge

#12118 Refine wallet full node peer selection
  chia/rpc/wallet_rpc_api.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge

#11733 dont request ses
  chia/wallet/wallet_node.py
Labels: ready_to_merge

#12026 EndpointResult
  chia/rpc/crawler_rpc_api.py
  chia/rpc/farmer_rpc_api.py
  chia/rpc/full_node_rpc_api.py
  chia/rpc/harvester_rpc_api.py
  chia/rpc/rpc_server.py
  chia/rpc/wallet_rpc_api.py
  chia/simulator/SimulatorFullNodeRpcApi.py
  chia/wallet/trade_manager.py
Labels: ready_to_merge

#12146 Pool store cache
  chia/pools/pool_wallet.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_pool_store.py
  tests/pools/test_wallet_pool_store.py
Labels: ready_to_merge

#12241 websockets - remove extra break preventing all sockets from being attempted
  chia/daemon/server.py
Labels: ready_to_merge

#12224 Remove unused finished_sync_up_to
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge

#12180 Fix misleading argument name
  chia/consensus/blockchain_interface.py
Labels: ready_to_merge

#12262 catch up with types-aiofiles hinting
  chia/util/files.py
Labels: ready_to_merge

#11856 streamable: Expand `Field` and introduce `Streamable._streamable_fields`
  chia/util/streamable.py
Labels: ready_to_merge

#11890 plot_sync: Fix type hints in `Receiver._process`
  chia/plot_sync/receiver.py
  chia/plot_sync/util.py
Labels: ready_to_merge

#12252 Removing `logging.basicConfig()` from `ChiaServer.__init__()`
  chia/server/server.py
Labels: ready_to_merge

#12274 extend min_coin to rpc calls & cli for coin selection
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
  chia/wallet/wallet.py
  tests/wallet/test_coin_selection.py
Labels: ready_to_merge

#12253 Initialize logging before Service instantiation
  chia/server/start_service.py
Labels: ready_to_merge

#12280 make sure chia commands output help when no args are given
  chia/cmds/configure.py
  chia/cmds/show.py
Labels: ready_to_merge

#12075 add install action
  .github/actions/install/action.yml
  .github/workflows/benchmarks.yml
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installer.yml
  .github/workflows/build-macos-m1-installer.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test-install-scripts.yml
  .github/workflows/test-single.yml
  Install.ps1
Labels: ready_to_merge

#12204 Simplify service start configuration loading
  chia/seeder/start_crawler.py
  chia/server/start_farmer.py
  chia/server/start_full_node.py
  chia/server/start_harvester.py
  chia/server/start_introducer.py
  chia/server/start_service.py
  chia/server/start_timelord.py
  chia/server/start_wallet.py
  chia/simulator/start_simulator.py
  tests/setup_services.py
Labels: ready_to_merge

#12239 Correct UncurriedNFT hinting
  chia/wallet/nft_wallet/uncurry_nft.py
Labels: ready_to_merge

#12261 Ms.fix coin selection
  chia/wallet/coin_selection.py
  tests/wallet/test_coin_selection.py
Labels: ready_to_merge

#12276 Additional data for `get_wallet_balance` and `get_wallets` endpoints
  chia/rpc/wallet_rpc_api.py
Labels: ready_to_merge

#12285 Increment macOS Intel installer build timeout to 55
  .github/workflows/build-macos-installer.yml
Labels: ready_to_merge

#12282 Tx submission idempotance, and prioritize wallet
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  tests/core/full_node/test_full_node.py
Labels: ready_to_merge

#12292 fixup
  .github/actions/install/action.yml
  chia/server/start_service.py
Labels: ready_to_merge

#12175 Create NFT wallet after the DID created
  chia/rpc/wallet_rpc_api.py
Labels: ready_to_merge

#11826 Wp validate from fork
  chia/full_node/weight_proof.py
  chia/wallet/wallet_blockchain.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_weight_proof_handler.py
  tests/wallet/sync/test_wallet_sync.py
Labels: ready_to_merge

#12234 Wallet dbwrapper 2
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/util/initial-config.yaml
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/cat_wallet/lineage_store.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/key_val_store.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/puzzles/tails.py
  chia/wallet/rl_wallet/rl_wallet.py
  chia/wallet/trade_manager.py
  chia/wallet/trading/trade_store.py
  chia/wallet/wallet.py
  chia/wallet/wallet_action_store.py
  chia/wallet/wallet_blockchain.py
  chia/wallet/wallet_coin_store.py
  chia/wallet/wallet_interested_store.py
  chia/wallet/wallet_nft_store.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_pool_store.py
  chia/wallet/wallet_puzzle_store.py
  chia/wallet/wallet_state_manager.py
  chia/wallet/wallet_transaction_store.py
  chia/wallet/wallet_user_store.py
  tests/pools/test_pool_rpc.py
  tests/pools/test_pool_wallet.py
  tests/pools/test_wallet_pool_store.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_nft_store.py
  tests/wallet/test_puzzle_store.py
  tests/wallet/test_transaction_store.py
  tests/wallet/test_wallet_blockchain.py
  tests/wallet/test_wallet_coin_store.py
  tests/wallet/test_wallet_interested_store.py
  tests/wallet/test_wallet_key_val_store.py
  tests/wallet/test_wallet_user_store.py
Labels: ready_to_merge

#12290 remove extra bt from as many tests as possible ( speed up tests)
  tests/blockchain/test_blockchain_transactions.py
  tests/conftest.py
  tests/core/daemon/test_daemon.py
  tests/core/full_node/full_sync/test_full_sync.py
  tests/core/full_node/stores/test_hint_store.py
  tests/core/full_node/test_full_node.py
  tests/core/full_node/test_mempool.py
  tests/core/full_node/test_mempool_performance.py
  tests/core/full_node/test_node_load.py
  tests/core/full_node/test_performance.py
  tests/core/full_node/test_transactions.py
  tests/core/server/test_dos.py
  tests/core/ssl/test_ssl.py
  tests/core/test_farmer_harvester_rpc.py
  tests/core/test_filter.py
  tests/core/test_full_node_rpc.py
  tests/farmer_harvester/test_farmer_harvester.py
  tests/plot_sync/test_plot_sync.py
  tests/plot_sync/test_sync_simulated.py
  tests/pools/test_pool_rpc.py
  tests/setup_nodes.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/rl_wallet/test_rl_rpc.py
  tests/wallet/rl_wallet/test_rl_wallet.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_blockchain.py
  tests/wallet/test_wallet_retry.py
Labels: ready_to_merge

#12236 20220705 clvm tools rs version bump
  setup.py
Labels: enhancement, dependencies, Pending regression test

#12153 rework service creation to be hint checkable
  chia/seeder/start_crawler.py
  chia/server/start_farmer.py
  chia/server/start_full_node.py
  chia/server/start_harvester.py
  chia/server/start_introducer.py
  chia/server/start_service.py
  chia/server/start_timelord.py
  chia/server/start_wallet.py
  chia/simulator/start_simulator.py
  tests/setup_services.py
Labels: ready_to_merge

#12235 use language:system for pre-commit mypy
  .pre-commit-config.yaml
Labels: ready_to_merge

#12323 Simplify wallet transaction store
  chia/wallet/wallet_transaction_store.py
Labels: ready_to_merge

#12334 Remove unused clear db
  chia/wallet/cat_wallet/lineage_store.py
  chia/wallet/key_val_store.py
  chia/wallet/trading/trade_store.py
  chia/wallet/wallet_action_store.py
  chia/wallet/wallet_coin_store.py
  chia/wallet/wallet_interested_store.py
  chia/wallet/wallet_nft_store.py
  chia/wallet/wallet_pool_store.py
  chia/wallet/wallet_puzzle_store.py
  chia/wallet/wallet_transaction_store.py
  chia/wallet/wallet_user_store.py
Labels: ready_to_merge

#10212 Fix trusted_peer example in initial-config.yaml
  chia/util/initial-config.yaml
Labels: ready_to_merge

#12358 service_name="full_node"
  chia/seeder/start_crawler.py
Labels: ready_to_merge

#12335 Wallet execute fetchall
  chia/util/db_wrapper.py
  chia/wallet/wallet_nft_store.py
  chia/wallet/wallet_puzzle_store.py
  chia/wallet/wallet_user_store.py
Labels: ready_to_merge

#12366 util: Improve `prompt_yes_no`
  chia/cmds/keys_funcs.py
  chia/cmds/passphrase_funcs.py
  chia/util/keyring_wrapper.py
  chia/util/misc.py
Labels: ready_to_merge

#12362 Add `Program.replace`.
  chia/types/blockchain_format/program.py
  tests/clvm/test_program.py
Labels: ready_to_merge

#12391 Optimize wallet set_spent()
  chia/wallet/wallet_coin_store.py
  tests/wallet/test_wallet_coin_store.py
Labels: ready_to_merge

#12072 Replace existing simulator config & Fix simulator
  chia/daemon/server.py
  chia/full_node/full_node.py
  chia/simulator/SimulatorFullNodeRpcApi.py
  chia/simulator/SimulatorFullNodeRpcClient.py
  chia/simulator/full_node_simulator.py
  chia/simulator/simulator_constants.py
  chia/simulator/start_simulator.py
  chia/util/config.py
  chia/util/initial-config.yaml
  tests/block_tools.py
  tests/setup_services.py
  tests/simulation/test_simulation.py
  tests/simulation/test_start_simulator.py
Labels: ready_to_merge

#12360 Expand select_coins rpc
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/coin_selection.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
  chia/wallet/wallet.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_coin_selection.py
Labels: ready_to_merge

#12275 add new_transaction() to DBWrapper2
  chia/clvm/spend_sim.py
  chia/consensus/blockchain.py
  chia/full_node/block_height_map.py
  chia/full_node/block_store.py
  chia/full_node/coin_store.py
  chia/full_node/full_node.py
  chia/full_node/hint_store.py
  chia/rpc/wallet_rpc_api.py
  chia/util/db_wrapper.py
  chia/wallet/cat_wallet/lineage_store.py
  chia/wallet/key_val_store.py
  chia/wallet/trading/trade_store.py
  chia/wallet/wallet_action_store.py
  chia/wallet/wallet_coin_store.py
  chia/wallet/wallet_interested_store.py
  chia/wallet/wallet_nft_store.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_pool_store.py
  chia/wallet/wallet_puzzle_store.py
  chia/wallet/wallet_transaction_store.py
  chia/wallet/wallet_user_store.py
  tests/blockchain/blockchain_test_utils.py
  tests/core/full_node/stores/test_block_store.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/stores/test_hint_store.py
  tests/core/full_node/test_block_height_map.py
  tests/core/test_db_validation.py
  tests/core/util/test_db_wrapper.py
  tests/pools/test_wallet_pool_store.py
Labels: ready_to_merge

#12287 run pre-commit across platforms in ci
  .github/workflows/pre-commit.yml
  activated.ps1
  chia/daemon/server.py
  chia/daemon/windows_signal.py
  chia/plotters/madmax.py
  chia/server/start_service.py
  chia/timelord/timelord_launcher.py
Labels: ready_to_merge

#12356 daemon|server: Log `chia_full_version_str` in daemon and all services
  chia/daemon/server.py
  chia/server/start_service.py
Labels: ready_to_merge

#12388 cmds: Move config loading into start/stop/passphrase commands
  chia/cmds/passphrase.py
  chia/cmds/passphrase_funcs.py
  chia/cmds/start.py
  chia/cmds/start_funcs.py
  chia/cmds/stop.py
  chia/daemon/client.py
Labels: ready_to_merge

#12440 update `WalletCoinStore.set_spent()` to use `DBWrapper2.writer_maybe_transaction()`
  chia/wallet/wallet_coin_store.py
Labels: ready_to_merge

#12456 Fix attribute error on `FullNode.simulator_transaction_callback`
  chia/full_node/full_node.py
Labels: ready_to_merge

#12459 on failure to get keys, log and return exception
  chia/rpc/wallet_rpc_api.py
Labels: ready_to_merge

#12463 Sleep to allow neworking layer to execute
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge

#10323 changed column selection: table `transaction_record`
  chia/wallet/wallet_transaction_store.py
Labels: ready_to_merge

#10368 changed column selection: table `trade_records`
  chia/wallet/trading/trade_store.py
Labels: ready_to_merge

#11823 write blockchain db full node startup progress to debug.log
  chia/full_node/block_store.py
  chia/full_node/coin_store.py
  chia/full_node/hint_store.py
Labels: ready_to_merge

#10915 Add support for excluding coins in `create_signed_transaction` wallet rpc
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/wallet.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_coin_selection.py
Labels: ready_to_merge

#12412 make DBWrapper2 test more reliable
  tests/core/util/test_db_wrapper.py
Labels: ready_to_merge

#12515 util: Make `FileKeyring` a `dataclass`
  chia/util/dump_keyring.py
  chia/util/file_keyring.py
  chia/util/keyring_wrapper.py
  tests/util/keyring.py
Labels: ready_to_merge

#12518 util: Drop unused `FileKeyring.prepare_for_migration`
  chia/util/file_keyring.py
Labels: ready_to_merge

#12467 optimize ph generation (~65% faster)
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/puzzles/p2_delegated_puzzle_or_hidden_puzzle.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
  tests/clvm/test_puzzles.py
  tests/clvm/test_singletons.py
  tests/core/test_cost_calculation.py
  tests/wallet/test_wallet.py
  tests/wallet_tools.py
Labels: ready_to_merge

#12517 util: Fix passphrase hint
  chia/util/file_keyring.py
  tests/core/util/test_keyring_wrapper.py
Labels: ready_to_merge

#12479 keychain: Drop `supports_keyring_passphrase`
  chia/cmds/chia.py
  chia/cmds/init.py
  chia/cmds/passphrase_funcs.py
  chia/daemon/keychain_proxy.py
  chia/daemon/server.py
  chia/util/keychain.py
  chia/util/keyring_wrapper.py
  tests/util/keyring.py
Labels: ready_to_merge

#12559 Drop EOL impish and hirsute
  .github/workflows/test-install-scripts.yml
Labels: ready_to_merge

#12535 util: Drop unused `dump_keyring.dump_to_string`
  chia/util/dump_keyring.py
Labels: ready_to_merge

#12341 Puzzle store from row
  chia/wallet/wallet_puzzle_store.py
Labels: ready_to_merge

#12544 Remove unneeded None check in NFT wallet
  chia/wallet/nft_wallet/nft_wallet.py
Labels: ready_to_merge

#12062 New RPC block_spends - Get spends for block using transaction generator
  chia/rpc/full_node_rpc_api.py
  chia/rpc/full_node_rpc_client.py
  chia/wallet/puzzles/decompress_block_spends.clvm
  chia/wallet/puzzles/decompress_block_spends.clvm.hex
  chia/wallet/puzzles/decompress_block_spends.clvm.hex.sha256tree
  chia/wallet/puzzles/decompress_block_spends.py
  tests/clvm/test_clvm_compilation.py
  tests/core/test_full_node_rpc.py
Labels: ready_to_merge

#11186 Bump clvm_tools_rs for bug fix
  tests/clvm/test_clvm_compilation.py
Labels: stale-pr

#12392 block sending an amount of 0
  chia/cmds/wallet_funcs.py
Labels: ready_to_merge

#12531 util: Enable `isort` and more `mypy` in `file_keyring.py`
  .isort.cfg
  chia/util/file_keyring.py
  mypy.ini
Labels: ready_to_merge

#12655 util: Free all non-class related functions in `FileKeyring`
  chia/util/dump_keyring.py
  chia/util/file_keyring.py
  tests/core/util/test_file_keyring_synchronization.py
  tests/util/keyring.py
Labels: ready_to_merge

#12549 Last new simulator rpc's
  chia/full_node/coin_store.py
  chia/simulator/SimulatorFullNodeRpcApi.py
  chia/simulator/SimulatorFullNodeRpcClient.py
  chia/simulator/full_node_simulator.py
  chia/simulator/simulator_full_node_rpc_api.py
  chia/simulator/simulator_full_node_rpc_client.py
  chia/simulator/simulator_protocol.py
  chia/simulator/start_simulator.py
  tests/simulation/test_simulation.py
  tests/simulation/test_start_simulator.py
Labels: ready_to_merge

#12520 NFT transfer/minting commands now validate the specified addresses
  chia/cmds/wallet_funcs.py
  chia/util/config.py
  chia/wallet/util/address_type.py
  tests/conftest.py
  tests/core/util/test_config.py
  tests/wallet/test_address_type.py
Labels: ready_to_merge

#12629 catchup: into main from long_lived/post_1.5.0 @ 916ccee549b1594349c19fcbb0d0d210698c899b
  .gitmodules
  CHANGELOG.md
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/util/default_root.py
  chia/wallet/cat_wallet/cat_constants.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/puzzles/cat.clvm
  chia/wallet/puzzles/cat.clvm.hex
  chia/wallet/puzzles/cat.clvm.hex.sha256tree
  chia/wallet/puzzles/cat_loader.py
  chia/wallet/puzzles/cat_v2.clvm
  chia/wallet/puzzles/cat_v2.clvm.hex
  chia/wallet/puzzles/cat_v2.clvm.hex.sha256tree
  chia/wallet/util/puzzle_compression.py
  chia/wallet/wallet_node.py
  tests/clvm/test_clvm_compilation.py
  tests/clvm/test_puzzle_compression.py
  tests/tools/test_run_block.py
  tests/wallet/cat_wallet/test_cat_outer_puzzle.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/test_wallet.py
Labels: ready_to_merge

#12550 Support for remembering the last used wallet key
  chia/daemon/keychain_proxy.py
  chia/daemon/keychain_server.py
  chia/wallet/wallet_node.py
  tests/wallet/test_wallet_node.py
Labels: ready_to_merge

#12608 update protocol message checks
  chia/protocols/protocol_state_machine.py
  tests/util/test_network_protocol_test.py
Labels: ready_to_merge
