Repository Chia-Network/chia-blockchain, pull requests merged in 2022-10, with the labels that each got.

#13545 server: Use `WebServer` in `ChiaServer`
  chia/server/server.py
Labels: PR

#13546 data_layer: Use `WebServer` in `DataLayerServer`
  chia/data_layer/data_layer_server.py
Labels: PR

#13571 daemon: Use `WebServer`
  chia/daemon/server.py
Labels: PR

#13219 Minimized a chance where `sudo` prompts users for password
  install.sh
Labels: ready_to_merge

#13472 Fix CAT offer aggregation edge case
  chia/wallet/cat_wallet/cat_outer_puzzle.py
  chia/wallet/trading/offer.py
  tests/wallet/cat_wallet/test_trades.py
Labels: PR

#13580 use @asynccontextmanager for chia.cmds.get_client()
  chia/cmds/data_funcs.py
Labels: ready_to_merge

#13610 logo-fix
  README.md
Labels: ready_to_merge

#13621 Fix typo in wallet: puzzle
  chia/wallet/wallet.py
Labels: ready_to_merge

#13466 feat: enable `create_signed_transaction` and `push_transaction`
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: PR

#13645 Fee estimates
  CHANGELOG.md
  benchmarks/utils.py
  chia/cmds/show.py
  chia/cmds/show_funcs.py
  chia/cmds/wallet.py
  chia/full_node/bitcoin_fee_estimator.py
  chia/full_node/fee_estimate.py
  chia/full_node/fee_estimate_store.py
  chia/full_node/fee_estimation.py
  chia/full_node/fee_estimator.py
  chia/full_node/fee_estimator_constants.py
  chia/full_node/fee_estimator_example.py
  chia/full_node/fee_estimator_interface.py
  chia/full_node/fee_history.py
  chia/full_node/fee_tracker.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/protocols/protocol_message_types.py
  chia/protocols/wallet_protocol.py
  chia/rpc/full_node_rpc_api.py
  chia/rpc/full_node_rpc_client.py
  chia/types/clvm_cost.py
  chia/types/fee_rate.py
  chia/types/mempool_item.py
  chia/types/mojos.py
  tests/conftest.py
  tests/core/full_node/test_mempool.py
  tests/core/full_node/test_mempool_fee_protocol.py
  tests/core/mempool/__init__.py
  tests/core/mempool/test_mempool_fee_estimator.py
  tests/fee_estimation/__init__.py
  tests/fee_estimation/cmdline_test.py
  tests/fee_estimation/test_fee_estimation_rpc.py
  tests/fee_estimation/test_fee_estimation_unit_tests.py
  tests/util/test_network_protocol_test.py
Labels: 1.6.1

#13586 Clean up data layer code to use the standard cli client
  chia/cmds/cmds_util.py
  chia/cmds/data_funcs.py
Labels: ready_to_merge

#13565 refactor `@api_request` decorator and family to use a single decorator
  chia/farmer/farmer_api.py
  chia/full_node/full_node_api.py
  chia/harvester/harvester_api.py
  chia/introducer/introducer_api.py
  chia/seeder/crawler_api.py
  chia/timelord/timelord_api.py
  chia/util/api_decorators.py
  chia/wallet/wallet_node_api.py
  tests/core/full_node/test_mempool.py
Labels: PR

#13325 Coin Selection CLI / RPC Expansion
  chia/cmds/cmds_util.py
  chia/cmds/coin_funcs.py
  chia/cmds/coins.py
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/coin_selection.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
  chia/wallet/wallet.py
  chia/wallet/wallet_coin_record.py
  chia/wallet/wallet_coin_store.py
  chia/wallet/wallet_protocol.py
  chia/wallet/wallet_state_manager.py
  chia/wallet/wallet_transaction_store.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge

#13713 Add a state_changed for frontend on notification
  chia/wallet/notification_manager.py
Labels: ready_to_merge

#13612 Minor Simulation CI test adjustments
  chia/simulator/simulator_test_tools.py
  tests/conftest.py
  tests/core/cmds/test_keys.py
  tests/simulation/test_simulation.py
  tests/simulation/test_start_simulator.py
Labels: ready_to_merge

#13605 debug_spend_bundle -- print coin id as hex string
  chia/wallet/util/debug_spend_bundle.py
Labels: ready_to_merge

#13440 Add atari get sync status RPC.
  chia/cmds/data.py
  chia/cmds/data_funcs.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_util.py
  chia/rpc/data_layer_rpc_api.py
  chia/rpc/data_layer_rpc_client.py
  tests/core/data_layer/test_data_rpc.py
Labels: data

#13710 Updating old reference to chia peer -a
  chia/cmds/show_funcs.py
Labels: ready_to_merge
