Repository Chia-Network/chia-blockchain, pull requests merged in 2022-04, with the labels that each got.

#10979 back to a single option for workflow parallel config
  tests/build-workflows.py
  tests/pools/config.py
  tests/testconfig.py
Labels: ready_to_merge

#10959 limit test output on CI
  .github/workflows/build-test-macos-blockchain.yml
  .github/workflows/build-test-macos-clvm.yml
  .github/workflows/build-test-macos-core-cmds.yml
  .github/workflows/build-test-macos-core-consensus.yml
  .github/workflows/build-test-macos-core-custom_types.yml
  .github/workflows/build-test-macos-core-daemon.yml
  .github/workflows/build-test-macos-core-full_node-full_sync.yml
  .github/workflows/build-test-macos-core-full_node-stores.yml
  .github/workflows/build-test-macos-core-full_node.yml
  .github/workflows/build-test-macos-core-server.yml
  .github/workflows/build-test-macos-core-ssl.yml
  .github/workflows/build-test-macos-core-util.yml
  .github/workflows/build-test-macos-core.yml
  .github/workflows/build-test-macos-farmer_harvester.yml
  .github/workflows/build-test-macos-generator.yml
  .github/workflows/build-test-macos-plotting.yml
  .github/workflows/build-test-macos-pools.yml
  .github/workflows/build-test-macos-simulation.yml
  .github/workflows/build-test-macos-tools.yml
  .github/workflows/build-test-macos-util.yml
  .github/workflows/build-test-macos-wallet-cat_wallet.yml
  .github/workflows/build-test-macos-wallet-did_wallet.yml
  .github/workflows/build-test-macos-wallet-rl_wallet.yml
  .github/workflows/build-test-macos-wallet-rpc.yml
  .github/workflows/build-test-macos-wallet-simple_sync.yml
  .github/workflows/build-test-macos-wallet-sync.yml
  .github/workflows/build-test-macos-wallet.yml
  .github/workflows/build-test-macos-weight_proof.yml
  .github/workflows/build-test-ubuntu-blockchain.yml
  .github/workflows/build-test-ubuntu-clvm.yml
  .github/workflows/build-test-ubuntu-core-cmds.yml
  .github/workflows/build-test-ubuntu-core-consensus.yml
  .github/workflows/build-test-ubuntu-core-custom_types.yml
  .github/workflows/build-test-ubuntu-core-daemon.yml
  .github/workflows/build-test-ubuntu-core-full_node-full_sync.yml
  .github/workflows/build-test-ubuntu-core-full_node-stores.yml
  .github/workflows/build-test-ubuntu-core-full_node.yml
  .github/workflows/build-test-ubuntu-core-server.yml
  .github/workflows/build-test-ubuntu-core-ssl.yml
  .github/workflows/build-test-ubuntu-core-util.yml
  .github/workflows/build-test-ubuntu-core.yml
  .github/workflows/build-test-ubuntu-farmer_harvester.yml
  .github/workflows/build-test-ubuntu-generator.yml
  .github/workflows/build-test-ubuntu-plotting.yml
  .github/workflows/build-test-ubuntu-pools.yml
  .github/workflows/build-test-ubuntu-simulation.yml
  .github/workflows/build-test-ubuntu-tools.yml
  .github/workflows/build-test-ubuntu-util.yml
  .github/workflows/build-test-ubuntu-wallet-cat_wallet.yml
  .github/workflows/build-test-ubuntu-wallet-did_wallet.yml
  .github/workflows/build-test-ubuntu-wallet-rl_wallet.yml
  .github/workflows/build-test-ubuntu-wallet-rpc.yml
  .github/workflows/build-test-ubuntu-wallet-simple_sync.yml
  .github/workflows/build-test-ubuntu-wallet-sync.yml
  .github/workflows/build-test-ubuntu-wallet.yml
  .github/workflows/build-test-ubuntu-weight_proof.yml
  tests/runner_templates/build-test-macos
  tests/runner_templates/build-test-ubuntu
Labels: ready_to_merge

#10965 Ms.flaky gen speed
  tests/core/test_cost_calculation.py
  tests/wallet/test_wallet.py
Labels: ready_to_merge

#10987 force index in get_coin_records_by_names
  chia/full_node/coin_store.py
Labels: ready_to_merge

#10962 Fix remaining linting issues
  benchmarks/utils.py
  chia/consensus/block_body_validation.py
  chia/consensus/block_creation.py
  chia/consensus/blockchain.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/block_store.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/rpc/full_node_rpc_api.py
  chia/server/server.py
  chia/simulator/simulator_constants.py
  chia/timelord/timelord_state.py
  chia/types/blockchain_format/proof_of_space.py
  chia/util/block_cache.py
  chia/util/generator_tools.py
  tests/block_tools.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/full_node/test_block_height_map.py
  tests/core/full_node/test_mempool.py
  tests/core/make_block_generator.py
  tests/pools/test_wallet_pool_store.py
  tests/util/key_tool.py
  tests/util/network_protocol_data.py
  tests/wallet_tools.py
  tests/weight_proof/test_weight_proof.py
Labels: ready_to_merge

#8862 run_generator2 rust call and compact conditions data structure
  chia/consensus/block_body_validation.py
  chia/consensus/blockchain.py
  chia/consensus/cost_calculator.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
  chia/full_node/mempool_check_conditions.py
  chia/full_node/mempool_manager.py
  chia/types/blockchain_format/program.py
  chia/types/name_puzzle_condition.py
  chia/types/spend_bundle_conditions.py
  chia/util/condition_tools.py
  chia/util/generator_tools.py
  tests/clvm/coin_store.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/test_mempool.py
  tests/core/test_cost_calculation.py
  tests/generator/test_rom.py
  tests/util/generator_tools_testing.py
  tools/run_block.py
Labels: ready_to_merge

#10986 Faster full node tests
  chia/full_node/full_node_api.py
  tests/conftest.py
  tests/core/full_node/test_full_node.py
  tests/core/full_node/test_mempool.py
Labels: ready_to_merge

#11047 Force apt to install the things we asked it to
  .github/workflows/benchmarks.yml
Labels: ready_to_merge

#11004 fix memory leak in test_full_sync
  tools/test_full_sync.py
Labels: ready_to_merge

#11046 full_node: Drop unused `MempoolManager.constants_json`
  chia/full_node/mempool_manager.py
Labels: ready_to_merge

#11007 simplify some header hash getting and assertions
  chia/consensus/blockchain.py
  chia/full_node/full_node_api.py
Labels: ready_to_merge

#11064 print average block rate at different block height windows
  tools/test_full_sync.py
Labels: ready_to_merge

#11053 Remove dead snakes usage from benchmark tests
  .github/workflows/benchmarks.yml
Labels: ready_to_merge

#10761 wallet: Improve logging in `create_more_puzzle_hashes`
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge

#10633 Increases the probability of connecting to local trusted node
  chia/wallet/util/wallet_sync_utils.py
Labels: ready_to_merge

#9695 chia|tests|github: Implement, integrate and test plot sync protocol
  .github/workflows/build-test-macos-plot_sync.yml
  .github/workflows/build-test-ubuntu-plot_sync.yml
  chia/farmer/farmer.py
  chia/farmer/farmer_api.py
  chia/harvester/harvester.py
  chia/harvester/harvester_api.py
  chia/plot_sync/__init__.py
  chia/plot_sync/delta.py
  chia/plot_sync/exceptions.py
  chia/plot_sync/receiver.py
  chia/plot_sync/sender.py
  chia/plot_sync/util.py
  chia/plotting/manager.py
  chia/protocols/harvester_protocol.py
  chia/protocols/protocol_message_types.py
  chia/protocols/shared_protocol.py
  chia/server/rate_limits.py
  setup.py
  tests/conftest.py
  tests/core/test_farmer_harvester_rpc.py
  tests/plot_sync/__init__.py
  tests/plot_sync/config.py
  tests/plot_sync/test_delta.py
  tests/plot_sync/test_plot_sync.py
  tests/plot_sync/test_receiver.py
  tests/plot_sync/test_sender.py
  tests/plot_sync/test_sync_simulated.py
  tests/plot_sync/util.py
  tests/plotting/test_plot_manager.py
  tests/setup_nodes.py
  tests/setup_services.py
Labels: ready_to_merge

#11094 transition to using chia_rs module
  chia/full_node/mempool_check_conditions.py
  chia/types/blockchain_format/program.py
  chia/types/spend_bundle_conditions.py
  chia/util/full_block_utils.py
  setup.py
  tests/wallet/test_singleton.py
  tools/analyze-chain.py
  tools/run_block.py
Labels: ready_to_merge

#11038 Fix the case of claiming a large number of coins
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/wallet_state_manager.py
  tests/pools/test_pool_rpc.py
Labels: ready_to_merge

#11051 Ms.fast test blockchain
  .github/workflows/benchmarks.yml
  .github/workflows/build-test-macos-blockchain.yml
  .github/workflows/build-test-macos-core-daemon.yml
  .github/workflows/build-test-macos-core-full_node-full_sync.yml
  .github/workflows/build-test-macos-core-full_node-stores.yml
  .github/workflows/build-test-macos-core-full_node.yml
  .github/workflows/build-test-macos-core-server.yml
  .github/workflows/build-test-macos-core-ssl.yml
  .github/workflows/build-test-macos-core-util.yml
  .github/workflows/build-test-macos-core.yml
  .github/workflows/build-test-macos-farmer_harvester.yml
  .github/workflows/build-test-macos-plot_sync.yml
  .github/workflows/build-test-macos-plotting.yml
  .github/workflows/build-test-macos-pools.yml
  .github/workflows/build-test-macos-simulation.yml
  .github/workflows/build-test-macos-wallet-cat_wallet.yml
  .github/workflows/build-test-macos-wallet-rpc.yml
  .github/workflows/build-test-macos-wallet-simple_sync.yml
  .github/workflows/build-test-macos-wallet-sync.yml
  .github/workflows/build-test-macos-wallet.yml
  .github/workflows/build-test-macos-weight_proof.yml
  .github/workflows/build-test-ubuntu-blockchain.yml
  .github/workflows/build-test-ubuntu-core-daemon.yml
  .github/workflows/build-test-ubuntu-core-full_node-full_sync.yml
  .github/workflows/build-test-ubuntu-core-full_node-stores.yml
  .github/workflows/build-test-ubuntu-core-full_node.yml
  .github/workflows/build-test-ubuntu-core-server.yml
  .github/workflows/build-test-ubuntu-core-ssl.yml
  .github/workflows/build-test-ubuntu-core-util.yml
  .github/workflows/build-test-ubuntu-core.yml
  .github/workflows/build-test-ubuntu-farmer_harvester.yml
  .github/workflows/build-test-ubuntu-plot_sync.yml
  .github/workflows/build-test-ubuntu-plotting.yml
  .github/workflows/build-test-ubuntu-pools.yml
  .github/workflows/build-test-ubuntu-simulation.yml
  .github/workflows/build-test-ubuntu-wallet-cat_wallet.yml
  .github/workflows/build-test-ubuntu-wallet-rpc.yml
  .github/workflows/build-test-ubuntu-wallet-simple_sync.yml
  .github/workflows/build-test-ubuntu-wallet-sync.yml
  .github/workflows/build-test-ubuntu-wallet.yml
  .github/workflows/build-test-ubuntu-weight_proof.yml
  chia/full_node/weight_proof.py
  chia/plotting/create_plots.py
  tests/block_tools.py
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/full_node/full_sync/test_full_sync.py
  tests/core/full_node/test_full_node.py
  tests/core/full_node/test_performance.py
  tests/runner_templates/checkout-test-plots.include.yml
  tests/util/blockchain.py
Labels: ready_to_merge

#11070 can we get by without dead snakes?
  .github/workflows/build-test-macos-core-daemon.yml
  .github/workflows/build-test-macos-simulation.yml
  .github/workflows/build-test-ubuntu-core-daemon.yml
  .github/workflows/build-test-ubuntu-simulation.yml
  install-timelord.sh
  tests/runner_templates/install-timelord.include.yml
Labels: ready_to_merge

#11081 Changelog from 1.3.3
  CHANGELOG.md
Labels: ready_to_merge

#11096 consistently name installer github actions artifact zips
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installer.yml
  .github/workflows/build-macos-m1-installer.yml
  .github/workflows/build-windows-installer.yml
Labels: ready_to_merge

#11098 git -C and consistent activation in installer builds
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installer.yml
  .github/workflows/build-macos-m1-installer.yml
  .github/workflows/build-windows-installer.yml
Labels: ready_to_merge

#11099 only check the version once in installer build workflows
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installer.yml
  .github/workflows/build-macos-m1-installer.yml
  .github/workflows/build-windows-installer.yml
  build_scripts/build_linux_deb.sh
  build_scripts/build_linux_rpm.sh
  build_scripts/build_macos.sh
  build_scripts/build_macos_m1.sh
  build_scripts/build_windows.ps1
Labels: ready_to_merge

#10978 Ms.plot load perf2
  chia/cmds/plots.py
  chia/daemon/server.py
  chia/plotters/chiapos.py
  chia/plotting/create_plots.py
  chia/plotting/manager.py
  chia/plotting/util.py
  tests/block_tools.py
  tests/pools/test_pool_rpc.py
Labels: ready_to_merge

#11154 optimize wallet tool
  tests/wallet_tools.py
Labels: ready_to_merge

#11164 make listen port collisions in CI less likely
  tests/util/socket.py
Labels: ready_to_merge

#11146 add tool to generate a blockchain with full blocks, as a benchmark
  tests/tools/test_full_sync.py
  tools/generate_chain.py
  tools/test_constants.py
  tools/test_full_sync.py
Labels: ready_to_merge

#11185 fix block_tools feature when specifying a list of block references
  tests/block_tools.py
  tests/blockchain/test_blockchain.py
Labels: ready_to_merge

#11227 Fix install.sh test for bookworm
  .github/workflows/test-install-scripts.yml
Labels: ready_to_merge

#11129 aiohttp==3.8.1 for Python 3.10
  setup.py
Labels: ready_to_merge

#11134 fix ssl context creation for server vs. client side
  chia/rpc/rpc_server.py
  chia/server/server.py
  tests/block_tools.py
Labels: ready_to_merge

#9903 plotting|tests|setup: Improve `PlotManager` cache
  chia/plotting/cache.py
  chia/plotting/manager.py
  setup.py
  tests/plotting/test_plot_manager.py
Labels: ready_to_merge

#10539 streamable: Enable `isort` + more `mypy`
  .isort.cfg
  chia/util/streamable.py
  mypy.ini
  tests/core/util/test_streamable.py
Labels: ready_to_merge

#10630 Fix timelord closing.
  chia/timelord/timelord.py
Labels: ready_to_merge

#10737 enable stricter mempool rule
  chia/full_node/mempool_check_conditions.py
  tests/core/full_node/test_mempool.py
Labels: ready_to_merge

#10791 wallet: Fix `CATLineageStore` creation in `create_new_cat_wallet`
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/puzzles/tails.py
  tests/wallet/cat_wallet/test_cat_wallet.py
Labels: ready_to_merge

#10940 Use --module pytest
  .github/workflows/build-test-macos-blockchain.yml
  .github/workflows/build-test-macos-clvm.yml
  .github/workflows/build-test-macos-core-cmds.yml
  .github/workflows/build-test-macos-core-consensus.yml
  .github/workflows/build-test-macos-core-custom_types.yml
  .github/workflows/build-test-macos-core-daemon.yml
  .github/workflows/build-test-macos-core-full_node-full_sync.yml
  .github/workflows/build-test-macos-core-full_node-stores.yml
  .github/workflows/build-test-macos-core-full_node.yml
  .github/workflows/build-test-macos-core-server.yml
  .github/workflows/build-test-macos-core-ssl.yml
  .github/workflows/build-test-macos-core-util.yml
  .github/workflows/build-test-macos-core.yml
  .github/workflows/build-test-macos-farmer_harvester.yml
  .github/workflows/build-test-macos-generator.yml
  .github/workflows/build-test-macos-plotting.yml
  .github/workflows/build-test-macos-pools.yml
  .github/workflows/build-test-macos-simulation.yml
  .github/workflows/build-test-macos-tools.yml
  .github/workflows/build-test-macos-util.yml
  .github/workflows/build-test-macos-wallet-cat_wallet.yml
  .github/workflows/build-test-macos-wallet-did_wallet.yml
  .github/workflows/build-test-macos-wallet-rl_wallet.yml
  .github/workflows/build-test-macos-wallet-rpc.yml
  .github/workflows/build-test-macos-wallet-simple_sync.yml
  .github/workflows/build-test-macos-wallet-sync.yml
  .github/workflows/build-test-macos-wallet.yml
  .github/workflows/build-test-macos-weight_proof.yml
  .github/workflows/build-test-ubuntu-blockchain.yml
  .github/workflows/build-test-ubuntu-clvm.yml
  .github/workflows/build-test-ubuntu-core-cmds.yml
  .github/workflows/build-test-ubuntu-core-consensus.yml
  .github/workflows/build-test-ubuntu-core-custom_types.yml
  .github/workflows/build-test-ubuntu-core-daemon.yml
  .github/workflows/build-test-ubuntu-core-full_node-full_sync.yml
  .github/workflows/build-test-ubuntu-core-full_node-stores.yml
  .github/workflows/build-test-ubuntu-core-full_node.yml
  .github/workflows/build-test-ubuntu-core-server.yml
  .github/workflows/build-test-ubuntu-core-ssl.yml
  .github/workflows/build-test-ubuntu-core-util.yml
  .github/workflows/build-test-ubuntu-core.yml
  .github/workflows/build-test-ubuntu-farmer_harvester.yml
  .github/workflows/build-test-ubuntu-generator.yml
  .github/workflows/build-test-ubuntu-plotting.yml
  .github/workflows/build-test-ubuntu-pools.yml
  .github/workflows/build-test-ubuntu-simulation.yml
  .github/workflows/build-test-ubuntu-tools.yml
  .github/workflows/build-test-ubuntu-util.yml
  .github/workflows/build-test-ubuntu-wallet-cat_wallet.yml
  .github/workflows/build-test-ubuntu-wallet-did_wallet.yml
  .github/workflows/build-test-ubuntu-wallet-rl_wallet.yml
  .github/workflows/build-test-ubuntu-wallet-rpc.yml
  .github/workflows/build-test-ubuntu-wallet-simple_sync.yml
  .github/workflows/build-test-ubuntu-wallet-sync.yml
  .github/workflows/build-test-ubuntu-wallet.yml
  .github/workflows/build-test-ubuntu-weight_proof.yml
  tests/runner_templates/build-test-macos
  tests/runner_templates/build-test-ubuntu
Labels: ready_to_merge

#10954 Fix incorrect return in "rollback_to_block"
  chia/full_node/coin_store.py
  tests/core/full_node/stores/test_coin_store.py
Labels: ready_to_merge

#11006 Correct wallet CLI sent/received indication
  chia/cmds/wallet_funcs.py
Labels: ready_to_merge

#11076 farmer: Introduce `UPDATE_POOL_INFO_FAILURE_RETRY_INTERVAL`
  chia/farmer/farmer.py
Labels: ready_to_merge

#11090 Expose transaction sorting options to CLI
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
Labels: ready_to_merge

#11103 Optimize test_wallet_sync
  tests/wallet/sync/test_wallet_sync.py
Labels: ready_to_merge

#11107 Up Windows installer build timeout to 50 minutes
  .github/workflows/build-windows-installer.yml
Labels: ready_to_merge

#11110 wallet: Drop unused `WalletStateManager.get_derivation_index`
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge

#11118 locate pyinstaller in dev deps rather than build scripts
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installer.yml
  .github/workflows/build-macos-m1-installer.yml
  build_scripts/build_linux_deb.sh
  build_scripts/build_linux_rpm.sh
  build_scripts/build_macos.sh
  build_scripts/build_macos_m1.sh
  setup.py
Labels: ready_to_merge

#11123 Remove code related to no-longer-used websockets library
  chia/util/chia_logging.py
  pylintrc
  tests/core/daemon/test_daemon.py
Labels: ready_to_merge

#11127 harvester: Enable `isort`
  .isort.cfg
  chia/harvester/harvester.py
  chia/harvester/harvester_api.py
  chia/protocols/harvester_protocol.py
Labels: ready_to_merge

#11128 farmer: Enable `isort`
  .isort.cfg
  chia/farmer/farmer.py
  chia/farmer/farmer_api.py
  chia/rpc/farmer_rpc_client.py
Labels: ready_to_merge

#11130 Correct "Older block not found" error message
  chia/rpc/full_node_rpc_api.py
Labels: ready_to_merge

#11133 Print MempoolInclusionStatus as string
  chia/cmds/cmds_util.py
  chia/cmds/plotnft_funcs.py
  chia/cmds/wallet_funcs.py
  chia/types/mempool_submission_status.py
  chia/wallet/trade_record.py
Labels: ready_to_merge

#11149 wallet: Some rollback fixes
  chia/wallet/wallet_blockchain.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge

#11162 optimize Program.curry()
  chia/types/blockchain_format/program.py
  tests/clvm/test_program.py
Labels: ready_to_merge

#11204 harvester: Use a set instead of a list to speed up availability checks
  chia/plotting/manager.py
Labels: ready_to_merge

#11221 cmds: Only call `is_running` endpoint once in `async_start`
  chia/cmds/start_funcs.py
Labels: ready_to_merge

#11226 Remove 3.9.11 for Windows Installer
  .github/workflows/build-windows-installer.yml
Labels: Windows, ready_to_merge

#11241 github: Fix `plot_sync` workflows after #10940 merge
  .github/workflows/build-test-macos-plot_sync.yml
  .github/workflows/build-test-ubuntu-plot_sync.yml
Labels: ready_to_merge

#11246 harvester: Tweak `get_plots` RPC
  chia/harvester/harvester.py
Labels: ready_to_merge

#11259 Check observer addresses in farm rewards dialog
  chia/farmer/farmer.py
  chia/rpc/farmer_rpc_api.py
  chia/rpc/farmer_rpc_client.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/derive_keys.py
  tests/core/test_farmer_harvester_rpc.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge

#11258 postinst/prerm scripts with the UI .deb
  build_scripts/assets/deb/postinst.sh
  build_scripts/assets/deb/prerm.sh
  build_scripts/build_linux_deb.sh
  build_scripts/deb-options.json
Labels: ready_to_merge

#11135 plotting: Enable `isort`
  .isort.cfg
  chia/plotting/check_plots.py
  chia/plotting/manager.py
  chia/plotting/util.py
  tests/plotting/test_plot_manager.py
  tests/plotting/util.py
Labels: ready_to_merge

#11243 check dependency artifacts
  .github/workflows/check_wheel_availability.yaml
  build_scripts/check_dependency_artifacts.py
Labels: ready_to_merge

#11120 have pyinstaller check platlib for dll's, not ROOT
  chia/pyinstaller.spec
Labels: ready_to_merge

#11278 Debian bookworm now uses 3.10, update the comment
  .github/workflows/test-install-scripts.yml
Labels: ready_to_merge

#11274 Update setproctitle to 1.2.3 for python 3.10
  setup.py
Labels: ready_to_merge

#11272 Remove multidict from setup.py for python 3.10
  setup.py
Labels: ready_to_merge

#11273 Update PyYAML to 6.0 for python 3.10
  setup.py
Labels: ready_to_merge

#11295 Add Linux Mint to test matrix
  .github/workflows/test-install-scripts.yml
Labels: ready_to_merge

#11309 Fix targeting for arm64 to not land on native arm64 mac runners
  .github/workflows/build-linux-arm64-installer.yml
Labels: ready_to_merge, 1.3.5-cherrypick

#10278 Change back constant
  chia/consensus/default_constants.py
Labels: ready_to_merge

#11261 make BlockTools generate more accurate block timestamps
  tests/block_tools.py
Labels: ready_to_merge

#11263 significantly speed up get_consecutive_blocks() in BlockTools
  tests/block_tools.py
Labels: ready_to_merge

#11310 Update names of installer workflows so they get grouped together in t…
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installer.yml
  .github/workflows/build-macos-m1-installer.yml
  .github/workflows/build-windows-installer.yml
Labels: ready_to_merge, 1.3.5-cherrypick

#11277 also m1 and arm64 for wheel checks
  .github/workflows/check_wheel_availability.yaml
  build_scripts/check_dependency_artifacts.py
Labels: ready_to_merge, 1.3.5-cherrypick

#11316 Upload CLI RPMS to s3, create checksums, etc
  .github/workflows/build-linux-installer-rpm.yml
Labels: ready_to_merge, 1.3.5-cherrypick

#11321 Build installers on push to release branches
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installer.yml
  .github/workflows/build-macos-m1-installer.yml
  .github/workflows/build-windows-installer.yml
Labels: ready_to_merge, 1.3.5-cherrypick

#11325 More general Ubuntu references in install.sh
  install.sh
Labels: ready_to_merge

#11318 Optimize BLS verification when public key is repeated
  chia/util/cached_bls.py
  tests/core/util/test_cached_bls.py
Labels: ready_to_merge

#11317 Match plurality between macOS and Ubuntu test job names
  .github/workflows/build-test-macos-blockchain.yml
  .github/workflows/build-test-macos-clvm.yml
  .github/workflows/build-test-macos-core-cmds.yml
  .github/workflows/build-test-macos-core-consensus.yml
  .github/workflows/build-test-macos-core-custom_types.yml
  .github/workflows/build-test-macos-core-daemon.yml
  .github/workflows/build-test-macos-core-full_node-full_sync.yml
  .github/workflows/build-test-macos-core-full_node-stores.yml
  .github/workflows/build-test-macos-core-full_node.yml
  .github/workflows/build-test-macos-core-server.yml
  .github/workflows/build-test-macos-core-ssl.yml
  .github/workflows/build-test-macos-core-util.yml
  .github/workflows/build-test-macos-core.yml
  .github/workflows/build-test-macos-farmer_harvester.yml
  .github/workflows/build-test-macos-generator.yml
  .github/workflows/build-test-macos-plot_sync.yml
  .github/workflows/build-test-macos-plotting.yml
  .github/workflows/build-test-macos-pools.yml
  .github/workflows/build-test-macos-simulation.yml
  .github/workflows/build-test-macos-tools.yml
  .github/workflows/build-test-macos-util.yml
  .github/workflows/build-test-macos-wallet-cat_wallet.yml
  .github/workflows/build-test-macos-wallet-did_wallet.yml
  .github/workflows/build-test-macos-wallet-rl_wallet.yml
  .github/workflows/build-test-macos-wallet-rpc.yml
  .github/workflows/build-test-macos-wallet-simple_sync.yml
  .github/workflows/build-test-macos-wallet-sync.yml
  .github/workflows/build-test-macos-wallet.yml
  .github/workflows/build-test-macos-weight_proof.yml
  tests/runner_templates/build-test-macos
Labels: ready_to_merge

#11242 improve generate_chain
  tests/block_tools.py
  tests/tools/test_full_sync.py
  tools/cpu_utilization.py
  tools/generate_chain.py
  tools/run_benchmark.sh
  tools/test_constants.py
  tools/test_full_sync.py
Labels: ready_to_merge

#11338 Fix issue with missing coins
  chia/wallet/util/wallet_sync_utils.py
  chia/wallet/wallet_node.py
Labels: ready_to_merge

#11329 add daemon entry point
  chia/daemon/server.py
  setup.py
Labels: ready_to_merge

#11339 Mark workspace safe for arm installers
  .github/workflows/build-linux-arm64-installer.yml
Labels: ready_to_merge, 1.3.5-cherrypick

#11345 Forward farmer "proof" event to metrics
  chia/rpc/farmer_rpc_api.py
Labels: ready_to_merge

#11058 Use Install.ps1 in build_windows.ps1
  build_scripts/build_windows.ps1
Labels: ready_to_merge

#11346 Updated warning about CHIA_ROOT being set when running init
  chia/cmds/init_funcs.py
Labels: ready_to_merge

#11343 cmds: Adjust stop daemon output
  chia/cmds/stop.py
Labels: ready_to_merge

#11328 lookup coins in large batches
  chia/consensus/block_body_validation.py
  chia/consensus/blockchain.py
  chia/full_node/coin_store.py
  tests/blockchain/test_blockchain.py
  tests/core/full_node/stores/test_coin_store.py
Labels: ready_to_merge

#11245 farmer|rpc: Introduce `get_harvesters_summary` RPC endpoint
  chia/farmer/farmer.py
  chia/plot_sync/receiver.py
  chia/rpc/farmer_rpc_api.py
  chia/rpc/farmer_rpc_client.py
  chia/util/misc.py
  tests/core/test_farmer_harvester_rpc.py
  tests/plot_sync/test_receiver.py
Labels: ready_to_merge, 1.3.5-cherrypick

#10568 Add configurable request size limit for data layer service
  chia/rpc/rpc_server.py
  chia/server/start_data_layer.py
  chia/server/start_service.py
  chia/util/initial-config.yaml
Labels: stale-pr

#11360 update pre-commit mypy to 0.950
  .pre-commit-config.yaml
Labels: ready_to_merge

#11342 farmer|rpc: Some changes to `get_harvesters{_summary}` RPC endpoints
  chia/plot_sync/receiver.py
  tests/plot_sync/test_receiver.py
Labels: ready_to_merge, 1.3.5-cherrypick

#11077 tidy installer building
  .github/workflows/build-windows-installer.yml
  build_scripts/build_windows.ps1
Labels: ready_to_merge

#11247 util: Implement `Paginator` class as interface to access a list by pages
  .github/workflows/build-test-macos-util.yml
  .github/workflows/build-test-ubuntu-util.yml
  chia/util/paginator.py
  tests/util/test_paginator.py
Labels: 1.3.5-cherrypick

#11368 Correct naming of Windows installer artifacts (the GitHub Actions ones)
  .github/workflows/build-windows-installer.yml
Labels: ready_to_merge
