Repository Chia-Network/chia-blockchain, pull requests merged in 2022-11, with the labels that each got.

#13119 Fix pending root when changelist is empty.
  chia/data_layer/data_store.py
Labels: data

#13774 Bump for new clvm_tools and clvm_tools_rs versions
  chia/wallet/nft_wallet/metadata_outer_puzzle.py
  chia/wallet/nft_wallet/ownership_outer_puzzle.py
  chia/wallet/trading/offer.py
  setup.py
  tests/wallet/cat_wallet/test_cat_outer_puzzle.py
Labels: ready_to_merge

#13829 Fix missing bladebit install for DMG build job
  .github/workflows/build-macos-installers.yml
Labels: CI

#13473 switch to context manager for task timing instrumentation
  chia/server/start_full_node.py
  chia/server/start_wallet.py
  chia/util/task_timing.py
Labels: PR

#13814 add_private_key now returns the fingerprint of the added key
  chia/daemon/keychain_server.py
  tests/core/daemon/test_daemon.py
Labels: ready_to_merge

#13818 remove unused unwrap() function
  chia/full_node/mempool_check_conditions.py
Labels: ready_to_merge

#13858 Create royalty payments in fewer coins
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trading/offer.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
Labels: ready_to_merge

#13802 Adding new templates
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release.yml
  .github/workflows/require-labels.yml
Labels: Changed, CI

#10081 Re-enable the trusted parametrization of test_address_sliding_window()
  tests/wallet/test_wallet.py
Labels: Changed, Tests

#13890 Add did_message_spend API
  chia/rpc/wallet_rpc_api.py
  tests/wallet/did_wallet/test_did.py
Labels: ready_to_merge, Added

#13878 server: Enable and fix `mypy` in `ws_connection.py`
  chia/plot_sync/exceptions.py
  chia/plot_sync/receiver.py
  chia/plot_sync/sender.py
  chia/server/ws_connection.py
  mypy.ini
  tests/connection_utils.py
  tests/core/ssl/test_ssl.py
  tests/plot_sync/test_plot_sync.py
  tests/plot_sync/test_receiver.py
  tests/plot_sync/test_sender.py
  tests/plot_sync/test_sync_simulated.py
  tests/plot_sync/util.py
Labels: Fixed, Cleanup

#13389 Delete DID wallet after transfer
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/did_wallet/test_did.py
Labels: ready_to_merge, Changed

#13727 Call close callback for already closed connections
  chia/server/server.py
  chia/server/ws_connection.py
  tests/connection_utils.py
Labels: Fixed

#13879 server: Add optional `outbound` parameter to `get_connections`
  chia/server/node_discovery.py
  chia/server/server.py
  tests/simulation/test_simulation.py
  tools/test_full_sync.py
Labels: Added

#13915 Set GUI binary name to chia-blockchain in the Fedora rpm
  build_scripts/build_linux_rpm-2-installer.sh
Labels: Fixed

#13910 Set GUI binary name to chia-blockchain in the Ubuntu DEB
  build_scripts/build_linux_deb-2-installer.sh
Labels: Fixed

#13907 Catch up pre-commit black
  .pre-commit-config.yaml
Labels: Changed, CI

#13603 rework around tx records and offer takes
  chia/rpc/wallet_rpc_api.py
  chia/simulator/full_node_simulator.py
  chia/wallet/trade_manager.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/db_wallet/test_dl_offers.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tests/wallet/test_wallet.py
Labels: Changed, Tests

#13845 less pip install and activate for windows build
  .github/workflows/build-windows-installer.yml
Labels: ready_to_merge, Changed, CI

#13775 dont validate wp on log_in
  chia/wallet/wallet_blockchain.py
  chia/wallet/wallet_node.py
Labels: Changed

#13880 refactor test utils for import availability outside of repo
  .isort.cfg
  chia/cmds/init_funcs.py
  chia/daemon/server.py
  chia/server/start_data_layer.py
  chia/simulator/block_tools.py
  chia/simulator/keyring.py
  chia/simulator/setup_nodes.py
  chia/simulator/setup_services.py
  chia/simulator/simulator_constants.py
  chia/simulator/simulator_test_tools.py
  chia/ssl/create_ssl.py
  chia/util/file_keyring.py
  chia/util/keyring_wrapper.py
  mypy.ini
  tests/blockchain/test_blockchain.py
  tests/blockchain/test_blockchain_transactions.py
  tests/conftest.py
  tests/core/data_layer/test_data_rpc.py
  tests/core/full_node/full_sync/test_full_sync.py
  tests/core/full_node/stores/test_block_store.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/full_node/test_conditions.py
  tests/core/full_node/test_full_node.py
  tests/core/server/test_rate_limits.py
  tests/core/test_cost_calculation.py
  tests/core/test_db_conversion.py
  tests/core/test_db_validation.py
  tests/core/test_full_node_rpc.py
  tests/core/util/test_file_keyring_synchronization.py
  tests/core/util/test_keychain.py
  tests/core/util/test_keyring_wrapper.py
  tests/core/util/test_streamable.py
  tests/pools/test_pool_rpc.py
  tests/simulation/test_simulation.py
  tests/wallet/db_wallet/test_dl_wallet.py
  tests/wallet/rpc/test_dl_wallet_rpc.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_wallet_blockchain.py
  tests/wallet/test_wallet_node.py
  tools/generate_chain.py
Labels: Changed, Tests

#13922 warn_redundant_casts = True
  mypy.ini
Labels: Changed, Tests

#13926 catch up test_complex_nft_offer() with return type change
  tests/wallet/nft_wallet/test_nft_1_offers.py
Labels: Fixed, Tests

#13914 server: Drop broken message types logging
  chia/server/server.py
Labels: Changed

#13906 Make `WSChiaConnection` a `dataclass`
  chia/server/server.py
  chia/server/ws_connection.py
  tests/connection_utils.py
  tests/core/ssl/test_ssl.py
Labels: Changed

#13916 Simplify `ChiaServer.close_all_connections`
  chia/server/server.py
Labels: Changed

#13895 Reuse `outbound_handshake`
  chia/server/ws_connection.py
Labels: Changed, Cleanup

#13917 Add option to analyze-chain to validate block signatures
  tools/analyze-chain.py
Labels: Added, Cleanup

#13935 Set up commit signing for the mozilla CA updates
  .github/workflows/mozilla-ca-cert.yml
Labels: Added, CI

#13905 setup services refactor
  chia/simulator/setup_nodes.py
  chia/simulator/setup_services.py
  tests/conftest.py
  tests/pools/test_pool_rpc.py
  tests/simulation/test_simulation.py
Labels: Fixed, Tests

#13422 retryAfter: 5 (24x) for conflict check
  .github/workflows/conflict-check.yml
Labels: ready_to_merge, Fixed, CI

#13930 Factor out member functions of `ProofOfSpace` to be free functions
  chia/consensus/block_header_validation.py
  chia/consensus/multiprocess_validation.py
  chia/farmer/farmer_api.py
  chia/full_node/full_node_api.py
  chia/full_node/weight_proof.py
  chia/harvester/harvester_api.py
  chia/plotting/cache.py
  chia/plotting/create_plots.py
  chia/simulator/block_tools.py
  chia/timelord/iters_from_block.py
  chia/types/blockchain_format/proof_of_space.py
  tests/core/custom_types/test_proof_of_space.py
  tests/core/full_node/test_full_node.py
  tests/weight_proof/test_weight_proof.py
Labels: Changed, Cleanup

#13928 Return minted NFT ID & Allow transfer NFT with NFT ID
  chia/rpc/wallet_rpc_api.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/nft_wallet/test_nft_bulk_mint.py
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: ready_to_merge, Changed

#13826 Ensure `chia-blockchain` still opens UI on Linux
  build_scripts/assets/deb/postinst.sh
  build_scripts/assets/deb/prerm.sh
  build_scripts/assets/rpm/postinst.sh
  build_scripts/assets/rpm/prerm.sh
Labels: Fixed

#13940 isort: Remove all `chia.cmds` exceptions and sort the related files
  .isort.cfg
  chia/cmds/chia.py
  chia/cmds/db.py
  chia/cmds/db_upgrade_func.py
  chia/cmds/farm.py
  chia/cmds/farm_funcs.py
  chia/cmds/init.py
  chia/cmds/init_funcs.py
  chia/cmds/keys.py
  chia/cmds/keys_funcs.py
  chia/cmds/netspace.py
  chia/cmds/passphrase.py
  chia/cmds/passphrase_funcs.py
  chia/cmds/plotnft.py
  chia/cmds/plotnft_funcs.py
  chia/cmds/plotters.py
  chia/cmds/show.py
  chia/cmds/start.py
  chia/cmds/start_funcs.py
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
Labels: Changed, Cleanup

#13939 isort: Remove all `chia.util` exceptions and sort the related files
  .isort.cfg
  chia/util/bech32m.py
  chia/util/byte_types.py
  chia/util/chain_utils.py
  chia/util/check_fork_next_block.py
  chia/util/chia_logging.py
  chia/util/condition_tools.py
  chia/util/dump_keyring.py
  chia/util/files.py
  chia/util/generator_tools.py
  chia/util/keychain.py
  chia/util/keyring_wrapper.py
  chia/util/log_exceptions.py
  chia/util/network.py
  chia/util/profiler.py
  chia/util/service_groups.py
  chia/util/ssl_check.py
  chia/util/ws_message.py
Labels: Changed, Cleanup

#13942 Trigger sync tests for all release types
  .github/workflows/start-sync-test.yml
  tests/wallet/did_wallet/test_did.py
Labels: Added, CI

#13941 isort: Remove all `chia.daemon` exceptions and sort the related files
  .isort.cfg
  chia/daemon/keychain_proxy.py
  chia/daemon/keychain_server.py
  chia/daemon/server.py
Labels: Changed, Cleanup

#13949 pre-commit -> timeout-minutes: 20
  .github/workflows/pre-commit.yml
Labels: Fixed, CI

#13950 use aws-actions/configure-aws-credentials@v1-node16 to clear warnings
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-windows-installer.yml
Labels: Fixed, CI

#13398 util: Remove legacy keyring support
  build_scripts/check_dependency_artifacts.py
  chia/cmds/chia.py
  chia/cmds/keys.py
  chia/cmds/keys_funcs.py
  chia/cmds/passphrase.py
  chia/cmds/passphrase_funcs.py
  chia/cmds/start.py
  chia/cmds/start_funcs.py
  chia/daemon/client.py
  chia/daemon/server.py
  chia/simulator/keyring.py
  chia/util/errors.py
  chia/util/keychain.py
  chia/util/keyring_wrapper.py
  pylintrc
  setup.py
  tests/core/cmds/test_keys.py
  tests/core/util/test_keyring_wrapper.py
Labels: Changed

#13953 isort: Remove all `chia.full_node` exceptions and sort the related files
  .isort.cfg
  chia/full_node/block_height_map.py
  chia/full_node/block_store.py
  chia/full_node/bundle_tools.py
  chia/full_node/coin_store.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/generator.py
  chia/full_node/hint_store.py
  chia/full_node/lock_queue.py
  chia/full_node/mempool_check_conditions.py
  chia/full_node/mempool_manager.py
  chia/full_node/weight_proof.py
Labels: Changed, Cleanup

#13227 Add a workflow for scanning python deps
  .github/workflows/snyk-python-scan.yml
Labels: ready_to_merge, Added

#13579 server: Enable and fix `mypy` in `server.py`
  chia/rpc/rpc_client.py
  chia/server/server.py
  mypy.ini
Labels: Fixed

#13615 full_node: Introduce `sync_store.Peak`
  chia/full_node/full_node.py
  chia/full_node/sync_store.py
  chia/rpc/full_node_rpc_api.py
  tests/core/full_node/stores/test_sync_store.py
Labels: Added

#13909 add --fingerprint option to chia keys show
  chia/cmds/keys.py
  chia/cmds/keys_funcs.py
  tests/core/cmds/test_keys.py
Labels: Added

#13959 Revert "Add a workflow for scanning python deps"
  .github/workflows/snyk-python-scan.yml
Labels: Fixed, CI

#13958 Fix wallet fingerprint cli tests
  tests/core/cmds/test_keys.py
Labels: Fixed, CI, Tests

#13655 add simple fix to set farmer response timer for `SP: 0`
  chia/full_node/full_node.py
Labels: Fixed

#13961 isort: Remove all `chia.types` exceptions and sort the related files
  .isort.cfg
  chia/types/blockchain_format/program.py
  chia/types/blockchain_format/proof_of_space.py
  chia/types/blockchain_format/vdf.py
  chia/types/coin_solution.py
  chia/types/coin_spend.py
  chia/types/full_block.py
  chia/types/generator_types.py
  chia/types/spend_bundle.py
Labels: Changed, Cleanup

#13962 isort: Remove all `tests.core` exceptions and sort the related files
  .isort.cfg
  tests/core/cmds/test_keys.py
  tests/core/custom_types/test_coin.py
  tests/core/custom_types/test_spend_bundle.py
  tests/core/daemon/test_daemon.py
  tests/core/full_node/full_sync/test_full_sync.py
  tests/core/full_node/ram_db.py
  tests/core/full_node/stores/test_block_store.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/full_node/stores/test_hint_store.py
  tests/core/full_node/test_block_height_map.py
  tests/core/full_node/test_conditions.py
  tests/core/full_node/test_full_node.py
  tests/core/full_node/test_mempool.py
  tests/core/full_node/test_mempool_performance.py
  tests/core/full_node/test_performance.py
  tests/core/server/test_dos.py
  tests/core/server/test_rate_limits.py
  tests/core/ssl/test_ssl.py
  tests/core/test_daemon_rpc.py
  tests/core/test_db_conversion.py
  tests/core/test_filter.py
  tests/core/test_full_node_rpc.py
  tests/core/util/test_cached_bls.py
  tests/core/util/test_config.py
  tests/core/util/test_file_keyring_synchronization.py
  tests/core/util/test_files.py
  tests/core/util/test_keychain.py
  tests/core/util/test_keyring_wrapper.py
Labels: Changed, Cleanup

#13968 Improve debug logging in `wallet_node` message queue
  chia/wallet/wallet_node.py
Labels: Changed, Cleanup

#13927 simplify TradeManager.respond_to_offer() return
  chia/rpc/wallet_rpc_api.py
  chia/wallet/trade_manager.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/db_wallet/test_dl_offers.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
Labels: Changed

#9697 Windows: start daemon without a window and detached from current console
  chia/cmds/start_funcs.py
Labels: Fixed

#13980 server: Drop unused code in `FullNodeDiscovery`
  chia/server/node_discovery.py
Labels: Changed, Cleanup

#13978 isort: Remove all `tests.wallet` exceptions and sort the related files
  .isort.cfg
  tests/wallet/cat_wallet/test_cat_lifecycle.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/cat_wallet/test_offer_lifecycle.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tests/wallet/test_singleton.py
  tests/wallet/test_singleton_lifecycle.py
  tests/wallet/test_singleton_lifecycle_fast.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_blockchain.py
  tests/wallet/test_wallet_interested_store.py
  tests/wallet/test_wallet_key_val_store.py
Labels: Changed, Cleanup

#13977 isort: Remove all `chia.wallet` exceptions and sort the related files
  .isort.cfg
  chia/wallet/cat_wallet/cat_info.py
  chia/wallet/cat_wallet/cat_utils.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/derive_keys.py
  chia/wallet/did_wallet/did_info.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/did_wallet/did_wallet_puzzles.py
  chia/wallet/lineage_proof.py
  chia/wallet/payment.py
  chia/wallet/puzzles/load_clvm.py
  chia/wallet/puzzles/prefarm/make_prefarm_ph.py
  chia/wallet/puzzles/prefarm/spend_prefarm.py
  chia/wallet/puzzles/puzzle_utils.py
  chia/wallet/puzzles/singleton_top_layer.py
  chia/wallet/puzzles/tails.py
  chia/wallet/sign_coin_spends.py
  chia/wallet/trade_record.py
  chia/wallet/trading/offer.py
  chia/wallet/trading/trade_store.py
  chia/wallet/transaction_record.py
  chia/wallet/util/compute_hints.py
  chia/wallet/util/compute_memos.py
  chia/wallet/util/debug_spend_bundle.py
  chia/wallet/util/puzzle_compression.py
  chia/wallet/util/wallet_sync_utils.py
  chia/wallet/wallet.py
  chia/wallet/wallet_blockchain.py
  chia/wallet/wallet_coin_store.py
  chia/wallet/wallet_interested_store.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_node_api.py
  chia/wallet/wallet_pool_store.py
  chia/wallet/wallet_state_manager.py
  chia/wallet/wallet_weight_proof_handler.py
Labels: Changed, Cleanup

#13936 Display key labels when making a wallet key selection
  chia/cmds/cmds_util.py
  chia/daemon/keychain_proxy.py
  tests/core/daemon/test_keychain_proxy.py
Labels: ready_to_merge, Changed

#13976 Add support for pending transactions to `get_mempool_item_by_tx_id()` #9443
  chia/full_node/mempool_manager.py
  chia/rpc/full_node_rpc_api.py
  chia/rpc/full_node_rpc_client.py
  tests/core/test_full_node_rpc.py
Labels: Changed

#13932 Setup services mypy
  chia/simulator/keyring.py
  chia/simulator/setup_nodes.py
  chia/simulator/setup_services.py
  mypy.ini
  tests/blockchain/test_blockchain_transactions.py
  tests/conftest.py
  tests/pools/test_pool_rpc.py
Labels: Fixed, Tests

#13986 Fix pool singleton sync height in DB
  chia/wallet/wallet_state_manager.py
Labels: Fixed

#13985 adding SECURITY.md
  SECURITY.md
Labels: Added

#13991 server: Compare `PeerInfo` in `address_manager.py`
  chia/server/address_manager.py
  tests/core/full_node/test_address_manager.py
Labels: Changed, Cleanup

#13994 isort: Remove all `chia.server` exceptions and sort the related files
  .isort.cfg
  chia/server/address_manager_sqlite_store.py
  chia/server/address_manager_store.py
  chia/server/introducer_peers.py
  chia/server/node_discovery.py
  chia/server/peer_store_resolver.py
  chia/server/reconnect_task.py
  chia/server/start_service.py
  chia/server/start_wallet.py
Labels: Changed, Cleanup

#13997 flake8: Fix issues after update
  chia/consensus/difficulty_adjustment.py
  chia/simulator/wallet_tools.py
  tests/build-job-matrix.py
Labels: Fixed, Cleanup

#14000 server: Some cleanup/refactoring in `node_discovery.py`
  chia/full_node/full_node.py
  chia/server/node_discovery.py
Labels: Changed, Cleanup

#13892 Remove duplicate nft wallet deletion in reorg
  chia/rpc/wallet_rpc_api.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: bug, Fixed, 1.7.0-b1

#14011 server: Drop unused `WSChiaConnection.is_feeler`
  chia/server/server.py
  chia/server/ws_connection.py
  tests/connection_utils.py
  tests/core/ssl/test_ssl.py
Labels: Changed, Cleanup

#13990 server: Enable and fix `mypy` for all `chia.server` files
  chia/server/address_manager.py
  chia/server/introducer_peers.py
  chia/server/node_discovery.py
  chia/server/peer_store_resolver.py
  chia/server/rate_limits.py
  chia/server/reconnect_task.py
  chia/server/server.py
  chia/server/ssl_context.py
  chia/server/start_data_layer.py
  chia/server/start_farmer.py
  chia/server/start_full_node.py
  chia/server/start_harvester.py
  chia/server/start_introducer.py
  chia/server/start_service.py
  chia/server/start_timelord.py
  chia/server/start_wallet.py
  chia/types/peer_info.py
  mypy.ini
Labels: Changed, Cleanup

#14022 server: Use `closed` property instead of the private member
  chia/server/ws_connection.py
Labels: Changed, Cleanup

#13925 Fix DID unnecessary wallet deletion
  chia/rpc/wallet_rpc_api.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/did_wallet/did_wallet_puzzles.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/did_wallet/test_did.py
Labels: Fixed, 1.7.0-b1

#14023 Improve performance of wallets with many NFTs
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet_nft_store.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/test_nft_store.py
Labels: Fixed

#14029 fix hints after crossed PRs
  chia/rpc/wallet_rpc_api.py
Labels: Fixed, CI

#13833 Made it able to RAM plot with bladebit2
  chia/daemon/server.py
  chia/plotters/bladebit.py
  chia/plotters/plotters.py
Labels: Changed

#14034 Remove outdated and unused in_transaction parameter
  chia/wallet/wallet_state_manager.py
Labels: Changed, CI
