Repository Chia-Network/chia-blockchain, pull requests merged in 2022-03, with the labels that each got.

#10675 harvester: Only lock while actually accessing `PlotManager.plots`
  chia/plotting/manager.py
Labels: Farming

#10554 Enable clvm_tools_rs by default
  chia/util/lock.py
  chia/wallet/puzzles/load_clvm.py
  setup.py
Labels: enhancement

#10166 new DBWrapper supporting concurrent readers
  benchmarks/block_ref.py
  benchmarks/block_store.py
  benchmarks/coin_store.py
  benchmarks/utils.py
  chia/clvm/spend_sim.py
  chia/consensus/blockchain.py
  chia/full_node/block_height_map.py
  chia/full_node/block_store.py
  chia/full_node/coin_store.py
  chia/full_node/full_node.py
  chia/full_node/hint_store.py
  chia/util/db_wrapper.py
  chia/util/initial-config.yaml
  tests/blockchain/blockchain_test_utils.py
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/full_node/ram_db.py
  tests/core/full_node/stores/test_block_store.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/full_node/stores/test_hint_store.py
  tests/core/full_node/test_block_height_map.py
  tests/core/full_node/test_conditions.py
  tests/core/test_db_conversion.py
  tests/core/test_db_validation.py
  tests/core/util/test_db_wrapper.py
  tests/util/blockchain.py
  tests/util/db_connection.py
Labels: ready_to_merge

#10878 use rust clvm in Program.run()
  chia/types/blockchain_format/program.py
  tests/util/network_protocol_data.py
Labels: ready_to_merge

#10921 Fix flaky trade test
  tests/wallet/cat_wallet/test_trades.py
Labels: ready_to_merge

#10906 await the db commit in the async version of set_db_version
  chia/util/db_version.py
Labels: ready_to_merge

#10902 bump pre-commit mypy to v0.942
  .pre-commit-config.yaml
Labels: ready_to_merge

#10698 Switch to integrated lock_and_load_config() context manager
  chia/cmds/configure.py
  chia/cmds/db_upgrade_func.py
  chia/cmds/init_funcs.py
  chia/farmer/farmer.py
  chia/plotting/util.py
  chia/pools/pool_config.py
  chia/util/config.py
  tests/block_tools.py
  tests/core/test_farmer_harvester_rpc.py
  tests/core/util/test_config.py
  tests/pools/test_pool_config.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge

#10892 move pytest.ini to the root directory
  pytest.ini
Labels: ready_to_merge

#10682 set CHIA_ROOT in tests instead of symlinking
  .github/workflows/build-test-macos-blockchain.yml
  .github/workflows/build-test-macos-clvm.yml
  .github/workflows/build-test-macos-core-cmds.yml
  .github/workflows/build-test-macos-core-consensus.yml
  .github/workflows/build-test-macos-core-custom_types.yml
  .github/workflows/build-test-macos-core-daemon.yml
  .github/workflows/build-test-macos-core-full_node-full_sync.yml
  .github/workflows/build-test-macos-core-full_node-stores.yml
  .github/workflows/build-test-macos-core-full_node.yml
  .github/workflows/build-test-macos-core-server.yml
  .github/workflows/build-test-macos-core-ssl.yml
  .github/workflows/build-test-macos-core-util.yml
  .github/workflows/build-test-macos-core.yml
  .github/workflows/build-test-macos-farmer_harvester.yml
  .github/workflows/build-test-macos-generator.yml
  .github/workflows/build-test-macos-plotting.yml
  .github/workflows/build-test-macos-pools.yml
  .github/workflows/build-test-macos-simulation.yml
  .github/workflows/build-test-macos-tools.yml
  .github/workflows/build-test-macos-util.yml
  .github/workflows/build-test-macos-wallet-cat_wallet.yml
  .github/workflows/build-test-macos-wallet-did_wallet.yml
  .github/workflows/build-test-macos-wallet-rl_wallet.yml
  .github/workflows/build-test-macos-wallet-rpc.yml
  .github/workflows/build-test-macos-wallet-simple_sync.yml
  .github/workflows/build-test-macos-wallet-sync.yml
  .github/workflows/build-test-macos-wallet.yml
  .github/workflows/build-test-macos-weight_proof.yml
  .github/workflows/build-test-ubuntu-blockchain.yml
  .github/workflows/build-test-ubuntu-clvm.yml
  .github/workflows/build-test-ubuntu-core-cmds.yml
  .github/workflows/build-test-ubuntu-core-consensus.yml
  .github/workflows/build-test-ubuntu-core-custom_types.yml
  .github/workflows/build-test-ubuntu-core-daemon.yml
  .github/workflows/build-test-ubuntu-core-full_node-full_sync.yml
  .github/workflows/build-test-ubuntu-core-full_node-stores.yml
  .github/workflows/build-test-ubuntu-core-full_node.yml
  .github/workflows/build-test-ubuntu-core-server.yml
  .github/workflows/build-test-ubuntu-core-ssl.yml
  .github/workflows/build-test-ubuntu-core-util.yml
  .github/workflows/build-test-ubuntu-core.yml
  .github/workflows/build-test-ubuntu-farmer_harvester.yml
  .github/workflows/build-test-ubuntu-generator.yml
  .github/workflows/build-test-ubuntu-plotting.yml
  .github/workflows/build-test-ubuntu-pools.yml
  .github/workflows/build-test-ubuntu-simulation.yml
  .github/workflows/build-test-ubuntu-tools.yml
  .github/workflows/build-test-ubuntu-util.yml
  .github/workflows/build-test-ubuntu-wallet-cat_wallet.yml
  .github/workflows/build-test-ubuntu-wallet-did_wallet.yml
  .github/workflows/build-test-ubuntu-wallet-rl_wallet.yml
  .github/workflows/build-test-ubuntu-wallet-rpc.yml
  .github/workflows/build-test-ubuntu-wallet-simple_sync.yml
  .github/workflows/build-test-ubuntu-wallet-sync.yml
  .github/workflows/build-test-ubuntu-wallet.yml
  .github/workflows/build-test-ubuntu-weight_proof.yml
  tests/runner_templates/build-test-macos
  tests/runner_templates/build-test-ubuntu
  tests/runner_templates/checkout-test-plots.include.yml
  tests/util/blockchain.py
Labels: ready_to_merge

#10454 Remove sys.exit() from chia daemon /exit endpoint
  chia/daemon/server.py
Labels: ready_to_merge

#10418 asyncio.get_event_loop() is deprecated in 3.10, stop using it (mostly)
  chia/cmds/chia.py
  chia/cmds/passphrase.py
  chia/cmds/plots.py
  chia/cmds/start.py
  chia/cmds/stop.py
  chia/daemon/server.py
  chia/full_node/full_node.py
  chia/harvester/harvester.py
  chia/plotters/bladebit.py
  chia/plotters/chiapos.py
  chia/plotters/madmax.py
  chia/seeder/dns_server.py
  chia/timelord/timelord_launcher.py
  chia/util/keyring_wrapper.py
Labels: ready_to_merge

#10923 restrict click to < 8.1 for black
  .pre-commit-config.yaml
Labels: ready_to_merge

#10925 fixup workflow template merge env duplication
  .github/workflows/build-test-macos-blockchain.yml
  .github/workflows/build-test-macos-clvm.yml
  .github/workflows/build-test-macos-core-cmds.yml
  .github/workflows/build-test-macos-core-consensus.yml
  .github/workflows/build-test-macos-core-custom_types.yml
  .github/workflows/build-test-macos-core-daemon.yml
  .github/workflows/build-test-macos-core-full_node-full_sync.yml
  .github/workflows/build-test-macos-core-full_node-stores.yml
  .github/workflows/build-test-macos-core-full_node.yml
  .github/workflows/build-test-macos-core-server.yml
  .github/workflows/build-test-macos-core-ssl.yml
  .github/workflows/build-test-macos-core-util.yml
  .github/workflows/build-test-macos-core.yml
  .github/workflows/build-test-macos-farmer_harvester.yml
  .github/workflows/build-test-macos-generator.yml
  .github/workflows/build-test-macos-plotting.yml
  .github/workflows/build-test-macos-pools.yml
  .github/workflows/build-test-macos-simulation.yml
  .github/workflows/build-test-macos-tools.yml
  .github/workflows/build-test-macos-util.yml
  .github/workflows/build-test-macos-wallet-cat_wallet.yml
  .github/workflows/build-test-macos-wallet-did_wallet.yml
  .github/workflows/build-test-macos-wallet-rl_wallet.yml
  .github/workflows/build-test-macos-wallet-rpc.yml
  .github/workflows/build-test-macos-wallet-simple_sync.yml
  .github/workflows/build-test-macos-wallet-sync.yml
  .github/workflows/build-test-macos-wallet.yml
  .github/workflows/build-test-macos-weight_proof.yml
  .github/workflows/build-test-ubuntu-blockchain.yml
  .github/workflows/build-test-ubuntu-clvm.yml
  .github/workflows/build-test-ubuntu-core-cmds.yml
  .github/workflows/build-test-ubuntu-core-consensus.yml
  .github/workflows/build-test-ubuntu-core-custom_types.yml
  .github/workflows/build-test-ubuntu-core-daemon.yml
  .github/workflows/build-test-ubuntu-core-full_node-full_sync.yml
  .github/workflows/build-test-ubuntu-core-full_node-stores.yml
  .github/workflows/build-test-ubuntu-core-full_node.yml
  .github/workflows/build-test-ubuntu-core-server.yml
  .github/workflows/build-test-ubuntu-core-ssl.yml
  .github/workflows/build-test-ubuntu-core-util.yml
  .github/workflows/build-test-ubuntu-core.yml
  .github/workflows/build-test-ubuntu-farmer_harvester.yml
  .github/workflows/build-test-ubuntu-generator.yml
  .github/workflows/build-test-ubuntu-plotting.yml
  .github/workflows/build-test-ubuntu-pools.yml
  .github/workflows/build-test-ubuntu-simulation.yml
  .github/workflows/build-test-ubuntu-tools.yml
  .github/workflows/build-test-ubuntu-util.yml
  .github/workflows/build-test-ubuntu-wallet-cat_wallet.yml
  .github/workflows/build-test-ubuntu-wallet-did_wallet.yml
  .github/workflows/build-test-ubuntu-wallet-rl_wallet.yml
  .github/workflows/build-test-ubuntu-wallet-rpc.yml
  .github/workflows/build-test-ubuntu-wallet-simple_sync.yml
  .github/workflows/build-test-ubuntu-wallet-sync.yml
  .github/workflows/build-test-ubuntu-wallet.yml
  .github/workflows/build-test-ubuntu-weight_proof.yml
  tests/runner_templates/build-test-macos
  tests/runner_templates/build-test-ubuntu
Labels: ready_to_merge

#10926 ignore lack of hinting on clvm_tools.binutils.assemble()
  chia/wallet/puzzles/prefarm/make_prefarm_ph.py
Labels: ready_to_merge

#10942 Contextualize some store test db names
  tests/pools/test_wallet_pool_store.py
  tests/wallet/test_wallet_blockchain.py
  tests/wallet/test_wallet_interested_store.py
  tests/wallet/test_wallet_key_val_store.py
Labels: ready_to_merge

#10935 Add more type checks to RL Wallet
  chia/wallet/rl_wallet/rl_wallet.py
Labels: ready_to_merge

#10934 Type check CAT Wallet
  chia/wallet/cat_wallet/cat_wallet.py
Labels: ready_to_merge

#10778 Consolidate test fixtures
  tests/blockchain/test_blockchain_transactions.py
  tests/conftest.py
  tests/core/daemon/test_daemon.py
  tests/core/full_node/full_sync/test_full_sync.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/full_node/test_full_node.py
  tests/core/full_node/test_mempool_performance.py
  tests/core/full_node/test_performance.py
  tests/core/full_node/test_transactions.py
  tests/core/server/test_dos.py
  tests/core/ssl/test_ssl.py
  tests/core/test_daemon_rpc.py
  tests/core/test_filter.py
  tests/core/test_full_node_rpc.py
  tests/pools/test_pool_rpc.py
  tests/wallet/cat_wallet/test_cat_lifecycle.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/cat_wallet/test_offer_lifecycle.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/did_wallet/test_did_rpc.py
  tests/wallet/rl_wallet/test_rl_rpc.py
  tests/wallet/rl_wallet/test_rl_wallet.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_blockchain.py
Labels: ready_to_merge

#10952 Quick fix for improper v2 DB initialization when targeting testnet
  chia/full_node/full_node.py
Labels: ready_to_merge

#10960 run more tests in parallel on CI
  .github/workflows/build-test-macos-core-full_node-full_sync.yml
  .github/workflows/build-test-macos-core-ssl.yml
  .github/workflows/build-test-macos-core-util.yml
  .github/workflows/build-test-macos-core.yml
  .github/workflows/build-test-ubuntu-core-full_node-full_sync.yml
  .github/workflows/build-test-ubuntu-core-ssl.yml
  .github/workflows/build-test-ubuntu-core-util.yml
  .github/workflows/build-test-ubuntu-core.yml
  tests/build-workflows.py
  tests/core/config.py
  tests/core/full_node/full_sync/config.py
  tests/core/ssl/config.py
  tests/core/test_farmer_harvester_rpc.py
  tests/core/util/config.py
Labels: ready_to_merge

#10958 improve error message when a block is missing from the blockchain database
  chia/full_node/block_height_map.py
Labels: ready_to_merge

#10947 Also throw DB error on double spending a coin
  chia/full_node/coin_store.py
  tests/core/full_node/stores/test_coin_store.py
Labels: ready_to_merge

#10943 reorg fixes
  chia/consensus/blockchain.py
  chia/full_node/block_height_map.py
  tests/block_tools.py
  tests/blockchain/blockchain_test_utils.py
  tests/blockchain/test_blockchain.py
  tests/core/full_node/test_block_height_map.py
Labels: ready_to_merge

#10977 Fix the issues in main (failing tests)
  chia/consensus/blockchain.py
  tests/blockchain/test_blockchain.py
Labels: ready_to_merge
