Repository Chia-Network/chia-blockchain, pull requests merged in 2023-03, with the labels that each got.

#14712 Soft fork2 tests
  chia/consensus/block_body_validation.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/mempool_check_conditions.py
  tests/blockchain/test_blockchain.py
  tests/core/full_node/test_conditions.py
  tests/core/mempool/test_mempool_manager.py
Labels: ready_to_merge, Changed, Tests

#14711 Fix Pool Wallet check for invalid state
  chia/pools/pool_wallet.py
Labels: ready_to_merge, Clean: caught up to main, Changed, CI

#14661 anyio is needed as a standard dependency for the simulator
  setup.py
Labels: Fixed

#14719 fixup ephemeral coin test in test_mempool
  tests/core/mempool/test_mempool.py
Labels: ready_to_merge, Changed, Tests

#14657 sqlite-backed mempool
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/types/mempool_item.py
  chia/util/db_wrapper.py
  tests/core/mempool/test_mempool_fee_estimator.py
  tests/core/mempool/test_mempool_manager.py
  tests/core/test_full_node_rpc.py
  tests/fee_estimation/test_fee_estimation_integration.py
Labels: ready_to_merge, Changed

#14725 Quick fix to some hostname problems
  chia/rpc/rpc_server.py
  chia/seeder/crawler.py
Labels: Fixed, Cleanup

#14720 Bump chia_rs to 0.2.3. and ASSERT_MY_BIRTH_*
  benchmarks/mempool.py
  chia/full_node/mempool_check_conditions.py
  chia/types/condition_opcodes.py
  chia/util/errors.py
  setup.py
  tests/blockchain/test_blockchain.py
  tests/core/full_node/test_conditions.py
  tests/core/full_node/test_generator_tools.py
  tests/core/full_node/test_hint_management.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_manager.py
  tests/fee_estimation/test_fee_estimation_integration.py
  tests/generator/test_rom.py
Labels: ready_to_merge, Changed

#14731 Listen on ::0 so we can respond to both ipv4 and ipv6
  chia/seeder/dns_server.py
Labels: Fixed

#14729 parameterize Timelock and compute_assert_height tests
  tests/core/mempool/test_mempool_manager.py
Labels: ready_to_merge, Changed, Tests

#14740 correct Announcement.__str__() to present hex
  chia/types/announcement.py
Labels: Fixed, Cleanup

#14734 hint chia.cmds.farm_funcs
  chia/cmds/farm_funcs.py
Labels: Fixed, Cleanup

#14735 hint chia.cmds.keys, keys_funcs
  chia/cmds/keys.py
  chia/cmds/keys_funcs.py
Labels: Fixed, Cleanup

#14737 hint chia.cmds.plotnft, plotnft_funcs
  chia/cmds/plotnft.py
  chia/cmds/plotnft_funcs.py
Labels: Fixed, Cleanup

#14738 hint_benchmarks
  benchmarks/block_ref.py
  benchmarks/block_store.py
  benchmarks/coin_store.py
  benchmarks/utils.py
Labels: Fixed, Cleanup

#14739 hint build_scripts
  build_scripts/installer-version.py
Labels: Fixed, Cleanup

#14750 ignore pkg_resources deprecation warning
  pytest.ini
Labels: Changed, Cleanup

#14721 fix DataStore.get_tree_generation() detection of no generations
  chia/data_layer/data_store.py
  tests/core/data_layer/test_data_store.py
Labels: Fixed, Cleanup

#14662 simplify and improve daemon connection handling
  chia/daemon/server.py
  chia/util/ws_message.py
  tests/conftest.py
  tests/core/daemon/test_daemon.py
  tests/core/daemon/test_daemon_register.py
Labels: Fixed, Cleanup

#14546 Move startup / shutdown logging to INFO
  chia/server/start_service.py
Labels: Clean: caught up to main, Changed, Logging

#14592 server: Drop outdated config update
  chia/server/start_wallet.py
Labels: Changed, Cleanup

#14741 hint most chia.types
  chia/consensus/block_header_validation.py
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/simulator/block_tools.py
  chia/types/announcement.py
  chia/types/blockchain_format/classgroup.py
  chia/types/blockchain_format/proof_of_space.py
  chia/types/blockchain_format/tree_hash.py
  chia/types/blockchain_format/vdf.py
  chia/types/full_block.py
  chia/types/header_block.py
  chia/types/spend_bundle.py
  chia/types/transaction_queue_entry.py
  chia/types/unfinished_block.py
  chia/types/unfinished_header_block.py
  chia/util/check_fork_next_block.py
  chia/wallet/cat_wallet/cat_utils.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet_node.py
  tests/core/data_layer/conftest.py
  tests/core/data_layer/test_data_store.py
  tests/core/data_layer/test_data_store_schema.py
  tests/core/data_layer/util.py
Labels: Fixed, Cleanup

#14701 switching more API calls to gh cli
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
  .github/workflows/test-single.yml
Labels: Changed, CI

#14760 update mypy.ini
  chia/types/blockchain_format/vdf.py
  mypy.ini
Labels: ready_to_merge, Changed, Cleanup, ready_to_review

#14767 catch up with mypy 1.1.1
  chia/full_node/weight_proof.py
  chia/util/streamable.py
  tests/core/test_farmer_harvester_rpc.py
  tests/fee_estimation/test_fee_estimation_integration.py
  tests/plot_sync/test_plot_sync.py
  tests/plot_sync/test_sync_simulated.py
Labels: Fixed, Cleanup

#14765 Adding Changed label to dependabot updates
  .github/dependabot.yml
Labels: Changed

#14758 Bump chia rs 0.2.4
  benchmarks/mempool.py
  chia/full_node/mempool_check_conditions.py
  chia/full_node/mempool_manager.py
  setup.py
  tests/conftest.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_manager.py
  tests/generator/test_rom.py
Labels: Changed

#14769 Don't create a coin for 0 amount royalty payments
  chia/wallet/nft_wallet/nft_wallet.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
Labels: ready_to_merge, Fixed

#14694 hint chia.pools.pool_wallet
  chia/pools/pool_wallet.py
Labels: Changed, Cleanup

#14776 Cleanup tests
  tests/blockchain/test_blockchain.py
  tests/core/mempool/test_mempool_manager.py
  tests/core/test_cost_calculation.py
Labels: ready_to_merge, Changed, Tests

#14777 full_node: Drop cache logs in `BlockStore`
  chia/full_node/block_store.py
Labels: Changed, Cleanup

#14692 hint chia.plotting.create_plots
  chia/cmds/plots.py
  chia/plotters/chiapos.py
  chia/plotting/create_plots.py
  chia/plotting/util.py
  chia/simulator/block_tools.py
Labels: Changed, Cleanup

#3954 avoid AttributeError when shutting down plotting
  chia/daemon/server.py
  tests/core/daemon/test_daemon.py
Labels: Fixed

#14700 Add unit tests for create_bundle_from_mempool
  tests/core/mempool/test_mempool_manager.py
Labels: ready_to_merge, Added, Cleanup

#14422 Stop sending change to a new address
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/util/initial-config.yaml
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
  chia/wallet/wallet.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/test_wallet.py
Labels: ready_to_merge, Changed

#14786 disable soft-fork 2 (for now)
  chia/consensus/default_constants.py
  chia/full_node/mempool_check_conditions.py
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/full_node/test_conditions.py
  tests/core/mempool/test_mempool_manager.py
Labels: Changed

#14788 in mempool, support sqlite without generated columns
  chia/full_node/mempool.py
Labels: Changed

#14801 Update the README to link to the Chia website
  README.md
Labels: documentation, Added

#14807 bump chiapos and fix lint
  chia/harvester/harvester_api.py
  chia/plotting/manager.py
  setup.py
Labels: Changed

#14789 nft royalty edge cases
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
Labels: ready_to_merge, Fixed, Tests, 1.7.1

#14830 checkpoint: into main from release/1.7.1 @ a6f423522bff6d81d06bc6617caed405d0357aaa
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
Labels: checkpoint_merge, Changed

#14813 wallet: Don't just subscribe to all coin ids from the DB
  chia/wallet/wallet_coin_store.py
  chia/wallet/wallet_node.py
  tests/wallet/test_wallet_coin_store.py
Labels: Changed

#14812 better handling of offer status and failed txs
  chia/wallet/trade_manager.py
  chia/wallet/transaction_record.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
  chia/wallet/wallet_transaction_store.py
  tests/wallet/cat_wallet/test_trades.py
Labels: ready_to_merge, Fixed, 1.7.1

#14833 wallet: Handle trade coins in the `try` block of `new_coin_state`
  chia/wallet/wallet_state_manager.py
Labels: Changed

#14782 Added `chia completion` command
  chia/cmds/chia.py
  chia/cmds/completion.py
Labels: CLI, Added, ready_to_review

#14836 checkpoint: into main from release/1.7.1 @ 6d09a060379a0eb77d11abf52ba810c93bd4be5f
  chia/wallet/trade_manager.py
  chia/wallet/transaction_record.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
  chia/wallet/wallet_transaction_store.py
  tests/wallet/cat_wallet/test_trades.py
Labels: checkpoint_merge, Changed

#14841 Test cleanups
  tests/blockchain/test_blockchain.py
  tests/core/full_node/test_conditions.py
  tests/core/mempool/test_mempool_manager.py
Labels: ready_to_merge, Changed, Tests

#14640 wallet: Disconnect untrusted peers if we find a trusted synced one
  chia/wallet/wallet_node.py
  chia/wallet/wallet_node_api.py
  tests/wallet/sync/test_wallet_sync.py
Labels: Fixed, Requires Decision

#14834 tests: Fix flaky RPC related tests in `test_nft_bulk_mint.py`
  tests/wallet/nft_wallet/test_nft_bulk_mint.py
Labels: ready_to_merge, Fixed, Tests

#14840 Only compile CLVM if source newer than hex
  chia/wallet/puzzles/load_clvm.py
Labels: Fixed

#14846 fix renaming of respond_block -> add_block
  tests/wallet/sync/test_wallet_sync.py
Labels: Fixed, Tests

#14828 wallet: Return a dict in `WalletCoinStore.get_coin_records`
  chia/rpc/wallet_rpc_api.py
  chia/wallet/wallet_coin_store.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/test_wallet_coin_store.py
Labels: Changed, Cleanup

#14851 fixup tests that do not close all event loops
  tests/core/server/test_event_loop.py
  tests/core/server/test_loop.py
  tests/wallet/db_wallet/test_dl_wallet.py
Labels: Fixed, Tests

#14859 pin pytest-asyncio just for release branch
  setup.py
Labels: Changed, Cleanup

#14860 1.7.1 fixes
  chia/consensus/blockchain.py
  chia/types/blockchain_format/program.py
  chia/wallet/util/puzzle_compression.py
  tests/clvm/test_puzzle_compression.py
  tests/core/full_node/test_full_node.py
Labels: Fixed, Cleanup

#14849 exclude CompressorArg.generator from repr() due to size
  chia/types/generator_types.py
Labels: Fixed

#14855 added wallet_removed to allowed changes
  chia/rpc/wallet_rpc_api.py
Labels: Added

#14730 Add support to cat_spend RPC for running TAIL
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/cat_wallet/cat_wallet.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge, Added

#14872 Update NFT wallet test timeout to 55m
  tests/wallet/nft_wallet/config.py
Labels: Fixed, CI

#14864 `can_replace()` tests
  chia/full_node/mempool_manager.py
  chia/types/mempool_item.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_manager.py
Labels: ready_to_merge, Changed, Tests, Cleanup

#14858 Add placeholders for DAO Wallet directories
  chia/wallet/dao_wallet/__init__.py
  tests/wallet/dao_wallet/__init__.py
Labels: Clean: caught up to main, Changed

#14799 Staging changelog for updates
  CHANGELOG.md
Labels: Changed, Cleanup

#14881 increase wallet.nft_wallet test job timeout to 70 minutes
  tests/wallet/nft_wallet/config.py
Labels: Fixed, CI

#14805 remove traceback from LockQueue._run() cancellation debug logging
  chia/full_node/lock_queue.py
Labels: Fixed, Cleanup

#14885 wallet: Cleanup `get_timestamp_for_height` + Drop `height_to_time`
  chia/wallet/wallet_node.py
Labels: Changed, Cleanup

#14901 checkpoint: into main from release/1.7.1 @ f637881f80049f5648acd1936a2da936b5ca79a1
  chia/consensus/blockchain.py
  chia/types/blockchain_format/program.py
  chia/wallet/util/puzzle_compression.py
  tests/clvm/test_puzzle_compression.py
  tests/core/full_node/test_full_node.py
Labels: checkpoint_merge, Changed

#14852 wallet: Simplify `WalletStateManager.coin_added`
  chia/wallet/wallet_state_manager.py
Labels: Changed, Cleanup

#14876 wallet: Drop some unused members of `WalletNode`
  chia/server/start_wallet.py
  chia/wallet/wallet_node.py
Labels: Changed, Cleanup

#14850 Remove no longer needed cost_per_byte cases
  chia/clvm/spend_sim.py
  chia/consensus/block_body_validation.py
  chia/consensus/block_creation.py
  chia/consensus/blockchain.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool_check_conditions.py
  chia/full_node/mempool_manager.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/wallet.py
  tests/blockchain/test_blockchain.py
  tests/blockchain/test_blockchain_transactions.py
  tests/clvm/benchmark_costs.py
  tests/clvm/coin_store.py
  tests/clvm/test_puzzles.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/mempool/test_mempool.py
  tests/core/test_cost_calculation.py
  tests/generator/test_rom.py
  tests/pools/test_pool_puzzles_lifecycle.py
  tests/util/generator_tools_testing.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/test_singleton_lifecycle_fast.py
Labels: Changed, Cleanup

#14905 checkpoint: into main from release/1.7.1 @ 9a4b42b022a31357e36fd92900cf3efc3be8a02d
  chia/types/generator_types.py
Labels: checkpoint_merge, Changed

#14904 Fixed windows issues with passphrase prompt on CLI by flushing prompt
  chia/cmds/passphrase_funcs.py
Labels: Fixed

#14887 daemon: Fix removal while iterating over connections set
  chia/daemon/server.py
Labels: Fixed

#14862 wallet: Drop `WalletCoinStore.get_multiple_coin_records`
  chia/wallet/trade_manager.py
  chia/wallet/wallet_coin_store.py
  tests/wallet/test_wallet_coin_store.py
Labels: Changed, Cleanup

#14886 wallet: Rename `WalletNode.untrusted_caches` -> `WalletNode.peer_caches`
  chia/wallet/wallet_node.py
Labels: Changed, Cleanup

#14897 wallet: Some `WalletType` cleanup
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_protocol.py
  chia/wallet/wallet_state_manager.py
Labels: Changed, Cleanup

#14912 wallet: Enable and fix more `mypy` in `wallet_weight_proof_handler.py`
  chia/wallet/wallet_weight_proof_handler.py
  mypy.ini
Labels: Changed, Cleanup

#14906 Adding py version exclusion
  .github/workflows/test-single.yml
  .github/workflows/test.yml
Labels: Changed, CI

#14916 checkpoint: into main from release/1.7.1 @ ba2570f50fed64be92a49f1342fd0cc3ff014831
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#14459 consensus: Rename add block method/enum
  chia/consensus/blockchain.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
  chia/simulator/full_node_simulator.py
  chia/wallet/wallet_blockchain.py
  chia/wallet/wallet_node.py
  tests/blockchain/blockchain_test_utils.py
  tests/blockchain/test_blockchain.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/full_node/test_conditions.py
  tests/core/test_db_conversion.py
  tests/core/test_db_validation.py
  tests/wallet/test_wallet_blockchain.py
Labels: Changed, Cleanup

#14863 wallet: Some tweaks and rename of `WalletStateManager.new_coin_state`
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
Labels: Changed, Cleanup

#14918 Minor simplification to the mempool conflicts check
  chia/full_node/mempool_manager.py
Labels: Changed, Cleanup

#14723 update condition codes constants in clvm include file
  chia/types/condition_opcodes.py
  chia/wallet/puzzles/condition_codes.clvm
Labels: ready_to_merge, Changed

#14914 Improve core mempool test runs
  tests/core/mempool/config.py
Labels: Changed, Cleanup

#14919 wallet: Drop some parameters from `WalletStateManager.add_new_wallet`
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/cat_wallet/test_cat_wallet.py
Labels: Changed, Cleanup

#14815 Add unit tests for replace by fee dynamics
  tests/core/mempool/test_mempool_manager.py
Labels: Added, Cleanup

#14847 slightly faster nft complex offer tests
  chia/wallet/cat_wallet/cat_outer_puzzle.py
  chia/wallet/nft_wallet/metadata_outer_puzzle.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/nft_wallet/singleton_outer_puzzle.py
  chia/wallet/puzzle_drivers.py
  chia/wallet/trading/offer.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_bulk_mint.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: Fixed, Tests

#14926 Fix the mempool fee rate calculation
  chia/full_node/mempool.py
  tests/core/mempool/test_mempool_manager.py
Labels: Fixed

#14931 assert_before_height, assert_before_seconds fields in MempoolItem
  chia/full_node/mempool.py
  tests/core/mempool/test_mempool_manager.py
Labels: ready_to_merge, Fixed

#14955 Make sql pre-commit check work when pre-commit hooks are in non-standard locations
  tests/check_sql_statements.py
Labels: ready_to_merge, Changed, Tests
