Repository Chia-Network/chia-blockchain, pull requests merged in 2023-02, with the labels that each got.

#14450 Check incoming notification hints
  chia/wallet/notification_manager.py
  tests/wallet/test_notifications.py
Labels: Fixed

#14434 Add a way to import a SpendSim and SimClient as a contextmanager
  chia/clvm/spend_sim.py
  tests/clvm/test_singletons.py
  tests/clvm/test_spend_sim.py
  tests/conftest.py
  tests/fee_estimation/test_mempoolitem_height_added.py
  tests/wallet/cat_wallet/test_cat_lifecycle.py
  tests/wallet/cat_wallet/test_offer_lifecycle.py
  tests/wallet/db_wallet/test_db_graftroot.py
  tests/wallet/nft_wallet/test_nft_lifecycle.py
Labels: ready_to_merge, Added, Tests

#14464 Typecheck _set_state_changed_callback
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_api.py
  chia/farmer/farmer.py
  chia/full_node/full_node.py
  chia/harvester/harvester.py
  chia/introducer/introducer.py
  chia/introducer/introducer_api.py
  chia/rpc/rpc_server.py
  chia/seeder/crawler.py
  chia/timelord/timelord.py
  chia/timelord/timelord_api.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
Labels: Changed, Cleanup

#14474 Correct fee estimate calculation to be in mojos, not millimojos
  chia/cmds/show_funcs.py
  chia/full_node/bitcoin_fee_estimator.py
  chia/full_node/fee_estimate.py
  chia/full_node/fee_estimator.py
  chia/full_node/fee_estimator_example.py
  chia/full_node/fee_estimator_interface.py
  chia/full_node/full_node_api.py
  chia/types/fee_rate.py
  tests/fee_estimation/test_fee_estimation_integration.py
  tests/fee_estimation/test_fee_estimation_unit_tests.py
Labels: Fixed

#14140 Add diff-cover report
  .github/workflows/test.yml
Labels: Added, CI

#14365 RPC call to reset wallet sync data
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/server/start_wallet.py
  chia/util/initial-config.yaml
  chia/wallet/wallet_node.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge, Added

#14420 Assert that we're getting a sensible limit in get_items_not_in_filter
  chia/full_node/mempool_manager.py
Labels: ready_to_merge, Changed, Cleanup

#14441 add unit test for mempool_check_time_locks
  tests/core/mempool/test_mempool_manager.py
Labels: ready_to_merge, Changed, Tests

#14466 server: Exclude some attributes from `WSChiaConnection.__repr__`
  chia/server/ws_connection.py
  tests/core/server/test_server.py
Labels: Changed, Cleanup

#14470 make the tests use the real COST_PER_BYTE constant
  chia/simulator/block_tools.py
  tests/core/full_node/test_full_node.py
Labels: ready_to_merge, Changed, Tests

#14491 gc.collect() before unlinking the db in some tests
  chia/simulator/setup_services.py
Labels: Fixed, CI

#14165 simulator: Replace `localhost` -> `127.0.0.1` in farmer/harvester config
  chia/simulator/setup_services.py
Labels: Changed, Tests, ready_to_review

#14433 Add unit tests for ephemeral time locks
  tests/core/mempool/test_mempool_manager.py
Labels: Added, Cleanup

#14368 Ensure fee estimates monotonically decrease with time
  chia/rpc/full_node_rpc_api.py
  chia/util/math.py
  tests/fee_estimation/test_fee_estimation_unit_tests.py
Labels: Changed

#14492 simplify get_block_spends()
  chia/full_node/mempool_check_conditions.py
  chia/rpc/full_node_rpc_api.py
  chia/wallet/puzzles/decompress_block_spends.clvm
  chia/wallet/puzzles/decompress_block_spends.clvm.hex
  chia/wallet/puzzles/decompress_block_spends.clvm.hex.sha256tree
  chia/wallet/puzzles/decompress_block_spends.py
Labels: ready_to_merge, Changed, Cleanup

#14503 pin mypy to < 1
  setup.py
Labels: Fixed, CI

#14504 pin mypy to < 1
  setup.py
Labels: Fixed, CI

#14497 Adding Community seeders/dns introducers
  chia/util/initial-config.yaml
Labels: Added

#14478 Quex.offer mod tests
  chia/data_layer/data_layer_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
  chia/wallet/trading/offer.py
  tests/clvm/test_puzzle_compression.py
  tests/core/data_layer/test_data_rpc.py
  tests/wallet/cat_wallet/test_offer_lifecycle.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/db_wallet/test_dl_offers.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
Labels: Fixed

#14362 wallet: Drop `WalletNode._primary_peer_sync_task`, just await the sync
  chia/wallet/wallet_node.py
Labels: Changed, Cleanup, ready_to_review

#14416 Add unit tests for get_items_not_in_filter
  tests/core/mempool/test_mempool_manager.py
Labels: Added, Cleanup

#14502 checkpoint: into main from release/1.7.0 @ d1a4c579f4dd2b058fcd46f2249a876a60b1dec5
  chia/wallet/notification_manager.py
  tests/wallet/test_notifications.py
Labels: checkpoint_merge, Changed

#14508 checkpoint: into main from release/1.7.0 @ 83c864b2f099afcbf93845d9e720a523d11a3eaa
  chia/cmds/show_funcs.py
  chia/full_node/bitcoin_fee_estimator.py
  chia/full_node/fee_estimate.py
  chia/full_node/fee_estimator.py
  chia/full_node/fee_estimator_example.py
  chia/full_node/fee_estimator_interface.py
  chia/full_node/full_node_api.py
  chia/types/fee_rate.py
  tests/fee_estimation/test_fee_estimation_integration.py
  tests/fee_estimation/test_fee_estimation_unit_tests.py
Labels: checkpoint_merge, Changed

#14512 checkpoint: into main from release/1.7.0 @ 9be3c7d00ae99105c40913aff1b07e97657609fb
  chia/rpc/full_node_rpc_api.py
  chia/util/math.py
  tests/fee_estimation/test_fee_estimation_unit_tests.py
Labels: checkpoint_merge, Changed

#14421 fix reporting of deprecation of plotter install and bladebit2 commands
  chia/plotters/plotters.py
Labels: Fixed, Cleanup

#14456 Don't print entire TransactionRecord to log file
  chia/wallet/wallet.py
Labels: Changed

#14454 Return a better error message when the 'coin_id' argument for nft_get_info cannot be decoded into a 32 byte hex string
  chia/rpc/wallet_rpc_api.py
Labels: Clean: caught up to main, PR, Changed, Logging

#14477 remove test aimed at the inital soft-fork to enable transactions
  tests/core/full_node/test_full_node.py
Labels: ready_to_merge, Changed, Tests

#14447 Always Log service startup and shutdown.
  chia/server/start_service.py
Labels: Clean: caught up to main, Changed, Logging

#14451 Output proper json
  chia/cmds/show_funcs.py
Labels: CLI, Clean: caught up to main, PR, Changed

#14480 fix crossed parameters for setup_simulators_and_wallets_inner() calling setup_full_node()
  chia/simulator/setup_nodes.py
Labels: Fixed, Tests

#14513 Fix get memo API
  chia/rpc/wallet_rpc_api.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/test_wallet.py
Labels: Fixed

#14196 refactor test_pool_rpc
  chia/simulator/full_node_simulator.py
  tests/conftest.py
  tests/pools/test_pool_rpc.py
  tests/wallet/test_wallet_retry.py
Labels: Fixed, Tests, Cleanup

#14482 Ak.test nft mint from xch rpc
  chia/wallet/wallet_state_manager.py
  tests/wallet/nft_wallet/test_nft_bulk_mint.py
Labels: Fixed, CI

#14519 Using gh-cli instead of curl for API calls to avoid rate-limiting
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: Changed, CI

#14520 wallet: Don't update `FINISHED_SYNC_UP_TO` during long sync
  chia/wallet/wallet_node.py
Labels: Fixed

#14438 full_node: Use more `ChiaServer.get_connections`
  chia/full_node/full_node.py
Labels: Changed, Cleanup

#14437 full_node: Drop unused `FullNode._num_needed_peers`
  chia/full_node/full_node.py
Labels: Changed, Cleanup

#14435 Rate limit 'Rate limiting' message
  chia/server/ws_connection.py
Labels: Clean: caught up to main, Changed, Logging

#14432 full_node: Hint the sync store and create it earlier
  chia/full_node/full_node.py
Labels: Changed, Cleanup

#14383 Delete lgtm.yml
  lgtm.yml
Labels: Changed, CI

#14431 rpc: Dont't expect `WalletNode._await_closed` to maybe return a task
  chia/rpc/wallet_rpc_api.py
Labels: Changed, Cleanup

#14472 wallet: Drop `async` for `can_use_peer_request_cache`
  chia/wallet/util/peer_request_cache.py
  chia/wallet/wallet_node.py
Labels: Changed, Cleanup

#14443 bookworm uses 3.11, catch up comment
  .github/workflows/test-install-scripts.yml
Labels: Changed, CI

#14251 update GUI when wallets are removed
  chia/wallet/wallet_state_manager.py
Labels: Changed

#14523 let sqlite count NFTs on removal
  chia/wallet/nft_wallet/nft_wallet.py
Labels: ready_to_merge, Changed

#14535 Purposefully break offer compression for older versions
  chia/wallet/trading/offer.py
  chia/wallet/util/puzzle_compression.py
Labels: Fixed

#14506 Revert "pin mypy to < 1 (#14504)"
  chia/util/files.py
  setup.py
Labels: Fixed, Tests

#14518 mypy: Fix `wallet_blockchain.py` and `wallet_sync_utils.py`
  chia/wallet/util/wallet_sync_utils.py
  chia/wallet/wallet_blockchain.py
  mypy.ini
Labels: Changed, Cleanup

#14529 Offer CLI command help now shows --fee units as XCH
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
Labels: Changed

#14532 checkpoint: into main from release/1.7.0 @ 9cc25cc820accad778bf626500aedd299f62a825
  chia/data_layer/data_layer_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
  chia/wallet/trading/offer.py
  tests/clvm/test_puzzle_compression.py
  tests/core/data_layer/test_data_rpc.py
  tests/wallet/cat_wallet/test_offer_lifecycle.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/db_wallet/test_dl_offers.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
Labels: checkpoint_merge, Changed

#14403 move wallet_is_synced/wallets_are_synced to FullNodeSimulator methods
  chia/simulator/full_node_simulator.py
  tests/conftest.py
  tests/core/data_layer/test_data_rpc.py
  tests/core/full_node/test_full_node.py
  tests/pools/test_pool_rpc.py
  tests/util/wallet_is_synced.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_bulk_mint.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_notifications.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_retry.py
Labels: Changed, Tests

#14444 Add cost logging to CLVM tests as fixture
  chia/clvm/spend_sim.py
  tests/clvm/test_singletons.py
  tests/conftest.py
  tests/wallet/cat_wallet/test_cat_lifecycle.py
  tests/wallet/cat_wallet/test_offer_lifecycle.py
  tests/wallet/db_wallet/test_db_graftroot.py
  tests/wallet/nft_wallet/test_nft_lifecycle.py
Labels: Added, Tests

#14531 optimize offers
  chia/cmds/wallet_funcs.py
  chia/data_layer/data_layer_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/types/spend_bundle.py
  chia/wallet/trade_manager.py
  chia/wallet/trade_record.py
  chia/wallet/trading/offer.py
Labels: ready_to_merge, Changed

#14533 bump chia_rs to 0.2.2
  chia/full_node/mempool_check_conditions.py
  chia/types/condition_opcodes.py
  chia/util/errors.py
  setup.py
  tests/clvm/test_puzzles.py
  tests/core/full_node/test_generator_tools.py
  tests/core/full_node/test_hint_management.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_manager.py
  tests/generator/test_rom.py
  tests/pools/test_pool_puzzles_lifecycle.py
Labels: ready_to_merge, Changed

#14542 Improve the help text for the peer command
  chia/cmds/peer.py
Labels: Changed

#14544 use run_block_generator() to run block generators
  chia/full_node/mempool_check_conditions.py
  chia/simulator/block_tools.py
  tests/core/test_cost_calculation.py
Labels: Changed, Cleanup

#14552 zstd==1.5.4.0
  setup.py
Labels: Changed, Cleanup

#14559 Simplify MINTING_COIN and RESERVE_FEE_CONDITION_FAILED unit tests
  tests/core/mempool/test_mempool_manager.py
Labels: ready_to_merge, Changed, Cleanup

#14556 Add dexie DNS seeder
  chia/util/initial-config.yaml
Labels: ready_to_merge, Added

#14545 Test DID Wallet creation by blockchain singleton update
  tests/conftest.py
  tests/wallet/did_wallet/test_did.py
Labels: Clean: caught up to main, Changed, Tests

#14550 checkpoint: into main from release/1.7.0 @ 5f737cc094d1a077755f0bb00ad5b7a56870a988
  chia/wallet/trading/offer.py
  chia/wallet/util/puzzle_compression.py
Labels: ready_to_merge, checkpoint_merge, Changed

#14562 full node optimizations
  chia/consensus/block_body_validation.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/coin_store.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/hint_store.py
  chia/full_node/mempool_manager.py
  chia/full_node/subscriptions.py
  chia/server/chia_policy.py
  chia/server/start_full_node.py
  chia/server/start_service.py
  chia/util/condition_tools.py
  chia/util/initial-config.yaml
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/stores/test_hint_store.py
  tests/core/full_node/test_subscriptions.py
  tests/core/mempool/test_mempool.py
  tests/core/server/flood.py
  tests/core/server/serve.py
  tests/core/server/test_event_loop.py
  tests/core/server/test_loop.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tools/analyze-chain.py
Labels: Changed, Cleanup

#14566 fixup event loop method testing
  tests/core/server/test_event_loop.py
  tests/core/server/test_loop.py
Labels: Changed, CI, Cleanup

#14582 1.7.0 Changelog
  CHANGELOG.md
Labels: Changed, Cleanup

#14404 Simplify request_mempool_transactions() and get_items_not_in_filter()
  chia/full_node/full_node_api.py
  chia/full_node/mempool_manager.py
  tests/core/mempool/test_mempool_manager.py
Labels: ready_to_merge, Changed

#14522 Fix removing spend bundles from the mempool when a new peak is available
  chia/full_node/mempool_manager.py
Labels: ready_to_merge, Changed, Cleanup

#14543 simplify compute_additions and remove unnecessary functions
  chia/simulator/block_tools.py
  chia/types/coin_spend.py
  chia/util/chain_utils.py
Labels: ready_to_merge, Changed, Cleanup

#14560 Remove redundant checks for minting coin and reserve fee
  chia/full_node/mempool_manager.py
Labels: ready_to_merge, Changed

#14567 parameterize TestConditions
  tests/core/full_node/test_conditions.py
Labels: ready_to_merge, Changed, Tests

#14570 rpc endpoint to count nfts per wallet or all wallets
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: ready_to_merge, Added

#14581 fix typo introduced in bumping of chia-rs dependency
  chia/util/errors.py
Labels: ready_to_merge, Fixed, Cleanup

#14585 Remove unneeded f-string notation
  chia/wallet/chialisp.py
Labels: ready_to_merge, Changed, Cleanup

#14587 Augment mempool's total_mempool_fees to int as it shouldn't be limited by type Mojos
  chia/full_node/fee_estimation.py
  chia/full_node/mempool.py
  tests/core/mempool/test_mempool_fee_estimator.py
Labels: Changed

#14575 catchup: into main from release/1.7.0 @ 124961a355e6175037067a06f5f2ab18600dfdf1
  chia/consensus/block_body_validation.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/coin_store.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/hint_store.py
  chia/full_node/mempool_manager.py
  chia/full_node/subscriptions.py
  chia/server/chia_policy.py
  chia/server/start_full_node.py
  chia/server/start_service.py
  chia/util/condition_tools.py
  chia/util/initial-config.yaml
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/stores/test_hint_store.py
  tests/core/full_node/test_subscriptions.py
  tests/core/mempool/test_mempool.py
  tests/core/server/flood.py
  tests/core/server/serve.py
  tests/core/server/test_event_loop.py
  tests/core/server/test_loop.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tools/analyze-chain.py
Labels: checkpoint_merge, Changed

#14561 nft paging at sqlite level
  chia/rpc/wallet_rpc_api.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet_nft_store.py
  tests/wallet/test_nft_store.py
Labels: ready_to_merge, Changed

#14594 checkpoint: into main from release/1.7.0 @ a8bcb8516e695e69e271b78241c0b4b9f41093c4
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#14584 Ignore unused config value in the DataLayer CLI commands
  chia/cmds/data_funcs.py
Labels: Changed, Cleanup

#14590 Don't raise on lack of hints in notification manager
  chia/wallet/notification_manager.py
Labels: Fixed

#14597 fixup test_agg_sig_unsafe() softfork fixture usage
  tests/core/mempool/test_mempool.py
Labels: Fixed, Tests

#14620 Remove leading / from endpoint
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: Fixed, CI

#14618 handle ._get_extra_info() call on a closing connection
  chia/server/ws_connection.py
Labels: Fixed

#14630 tests: Setup 4 nodes in `setup_four_nodes`
  tests/conftest.py
Labels: Changed, Tests

#14401 Check Wallet DB integrity
  chia/cmds/check_wallet_db.py
  chia/cmds/wallet.py
  chia/util/collection.py
  chia/util/pprint.py
  tests/cmds/__init__.py
  tests/cmds/test_wallet_check.py
  tests/util/test_collection.py
  tests/util/test_pprint.py
Labels: Changed

#14612 make SpendBundle.additions() count complete cost
  chia/types/coin_spend.py
  chia/types/spend_bundle.py
  chia/wallet/trading/offer.py
  tests/core/custom_types/test_spend_bundle.py
Labels: ready_to_merge, Changed, Cleanup

#14629 tests: Merge some fixtures and drop other redundant ones
  chia/simulator/setup_nodes.py
  tests/conftest.py
  tests/core/full_node/test_transactions.py
  tests/core/mempool/test_mempool_fee_protocol.py
  tests/core/ssl/test_ssl.py
  tests/core/test_filter.py
  tests/simulation/test_simulation.py
  tests/wallet/db_wallet/test_dl_wallet.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_blockchain.py
  tests/wallet/test_wallet_node.py
Labels: Changed, Tests

#14415 close the keychain proxy in more failure and cancellation cases
  chia/cmds/cmds_util.py
  chia/plotting/create_plots.py
  chia/simulator/block_tools.py
Labels: Fixed

#14167 types: Use `IPAddress` instead of `str` in `PeerInfo`
  chia/server/address_manager.py
  chia/server/node_discovery.py
  chia/server/server.py
  chia/types/peer_info.py
  tests/core/full_node/test_full_node.py
  tests/simulation/test_simulator.py
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: Changed, Cleanup

#14613 exploring loop test adjustments
  tests/core/server/test_loop.py
Labels: Changed, Tests

#14615 make conditions_for_solution() support untrusted input
  chia/types/blockchain_format/program.py
  chia/util/condition_tools.py
  tests/core/mempool/test_mempool.py
  tests/generator/test_rom.py
Labels: ready_to_merge, Changed

#14635 extend and improve the mempool benchmark
  benchmarks/mempool.py
Labels: ready_to_merge, Changed, Tests

#14593 Mempool private implementation
  chia/clvm/spend_sim.py
  chia/full_node/full_node.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/rpc/full_node_rpc_api.py
  chia/simulator/full_node_simulator.py
  tests/blockchain/test_blockchain_transactions.py
  tests/core/data_layer/test_data_rpc.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_fee_estimator.py
  tests/fee_estimation/test_mempoolitem_height_added.py
  tests/pools/test_pool_rpc.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_wallet_retry.py
Labels: ready_to_merge, Changed, Cleanup

#14588 add nft id to rpcs
  chia/wallet/nft_wallet/nft_info.py
  chia/wallet/nft_wallet/nft_puzzles.py
Labels: Added

#14524 wallet: Fix sync mode indication
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/test_wallet_state_manager.py
Labels: Fixed

#14586 Move imports to the top of the file
  chia/util/bech32m.py
Labels: Changed, Cleanup

#14650 cleanup adjacent string literals
  chia/cmds/db_upgrade_func.py
  chia/cmds/db_validate_func.py
  chia/cmds/farm.py
  chia/cmds/show_funcs.py
  chia/cmds/wallet_funcs.py
  chia/data_layer/data_layer_util.py
  chia/full_node/full_node.py
  chia/full_node/full_node_store.py
  chia/plot_sync/sender.py
  chia/server/ws_connection.py
  chia/simulator/block_tools.py
  chia/timelord/timelord.py
  chia/util/ws_message.py
  chia/wallet/cat_wallet/lineage_store.py
  chia/wallet/key_val_store.py
  chia/wallet/notification_store.py
  chia/wallet/trading/trade_store.py
  chia/wallet/wallet_nft_store.py
  chia/wallet/wallet_node.py
  tests/core/test_cost_calculation.py
  tests/wallet/test_notifications.py
Labels: Changed, Cleanup

#14643 wallet: Access `trusted_peers` with a default
  chia/wallet/wallet_node.py
Labels: Fixed, Cleanup

#14628 Introduce BlockRecordProtocol as a subset of BlockRecord that the mempool manager uses for peak
  benchmarks/mempool.py
  chia/clvm/spend_sim.py
  chia/consensus/block_record.py
  chia/full_node/mempool_manager.py
  tests/core/mempool/test_mempool_manager.py
Labels: Changed

#14458 full_node: Rename some `receive`/`respond` prefixes to `add`
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/rpc/full_node_rpc_api.py
  chia/simulator/full_node_simulator.py
  tests/blockchain/test_blockchain_transactions.py
  tests/conftest.py
  tests/core/full_node/full_sync/test_full_sync.py
  tests/core/full_node/stores/test_hint_store.py
  tests/core/full_node/test_full_node.py
  tests/core/full_node/test_node_load.py
  tests/core/full_node/test_performance.py
  tests/core/full_node/test_transactions.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_fee_protocol.py
  tests/core/mempool/test_mempool_performance.py
  tests/core/test_full_node_rpc.py
  tests/pools/test_pool_rpc.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_blockchain.py
  tools/test_full_sync.py
Labels: Changed, Cleanup

#14654 remove unneeded parentheses
  chia/cmds/keys_funcs.py
  chia/cmds/show_funcs.py
  chia/plotting/check_plots.py
  chia/util/ssl_check.py
  chia/wallet/transaction_record.py
  tests/wallet/cat_wallet/test_offer_lifecycle.py
Labels: Changed, Cleanup

#14655 drop trailing commas in unpacking assignment
  chia/consensus/block_creation.py
  chia/full_node/weight_proof.py
  chia/simulator/block_tools.py
Labels: Changed, Cleanup

#14658 Annotate chia/rpc/full_node_rpc_api.py
  chia/rpc/full_node_rpc_api.py
  mypy.ini
Labels: ready_to_merge, Changed, Cleanup

#14448 Extend sign API to support hex string
  chia/rpc/wallet_rpc_api.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/test_wallet.py
Labels: Changed

#14659 correct rate limiting of rate limit log message
  chia/server/ws_connection.py
Labels: Fixed, Cleanup

#14664 write service groups as lists instead of splitting strings
  chia/util/service_groups.py
Labels: Changed, Cleanup

#14665 simplify the mempool filter to only pass in the spend_bundle name
  chia/clvm/spend_sim.py
  chia/full_node/mempool_manager.py
  tests/fee_estimation/test_mempoolitem_height_added.py
Labels: ready_to_merge, Changed, Cleanup

#14476 Separate mempool item's JSON response value from the internal structure
  chia/rpc/full_node_rpc_api.py
  chia/types/mempool_item.py
Labels: ready_to_merge, Changed

#14685 simplify fee estimator by not leaking MempoolItem into its interface
  chia/full_node/bitcoin_fee_estimator.py
  chia/full_node/fee_estimation.py
  chia/full_node/fee_estimator_example.py
  chia/full_node/fee_estimator_interface.py
  chia/full_node/fee_tracker.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  tests/core/mempool/test_mempool_fee_estimator.py
  tests/fee_estimation/test_fee_estimation_integration.py
  tests/fee_estimation/test_fee_estimation_unit_tests.py
Labels: ready_to_merge, Changed, Cleanup

#14668 Fix a DID Wallet issue where an old DID coin causes us to assert during wallet creation
  chia/wallet/did_wallet/did_wallet.py
  tests/wallet/did_wallet/test_did.py
Labels: ready_to_merge, Changed, Tests

#14688 Improve chia wallet check help and diagnostic messages
  chia/cmds/check_wallet_db.py
  chia/cmds/wallet.py
Labels: Changed

#14681 add hinting around get_any_service_client()
  chia/cmds/cmds_util.py
  chia/cmds/data_funcs.py
  chia/cmds/farm_funcs.py
  chia/cmds/netspace_funcs.py
  chia/cmds/peer_funcs.py
  chia/cmds/plotnft_funcs.py
  chia/cmds/show_funcs.py
Labels: Changed, Cleanup

#14678 hint chia.cmds.configure
  chia/cmds/configure.py
Labels: Changed, Cleanup

#14679 hint chia.cmds.db
  chia/cmds/db.py
Labels: Changed, Cleanup

#14680 hint chia.cmds.db_upgrade_func
  chia/cmds/db_upgrade_func.py
Labels: Changed, Cleanup

#14682 hint chia.cmds.init, chia.cmds.init_funcs
  chia/cmds/init.py
  chia/cmds/init_funcs.py
  chia/simulator/block_tools.py
Labels: Changed, Cleanup

#14686 hint and dataclass chia.daemon.keychain_server
  chia/daemon/keychain_server.py
Labels: Changed, Cleanup

#14687 hint chia.farmer.farmer
  chia/farmer/farmer.py
Labels: Changed, Cleanup

#14702 gc.collect() before unlinking the db in some tests (more)
  chia/simulator/setup_services.py
Labels: Fixed, Tests

#14703 add more wallet syncs to test_pool_rpc
  tests/pools/test_pool_rpc.py
Labels: Fixed, Tests

#14697 hint chia.rpc.farmer_rpc_api, client
  chia/rpc/data_layer_rpc_client.py
  chia/rpc/farmer_rpc_api.py
  chia/rpc/farmer_rpc_client.py
  chia/rpc/harvester_rpc_client.py
  chia/rpc/rpc_client.py
  chia/rpc/wallet_rpc_client.py
Labels: Changed, Cleanup

#14696 hint chia.rpc.crawler_rpc_api
  chia/rpc/crawler_rpc_api.py
Labels: Changed, Cleanup

#14695 hint chia.protocols.pool_protocol
  chia/protocols/pool_protocol.py
Labels: Changed, Cleanup

#14693 hint chia.pools.pool_config
  chia/pools/pool_config.py
Labels: Changed, Cleanup

#14691 hint chia.plotting.check_plots
  chia/plotting/check_plots.py
Labels: Changed, Cleanup

#14690 hint chia.harvester.harvester, harvester_api
  chia/harvester/harvester.py
  chia/harvester/harvester_api.py
  chia/plot_sync/sender.py
  chia/plotting/manager.py
  tests/plot_sync/test_plot_sync.py
  tests/plot_sync/test_sync_simulated.py
Labels: Changed, Cleanup

#14674 daemon: Fix server shutdown / wait for it
  chia/daemon/server.py
  chia/simulator/setup_services.py
  chia/simulator/simulator_test_tools.py
Labels: Fixed, Cleanup

#14673 Extend did_find_lost_did API
  chia/rpc/wallet_rpc_api.py
  chia/wallet/cat_wallet/cat_wallet.py
Labels: Changed

#14563 Refine help text for chia peer -a
  chia/cmds/peer.py
Labels: Changed

#14706 update mypy.ini
  chia/rpc/farmer_rpc_client.py
  mypy.ini
Labels: Changed, Cleanup
