Repository Chia-Network/chia-blockchain, pull requests merged in 2023-09, with the labels that each got.

#16213 Increase peak timeout due to slow runners
  tests/core/full_node/full_sync/test_full_sync.py
Labels: Fixed, Exclude_Notes

#16220 Adapt some tests to the recent limit_consensus_modes mark
  tests/blockchain/test_blockchain.py
  tests/core/full_node/full_sync/test_full_sync.py
Labels: Changed, Cleanup

#15856 Timelord peak change
  chia/simulator/setup_nodes.py
  chia/simulator/setup_services.py
  chia/timelord/timelord_api.py
  mypy-exclusions.txt
  tests/conftest.py
  tests/timelord/__init__.py
  tests/timelord/config.py
  tests/timelord/test_new_peak.py
Labels: timelord, Changed

#15706 Fix max-line-lengh for pylint
  pylintrc
Labels: Changed, Exclude_Notes

#16062 full_node: Stop updating wallets during long sync
  chia/full_node/full_node.py
Labels: Changed

#16215 server: Drop unused send messages
  chia/server/server.py
  chia/server/ws_connection.py
Labels: Changed, Cleanup

#16217 tests: Fix a `BlockCache` instance in `test_weight_proof_extend_new_ses`
  tests/weight_proof/test_weight_proof.py
Labels: Fixed, Tests

#16235 increase data store batch insert benchmark limit from 19s to 24s
  tests/core/data_layer/test_data_store.py
Labels: Changed, CI, Exclude_Notes

#16248 Installer Workflow Updates
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: Changed, CI

#16231 Block tools compute cost
  chia/simulator/block_tools.py
  tests/core/mempool/test_mempool.py
Labels: ready_to_merge, Changed, Tests

#16229 add _run() method to Program
  chia/types/blockchain_format/program.py
Labels: Added, Cleanup

#16228 remove unused test-blocks fixture
  tests/conftest.py
Labels: ready_to_merge, Changed, Tests, Cleanup

#16232 Fix issue with GUI and `chia plotters` when making compressed plots
  chia/daemon/server.py
  chia/plotters/bladebit.py
  chia/plotters/plotters.py
Labels: Fixed

#16245 simulator: Increase duration limit in `test_callback` of `BlockTools`
  chia/simulator/block_tools.py
Labels: Fixed, CI

#16262 wallet: Refactor `new_peak` in `WalletStateManager` and `PoolWallet`
  chia/pools/pool_wallet.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
Labels: Changed, Cleanup

#16239 wallet: Fix and improve untrusted race caching
  chia/wallet/util/peer_request_cache.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_node_api.py
  tests/wallet/test_wallet_node.py
  tests/wallet/test_wallet_utils.py
Labels: Fixed

#16260 xfail `core.server.test_loop.test_loop()`
  tests/core/server/test_loop.py
Labels: Changed, Tests

#13568 commonize signal setup
  chia/daemon/server.py
  chia/data_layer/data_layer_server.py
  chia/seeder/dns_server.py
  chia/seeder/start_crawler.py
  chia/server/start_data_layer.py
  chia/server/start_farmer.py
  chia/server/start_full_node.py
  chia/server/start_harvester.py
  chia/server/start_introducer.py
  chia/server/start_service.py
  chia/server/start_timelord.py
  chia/server/start_wallet.py
  chia/simulator/setup_services.py
  chia/simulator/simulator_test_tools.py
  chia/simulator/start_simulator.py
  chia/timelord/timelord_launcher.py
  chia/util/misc.py
Labels: stale-pr, PR, Changed, Cleanup, coverage-diff

#16204 `@dataclass` for `DataLayer`
  chia/data_layer/data_layer.py
  chia/server/start_data_layer.py
  tests/core/data_layer/test_data_layer.py
  tests/core/data_layer/test_data_rpc.py
Labels: Changed, Cleanup

#16266 checkpoint: into main from release/2.0.1 @ 27ccd9a86dab07f665820e1ed2e6a6e76c059c72
  chia/daemon/server.py
  chia/plotters/bladebit.py
  chia/plotters/plotters.py
Labels: checkpoint_merge, Changed

#16267 Update all remaining glue calls to use the ${{ env.VAR }} syntax for accessing env vars
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/start-release.yml
Labels: Fixed, CI

#16226 Optimize CAT coin_added
  chia/wallet/cat_wallet/cat_info.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/wallet_state_manager.py
Labels: Changed

#16227 Optimize NFT coin_added
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/nft_wallet/uncurry_nft.py
  chia/wallet/wallet_state_manager.py
Labels: Changed

#16194 add new `plugins:` config allowing for custom headers
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_util.py
  chia/data_layer/download_data.py
  chia/server/start_data_layer.py
  chia/util/initial-config.yaml
  chia/util/network.py
  tests/core/data_layer/test_data_layer.py
Labels: Added

#16269 reference SHA in coverage diff comment
  .github/workflows/test.yml
Labels: Fixed, CI

#16182 Delete DL files on unsubscribe.
  chia/cmds/data.py
  chia/cmds/data_funcs.py
  chia/data_layer/data_layer.py
  chia/rpc/data_layer_rpc_api.py
  chia/rpc/data_layer_rpc_client.py
  tests/core/data_layer/test_data_rpc.py
Labels: Fixed, DataLayer

#16110 Add `--verbose` option to `data create_data_store` and limit default output to the store id
  chia/cmds/data.py
  chia/cmds/data_funcs.py
  chia/rpc/data_layer_rpc_api.py
  chia/rpc/data_layer_rpc_client.py
  tests/core/data_layer/test_data_rpc.py
Labels: Fixed

#16278 chiavdf==1.0.11 for setuptools fix
  setup.py
Labels: Fixed

#16263 Invoke python instead of python3 consistently in pre-commit flows
  .pre-commit-config.yaml
Labels: Changed, Cleanup

#16221 log traceback for `sync from fork point failed`
  chia/full_node/full_node.py
Labels: Changed, Cleanup

#15797 more ws message type awareness in the deamon
  chia/daemon/server.py
Labels: stale-pr, Fixed, coverage-diff

#16224 report bad `@pytest.mark.limit_consensus_modes()` use with fixtureless tests
  tests/conftest.py
Labels: Fixed, Tests, coverage-diff

#16281 checkpoint: into main from release/2.0.1 @ e66f3a9876e9a1c4f3da30dd889d80a8627b6782
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#16280 Add traceback to front-end error responses
  chia/rpc/util.py
Labels: ready_to_merge, Added, coverage-diff

#15996 flush only the updated parts of the height-to-hash cache file
  chia/full_node/block_height_map.py
  tests/core/full_node/test_block_height_map.py
Labels: Changed

#16283 push out CHIP-13 activation height (SOFT_FORK4) to the hard-fork
  chia/consensus/default_constants.py
Labels: Changed, Exclude_Notes

#15977 extend tests being parametrised by soft-fork
  chia/simulator/setup_nodes.py
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/daemon/config.py
  tests/core/daemon/test_daemon.py
  tests/core/data_layer/config.py
  tests/core/full_node/test_full_node.py
  tests/pools/test_pool_rpc.py
  tests/wallet/cat_wallet/config.py
  tests/wallet/cat_wallet/test_cat_lifecycle.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/db_wallet/test_dl_offers.py
  tests/wallet/db_wallet/test_dl_wallet.py
  tests/wallet/nft_wallet/config.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/rpc/config.py
  tests/wallet/rpc/test_dl_wallet_rpc.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_blockchain.py
  tests/wallet/test_wallet_node.py
Labels: Added, Tests, coverage-diff

#16300 `@pytest.mark.limit_consensus_modes()` in DataLayer RPC tests
  tests/core/data_layer/test_data_rpc.py
Labels: Changed, Tests

#16244 Remove old debugging test
  tests/weight_proof/test_weight_proof.py
Labels: Changed, Cleanup

#16296 move `using_temp_file_keyring()` decorator to test fixtures
  chia/simulator/keyring.py
  tests/conftest.py
  tests/core/util/test_file_keyring_synchronization.py
  tests/core/util/test_keychain.py
  tests/core/util/test_keyring_wrapper.py
Labels: Changed, Cleanup

#16295 Rename USDS --> USDSC
  chia/wallet/cat_wallet/cat_constants.py
Labels: ready_to_merge, Changed

#16135 Configure number of stored full files in DL.
  chia/data_layer/data_layer.py
  chia/data_layer/download_data.py
  chia/data_layer/s3_plugin_service.py
  chia/util/initial-config.yaml
  tests/core/data_layer/test_data_rpc.py
  tests/core/data_layer/test_data_store.py
Labels: Added, DataLayer

#16285 add fee for cat creation
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/puzzles/tails.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Fixed

#16303 max_coin_amount should default to None in walllet send command
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
Labels: Fixed

#16288 Fix test_dusted_wallet flakiness
  tests/wallet/sync/test_wallet_sync.py
Labels: ready_to_merge, Fixed, Exclude_Notes

#16261 wallet: Drop `is_peer_synced` / More cache usage
  chia/wallet/util/wallet_sync_utils.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_node_api.py
  tests/wallet/test_wallet_node.py
Labels: Changed

#16126 Refactor simulator setups from async generators to context managers
  chia/simulator/setup_nodes.py
  chia/simulator/setup_services.py
  tests/conftest.py
  tests/core/daemon/test_keychain_proxy.py
  tests/core/full_node/test_full_node.py
  tests/farmer_harvester/test_filter_prefix_bits.py
  tests/pools/test_pool_rpc.py
  tests/simulation/test_simulation.py
  tests/wallet/test_wallet.py
Labels: ready_to_merge, Changed, Tests

#16241 run_block_generator2()
  .github/workflows/benchmarks.yml
  .github/workflows/test-single.yml
  chia/consensus/constants.py
  chia/consensus/default_constants.py
  chia/full_node/mempool_check_conditions.py
  chia/server/start_full_node.py
  chia/simulator/block_tools.py
  chia/util/initial-config.yaml
  tests/conftest.py
  tests/core/full_node/test_conditions.py
  tests/core/mempool/test_mempool.py
  tests/core/test_cost_calculation.py
  tests/farmer_harvester/test_filter_prefix_bits.py
  tests/generator/test_rom.py
  tests/util/test_testnet_overrides.py
Labels: ready_to_merge, Changed

#16208 Bladebit Hybrid disk mode
  chia/daemon/server.py
  chia/plotters/bladebit.py
  chia/plotters/plotters.py
  setup.py
  tests/core/daemon/test_daemon.py
Labels: ready_to_merge, plotting, Added, coverage-diff

#16054 Add ergonomic timelock parsing to RPCs
  chia/rpc/util.py
  chia/rpc/wallet_rpc_client.py
Labels: ready_to_merge, Added

#16238 full_node: Move wallet updates into a separate task
  chia/full_node/full_node.py
  tests/core/full_node/test_full_node.py
Labels: Changed

#16277 wallet: Drop unused methods in `wallet_sync_utils.py`
  chia/wallet/util/wallet_sync_utils.py
Labels: Changed, Cleanup

#16286 improve `dataclasses.replace()` usage to improve hint checking
  chia/consensus/constants.py
  chia/consensus/default_constants.py
  chia/simulator/block_tools.py
  chia/simulator/setup_nodes.py
  chia/util/make_test_constants.py
  mypy-exclusions.txt
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/consensus/test_pot_iterations.py
  tests/core/full_node/full_sync/test_full_sync.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/farmer_harvester/test_farmer.py
  tests/farmer_harvester/test_filter_prefix_bits.py
  tests/fee_estimation/test_mempoolitem_height_added.py
  tests/simulation/test_simulation.py
  tests/tools/test_run_block.py
  tests/weight_proof/test_weight_proof.py
  tools/test_constants.py
Labels: Changed, Cleanup, coverage-diff

#16322 remove `const_dict=` parameter from `BlockTools()`
  chia/simulator/block_tools.py
Labels: Changed, Cleanup

#15972 send --fix-ssl-permissions to stderr
  chia/ssl/create_ssl.py
  chia/util/ssl_check.py
  tests/util/test_ssl_check.py
Labels: Changed

#16320 remove CHIP-13 and SOFT_FORK4
  benchmarks/block_store.py
  chia/cmds/db_validate_func.py
  chia/consensus/block_body_validation.py
  chia/consensus/block_header_validation.py
  chia/consensus/block_record.py
  chia/consensus/constants.py
  chia/consensus/default_constants.py
  chia/consensus/full_block_to_block_record.py
  chia/full_node/block_store.py
  chia/server/start_full_node.py
  chia/simulator/block_tools.py
  chia/util/full_block_utils.py
  chia/util/initial-config.yaml
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/full_node/full_sync/test_full_sync.py
  tests/core/full_node/stores/test_block_store.py
  tests/core/full_node/test_full_node.py
  tests/pools/test_pool_rpc.py
  tests/util/test_full_block_utils.py
  tests/util/test_testnet_overrides.py
Labels: ready_to_merge, Fixed

#16321 Ban relative timelocks from RPC
  chia/rpc/util.py
Labels: Changed

#16255 Add valid_times to Offer object
  chia/cmds/wallet_funcs.py
  chia/rpc/util.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/trade_manager.py
  chia/wallet/trade_record.py
  chia/wallet/trading/offer.py
  tests/wallet/cat_wallet/test_offer_lifecycle.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Added, coverage-diff

#16276 add `SizedBytes.random()`/`.secret()`, replace `token_bytes()` usage
  chia/full_node/full_node_api.py
  chia/plotting/create_plots.py
  chia/server/ws_connection.py
  chia/simulator/setup_services.py
  chia/simulator/simulator_full_node_rpc_api.py
  chia/util/byte_types.py
  chia/util/keychain.py
  chia/util/ws_message.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/wallet_state_manager.py
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/custom_types/test_proof_of_space.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/full_node/test_full_node.py
  tests/core/full_node/test_transactions.py
  tests/core/full_node/test_tx_processing_queue.py
  tests/core/util/test_keychain.py
  tests/plot_sync/test_receiver.py
  tests/plot_sync/test_sender.py
  tests/plot_sync/test_sync_simulated.py
  tests/plot_sync/util.py
  tests/pools/test_wallet_pool_store.py
  tests/util/benchmark_cost.py
  tests/wallet/clawback/test_clawback_metadata.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_bulk_mint.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/nft_wallet/test_nft_puzzles.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_nft_store.py
  tests/wallet/test_notifications.py
  tests/wallet/test_puzzle_store.py
  tests/wallet/test_transaction_store.py
  tests/wallet/test_wallet_coin_store.py
  tests/wallet/test_wallet_interested_store.py
  tests/wallet/test_wallet_trade_store.py
Labels: Changed, Tests, coverage-diff

#16323 ban peers for 10 minutes when violating consensus rules
  chia/protocols/protocol_timing.py
  chia/server/ws_connection.py
Labels: Changed, coverage-diff

#16315 Annotate test_new_peak.py
  mypy-exclusions.txt
  tests/timelord/test_new_peak.py
Labels: Changed, Cleanup

#16325 Remove tx_endpoint from select_coins
  chia/rpc/wallet_rpc_api.py
Labels: Changed

#16339 bump data layer benchmark timeout for batch insert from 17 -> 18 seconds
  tests/core/data_layer/test_data_store.py
Labels: ready_to_merge, Fixed, Tests

#16338 skip test_parser() test
  tests/util/test_full_block_utils.py
Labels: Changed, Tests

#16324 more (more) `uint*()`
  chia/full_node/weight_proof.py
  chia/simulator/block_tools.py
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/consensus/test_pot_iterations.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/simulation/test_simulation.py
  tests/wallet/test_transaction_store.py
  tests/wallet/test_wallet_node.py
  tools/test_constants.py
Labels: Changed, Cleanup

#16326 Better timestamps on simulated chains
  .github/workflows/benchmarks.yml
  .github/workflows/test-single.yml
  chia/simulator/block_tools.py
  tests/farmer_harvester/test_filter_prefix_bits.py
  tools/generate_chain.py
Labels: ready_to_merge, Changed, Tests

#16113 Add the basics for a more ergonomic wallet test framework
  tests/wallet/conftest.py
  tests/wallet/test_wallet_test_framework.py
  tests/wallet/vc_wallet/test_vc_wallet.py
Labels: ready_to_merge, Added, Tests

#16340 Add extra_conditions to special offer making
  chia/data_layer/data_layer_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
Labels: Fixed

#16353 Bump test_mempool_update_performance benchmark duration from 0.1 to 0.15
  tests/core/mempool/test_mempool_performance.py
Labels: Changed, Cleanup

#16246 Run CI using Python 3.10
  .github/workflows/benchmarks.yml
  .github/workflows/pre-commit.yml
  .github/workflows/snyk-python-scan.yml
  .github/workflows/test-install-scripts.yml
  .github/workflows/test-single.yml
  .github/workflows/test.yml
Labels: Changed, Cleanup

#16345 fix runtime type risk in `parse_timelock_info()`
  chia/wallet/conditions.py
Labels: Changed, Cleanup

#16357 Remove EOL & unsupported operating systems and add newer versions
  .github/workflows/test-install-scripts.yml
Labels: Changed, CI, Cleanup

#16341 bump data layer benchmark timeout for batch insert from 17 -> 18 seconds
  tests/core/data_layer/test_data_store.py
Labels: Fixed, Tests

#16243 Annotate test_weight_proof.py
  mypy-exclusions.txt
  tests/weight_proof/test_weight_proof.py
Labels: Changed, Cleanup

#16290 Return TransactionRecord from create_message_spend
  chia/rpc/wallet_rpc_api.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/vc_wallet/vc_wallet.py
Labels: ready_to_merge, Added, Exclude_Notes

#16362 checkpoint: into main from release/2.1.0 @ 018e812d85911489901dee7e83cdaf0252493bb0
  chia/data_layer/data_layer_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
Labels: checkpoint_merge, Changed

#16356 chiabip158==1.3
  setup.py
Labels: Changed

#16364 Remove the Snyk scan file for py deps. We now use GHAS.
  .github/workflows/snyk-python-scan.yml
Labels: Changed, CI

#16358 RPM: Change the --depends to a Recommends: tag on the specific compat package
  build_scripts/build_linux_rpm-2-installer.sh
Labels: Fixed, CI

#15190 switch from a benchmark mark to a fixture
  pytest.ini
  tests/conftest.py
  tests/core/data_layer/test_data_store.py
  tests/core/full_node/test_node_load.py
  tests/core/full_node/test_performance.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_performance.py
  tests/core/test_cost_calculation.py
  tests/util/misc.py
  tests/wallet/test_offer_parsing_performance.py
Labels: stale-pr, Changed, CI, Tests, coverage-diff

#16369 checkpoint: into main from release/2.1.0 @ 056f20dc3c4a531e008a50bd3b42884fa8af1701
  setup.py
Labels: checkpoint_merge, Changed

#16372 checkpoint: into main from release/2.1.0 @ 959dc2ac5281a72f20044b488cd330d1e7c85745
  build_scripts/build_linux_rpm-2-installer.sh
Labels: checkpoint_merge, Changed

#16360 Make the standard wallet return `List[TransactionRecord]`
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/simulator/full_node_simulator.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/notification_manager.py
  chia/wallet/puzzles/tails.py
  chia/wallet/trade_manager.py
  chia/wallet/wallet.py
  tests/core/full_node/test_full_node.py
  tests/core/full_node/test_transactions.py
  tests/core/mempool/test_mempool_manager.py
  tests/core/mempool/test_mempool_performance.py
  tests/simulation/test_simulation.py
  tests/simulation/test_simulator.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_retry.py
Labels: ready_to_merge, Changed, Exclude_Notes, coverage-diff

#16374 run `chia version` from packaging artifacts
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: Added, Tests

#16375 Update build-linux-installer-rpm.yml
  .github/workflows/build-linux-installer-rpm.yml
Labels: Fixed, CI

#16378 checkpoint: into main from release/2.1.0 @ 91d94df63a9c07bdfce91b97636991c71d43672f
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: checkpoint_merge, Changed

#16379 checkpoint: into main from release/2.1.0 @ 519214ab283dc6df95033ea95b9a1018b5c78aa1
  .github/workflows/build-linux-installer-rpm.yml
Labels: checkpoint_merge, Changed

#16380 add clean-workspace step for package artifact tests
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: Fixed, CI

#16352 mypy 1.5.1
  chia/consensus/block_header_validation.py
  chia/consensus/constants.py
  chia/wallet/conditions.py
  setup.py
  tests/blockchain/test_blockchain.py
  tests/core/test_farmer_harvester_rpc.py
  tests/tools/test_run_block.py
Labels: Fixed, Exclude_Notes

#16366 Annotate test_hint_store.py
  mypy-exclusions.txt
  tests/core/full_node/stores/test_hint_store.py
Labels: Changed, Cleanup

#16382 checkpoint: into main from release/2.1.0 @ bbd57321faee72eb3b1d783cb2ea829a20d9731f
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: checkpoint_merge, Changed

#16289 Add RPC Client context manager
  chia/rpc/rpc_client.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge, Added, Exclude_Notes

#16394 Increase trade test timeouts
  tests/wallet/cat_wallet/test_trades.py
Labels: Changed, Tests, Exclude_Notes

#16414 pin `astroid==2.15.6` for pylint false positives
  setup.py
Labels: Fixed, CI

#16389 Fix condition serialization in RPC client
  chia/rpc/wallet_rpc_client.py
  chia/wallet/conditions.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_conditions.py
Labels: Fixed

#16418 pin `astroid==2.15.6` for pylint false positives
  setup.py
Labels: Fixed, CI

#16409 bump chia_rs to include bugfix for new AGG_SIG_* conditions in mempool mode
  setup.py
  tests/core/mempool/test_mempool.py
Labels: Fixed

#16387 Fix `chia farm summary` aborting early if no local full node present
  chia/cmds/farm_funcs.py
Labels: Fixed

#16417 fix typo in PendingTxCache
  chia/full_node/pending_tx_cache.py
  tests/core/mempool/test_mempool.py
Labels: ready_to_merge, Fixed

#16419 Update chiapos
  setup.py
Labels: Changed

#16383 rename `chia data add_missing_files` `-f`/`--foldername` to `-d`/`--directory`
  chia/cmds/data.py
Labels: Fixed

#16408 Wallet workaround for python issue 97641 and update anyio for issue 589
  chia/simulator/setup_services.py
  setup.py
Labels: Fixed

#16415 Fix issue with trade failures
  chia/wallet/wallet_state_manager.py
Labels: Fixed

#16423 Fix CAT --> CR-CAT wallet conversion
  chia/wallet/vc_wallet/cr_cat_wallet.py
Labels: ready_to_merge, Fixed

#16416 checkpoint: into main from release/2.1.0 @ e120ec4e569effae6f0fa6efcf303c49c1a4aece
  tests/wallet/cat_wallet/test_trades.py
Labels: checkpoint_merge, Changed

#16327 Extend sign APIs for customized puzzle
  chia/rpc/wallet_rpc_api.py
  chia/types/signing_mode.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/test_wallet.py
Labels: Added, coverage-diff

#16413 hint `SSLTestCollateralTracker.in_use`
  chia/simulator/ssl_certs.py
Labels: Fixed, Cleanup

#16420 stop using `pkg_resources.get_distribution()` in `pyinstaller.spec`
  build_scripts/pyinstaller.spec
Labels: Changed, Cleanup

#16412 hint `chia.simulator.setup_services`/`start_simulator`
  chia/simulator/setup_services.py
  chia/simulator/simulator_test_tools.py
  chia/simulator/start_simulator.py
  mypy-exclusions.txt
Labels: Fixed, Exclude_Notes

#16407 add `try`/`finally` to `setup_services` context managers
  chia/simulator/setup_services.py
Labels: Fixed, Tests, coverage-diff

#16410 pylint config: builtins.Exception
  pylintrc
Labels: Fixed, Tests, Cleanup

#16424 Update install-gui.sh to use check Node 18 and npm 9
  install-gui.sh
  start-gui.sh
Labels: Changed

#16434 Fix glitch NFT wallet test
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: Fixed

#14753 use importlib.metadata to get package versions
  build_scripts/pyinstaller.spec
  chia/__init__.py
  chia/plotters/chiapos.py
Labels: Changed, Cleanup, coverage-diff

#16436 checkpoint: into main from release/2.1.0 @ 79f4a999fb6d6fd06f2d815e4b08965aa283a7ec
  setup.py
  tests/core/mempool/test_mempool.py
Labels: checkpoint_merge, Changed

#16442 Fixing TAG_TYPE env for CI
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: Fixed, CI

#16441 encapsulate `SyncStore._backtrack_syncing` dict
  chia/full_node/full_node.py
  chia/full_node/sync_store.py
  tests/core/full_node/stores/test_sync_store.py
Labels: Changed, Cleanup

#16446 checkpoint: into main from release/2.1.0 @ d2934682ecc4a96c6b4641e8a68f48d5446787ea
  chia/cmds/farm_funcs.py
Labels: checkpoint_merge, Changed, coverage-diff

#16455 checkpoint: into main from release/2.1.0 @ fb2a939606f85c27d31c2ae1fad60789f158984d
  chia/full_node/pending_tx_cache.py
  tests/core/mempool/test_mempool.py
Labels: checkpoint_merge, Changed

#16460 checkpoint: into main from release/2.1.0 @ d298d6b8c680df4f59a172e64cb6c929989770ca
  setup.py
Labels: checkpoint_merge, Changed
