Repository Chia-Network/chia-blockchain, pull requests merged in 2023-12, with the labels that each got.

#16556 `chia show keys --show-mnemonic-seed`: Also show farmer private key
  chia/cmds/keys_funcs.py
Labels: Changed

#16990 checkpoint: into main from release/2.1.2 @ fde036c503ad76a45659bdc98b2d72ff820d840c
  chia/cmds/keys_funcs.py
Labels: checkpoint_merge, Changed

#16992 Update SECURITY.md
  SECURITY.md
Labels: documentation, Changed, Exclude_Notes

#16980 claim ownership of `/opt/chia` in the RPM
  build_scripts/build_linux_rpm-2-installer.sh
Labels: Fixed

#16973 add RPC API generic parameter to `Service`
  chia/rpc/rpc_server.py
  chia/seeder/start_crawler.py
  chia/server/start_data_layer.py
  chia/server/start_farmer.py
  chia/server/start_full_node.py
  chia/server/start_harvester.py
  chia/server/start_service.py
  chia/server/start_timelord.py
  chia/server/start_wallet.py
  chia/types/aliases.py
Labels: Changed, Exclude_Notes

#16889 add `SpendSim.managed()`
  chia/clvm/spend_sim.py
Labels: Changed, Exclude_Notes

#16890 add `DataStore.managed()`
  chia/data_layer/data_layer.py
  chia/data_layer/data_store.py
  chia/data_layer/util/benchmark.py
  tests/core/data_layer/conftest.py
  tests/core/data_layer/test_data_store.py
Labels: Changed, Exclude_Notes

#16991 clean out `/opt/chia` before install and after removal of rpm
  build_scripts/assets/rpm/before-install.sh
  build_scripts/build_linux_rpm-2-installer.sh
Labels: Fixed

#17006 checkpoint: into main from release/2.1.2 @ 196459382a7946747e1934b6b8932ccfe689624d
  build_scripts/build_linux_rpm-2-installer.sh
Labels: checkpoint_merge, Changed

#16934 Fix TX amount calculation in trade manager
  chia/wallet/trade_manager.py
  tests/wallet/cat_wallet/test_trades.py
Labels: Fixed

#16969 Don't allow DL mirrors with empty urls.
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_wallet.py
Labels: Fixed, DataLayer

#17020 skip diff coverage on dispatch and schedule triggers
  .github/workflows/test.yml
Labels: Fixed, CI

#16988 dao vote amount checks
  chia/cmds/dao.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/puzzles/dao_proposal.clsp
  chia/wallet/puzzles/dao_proposal.clsp.hex
  chia/wallet/puzzles/dao_proposal_validator.clsp
  chia/wallet/puzzles/dao_proposal_validator.clsp.hex
  chia/wallet/puzzles/deployed_puzzle_hashes.json
  chia/wallet/puzzles/utility_macros.clib
Labels: Fixed

#17021 Adjust ban times for DL dat files
  chia/data_layer/data_store.py
  chia/data_layer/download_data.py
  tests/core/data_layer/test_data_store.py
Labels: Changed

#17023 Fix the LAST missing pwsh-syntax-in-bash error
  .github/workflows/build-windows-installer.yml
Labels: Fixed, CI, Exclude_Notes

#17014 checkpoint: into main from release/2.1.2 @ 949ed00e47896708051874d0725968e04b86198b
  build_scripts/assets/rpm/before-install.sh
  build_scripts/build_linux_rpm-2-installer.sh
Labels: checkpoint_merge, Changed

#17022 add SerializedProgram.to() to simplify some code
  chia/types/blockchain_format/serialized_program.py
  tests/blockchain/test_blockchain.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_manager.py
  tests/core/test_program.py
Labels: ready_to_merge, Fixed

#17026 include information for setuptools_scm in git archives
  .git_archival.txt
  .gitattributes
Labels: Fixed

#17032 checkpoint: into main from release/2.1.2 @ ca9a6011ec90836d8d47efe196c2d4c77040613e
  chia/cmds/dao.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/puzzles/dao_proposal.clsp
  chia/wallet/puzzles/dao_proposal.clsp.hex
  chia/wallet/puzzles/dao_proposal_validator.clsp
  chia/wallet/puzzles/dao_proposal_validator.clsp.hex
  chia/wallet/puzzles/deployed_puzzle_hashes.json
  chia/wallet/puzzles/utility_macros.clib
Labels: checkpoint_merge, Changed, coverage-diff

#17033 checkpoint: into main from release/2.1.2 @ cfab3a407d832fff5b7f966bf447f0dd92bf9e22
  chia/data_layer/data_store.py
  chia/data_layer/download_data.py
  tests/core/data_layer/test_data_store.py
Labels: checkpoint_merge, Changed

#17031 make spend_prefarm.py checked by mypy
  chia/wallet/puzzles/prefarm/spend_prefarm.py
  mypy-exclusions.txt
Labels: Fixed, Cleanup

#17035 checkpoint: into main from release/2.1.2 @ d55c8a5dcd268d8397d98469decd865765e68788
  .github/workflows/build-windows-installer.yml
Labels: checkpoint_merge, Changed

#17030 fix type mismatch with Optional[bytes] and bytes in wallet/conditions.py
  chia/types/blockchain_format/program.py
  chia/wallet/conditions.py
  tests/wallet/test_conditions.py
Labels: ready_to_merge, Fixed

#17029 DAO resync
  chia/cmds/dao.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/dao_wallet/test_dao_wallets.py
Labels: Fixed

#17019 Move nightly schedule to the actual test workflow
  .github/workflows/daily-matrix.yml
  .github/workflows/test.yml
Labels: Added, CI, Exclude_Notes

#17038 checkpoint: into main from release/2.1.2 @ 219667b6d8547eae7c7a72b1dc699201abfd8843
  chia/cmds/dao.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/dao_wallet/test_dao_wallets.py
Labels: checkpoint_merge, Changed

#17016 drop `int512.PACK`
  chia/util/ints.py
  chia/util/struct_stream.py
Labels: Changed, Cleanup

#17041 remove coverage ignore
  chia/cmds/dao.py
Labels: Fixed, Cleanup

#17040 Optional atom fixes
  chia/full_node/mempool_check_conditions.py
  chia/simulator/block_tools.py
  chia/types/coin_spend.py
  chia/wallet/vc_wallet/cr_cat_drivers.py
  chia/wallet/vc_wallet/vc_drivers.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet_singleton_store.py
  tests/wallet/nft_wallet/test_nft_puzzles.py
  tools/run_block.py
Labels: ready_to_merge, Fixed, Cleanup

#17024 Program type fixes
  chia/simulator/block_tools.py
  tests/generator/test_compression.py
  tests/util/network_protocol_data.py
Labels: ready_to_merge, Fixed, Cleanup

#17034 adapt `conditions_dict_for_solution()` to how it's used
  chia/simulator/wallet_tools.py
  chia/util/condition_tools.py
  chia/wallet/sign_coin_spends.py
  tests/util/key_tool.py
  tests/wallet/clawback/test_clawback_lifecycle.py
Labels: ready_to_merge, Fixed, Cleanup

#17042 Update CHANGELOG.md
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#17059 checkpoint: into main from release/2.1.2 @ e2c2626e461d50e93291b72646d8df5970fc4ccd
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#17052 `get_tree_hash()` returns `bytes32`
  tests/wallet/dao_wallet/test_dao_clvm.py
  tests/wallet/vc_wallet/test_vc_lifecycle.py
Labels: ready_to_merge, Fixed, Cleanup

#17056 fix type annotation for solve_did_tp
  chia/wallet/vc_wallet/vc_drivers.py
Labels: ready_to_merge, Fixed, Cleanup

#16984 artifact fpm generated rpm `.spec` files
  .github/workflows/build-linux-installer-rpm.yml
  build_scripts/build_linux_rpm-2-installer.sh
Labels: Added, Exclude_Notes

#16979 uninstall and version tests for linux packages
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
Labels: Added, Tests

#17064 coverage ignore benchmark tests
  .coveragerc
  setup.py
Labels: Changed, Tests

#16926 `SerializedProgram` updates
  chia/data_layer/data_layer_wallet.py
  chia/full_node/generator.py
  chia/full_node/mempool_check_conditions.py
  chia/types/blockchain_format/serialized_program.py
  chia/types/coin_spend.py
  chia/wallet/cat_wallet/cat_utils.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/did_wallet/did_wallet_puzzles.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/notification_manager.py
  chia/wallet/puzzles/clawback/drivers.py
  chia/wallet/puzzles/singleton_top_layer.py
  chia/wallet/puzzles/singleton_top_layer_v1_1.py
  chia/wallet/trading/offer.py
  chia/wallet/util/wallet_sync_utils.py
  chia/wallet/vc_wallet/cr_cat_drivers.py
  chia/wallet/vc_wallet/vc_drivers.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  tests/clvm/test_puzzle_compression.py
  tests/clvm/test_puzzles.py
  tests/clvm/test_singletons.py
  tests/clvm/test_spend_sim.py
  tests/core/custom_types/test_spend_bundle.py
  tests/core/full_node/test_conditions.py
  tests/core/full_node/test_full_node.py
  tests/core/make_block_generator.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_manager.py
  tests/fee_estimation/test_mempoolitem_height_added.py
  tests/pools/test_pool_puzzles_lifecycle.py
  tests/pools/test_wallet_pool_store.py
  tests/wallet/cat_wallet/test_cat_lifecycle.py
  tests/wallet/cat_wallet/test_cat_outer_puzzle.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/cat_wallet/test_offer_lifecycle.py
  tests/wallet/clawback/test_clawback_lifecycle.py
  tests/wallet/dao_wallet/test_dao_clvm.py
  tests/wallet/db_wallet/test_db_graftroot.py
  tests/wallet/nft_wallet/test_nft_lifecycle.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_debug_spend_bundle.py
  tests/wallet/test_sign_coin_spends.py
  tests/wallet/test_singleton_lifecycle.py
  tests/wallet/test_singleton_lifecycle_fast.py
  tests/wallet/test_singleton_store.py
  tests/wallet/test_util.py
  tests/wallet/vc_wallet/test_vc_lifecycle.py
  tests/wallet/vc_wallet/test_vc_wallet.py
Labels: ready_to_merge, Changed, Cleanup

#17061 fix DAO type hints
  chia/wallet/cat_wallet/dao_cat_wallet.py
  chia/wallet/dao_wallet/dao_utils.py
  chia/wallet/dao_wallet/dao_wallet.py
  tests/wallet/dao_wallet/test_dao_clvm.py
Labels: ready_to_merge, Fixed, Cleanup

#17062 fix type hints in data layer
  chia/data_layer/data_layer_wallet.py
  chia/data_layer/data_store.py
  tests/core/data_layer/conftest.py
  tests/core/data_layer/test_data_store.py
  tests/core/data_layer/util.py
Labels: ready_to_merge, Fixed, Cleanup

#17057 tiny comment typo correction
  chia/util/byte_types.py
Labels: Fixed, Exclude_Notes

#17054 Verify p2 delegated conditions signatures
  chia/rpc/wallet_rpc_api.py
  chia/types/signing_mode.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Added

#17071 Fix compressed blocks
  chia/consensus/block_creation.py
  chia/simulator/block_tools.py
  tests/core/consensus/test_block_creation.py
Labels: Fixed

#17007 move electron build config to `build_scripts/electron-builder.json`
  .github/workflows/build-linux-installer-rpm.yml
  build_scripts/build_linux_deb-2-installer.sh
  build_scripts/build_linux_rpm-2-installer.sh
  build_scripts/build_macos-2-installer.sh
  build_scripts/build_windows-2-installer.ps1
  build_scripts/electron-builder.json
Labels: Changed, Exclude_Notes

#17076 fixed typo, it's -> its
  chia/rpc/full_node_rpc_api.py
Labels: Fixed

#17075 revert `StructStream.__bytes__()` to a working state instead of intentional failure
  chia/util/struct_stream.py
  tests/util/test_struct_stream.py
Labels: Fixed

#17074 bump chia_rs to 0.3.3
  chia/full_node/mempool_check_conditions.py
  setup.py
Labels: Changed

#17082 Update CHANGELOG.md
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#17081 checkpoint: into main from release/2.1.3 @ 788db8bdffdebc612fbb97973fc0312a76fe3955
  chia/consensus/block_creation.py
  chia/simulator/block_tools.py
  tests/core/consensus/test_block_creation.py
Labels: checkpoint_merge, Changed

#17085 checkpoint: into main from release/2.1.3 @ a6730326e202c0bd6f0b013fdae357c628f28fde
  chia/util/struct_stream.py
  tests/util/test_struct_stream.py
Labels: checkpoint_merge, Changed

#17090 checkpoint: into main from release/2.1.3 @ 3856324cadb913fa599c5378d4c43ab216194e75
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#17089 initiate phasing out of the `coin_solutions` name in JSON structs
  chia/types/spend_bundle.py
  pytest.ini
  tests/core/custom_types/test_spend_bundle.py
Labels: ready_to_merge, Changed

#17068 DL: Use unsubscribe queue to relax subscriptions lock.
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_util.py
  tests/core/data_layer/test_data_rpc.py
Labels: Fixed, DataLayer

#17011 DL upsert.
  chia/data_layer/data_store.py
  tests/core/data_layer/test_data_rpc.py
  tests/core/data_layer/test_data_store.py
Labels: ready_to_merge, Added, DataLayer

#17060 Improve input for DL CLI add_missing_files.
  chia/cmds/data.py
Labels: Fixed, DataLayer

#17109 Address and remove DAO related files from flake8's exclusion list
  .flake8
  chia/wallet/dao_wallet/dao_wallet.py
  tests/wallet/dao_wallet/test_dao_clvm.py
Labels: Changed, Cleanup

#17111 Simplify request construction in send_transaction for wallet RPC client
  chia/rpc/wallet_rpc_client.py
Labels: Changed, Cleanup

#17112 Allow construct_cat_puzzle to take either inner puzzle or hash and document the use cases
  chia/wallet/cat_wallet/cat_utils.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/vc_wallet/cr_cat_drivers.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  tests/wallet/cat_wallet/test_cat_wallet.py
Labels: Changed, Cleanup

#17113 Extract check_wallets to be reused instead of reimplemented
  tests/wallet/cat_wallet/test_cat_wallet.py
Labels: Changed, Cleanup

#17114 Reuse acs and acs_ph instead of recomputing them and their similar values
  tests/wallet/cat_wallet/test_cat_lifecycle.py
Labels: Changed, Cleanup

#17115 Extract get_trade_and_status to be reused instead of reimplemented
  tests/wallet/cat_wallet/test_trades.py
Labels: Changed, Cleanup

#17116 Allow DID's create_innerpuz to take p2_puzzle or hash, and document the use cases
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/did_wallet/did_wallet_puzzles.py
Labels: Changed, Cleanup

#17117 Reuse cat tail and puzzle hashes in generate_coins
  tests/wallet/cat_wallet/test_offer_lifecycle.py
Labels: Changed, Cleanup

#17118 Explicitly check spend bundles against None in some NFT wallet tests
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: Changed, Cleanup

#17120 Reuse coin_id in DID wallet's test_get_info
  tests/wallet/did_wallet/test_did.py
Labels: Changed, Cleanup

#17119 Explicitly name fields to improve clarity and avoid mistakes
  chia/wallet/did_wallet/did_wallet.py
Labels: Changed, Cleanup

#17105 extend the mempool tests for timelocks, and improve error codes
  chia/full_node/mempool_manager.py
  tests/core/mempool/test_mempool_manager.py
Labels: Fixed

#17107 improve performance of `total_mempool_fees()` and `total_mempool_cost()`
  chia/consensus/default_constants.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_manager.py
  tests/util/misc.py
Labels: ready_to_merge, Fixed

#17130 Simplify request construction in send_transaction_multi for wallet RPC client
  chia/rpc/wallet_rpc_client.py
Labels: Changed, Cleanup

#17131 Annotate test_cat_lifecycle.py
  mypy-exclusions.txt
  tests/wallet/cat_wallet/test_cat_lifecycle.py
Labels: Changed, Cleanup

#17132 Leverage str_to_tail in str_to_tail_hash
  tests/wallet/cat_wallet/test_offer_lifecycle.py
Labels: Changed, Cleanup

#17133 Remove confusing coinsol value (it's rather a coin spend) in create_spend_for_message
  chia/wallet/did_wallet/did_wallet_puzzles.py
Labels: Changed, Cleanup

#17134 Remove what seems to be a leftover print in test_cat_spend_multiple
  tests/wallet/cat_wallet/test_cat_wallet.py
Labels: Changed, Cleanup

#17135 Simplify get_coins_with_ph
  tests/wallet/did_wallet/test_did.py
Labels: Changed, Cleanup

#17136 Annotate test_nft_puzzles.py
  mypy-exclusions.txt
  tests/wallet/nft_wallet/test_nft_puzzles.py
Labels: Changed, Cleanup

#17137 Clarify checking compute_memos results in NFT wallet tests
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: Changed, Cleanup

#17141 checkpoint: into main from release/2.1.4 @ 55c064a29215d78393b3b37f2c3029c100560e12
  chia/consensus/default_constants.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_manager.py
  tests/util/misc.py
Labels: checkpoint_merge, Changed

#17155 Performance tweaks
  chia/server/server.py
  chia/server/start_full_node.py
  chia/util/db_synchronous.py
  chia/util/initial-config.yaml
Labels: Changed

#17139 Mempool multifetch
  benchmarks/mempool-long-lived.py
  benchmarks/mempool.py
  chia/clvm/spend_sim.py
  chia/full_node/coin_store.py
  chia/full_node/full_node.py
  chia/full_node/mempool_manager.py
  tests/core/mempool/test_mempool_fee_estimator.py
  tests/core/mempool/test_mempool_manager.py
  tests/fee_estimation/test_fee_estimation_integration.py
Labels: Changed

#17156 checkpoint: into main from release/2.1.4 @ a4cab829edd4f16dd89b29c7234ed39c23c5dcaa
  chia/server/server.py
  chia/server/start_full_node.py
  chia/util/db_synchronous.py
  chia/util/initial-config.yaml
Labels: checkpoint_merge, Changed

#17157 checkpoint: into main from release/2.1.4 @ 507899ff19b0d0bbe14bc7ed8a192f5ad0bc7aa2
  benchmarks/mempool-long-lived.py
  benchmarks/mempool.py
  chia/clvm/spend_sim.py
  chia/full_node/coin_store.py
  chia/full_node/full_node.py
  chia/full_node/mempool_manager.py
  tests/core/mempool/test_mempool_fee_estimator.py
  tests/core/mempool/test_mempool_manager.py
  tests/fee_estimation/test_fee_estimation_integration.py
Labels: ready_to_merge, checkpoint_merge, Changed

#17129 Bail out earlier if the transaction record has no spend bundle in generate_new_decentralised_id
  chia/wallet/did_wallet/did_wallet.py
Labels: Changed, Cleanup

#17143 Don't verify right after signing, and as a result don't re-verify the aggregated version, in sign_coin_spends
  chia/wallet/sign_coin_spends.py
Labels: Changed, Cleanup

#17171 eliminate polling in full node for processed tx
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/types/transaction_queue_entry.py
Labels: Changed, Exclude_Notes
