Repository Chia-Network/chia-blockchain, pull requests merged in 2023-10, with the labels that each got.

#16462 checkpoint: into main from release/2.1.0 @ ee09892f06e5ff697afde22ec667e6ecad52e888
  chia/cmds/data.py
Labels: checkpoint_merge, Changed

#16452 full_sync flake test.
  chia/simulator/block_tools.py
  tests/core/full_node/full_sync/test_full_sync.py
Labels: Fixed

#16435 Add new RPC to get block spends with conditions
  chia/full_node/mempool_check_conditions.py
  chia/rpc/full_node_rpc_api.py
  chia/rpc/full_node_rpc_client.py
  chia/types/coin_spend.py
  tests/core/test_full_node_rpc.py
Labels: Added, Tests, coverage-diff

#16466 checkpoint: into main from release/2.1.0 @ 07e2a0b8bb75d72a4db689289109c69eb8e81234
  chia/simulator/setup_services.py
  setup.py
Labels: checkpoint_merge, Changed, coverage-diff

#16468 checkpoint: into main from release/2.1.0 @ 867b55097e53de52f052aab9fcb1f4ec9c7422de
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge, checkpoint_merge, Changed

#16453 remove test classes from `test/core/full_node/stores/`
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/full_node/stores/test_hint_store.py
  tests/core/full_node/stores/test_sync_store.py
Labels: Changed, Tests, Cleanup

#16473 Remove unused tmp_dir fixture from HintStore DB schema version test
  tests/core/full_node/stores/test_hint_store.py
Labels: Changed, Cleanup

#16476 hint `chia.util.block_cache` and remove from exclusions
  chia/util/block_cache.py
  mypy-exclusions.txt
Labels: Fixed, Cleanup

#16381 correct backtick usage in coverage comment
  .github/workflows/test.yml
Labels: Fixed, CI

#16489 checkpoint: into main from release/2.1.0 @ 58ad8b8f0923b7cce09c5d04d9a543ac8af8ed2a
  chia/wallet/vc_wallet/cr_cat_wallet.py
Labels: checkpoint_merge, Changed

#16490 checkpoint: into main from release/2.1.0 @ 8b4b2ca86916d66ae6cc4a6fa9046b44b81172fa
  install-gui.sh
  start-gui.sh
Labels: checkpoint_merge, Changed

#16491 checkpoint: into main from release/2.1.0 @ 04fa3b3780e34b735cadc66e8a2f2782579c189c
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: checkpoint_merge, Changed

#16492 checkpoint: into main from release/2.1.0 @ 2ffd471f99b3a57ea0cb4fc9996e9aedbcbb2110
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: checkpoint_merge, Changed

#1332 `@dataclass` `FullNode` to avoid risks of instances without attributes set
  chia/full_node/full_node.py
  chia/server/start_full_node.py
  chia/simulator/setup_services.py
  chia/simulator/start_simulator.py
  tools/test_full_sync.py
Labels: Changed, Cleanup, Exclude_Notes

#16385 `@dataclass` `RpcClient`
  chia/rpc/rpc_client.py
Labels: Changed, Cleanup, Exclude_Notes

#16488 remove test classes from `test/clvm/` and switch to pytest
  tests/clvm/test_chialisp_deserialization.py
  tests/clvm/test_clvm_step.py
  tests/clvm/test_program.py
  tests/clvm/test_puzzle_compression.py
  tests/clvm/test_puzzles.py
  tests/clvm/test_singletons.py
  tests/clvm/test_spend_sim.py
Labels: Changed, Cleanup

#16493 hint `chia.pools` and remove from exclusions
  chia/pools/pool_puzzles.py
  chia/pools/pool_wallet.py
  chia/pools/pool_wallet_info.py
  mypy-exclusions.txt
  tests/pools/test_pool_wallet.py
Labels: Fixed, Cleanup

#15024 merge `listen` into `advertised_port` as `None`
  chia/server/server.py
  chia/server/start_data_layer.py
  chia/server/start_harvester.py
  chia/server/start_service.py
  chia/server/start_timelord.py
  chia/server/start_wallet.py
  chia/server/ws_connection.py
  chia/simulator/setup_nodes.py
  tests/conftest.py
  tests/connection_utils.py
  tests/core/data_layer/test_data_rpc.py
  tests/core/full_node/full_sync/test_full_sync.py
  tests/core/full_node/test_full_node.py
  tests/core/full_node/test_node_load.py
  tests/core/full_node/test_transactions.py
  tests/core/mempool/test_mempool_manager.py
  tests/core/mempool/test_mempool_performance.py
  tests/core/server/test_dos.py
  tests/core/server/test_rate_limits.py
  tests/core/server/test_server.py
  tests/core/ssl/test_ssl.py
  tests/core/test_crawler.py
  tests/farmer_harvester/test_farmer_harvester.py
  tests/pools/test_pool_rpc.py
  tests/simulation/test_simulation.py
  tests/simulation/test_simulator.py
  tests/timelord/test_timelord.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/clawback/test_clawback_decorator.py
  tests/wallet/clawback/test_clawback_metadata.py
  tests/wallet/conftest.py
  tests/wallet/db_wallet/test_dl_wallet.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_bulk_mint.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/rpc/test_dl_wallet_rpc.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_notifications.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_node.py
  tests/wallet/test_wallet_retry.py
  tests/wallet/test_wallet_state_manager.py
  tests/wallet/vc_wallet/test_vc_wallet.py
Labels: stale-pr, Fixed, Cleanup, coverage-diff

#16520 Update chiapos to 2.0.3
  setup.py
Labels: Changed, Exclude_Notes

#16522 checkpoint: into main from release/2.1.0 @ debeb1b5500f9aaed6d13c37ef6ce5e0c297dada
  setup.py
Labels: checkpoint_merge, Changed

#16495 fix flaky test_bad_timestamp.
  tests/blockchain/test_blockchain.py
Labels: Fixed

#16081 Refactor daemon simulation test
  chia/daemon/server.py
  chia/rpc/full_node_rpc_api.py
  chia/simulator/setup_nodes.py
  chia/simulator/setup_services.py
  chia/timelord/timelord_launcher.py
  tests/conftest.py
  tests/core/daemon/config.py
  tests/core/daemon/test_daemon.py
  tests/simulation/test_simulation.py
Labels: Changed, CI

#16519 remove test classes from `test/core/`
  tests/core/test_cost_calculation.py
  tests/core/test_crawler_rpc.py
  tests/core/test_daemon_rpc.py
  tests/core/test_db_conversion.py
  tests/core/test_filter.py
  tests/core/test_full_node_rpc.py
  tests/core/test_merkle_set.py
Labels: Changed, Cleanup

#16472 fix mutable defaults in `Service.__init__()`
  chia/server/start_service.py
Labels: Fixed, Exclude_Notes

#16531 Updated default bladebit version to v3.1.0
  Install-plotter.ps1
  install-plotter.sh
Labels: Changed

#16534 checkpoint: into main from release/2.1.0 @ 2f41a8cfaa82a61702d92fefa3e5c0d9d6a5ae8f
  Install-plotter.ps1
  install-plotter.sh
Labels: checkpoint_merge, Changed

#16512 Update CHANGELOG.md
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#16256 DID wallet coin_added
  chia/rpc/wallet_rpc_api.py
  chia/wallet/did_wallet/did_info.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/wallet_state_manager.py
Labels: Changed

#16291 Enhancements to WalletTestFramework
  chia/simulator/full_node_simulator.py
  tests/wallet/conftest.py
  tests/wallet/test_wallet_test_framework.py
  tests/wallet/vc_wallet/test_vc_wallet.py
Labels: Added, Tests, Exclude_Notes

#15675 Fix DID resync
  chia/wallet/wallet_state_manager.py
  tests/wallet/did_wallet/test_did.py
Labels: Fixed

#16539 skip coverage commenting and labels on `main`
  .github/workflows/test.yml
Labels: Fixed, CI

#16525 Use network overrides for default port for WalletPeers
  chia/wallet/wallet_node.py
Labels: Changed

#16528 Sync store's clear_sync_info doesn't need to be async
  chia/full_node/full_node.py
  chia/full_node/sync_store.py
  tests/core/full_node/stores/test_sync_store.py
Labels: Changed, Cleanup

#16451 Get block spends
  chia/clvm/spend_sim.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool_check_conditions.py
  chia/rpc/full_node_rpc_api.py
  tests/core/mempool/test_mempool.py
  tests/core/test_cost_calculation.py
  tests/core/test_full_node_rpc.py
  tests/generator/test_compression.py
Labels: Fixed

#16560 unpin astroid
  setup.py
Labels: Changed, Exclude_Notes

#14922 cleanup unused peer config
  chia/cmds/configure.py
  chia/cmds/sim_funcs.py
  chia/util/initial-config.yaml
Labels: stale-pr, Changed, Cleanup

#16518 test_services.py flaky test.
  chia/simulator/socket.py
  tests/core/services/__init__.py
  tests/core/services/config.py
  tests/core/services/test_services.py
Labels: Fixed, coverage-diff

#16521 hint `chia.util` and remove from exclusions
  chia/util/chia_logging.py
  chia/util/config.py
  chia/util/db_wrapper.py
  chia/util/hash.py
  chia/util/json_util.py
  chia/util/keychain.py
  chia/util/keyring_wrapper.py
  chia/util/merkle_set.py
  chia/util/partial_func.py
  chia/util/profiler.py
  chia/util/service_groups.py
  chia/util/ssl_check.py
  mypy-exclusions.txt
  tests/core/cmds/test_keys.py
  tests/util/misc.py
  tests/wallet/test_coin_selection.py
Labels: Changed, Cleanup

#16562 enable reorg tests in TestFullNodeBlockCompression
  tests/core/full_node/test_full_node.py
Labels: ready_to_merge, Fixed, CI, Tests

#16537 increase timeouts and use some helpers to reduce flakes in nft tests
  tests/wallet/nft_wallet/test_nft_1_offers.py
Labels: Changed, CI, Exclude_Notes

#16545 Add config option to set rpc timeout and use it for simulator tests
  chia/rpc/rpc_client.py
  chia/util/initial-config.yaml
  tests/cmds/test_sim.py
Labels: Changed

#16581 Changelog for 2.1.1
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#16584 checkpoint: into main from release/2.1.1 @ 10a5f7559ee9b0f4c9e2f78f087dad51cb6168e9
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#16552 separate installer build and publish to separate jobs
  .github/actions/install/action.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: Changed, CI

#16586 Better timestamps on simulated chains (#16326)
  .github/workflows/benchmarks.yml
  .github/workflows/test-single.yml
  chia/simulator/block_tools.py
  tests/farmer_harvester/test_filter_prefix_bits.py
  tools/generate_chain.py
Labels: ready_to_merge, Changed, Tests

#16583 drop ipython dev dependency
  setup.py
Labels: Changed, Exclude_Notes

#16595 allow macOS installer publish job to use GitHub Python
  .github/workflows/build-macos-installers.yml
Labels: Changed, CI

#16596 allow macOS installer build job to use GitHub Python
  .github/workflows/build-macos-installers.yml
Labels: Changed, CI

#16599 run benchmarks in 22.04 container
  .github/workflows/benchmarks.yml
  tests/core/data_layer/test_data_store.py
Labels: Changed, CI, Exclude_Notes

#16601 remove unused test utility function
  tests/blockchain/blockchain_test_utils.py
Labels: ready_to_merge, Changed, Tests, Cleanup

#16605 fixup macos keychain deletion
  .github/workflows/build-macos-installers.yml
Labels: Fixed, CI

#16593 Shutdown on startup failure and log to the log if possible
  chia/server/start_service.py
Labels: Fixed

#16614 Update to the upstream actions
  .github/workflows/stale-issue.yml
Labels: Changed, CI, Exclude_Notes

#16459 remove synchronized block height based clearing of `SyncStore.peak_to_peer` cache
  chia/full_node/full_node.py
  chia/full_node/sync_store.py
  tests/core/full_node/stores/test_sync_store.py
Labels: Changed, Cleanup

#16590 checkpoint: into main from release/2.1.2 @ fe8ae5865099aca446fb446057b8e6c320402839
  chia/clvm/spend_sim.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool_check_conditions.py
  chia/rpc/full_node_rpc_api.py
  tests/core/mempool/test_mempool.py
  tests/core/test_cost_calculation.py
  tests/core/test_full_node_rpc.py
  tests/generator/test_compression.py
Labels: checkpoint_merge, Changed

#16619 checkpoint: into main from release/2.1.2 @ 21f0ee077f356aab7736f2fca49323224916a2c8
  tests/core/full_node/test_full_node.py
Labels: checkpoint_merge, Changed

#16602 Convert KeyTool to a dataclass and annotate it
  mypy-exclusions.txt
  tests/clvm/test_puzzles.py
  tests/util/key_tool.py
  tests/wallet/clawback/test_clawback_lifecycle.py
Labels: Changed, Cleanup

#16523 consistently use `CliRunner.invoke(catch_exceptions=False)`
  tests/cmds/test_sim.py
  tests/core/cmds/test_keys.py
  tests/fee_estimation/cmdline_test.py
  tests/pools/test_pool_cmdline.py
  tests/util/test_dump_keyring.py
Labels: Changed, Tests, Cleanup, coverage-diff

#16603 cleanup unused test config settings
  tests/core/full_node/config.py
  tests/testconfig.py
Labels: Changed, CI

#16529 Make the sync store tests synchronous
  tests/core/full_node/stores/test_sync_store.py
Labels: Changed, Cleanup

#16618 fix issue with syncing testnet, introduced in: Get block spends (#16451)
  chia/full_node/mempool_check_conditions.py
Labels: Fixed

#16634 Remove unused tmp_dir fixture from test_unsupported_version
  tests/core/full_node/stores/test_coin_store.py
Labels: Changed, Cleanup

#16623 Fixed an issue where plot filter reduction was not applied on testnet10
  chia/consensus/default_constants.py
  chia/server/start_farmer.py
  chia/server/start_full_node.py
  tests/util/test_testnet_overrides.py
Labels: Fixed

#16628 remove unnecessary parameter to ClassgroupElement.get_size()
  chia/timelord/timelord.py
  chia/types/blockchain_format/classgroup.py
  chia/util/vdf_prover.py
Labels: Changed, Cleanup

#16643 checkpoint: into main from release/2.1.2 @ c21c2d673400b9b88206c7ba89fd9abf25da1d14
  chia/full_node/mempool_check_conditions.py
Labels: checkpoint_merge, Changed

#16621 Add timeouts and reduce flakes for datalayer
  chia/data_layer/data_layer.py
  tests/core/data_layer/test_data_rpc.py
Labels: Changed, CI, Exclude_Notes, coverage-diff

#16639 Chunk SQLite query for old TR/TX conversion
  chia/wallet/trading/trade_store.py
  chia/wallet/wallet_transaction_store.py
  tests/wallet/test_transaction_store.py
  tests/wallet/test_wallet_trade_store.py
Labels: Fixed

#16652 simplify test_mempool_update_performance()
  tests/core/mempool/test_mempool_performance.py
Labels: Fixed, Tests

#16655 blind bump `test_benchmark_batch_insert_speed()` runtime limits
  tests/core/data_layer/test_data_store.py
Labels: Changed, CI

#16635 rename ClassgroupElement.from_bytes()
  chia/full_node/weight_proof.py
  chia/timelord/timelord.py
  chia/types/blockchain_format/classgroup.py
  chia/util/vdf_prover.py
  tests/blockchain/test_blockchain.py
Labels: ready_to_merge, Changed

#16636 Allow set_status to overwrite trade in store
  chia/wallet/trading/trade_store.py
  tests/wallet/cat_wallet/test_trades.py
Labels: ready_to_merge, Fixed

#16640 Add cache to wallet node preventing resend of processing TX
  chia/wallet/wallet_node.py
  chia/wallet/wallet_node_api.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/test_wallet_node.py
Labels: Fixed

#16653 improve `benchmark_runner` usage efficiency
  tests/conftest.py
  tests/util/misc.py
Labels: Fixed, CI, coverage-diff

#16659 blind bump `test_duplicate_reserve_fee()` runtime limits
  tests/core/mempool/test_mempool.py
Labels: Changed, Tests

#16663 Swap the benchmark job to the same container we use for installers with some things preinstalled
  .github/workflows/benchmarks.yml
Labels: Changed, CI

#16430 Optimize CRCAT trades
  chia/rpc/wallet_rpc_api.py
  chia/wallet/cat_wallet/cat_utils.py
  chia/wallet/trade_manager.py
  chia/wallet/trading/offer.py
  chia/wallet/util/compute_hints.py
  chia/wallet/vc_wallet/cr_cat_drivers.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/vc_drivers.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/test_util.py
  tests/wallet/vc_wallet/test_vc_wallet.py
Labels: Changed

#16632 add NFT, DID, DAO_CAT to wallets denominated in mojos
  chia/cmds/wallet_funcs.py
Labels: Fixed

#16673 Remove unused `Service._rpc_close_task` attribute
  chia/server/start_service.py
Labels: Changed, Cleanup

#16674 require SerializedProgram.from_bytes() is passed a valid clvm structure
  chia/types/blockchain_format/serialized_program.py
  tests/core/full_node/stores/test_block_store.py
  tests/core/mempool/test_mempool_manager.py
  tests/core/test_cost_calculation.py
  tests/generator/test_compression.py
Labels: Changed, Cleanup

#16376 Add support for lists of peers in the config
  chia/cmds/configure.py
  chia/cmds/sim_funcs.py
  chia/server/start_farmer.py
  chia/server/start_harvester.py
  chia/server/start_timelord.py
  chia/server/start_wallet.py
  chia/simulator/setup_services.py
  chia/util/config.py
  chia/util/initial-config.yaml
  tests/core/util/test_config.py
  tests/util/test_config.py
Labels: Added

#16649 Fix benchmark flakiness
  tests/core/full_node/test_performance.py
  tests/core/mempool/test_mempool.py
  tests/core/test_cost_calculation.py
  tests/wallet/test_offer_parsing_performance.py
Labels: Fixed, coverage-diff

#16690 add `-force` to `hdiutil detach`
  .github/workflows/build-macos-installers.yml
Labels: Fixed, CI, Exclude_Notes

#16660 add junit output and summaries for benchmarks
  .github/workflows/benchmarks.yml
  pytest.ini
  setup.py
  tests/conftest.py
  tests/core/full_node/test_performance.py
  tests/core/test_cost_calculation.py
  tests/process_benchmarks.py
  tests/util/misc.py
  tests/wallet/test_offer_parsing_performance.py
Labels: Added, CI

#16644 Simplify test_mempool_performance.py
  tests/core/mempool/test_mempool_performance.py
Labels: Changed, Cleanup

#16692 Simplify add_block_batch by making it take PeerInfo instead of WSChiaConnection
  chia/full_node/full_node.py
  tests/core/mempool/test_mempool_performance.py
  tools/test_full_sync.py
Labels: ready_to_merge, Changed, Cleanup

#16693 Annotate test_mempool_performance.py
  mypy-exclusions.txt
  tests/core/mempool/test_mempool_performance.py
Labels: Changed, Cleanup

#16698 Sync no farmer
  chia/full_node/full_node.py
  chia/simulator/setup_nodes.py
  chia/util/initial-config.yaml
  tests/core/full_node/test_full_node.py
Labels: ready_to_merge, Changed, Tests

#16694 harmonize `SerializedProgram` with `Program`
  chia/simulator/block_tools.py
  chia/types/blockchain_format/program.py
  chia/types/blockchain_format/serialized_program.py
  tests/core/test_cost_calculation.py
  tests/generator/test_rom.py
  tools/run_block.py
Labels: Changed

#16703 Swap some info logs in seeder to warning
  chia/seeder/dns_server.py
Labels: Changed, coverage-diff

#16700 bump benchmark limits
  tests/core/data_layer/test_data_store.py
  tests/core/mempool/test_mempool.py
Labels: Changed, Exclude_Notes

#16702 enable pylint warnings, add all active pylint warnings to ignore list
  pylintrc
Labels: Changed, CI

#16691 dao updates
  chia/wallet/dao_wallet/dao_utils.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/puzzles/deployed_puzzle_hashes.json
  chia/wallet/puzzles/p2_singleton_aggregator.clsp
  chia/wallet/puzzles/p2_singleton_aggregator.clsp.hex
  tests/wallet/dao_wallet/test_dao_clvm.py
Labels: Fixed

#16710 explicit protocol checks against `RpcServiceProtocol`
  chia/data_layer/data_layer.py
  chia/farmer/farmer.py
  chia/full_node/full_node.py
  chia/harvester/harvester.py
  chia/introducer/introducer.py
  chia/seeder/crawler.py
  chia/timelord/timelord.py
  chia/wallet/wallet_node.py
Labels: Changed, Exclude_Notes

#15408 refactor WebSocketServer.ping_task() to loop
  chia/daemon/server.py
Labels: Changed, Cleanup

#16714 Make pylint ignore bare-except in this particular case, just like we do with flake8
  chia/daemon/server.py
Labels: Changed, Cleanup

#16384 Remove Announcement class
  chia/cmds/wallet_funcs.py
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/simulator/wallet_tools.py
  chia/types/announcement.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/cat_wallet/dao_cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/notification_manager.py
  chia/wallet/trade_manager.py
  chia/wallet/trading/offer.py
  chia/wallet/vc_wallet/cr_cat_drivers.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/vc_drivers.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
  tests/blockchain/test_blockchain_transactions.py
  tests/cmds/wallet/test_did.py
  tests/core/data_layer/test_data_rpc.py
  tests/core/full_node/test_conditions.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_manager.py
  tests/wallet/cat_wallet/test_offer_lifecycle.py
  tests/wallet/nft_wallet/test_nft_lifecycle.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_singleton.py
  tests/wallet/test_singleton_lifecycle.py
  tests/wallet/test_singleton_lifecycle_fast.py
  tests/wallet/vc_wallet/test_vc_lifecycle.py
Labels: Changed, Exclude_Notes, vault

#16633 move vdf validation to a free free function
  chia/consensus/block_header_validation.py
  chia/full_node/full_node.py
  chia/full_node/full_node_store.py
  chia/full_node/weight_proof.py
  chia/timelord/timelord.py
  chia/types/blockchain_format/vdf.py
  tests/blockchain/test_blockchain.py
Labels: ready_to_merge, Changed, Cleanup

#16735 fix full node hangs and timeouts
  tests/core/full_node/config.py
  tests/core/full_node/test_full_node.py
Labels: Fixed, Tests

#16733 generalize JSON serializer
  chia/util/json_util.py
Labels: ready_to_merge, Fixed

#16645 datalayer test coverage
  .coveragerc
  tests/core/data_layer/test_data_cli.py
  tests/core/data_layer/test_data_layer_util.py
  tests/core/data_layer/test_data_rpc.py
  tests/core/data_layer/test_data_store_schema.py
  tests/core/data_layer/util.py
Labels: Changed, CI

#16713 Use version 3.10 for checks that are part of the lint and upload source distribution workflow
  .github/workflows/upload-pypi-source.yml
Labels: Changed, Cleanup

#16737 bump chia_rs to version 0.2.13
  chia/full_node/mempool_check_conditions.py
  setup.py
  tests/generator/test_rom.py
Labels: ready_to_merge, Changed

#16701 transition away from `__bytes__` conversion for fixed-size integers
  chia/clvm/spend_sim.py
  chia/consensus/block_body_validation.py
  chia/data_layer/dl_wallet_store.py
  chia/full_node/coin_store.py
  chia/full_node/full_node_api.py
  chia/simulator/block_tools.py
  chia/simulator/setup_nodes.py
  chia/util/streamable.py
  chia/util/struct_stream.py
  chia/wallet/key_val_store.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/notification_store.py
  chia/wallet/trading/offer.py
  chia/wallet/vc_wallet/vc_store.py
  chia/wallet/wallet_coin_store.py
  chia/wallet/wallet_transaction_store.py
  tests/wallet/cat_wallet/test_cat_outer_puzzle.py
  tests/wallet/test_transaction_store.py
  tests/wallet/vc_wallet/test_cr_outer_puzzle.py
Labels: ready_to_merge, Changed
