Repository Chia-Network/chia-blockchain, pull requests merged in 2023-04, with the labels that each got.

#14965 util: Drop unused `chia.util.pip_import`
  chia/util/pip_import.py
  mypy.ini
Labels: Changed, Cleanup

#14923 wallet: Remove unused transaction getter
  chia/wallet/wallet_state_manager.py
  chia/wallet/wallet_transaction_store.py
Labels: Changed, Cleanup

#14911 wallet: Improve coin state retry wait logic and retry store test
  chia/wallet/wallet_node.py
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed

#14631 wallet: Improve balance caching
  chia/rpc/wallet_rpc_api.py
  chia/wallet/wallet_node.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_wallet_node.py
Labels: Changed

#14460 wallet: Rename add block/state methods
  chia/wallet/wallet_blockchain.py
  chia/wallet/wallet_node.py
  tests/wallet/test_wallet_blockchain.py
Labels: Changed, Cleanup

#14842 wallet: Raise in `WalletNode.get_full_node_peer` and move some of its calls
  chia/rpc/wallet_rpc_api.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/wallet_node.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/db_wallet/test_dl_offers.py
  tests/wallet/db_wallet/test_dl_wallet.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
Labels: Changed, Cleanup

#14973 skip empty directories pre-commit
  tests/build-init-files.py
Labels: Fixed

#14974 remove synced status check from wallet rpc `/push_transactions` endpoint
  chia/rpc/wallet_rpc_api.py
Labels: Changed, Cleanup

#14972 Check hint length in notficication manager to avoid raise
  chia/wallet/notification_manager.py
Labels: Fixed

#14964 wallet: Introduce `WalletIdentifier`
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/notification_manager.py
  chia/wallet/trade_manager.py
  chia/wallet/util/wallet_types.py
  chia/wallet/wallet_puzzle_store.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_puzzle_store.py
Labels: Changed, Cleanup

#14971 Mempool insertion order
  chia/full_node/mempool.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_manager.py
Labels: ready_to_merge, Fixed

#14878 data_layer: Simplify wallet get and create code
  chia/data_layer/data_layer_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/db_wallet/test_dl_offers.py
  tests/wallet/db_wallet/test_dl_wallet.py
Labels: Changed, Cleanup

#14934 Simplify creating a spend bundle from mempool items and move this logic to the mempool
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
Labels: Changed, Cleanup

#14987 windows fix of memory profiler
  chia/util/profiler.py
Labels: ready_to_merge, Fixed

#14982 Update Wallet command line help for key fingerprints
  chia/cmds/coins.py
  chia/cmds/plotnft.py
  chia/cmds/wallet.py
Labels: Clean: caught up to main, Changed

#14899 wallet: Drop `chia.wallet.user_settings`
  chia/wallet/settings/__init__.py
  chia/wallet/settings/default_settings.py
  chia/wallet/settings/settings_objects.py
  chia/wallet/settings/user_settings.py
  mypy.ini
  setup.py
Labels: Changed, Cleanup

#14642 wallet: Handle some peer closed cases better
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
Labels: Changed, Cleanup

#14913 wallet: Enable and fix more `mypy` in `wallet_node.py`
  chia/wallet/wallet_node.py
  mypy.ini
  tests/wallet/test_wallet_node.py
Labels: Changed, Cleanup

#14831 add new peak and tidy new compact vdf limited semaphore full logging
  chia/full_node/full_node_api.py
Labels: Added, Cleanup

#15012 Clean create tandem xch tx
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet.py
Labels: Changed, Cleanup

#14070 Fixed an issue where `label-conflict` action did not run when opening a PR
  .github/workflows/conflict-check.yml
Labels: Fixed, ready_to_review

#14541 mypy chia.util.files
  chia/util/files.py
  mypy.ini
Labels: stale-pr, Clean: caught up to main, Changed, Cleanup

#14736 hint chia.cmds.passphrase, passphrase_funcs
  chia/cmds/passphrase.py
  chia/cmds/start_funcs.py
  chia/util/file_keyring.py
  chia/util/keychain.py
  chia/util/keyring_wrapper.py
Labels: Fixed, Cleanup

#14626 Small improvements to trusted peer check to include IPv6 addresses and add tests
  chia/cmds/peer_funcs.py
  chia/server/server.py
  chia/util/network.py
  tests/util/test_trusted_peer.py
Labels: Fixed

#14781 Changed: remove unused self.new_subslot_end
  chia/timelord/timelord.py
  chia/timelord/timelord_api.py
Labels: Changed, Cleanup

#14804 avoid FullNode.fetch_block_batches() from putting two `None`s into the batch queue
  chia/full_node/full_node.py
Labels: Fixed, Cleanup

#14867 close daemon client even for a BaseException in acquire_connection_to_daemon()
  chia/daemon/client.py
Labels: Fixed

#14928 remove unused Service(server_listen_ports=) parameter
  chia/seeder/start_crawler.py
  chia/server/start_data_layer.py
  chia/server/start_farmer.py
  chia/server/start_full_node.py
  chia/server/start_harvester.py
  chia/server/start_introducer.py
  chia/server/start_service.py
  chia/server/start_timelord.py
  chia/server/start_wallet.py
  chia/simulator/start_simulator.py
Labels: Changed, Cleanup

#14937 more passing arguments by name in `ChiaServer`
  chia/server/server.py
Labels: Changed, Cleanup

#15001 correct broken exit codes from `manage_clvm.py`
  tools/manage_clvm.py
Labels: Fixed, CI

#15011 Print mypy version in CI jobs
  .github/workflows/upload-pypi-source.yml
Labels: Clean: caught up to main, Changed, CI, Cleanup

#14536 No need to test install scripts on Mint
  .github/workflows/test-install-scripts.yml
Labels: Changed, CI

#14151 server: `peer_host` + `peer_port` -> `peer_info` in `WSChiaConnection`
  chia/farmer/farmer.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/introducer/introducer_api.py
  chia/plot_sync/receiver.py
  chia/rpc/rpc_server.py
  chia/server/node_discovery.py
  chia/server/server.py
  chia/server/ws_connection.py
  chia/wallet/util/wallet_sync_utils.py
  chia/wallet/wallet_node.py
  tests/core/server/test_dos.py
  tests/plot_sync/test_receiver.py
  tests/plot_sync/util.py
Labels: Changed, Cleanup

#15018 tests: Reuse `puzzle_utils.make_create_coin_condition` in `test_puzzles`
  tests/clvm/test_puzzles.py
Labels: Changed, Cleanup

#14883 Dl plugin service
  chia/data_layer/data_layer.py
  chia/data_layer/download_data.py
  chia/data_layer/s3_plugin_config.yml
  chia/data_layer/s3_plugin_service.py
  chia/server/start_data_layer.py
  chia/util/initial-config.yaml
  tests/core/data_layer/test_data_rpc.py
Labels: enhancement, Added

#14983 Rename singleton helper functions
  chia/rpc/wallet_rpc_api.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/did_wallet/did_wallet_puzzles.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/singleton.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/did_wallet/test_did.py
Labels: Clean: caught up to main, Changed, Cleanup

#14572 wallet: Some rework/cleanup of weight proof validation
  chia/wallet/wallet_node.py
  chia/wallet/wallet_weight_proof_handler.py
  tests/wallet/test_wallet_blockchain.py
Labels: Changed, Cleanup

#15026 cleanup connection removal from `ChiaServer.all_connections`
  chia/server/server.py
Labels: Fixed, Cleanup

#14969 wallet: Reduce DB lookups in `handle_did` and `handle_nft`
  chia/wallet/wallet_state_manager.py
Labels: Changed

#15009 util: Cleanup `Tuple[Optional[Err], ..]` returns in `condition_tools.py`
  chia/simulator/wallet_tools.py
  chia/util/condition_tools.py
  chia/wallet/cat_wallet/cat_utils.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/puzzles/prefarm/make_prefarm_ph.py
  chia/wallet/puzzles/prefarm/spend_prefarm.py
  chia/wallet/sign_coin_spends.py
  chia/wallet/util/debug_spend_bundle.py
  tests/core/mempool/test_mempool.py
  tests/util/key_tool.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/test_singleton.py
Labels: Changed, Cleanup

#14997 server: Rework config peer resolving and connection handling
  chia/server/reconnect_task.py
  chia/server/start_farmer.py
  chia/server/start_harvester.py
  chia/server/start_service.py
  chia/server/start_timelord.py
  chia/server/start_wallet.py
  chia/simulator/setup_nodes.py
  chia/simulator/setup_services.py
  chia/types/peer_info.py
  tests/farmer_harvester/test_farmer_harvester.py
  tests/plot_sync/test_plot_sync.py
  tests/plot_sync/util.py
Labels: Fixed

#15017 wallet: Drop unused `Wallet.create_spend_bundle_relative_chia`
  chia/wallet/wallet.py
Labels: Changed, Cleanup

#14993 limit expiring transactions
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  tests/core/mempool/test_mempool.py
Labels: ready_to_merge, Changed

#15037 S3 plugin config and endpoint updates
  chia/data_layer/data_layer.py
  chia/data_layer/download_data.py
  chia/data_layer/s3_plugin_config.yml
  chia/data_layer/s3_plugin_service.py
  chia/pyinstaller.spec
  setup.py
Labels: Added, Cleanup

#15020 Return fee estimates as integer mojos
  chia/rpc/full_node_rpc_api.py
Labels: Changed

#15031 Add very basic logging support to S3 plugin
  chia/data_layer/s3_plugin_config.yml
  chia/data_layer/s3_plugin_service.py
Labels: Added, Cleanup

#15051 wallet: Select enough XCH to cover the fee when creating an offer
  chia/wallet/trade_manager.py
  chia/wallet/wallet.py
Labels: Changed, Cleanup

#15060 Introduce and use the ability to honor spends IDs in make_test_conds
  tests/core/mempool/test_mempool_manager.py
Labels: Changed, Cleanup

#15038 extend mempool-benchmark
  benchmarks/mempool.py
Labels: ready_to_merge, Changed, Tests

#15056 Simplify create_bundle_from_mempool's handling of removals
  chia/clvm/spend_sim.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  tests/blockchain/test_blockchain_transactions.py
  tests/core/mempool/test_mempool_manager.py
Labels: Changed, Cleanup

#15057 Added some sanity checks to upload and download for S3 plugin
  chia/data_layer/data_layer.py
  chia/data_layer/s3_plugin_config.yml
  chia/data_layer/s3_plugin_service.py
Labels: Changed, Cleanup

#14896 wallet: Some cleanup of `WalletNode.fetch_puzzle_solution`
  chia/data_layer/data_layer_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/util/wallet_sync_utils.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#15046 server: Try to convert in `known_active_capabilities`
  chia/server/capabilities.py
Labels: Changed, Cleanup

#15047 tests: Drop some unused code in `test_puzzle_store.py`
  tests/wallet/test_puzzle_store.py
Labels: Changed, Cleanup

#15048 wallet: Fix, simplify and test `TransactionRecord.is_valid`
  chia/wallet/transaction_record.py
  tests/wallet/test_transaction_store.py
Labels: Fixed

#15055 Generator mod cleanup and simplification
  chia/full_node/generator.py
  chia/full_node/mempool_check_conditions.py
  chia/simulator/block_tools.py
  chia/wallet/puzzles/rom_bootstrap_generator.py
  mypy.ini
  tests/conftest.py
  tests/generator/test_compression.py
  tests/generator/test_generator_types.py
  tests/generator/test_rom.py
  tools/analyze-chain.py
Labels: ready_to_merge, Changed, Cleanup

#15028 Add plugin_info and healthz endpoints to s3 plugin service, add `chia data plugins check` cli
  chia/cmds/data.py
  chia/cmds/data_funcs.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_util.py
  chia/data_layer/s3_plugin_service.py
  chia/rpc/data_layer_rpc_api.py
  chia/rpc/data_layer_rpc_client.py
Labels: Added, Cleanup

#15062 DL plugin Add missing files
  chia/data_layer/data_layer.py
  chia/data_layer/s3_plugin_service.py
Labels: enhancement, Added

#14921 activate the soft-fork and soft-fork2 earlier on testnet10
  chia/server/start_full_node.py
  chia/util/initial-config.yaml
Labels: Changed

#14990 Check for directory existence before creating offer
  chia/cmds/wallet_funcs.py
Labels: ready_to_merge, Fixed

#15082 Removed "failed to write files" log spam from data layer
  chia/data_layer/data_layer.py
Labels: Fixed, Cleanup

#15075 Fix manage_clvm.py hash building and std libraries
  tools/manage_clvm.py
Labels: ready_to_merge, Fixed

#15083 Add timestamp and formatting to S3 plugin log
  chia/data_layer/s3_plugin_config.yml
  chia/data_layer/s3_plugin_service.py
Labels: Added, Cleanup

#15030 New S3 plugin endpoints for add_store_id and remove_store_id
  chia/data_layer/s3_plugin_service.py
Labels: Added, Cleanup

#14927 Adding daily full matrix test
  .github/workflows/daily-matrix.yml
Labels: Added, CI, ready_to_review

#15005 Add Chia Simulator tools directly Into Chia Blockchain
  chia/cmds/chia.py
  chia/cmds/cmds_util.py
  chia/cmds/dev.py
  chia/cmds/sim.py
  chia/cmds/sim_funcs.py
  chia/cmds/start.py
  chia/cmds/start_funcs.py
  chia/cmds/stop.py
  chia/simulator/block_tools.py
  chia/util/default_root.py
  tests/cmds/test_sim.py
  tests/pools/test_pool_rpc.py
Labels: Added, Cleanup

#15102 Clawback proposed updates
  chia/rpc/wallet_rpc_api.py
  chia/wallet/puzzles/clawback/drivers.py
  chia/wallet/wallet_state_manager.py
Labels: Changed

#15110 bump chia_rs to 0.2.7
  setup.py
Labels: ready_to_merge, Changed

#15061 Annotate test_blockchain_transactions.py
  mypy.ini
  tests/blockchain/test_blockchain_transactions.py
Labels: Changed, Cleanup

#15103 Use "item" instead of "spend" in mempool's items functions names
  chia/clvm/spend_sim.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/rpc/full_node_rpc_api.py
  tests/core/mempool/test_mempool.py
  tests/wallet/test_wallet_retry.py
Labels: Changed, Cleanup

#14705 hint chia.rpc.full_node_rpc_client
  chia/cmds/netspace_funcs.py
  chia/cmds/show.py
  chia/cmds/show_funcs.py
  chia/rpc/full_node_rpc_client.py
Labels: Changed, Cleanup

#15088 tests: Fix flaky `test_long_sync_untrusted_break`
  tests/wallet/sync/test_wallet_sync.py
Labels: Fixed, Tests

#15086 extract wallet specific behavior from get any service client
  chia/cmds/cmds_util.py
  chia/cmds/data_funcs.py
  chia/cmds/farm_funcs.py
  chia/cmds/netspace_funcs.py
  chia/cmds/peer_funcs.py
  chia/cmds/plotnft_funcs.py
  chia/cmds/show_funcs.py
  chia/cmds/sim_funcs.py
Labels: Changed, Cleanup

#15084 be more careful about deleting temporary plots
  tests/pools/test_pool_rpc.py
Labels: Fixed, Cleanup

#15080 fail for under 100% diff coverage
  .github/workflows/test.yml
Labels: Added, CI

#15035 lower MAX_FUTURE_TIME to 2 minutes with the 1.8.0 soft-fork activation
  chia/consensus/block_header_validation.py
  chia/consensus/constants.py
  chia/consensus/default_constants.py
  tests/blockchain/test_blockchain.py
Labels: ready_to_merge, Changed

#15093 improve ignore handling in `__init__.py` creation script
  tests/build-init-files.py
Labels: Fixed, Cleanup

#15108 wallet: Implement `WalletCoinRecord.to_json_dict_parsed_metadata`
  chia/wallet/util/wallet_types.py
  chia/wallet/wallet_coin_record.py
  tests/wallet/test_wallet_coin_store.py
Labels: Added

#14900 wallet: Enable and fix more `mypy` for `wallet_state_manager.py`
  chia/wallet/wallet_state_manager.py
  mypy.ini
Labels: Changed, Cleanup

#15019 wallet: Drop `AmountWithPuzzlehHash`, use `Payment` instead
  chia/data_layer/data_layer_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/simulator/full_node_simulator.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/puzzles/puzzle_utils.py
  chia/wallet/puzzles/tails.py
  chia/wallet/util/wallet_types.py
  chia/wallet/wallet.py
  tests/clvm/test_puzzles.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_wallet.py
Labels: Changed, Cleanup

#15058 Simplify MempoolItem's cost property
  chia/types/mempool_item.py
Labels: Changed, Cleanup

#15069 Implement get_items_by_coin_ids() for the mempool
  chia/full_node/mempool.py
  tests/core/mempool/test_mempool.py
Labels: Added

#15128 wallet: Implement `WalletNFTStore.delete_wallet`
  chia/wallet/wallet_nft_store.py
  tests/wallet/test_nft_store.py
Labels: Added

#15131 Simplify handling additions and removals in validate_spend_bundle()
  chia/full_node/mempool_manager.py
Labels: Changed, Cleanup

#15134 rework class protocol check pattern
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet.py
Labels: Changed, Cleanup

#14999 util: Async DNS lookups
  chia/rpc/rpc_server.py
  chia/seeder/crawler.py
  chia/server/node_discovery.py
  chia/server/start_service.py
  chia/timelord/timelord_launcher.py
  chia/util/network.py
  tests/util/test_network.py
Labels: Fixed

#15148 wallet: Move assignments of `WalletStateManager._sync_target`
  chia/wallet/wallet_state_manager.py
Labels: Fixed

#15149 wallet: Lock `WalletStateManager.lock` while populating balances initially
  chia/wallet/wallet_node.py
Labels: Fixed
