Repository Chia-Network/chia-blockchain, pull requests merged in 2023-07, with the labels that each got.

#15634 Apply Kevin's suggestion to send peak height instead of filter prefix bits as part of NewSignagePoint
  chia/farmer/farmer_api.py
  chia/full_node/full_node.py
  chia/protocols/farmer_protocol.py
  tests/core/test_farmer_harvester_rpc.py
  tests/farmer_harvester/test_farmer_harvester.py
  tests/farmer_harvester/test_filter_prefix_bits.py
  tests/util/network_protocol_data.py
  tests/util/protocol_messages_bytes-v1.0
  tests/util/protocol_messages_json.py
Labels: Changed, Cleanup

#15668 add get_wallet_addresses RPC for deriving wallet addresses
  chia/daemon/server.py
  tests/core/daemon/test_daemon.py
Labels: enhancement, Added

#15672 update build script for lerna 7
  build_scripts/build_windows-1-gui.ps1
  build_scripts/npm_windows/package-lock.json
  build_scripts/npm_windows/package.json
Labels: Fixed

#15645 add DataLayer batch insert benchmark
  tests/core/data_layer/test_data_store.py
Labels: Added, Tests

#15629 Fix fork height constant for simulator / block tools
  chia/simulator/block_tools.py
  tests/blockchain/test_blockchain.py
Labels: Fixed

#15686 Remove no longer needed filter prefix bit related logic and make height non optional in verify_and_get_quality_string()
  chia/farmer/farmer.py
  chia/farmer/farmer_api.py
  chia/types/blockchain_format/proof_of_space.py
  tests/core/custom_types/test_proof_of_space.py
  tests/farmer_harvester/test_farmer_harvester.py
Labels: Changed, Cleanup

#15693 multi threaded `chia plots check`
  chia/harvester/harvester_api.py
  chia/plotting/check_plots.py
Labels: ready_to_merge, Added

#15670 checkpoint: into main from release/1.8.2 @ f90ddf42ad5ff047533ba979b96c4d7f3b21f916
  chia/consensus/get_block_challenge.py
  chia/full_node/full_node.py
  chia/full_node/full_node_store.py
  chia/timelord/timelord.py
  chia/timelord/timelord_api.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/full_node/test_full_node.py
Labels: checkpoint_merge, Changed

#15709 checkpoint: into main from release/1.8.2 @ 4f1810e9170cbb704fec94518a39faa29d765e49
  setup.py
Labels: checkpoint_merge, Changed

#15712 checkpoint: into main from release/1.8.2 @ f0764f27defa865fd4ccc28756195e535adc6bd9
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#15535 test-single.yml: defaults: run: shell: bash
  .github/workflows/test-single.yml
Labels: ready_to_merge, Changed, CI

#15689 less e501
  tests/core/full_node/config.py
  tests/core/full_node/stores/config.py
  tests/wallet/cat_wallet/config.py
  tests/wallet/clawback/config.py
  tests/wallet/config.py
  tests/wallet/did_wallet/config.py
Labels: Fixed, Tests, Cleanup

#15628 Convert All CLI Commands to using async generators
  chia/cmds/cmds_util.py
  chia/cmds/coin_funcs.py
  chia/cmds/coins.py
  chia/cmds/plotnft.py
  chia/cmds/plotnft_funcs.py
  chia/cmds/plots.py
  chia/cmds/plotters.py
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_client.py
  mypy-exclusions.txt
Labels: CLI, Changed

#15581 Hard fork 2.0
  chia/full_node/mempool_check_conditions.py
  chia/simulator/block_tools.py
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/full_node/test_conditions.py
  tests/core/mempool/test_mempool.py
  tests/wallet/test_singleton_lifecycle.py
Labels: ready_to_merge, Added

#15708 forward `flags` in `get_puzzle_and_solution_for_coin()`
  chia/clvm/spend_sim.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool_check_conditions.py
  chia/rpc/full_node_rpc_api.py
  tests/core/mempool/test_mempool.py
  tests/core/test_cost_calculation.py
  tests/generator/test_compression.py
Labels: ready_to_merge, Added, Exclude_Notes

#15676 remove ROM bootstrap generator2, as we're not making this transition
  chia/wallet/puzzles/deployed_puzzle_hashes.json
  chia/wallet/puzzles/rom_bootstrap_generator.py
  chia/wallet/puzzles/rom_bootstrap_generator2.clsp
  chia/wallet/puzzles/rom_bootstrap_generator2.clsp.hex
  chia/wallet/puzzles/rom_bootstrap_generator2.clsp.hex.sha256tree
Labels: ready_to_merge, Changed, Cleanup

#15725 server: Store `Handshake.software_version` in connections as `str`
  chia/server/ws_connection.py
  tests/core/server/test_server.py
Labels: Changed

#15727 fix typo in chia plots check
  chia/plotting/check_plots.py
Labels: ready_to_merge, Fixed, Exclude_Notes

#15704 Cleanup CLI RPC connection error handling
  chia/cmds/chia.py
  chia/cmds/cmds_util.py
  chia/cmds/coin_funcs.py
  chia/cmds/data_funcs.py
  chia/cmds/farm_funcs.py
  chia/cmds/netspace_funcs.py
  chia/cmds/peer_funcs.py
  chia/cmds/plotnft_funcs.py
  chia/cmds/show_funcs.py
  chia/cmds/sim_funcs.py
  chia/cmds/wallet_funcs.py
  chia/util/errors.py
Labels: CLI, Changed

#15715 Some NFT RPC mypy fixes
  chia/rpc/wallet_rpc_api.py
Labels: Fixed

#15736 pass consensus constants into get_name_puzzle_conditions().
  chia/clvm/spend_sim.py
  chia/consensus/block_creation.py
  chia/consensus/blockchain.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool_check_conditions.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/wallet.py
  tests/blockchain/test_blockchain.py
  tests/blockchain/test_blockchain_transactions.py
  tests/clvm/benchmark_costs.py
  tests/clvm/coin_store.py
  tests/clvm/test_puzzles.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_manager.py
  tests/core/test_cost_calculation.py
  tests/generator/test_rom.py
  tests/pools/test_pool_puzzles_lifecycle.py
  tests/util/generator_tools_testing.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/test_singleton_lifecycle_fast.py
Labels: ready_to_merge, Changed, Tests

#15496 Clawback resync
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/util/transaction_type.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_wallet.py
Labels: ready_to_merge, Fixed

#15336 Plot filter hard fork
  chia/consensus/block_header_validation.py
  chia/consensus/multiprocess_validation.py
  chia/farmer/farmer_api.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/weight_proof.py
  chia/harvester/harvester_api.py
  chia/protocols/farmer_protocol.py
  chia/protocols/harvester_protocol.py
  chia/simulator/block_tools.py
  chia/timelord/iters_from_block.py
  chia/timelord/timelord.py
  chia/timelord/timelord_api.py
  chia/timelord/timelord_state.py
  chia/types/blockchain_format/proof_of_space.py
  tests/core/custom_types/test_proof_of_space.py
  tests/core/test_farmer_harvester_rpc.py
  tests/farmer_harvester/test_farmer_harvester.py
  tests/farmer_harvester/test_filter_prefix_bits.py
  tests/util/network_protocol_data.py
  tests/util/protocol_messages_bytes-v1.0
  tests/util/protocol_messages_json.py
  tests/weight_proof/test_weight_proof.py
Labels: Changed

#15730 Add DIDWallet.get_coin() to simplify DID wallet
  chia/rpc/wallet_rpc_api.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/vc_wallet/vc_wallet.py
  tests/wallet/did_wallet/test_did.py
Labels: Changed

#15695 Add fields to BlockRecord.
  benchmarks/block_store.py
  chia/cmds/db_validate_func.py
  chia/consensus/block_record.py
  chia/consensus/full_block_to_block_record.py
  chia/full_node/block_store.py
  chia/util/full_block_utils.py
  tests/core/full_node/stores/test_block_store.py
  tests/util/test_full_block_utils.py
Labels: ready_to_merge, Added

#15515 Update config.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: Changed

#15702 compressed plot support
  chia/harvester/harvester.py
  chia/harvester/harvester_api.py
  chia/plotting/check_plots.py
  chia/plotting/manager.py
  chia/simulator/block_tools.py
  chia/simulator/setup_services.py
  chia/util/initial-config.yaml
  setup.py
  tests/core/daemon/test_daemon.py
Labels: Added

#15751 Renaming instances of 'decompresser' to 'decompressor'
  chia/harvester/harvester.py
  chia/plotting/check_plots.py
  chia/plotting/manager.py
  chia/simulator/setup_services.py
  chia/util/initial-config.yaml
  setup.py
  tests/core/daemon/test_daemon.py
Labels: Changed

#15493 protocols: Introduce `error` protocol message
  chia/protocols/protocol_message_types.py
  chia/protocols/shared_protocol.py
  chia/server/rate_limit_numbers.py
  chia/server/ws_connection.py
  chia/util/errors.py
  tests/core/server/test_server.py
  tests/util/build_network_protocol_files.py
  tests/util/network_protocol_data.py
  tests/util/protocol_messages_bytes-v1.0
  tests/util/protocol_messages_json.py
  tests/util/test_errors.py
  tests/util/test_network_protocol_files.py
  tests/util/test_network_protocol_json.py
  tests/util/test_network_protocol_test.py
Labels: Added

#15556 wallet: Convert coin ids in `_add_coin_states` to `bytes32`
  chia/wallet/wallet_state_manager.py
Labels: Changed, Cleanup

#15760 bump chia_rs dependency to 0.2.9
  benchmarks/mempool-long-lived.py
  benchmarks/mempool.py
  setup.py
  tests/core/full_node/test_generator_tools.py
  tests/core/full_node/test_hint_management.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_manager.py
  tests/generator/test_rom.py
Labels: ready_to_merge, Changed

#15680 Fix variable name typo
  build_scripts/installer-version.py
Labels: Fixed

#15767 Fixed add lock around plot info
  chia/plotting/check_plots.py
Labels: Fixed

#14611 remove support for Python 3.7
  .github/workflows/check_wheel_availability.yaml
  .github/workflows/test-install-scripts.yml
  .github/workflows/test-single.yml
  .github/workflows/upload-pypi-source.yml
  Install.ps1
  README.md
  benchmarks/mempool.py
  chia/server/chia_policy.py
  chia/util/task_timing.py
  install.sh
  setup.py
  tests/core/server/test_loop.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/db_wallet/test_dl_offers.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/test_offer_parsing_performance.py
  tools/generate_chain.py
  tools/test_full_sync.py
Labels: stale-pr, ready_to_merge, Changed

#15775 Added quality lookup time info to FarmingInfo
  chia/farmer/farmer_api.py
  chia/harvester/harvester_api.py
  chia/protocols/farmer_protocol.py
  chia/rpc/harvester_rpc_api.py
  tests/util/network_protocol_data.py
  tests/util/protocol_messages_bytes-v1.0
  tests/util/protocol_messages_json.py
Labels: Changed

#15754 use actual chiapos version when testing daemon
  tests/core/daemon/test_daemon.py
Labels: Fixed, Tests

#15762 Fix Cli error when exiting on some builds of python.
  chia/cmds/chia.py
  chia/cmds/cmds_util.py
  chia/util/errors.py
Labels: Fixed

#15755 move sqlite host parameter limit to db wrapper
  chia/consensus/blockchain.py
  chia/full_node/block_store.py
  chia/util/db_wrapper.py
  tests/core/full_node/stores/test_block_store.py
Labels: Changed, Cleanup

#15779 Fix whitespace on legacy-support-policy.md
  legacy-support-policy.md
Labels: Fixed

#15771 Updated `UI_ACTUAL_SPACE_CONSTANT_FACTOR` to 0.78
  chia/consensus/pos_quality.py
Labels: Changed

#15698 Cleanup & Fix Simulator Sub Epoch Logic
  chia/simulator/block_tools.py
Labels: simulator, Fixed

#15758 Add RPC client and tests for cancel_offers endpoint
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge, Added

#15690 add sql logging config for DataLayer
  chia/data_layer/data_layer.py
  chia/data_layer/data_store.py
  chia/util/db_wrapper.py
  chia/util/initial-config.yaml
  tests/conftest.py
  tests/core/data_layer/test_data_layer.py
Labels: Added

#15691 avoid DataLayer insert precheck
  chia/data_layer/data_store.py
  tests/core/data_layer/test_data_store.py
Labels: Changed

#15759 Fix flaky CAT test
  chia/wallet/wallet_transaction_store.py
  tests/wallet/test_transaction_store.py
Labels: ready_to_merge, Fixed

#15790 Announce conditions limit
  tests/conftest.py
  tests/core/full_node/test_conditions.py
  tests/wallet/sync/test_wallet_sync.py
Labels: ready_to_merge, Added, Tests

#15518 Report certificate errors directly for CLI connection errors
  chia/cmds/cmds_util.py
Labels: Changed

#15694 Remove references to old offer mod
  chia/data_layer/data_layer_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/puzzles/deployed_puzzle_hashes.json
  chia/wallet/puzzles/settlement_payments_old.clsp
  chia/wallet/puzzles/settlement_payments_old.clsp.hex
  chia/wallet/trade_manager.py
  chia/wallet/trading/offer.py
  chia/wallet/util/puzzle_compression.py
  tests/clvm/test_puzzle_compression.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/db_wallet/test_dl_offers.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_offer_parsing_performance.py
Labels: ready_to_merge, Changed

#15728 avoid DataLayer insert ancestors precheck
  chia/data_layer/data_store.py
  tests/core/data_layer/test_data_store.py
Labels: Changed

#15764 Improved pool stats handling
  chia/farmer/farmer.py
  chia/farmer/farmer_api.py
  chia/rpc/farmer_rpc_api.py
  tests/farmer_harvester/test_farmer.py
Labels: Changed

#15777 Added `average_block_time` to `get_blockchain_state` FullNode RPC API
  chia/rpc/full_node_rpc_api.py
  tests/core/test_full_node_rpc.py
Labels: Changed

#15772 Added `get_keys_for_plot` daemon server API
  chia/daemon/client.py
  chia/daemon/server.py
  tests/core/daemon/test_daemon.py
Labels: Changed

#15774 Added cuda and plot compression support for bladebit 3
  chia/daemon/server.py
  chia/plotters/bladebit.py
  chia/plotters/plotters.py
  tests/core/daemon/test_daemon.py
Labels: Changed

#15770 Added `total_effective_plot_size` for `get_harvesters` RPC API
  chia/cmds/farm_funcs.py
  chia/plot_sync/receiver.py
  tests/cmds/config.py
  tests/cmds/test_farm_cmd.py
  tests/conftest.py
  tests/plot_sync/test_receiver.py
  tests/plot_sync/test_sync_simulated.py
Labels: Changed

#15776 Added compression level and harvesting mode to harvester protocol/mes…
  chia/harvester/harvester.py
  chia/harvester/harvester_api.py
  chia/plot_sync/receiver.py
  chia/plot_sync/sender.py
  chia/plotting/cache.py
  chia/plotting/manager.py
  chia/plotting/util.py
  chia/protocols/harvester_protocol.py
  chia/rpc/harvester_rpc_api.py
  chia/rpc/harvester_rpc_client.py
  tests/farmer_harvester/test_farmer_harvester.py
  tests/plot_sync/test_delta.py
  tests/plot_sync/test_plot_sync.py
  tests/plot_sync/test_receiver.py
  tests/plot_sync/test_sender.py
  tests/plot_sync/test_sync_simulated.py
  tests/plotting/test_plot_manager.py
  tests/util/network_protocol_data.py
  tests/util/protocol_messages_bytes-v1.0
  tests/util/protocol_messages_json.py
Labels: Changed

#15765 Farmer now returns missing signage points
  chia/farmer/farmer.py
  chia/farmer/farmer_api.py
  chia/rpc/farmer_rpc_api.py
  tests/farmer_harvester/test_farmer_harvester.py
Labels: Changed

#15613 pass DataLayer root and generation instead of requerying
  chia/data_layer/data_layer_util.py
  chia/data_layer/data_store.py
  tests/core/data_layer/test_data_store.py
  tests/core/data_layer/util.py
Labels: Changed

#15811 Fix CLI indentation
  chia/cmds/cmds_util.py
Labels: ready_to_merge, Fixed

#15816 Update chiapos
  setup.py
Labels: Changed

#15820 Added defaults to `get_harvester_config` API
  chia/harvester/harvester.py
  chia/plotting/util.py
Labels: Changed

#15821 Update macos build scripts lerna to 7.1.3 and nx to 16.3.2
  .github/workflows/build-macos-installers.yml
  build_scripts/npm_macos/package-lock.json
  build_scripts/npm_macos/package.json
Labels: Changed, CI, Exclude_Notes

#15769 New aggregate signature conditions
  chia/simulator/block_tools.py
  chia/simulator/wallet_tools.py
  chia/types/coin_spend.py
  chia/types/condition_opcodes.py
  chia/util/condition_tools.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/sign_coin_spends.py
  chia/wallet/util/debug_spend_bundle.py
  tests/blockchain/test_blockchain.py
  tests/core/mempool/test_mempool.py
  tests/util/key_tool.py
  tests/util/test_condition_tools.py
  tests/wallet/clawback/test_clawback_lifecycle.py
Labels: Added

#15812 Remove CAT1 UX guards
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Changed

#15688 Chip13
  .github/workflows/benchmarks.yml
  .github/workflows/test-single.yml
  chia/consensus/block_body_validation.py
  chia/consensus/block_header_validation.py
  chia/consensus/constants.py
  chia/consensus/default_constants.py
  chia/simulator/block_tools.py
  tests/blockchain/blockchain_test_utils.py
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/test_full_node_rpc.py
Labels: Changed

#15818 fix error in dao_get_treasury_balance RPC
  chia/rpc/wallet_rpc_api.py
Labels: Fixed

#15825 Chip13 (#15688)
  .github/workflows/benchmarks.yml
  .github/workflows/test-single.yml
  chia/consensus/block_body_validation.py
  chia/consensus/block_header_validation.py
  chia/consensus/constants.py
  chia/consensus/default_constants.py
  chia/simulator/block_tools.py
  tests/blockchain/blockchain_test_utils.py
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/daemon/test_daemon.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/test_full_node_rpc.py
Labels: Added

#15828 Add check to ubuntu_cmake_install for distribution ID
  install-timelord.sh
Labels: Fixed

#15830 checkpoint: into main from release/2.0.0 @ 97245c959df4441687d1b2efb694edcc9d196d4b
  tests/core/daemon/test_daemon.py
Labels: checkpoint_merge, Changed

#15831 Update testnet height for SOFT_FORK3 and fix Chip-13 logic
  chia/consensus/block_body_validation.py
  chia/consensus/block_header_validation.py
  chia/server/start_full_node.py
  tests/util/test_testnet_overrides.py
Labels: Changed, Exclude_Notes

#15813 Add uncurried args to debug_spend_bundle
  chia/wallet/util/debug_spend_bundle.py
  tests/wallet/test_debug_spend_bundle.py
Labels: ready_to_merge, Added

#15833 use chiapos and bladebit release-candidates
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
  setup.py
Labels: Changed, CI

#15804 Dedup offer cancellation logic
  chia/rpc/wallet_rpc_api.py
  chia/wallet/trade_manager.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/db_wallet/test_dl_offers.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
Labels: ready_to_merge, Changed

#15842 checkpoint: into main from release/2.0.0 @ 83192be416bbc57d52db5e27307a1f2bccd2c22b
  chia/consensus/block_body_validation.py
  chia/consensus/block_header_validation.py
  chia/server/start_full_node.py
  tests/util/test_testnet_overrides.py
Labels: checkpoint_merge, Changed

#15844 checkpoint: into main from release/2.0.0 @ bce770962c912351d7a85663c13a35d099cf91e8
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
  setup.py
Labels: checkpoint_merge, Changed

#15839 Update cuda plot log-progress mapping
  chia/plotters/bladebit.py
Labels: Changed

#15810 more precommit tidy
  .pre-commit-config.yaml
Labels: Changed, CI

#15808 use venv for pre-commit flake8
  .pre-commit-config.yaml
Labels: Changed, CI

#15801 cleanup basic `asyncio.CancelledError` uses for 3.8
  chia/data_layer/data_layer.py
  chia/data_layer/download_data.py
  chia/full_node/full_node.py
Labels: Changed, Cleanup

#15611 limit `DataStore.get_node()` query
  chia/data_layer/data_store.py
Labels: Changed, Cleanup

#15609 limit `DataStore.get_node_type()` query
  chia/data_layer/data_store.py
Labels: Changed, Cleanup

#15608 limit `DataStore.tree_id_exists()` query
  chia/data_layer/data_store.py
Labels: Changed, Cleanup

#15606 limit `DataStore._insert_ancestor_table()` query
  chia/data_layer/data_store.py
Labels: Changed, Cleanup

#15602 recursive query for `DataStore.get_terminal_node_for_seed()`
  chia/data_layer/data_store.py
Labels: Changed, Cleanup

#15532 test installed code, not source
  .coveragerc
  .github/actions/install/action.yml
  .github/workflows/test-single.yml
  Install.ps1
  install.sh
Labels: Fixed, CI

#15604 limit `DataStore.get_tree_root()` query
  chia/data_layer/data_store.py
Labels: Changed, Cleanup

#15607 limit `DataStore.get_pending_root()` query
  chia/data_layer/data_store.py
Labels: Changed, Cleanup

#15848 Update testnet height for SOFT_FORK3 in initial-config
  chia/util/initial-config.yaml
Labels: Changed, Exclude_Notes

#15838 Update install plotters scripts
  Install-plotter.ps1
  chia/pyinstaller.spec
  install-plotter.sh
Labels: Changed

#15845 Fix default parallel decompressor count
  chia/plotting/util.py
Labels: Fixed

#15851 [Snyk] Security upgrade electron-builder from 24.4.0 to 24.6.3 and Lerna to 7.1.3
  build_scripts/npm_linux/package-lock.json
  build_scripts/npm_linux/package.json
  build_scripts/npm_macos/package-lock.json
  build_scripts/npm_macos/package.json
  build_scripts/npm_windows/package-lock.json
  build_scripts/npm_windows/package.json
Labels: Changed

#15852 Change include_standard_libraries for CLVM compilation default to True
  chia/wallet/puzzles/load_clvm.py
Labels: Fixed

#15826 Skip clawback incoming txs while deleting the unconfirmed txs
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/wallet_transaction_store.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_transaction_store.py
Labels: Fixed

#14301 add dust warning message to chia coins commands & cleanup code
  chia/cmds/coin_funcs.py
Labels: CLI, Fixed

#15857 checkpoint: into main from release/2.0.0 @ cc8811450b0609f64aeaef39ec57d2bc4c5880bd
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: checkpoint_merge, Changed

#15746 Add Click CLI Unit Tests (Proof of Concept)
  tests/cmds/cmd_test_utils.py
  tests/cmds/conftest.py
  tests/cmds/test_show.py
  tests/cmds/testing_classes.py
Labels: CLI, Added, Tests

#15860 Change test to run only once per consensus mode as a flake workaround
  tests/core/data_layer/test_data_rpc.py
Labels: Changed, CI, Exclude_Notes

#15864 Update chiavdf to 1.0.10
  setup.py
Labels: Changed

#15835 Add Chris as codeowner for .github/*
  .github/CODEOWNERS
Labels: Changed, CI

#15858 make ConditionOpcodes not streamable
  chia/types/condition_opcodes.py
  chia/types/condition_with_args.py
  chia/util/streamable.py
  tests/util/test_condition_tools.py
Labels: Fixed, Cleanup

#15866 Fixed `chia rpc status` output
  chia/cmds/rpc.py
Labels: RPC, CLI, Fixed

#15870 fix initial-config for testnet fork points heights
  chia/util/initial-config.yaml
Labels: Fixed

#15872 Update soft for height in main for testnet to 2997292
  chia/server/start_full_node.py
  chia/util/initial-config.yaml
  tests/util/test_testnet_overrides.py
Labels: Changed, Exclude_Notes

#15869 checkpoint: into main from release/2.0.0 @ 2d65fc7114d626220cff5a37f1899256f495a930
  chia/plotters/bladebit.py
Labels: checkpoint_merge, Changed

#15873 fix initial-config for testnet fork points heights
  chia/server/start_full_node.py
  tests/util/test_testnet_overrides.py
Labels: Fixed

#15861 bump softfork3 activation by about 2 weeks
  chia/consensus/default_constants.py
  tests/conftest.py
Labels: Changed

#15871 remove chip13
  chia/consensus/block_body_validation.py
  chia/consensus/block_header_validation.py
  chia/simulator/block_tools.py
  tests/blockchain/test_blockchain.py
Labels: Changed

#15832 Add force option for spend_clawback_coin
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/wallet_state_manager.py
Labels: Added

#15862 Drop macos-10.14 support
  .github/workflows/build-macos-installers.yml
  .github/workflows/check_wheel_availability.yaml
Labels: Changed

#15880 Set minimum macOS version to macOS 11 for Chia.app
  build_scripts/build_macos-2-installer.sh
Labels: Changed

#15878 checkpoint: into main from release/2.0.0 @ d7539b14c6ba2e1144e0fe1e5b0fd41353bb3448
  Install-plotter.ps1
  chia/pyinstaller.spec
  install-plotter.sh
Labels: checkpoint_merge, Changed

#15879 dataclasses does not allow mutable member initializers
  tests/cmds/cmd_test_utils.py
Labels: ready_to_merge, Fixed, Tests

#15877 Fix a typo in code style documentation
  PRETTY_GOOD_PRACTICES.md
Labels: Fixed

#15881 checkpoint: into main from release/2.0.0 @ 3a3b7e5ac21467e51ed0875e37ef45d17c99c63e
  chia/plotting/util.py
Labels: checkpoint_merge, Changed

#15444 Add support for multi node farmers
  chia/farmer/farmer_api.py
  chia/harvester/harvester_api.py
  chia/server/server.py
  tests/conftest.py
  tests/connection_utils.py
  tests/core/farmer/__init__.py
  tests/core/farmer/config.py
  tests/core/farmer/test_farmer_api.py
  tests/core/server/test_server.py
Labels: ready_to_merge, Added

#15891 checkpoint: into main from release/2.0.0 @ 643b3e9b727f2ce689c834096a3a8281014b7aef
  chia/wallet/wallet_transaction_store.py
  tests/wallet/test_transaction_store.py
Labels: checkpoint_merge, Changed

#15900 Arvid's fix flake8 warnings (PR #15897)
  chia/types/blockchain_format/serialized_program.py
  chia/util/files.py
  chia/util/streamable.py
  chia/wallet/util/compute_memos.py
  tests/core/util/test_streamable.py
  tests/plot_sync/test_delta.py
  tests/plot_sync/test_receiver.py
  tests/plotting/test_plot_manager.py
  tests/util/test_struct_stream.py
  tools/run_block.py
Labels: Changed, Cleanup

#15846 Remove hack_populate'ing secret keys
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/secret_key_store.py
  chia/wallet/sign_coin_spends.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/test_sign_coin_spends.py
  tests/wallet/test_wallet.py
Labels: ready_to_merge, Changed

#15893 William's PR #15887 (Rework Bladebit artifact logic, CI cleanup, release simulation) against main
  .github/workflows/benchmarks.yml
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
  .github/workflows/snyk-python-scan.yml
  .github/workflows/start-release.yml
  .github/workflows/start-sync-test.yml
  .github/workflows/test-install-scripts.yml
  .github/workflows/test-single.yml
  .github/workflows/test.yml
  .github/workflows/trigger-docker-dev.yml
  .github/workflows/upload-pypi-source.yml
Labels: Changed, Cleanup

#15887 Rework Bladebit artifact logic, CI cleanup, release simulation
  .github/workflows/benchmarks.yml
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
  .github/workflows/snyk-python-scan.yml
  .github/workflows/start-release.yml
  .github/workflows/start-sync-test.yml
  .github/workflows/test-install-scripts.yml
  .github/workflows/test-single.yml
  .github/workflows/test.yml
  .github/workflows/trigger-docker-dev.yml
  .github/workflows/upload-pypi-source.yml
Labels: Changed, CI
