Repository Chia-Network/chia-blockchain, pull requests merged in 2023-01, with the labels that each got.

#14175 Fix fee estimator being re-created every block
  chia/full_node/bitcoin_fee_estimator.py
  chia/full_node/fee_estimation.py
  chia/full_node/fee_estimator.py
  chia/full_node/fee_estimator_interface.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/rpc/full_node_rpc_api.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_fee_estimator.py
  tests/fee_estimation/test_fee_estimation_integration.py
Labels: bug, ready_to_merge, Clean: caught up to main, PR, Fixed

#14188 add local max subscription config
  chia/full_node/full_node_api.py
  chia/simulator/setup_services.py
  chia/util/initial-config.yaml
  tests/wallet/simple_sync/test_simple_sync_protocol.py
Labels: enhancement, full_node, Changed

#14229 only send_to_all(), drop send_to_all_except()
  chia/full_node/full_node.py
  chia/server/server.py
  tools/test_full_sync.py
Labels: Changed, Cleanup

#14255 Force coverage==7.0.1
  setup.py
Labels: Fixed, CI

#14262 Force coverage==7.0.1 (#14255)
  setup.py
Labels: Fixed, CI

#14147 update changelog
  CHANGELOG.md
Labels: Changed, Cleanup

#14177 add cache to speed up manage_clvm/clvm_hex pre-commit check
  .github/workflows/pre-commit.yml
  .gitignore
  tools/manage_clvm.py
Labels: Added, Cleanup

#14182 wallet: Drop unused `WalletNode.get_coins_with_puzzle_hash`
  chia/wallet/wallet_node.py
Labels: Changed, Cleanup

#14242 close websocket in ssl tests to avoid event loop closed errors
  tests/core/ssl/test_ssl.py
Labels: Changed, Tests

#14263 Add MempoolRemoveReason, which represents why we are removing a MempoolItem
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  tests/fee_estimation/test_fee_estimation_integration.py
  tests/wallet/test_wallet_retry.py
Labels: ready_to_merge, Clean: caught up to main, PR, Fixed

#14267 use .get("testing", False) to avoid errors when missing
  chia/server/server.py
  chia/server/start_wallet.py
  chia/wallet/wallet_node.py
Labels: Fixed, Cleanup

#14272 Remove redundant check for duplicate inputs
  chia/full_node/mempool_manager.py
  tests/core/mempool/test_mempool_manager.py
Labels: Changed

#14265 checkpoint: into main from release/1.6.2 @ ba1ff12b31f8fea600e8ee2058bf472e211f1f7a
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#14276 Fix GITHUB_OUTPUT in build workflows
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
Labels: Fixed, CI

#14270 Refactor get_bucket_index
  chia/full_node/fee_estimator.py
  chia/full_node/fee_tracker.py
Labels: ready_to_merge, Clean: caught up to main, Changed, Cleanup

#14163 Add a height timestamp for wallet notifications
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/notification_manager.py
  chia/wallet/notification_store.py
  tests/wallet/test_notifications.py
Labels: ready_to_merge, Added

#14187 wallet: Don't add derived puzzle hashes to the `WalletInterestedStore`
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
Labels: Changed, Cleanup

#14222 factor out coin- and PH subscription handling in order to add unit tests
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/hint_management.py
  chia/full_node/subscriptions.py
  tests/core/full_node/test_hint_management.py
  tests/core/full_node/test_subscriptions.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
Labels: ready_to_merge, Changed, Cleanup

#14273 use config.get("trusted_peers", {}) for wallet
  chia/full_node/full_node_api.py
Labels: Fixed, Cleanup

#14274 return failure if mempool manager has no peak
  chia/full_node/full_node.py
Labels: Fixed, Cleanup

#14185 wallet: Some simplifications in `WalletNode.long_sync`
  chia/wallet/wallet_node.py
Labels: Changed, Cleanup

#14287 wallet: Drop duplicate puzzle hashes assert
  chia/wallet/wallet_node.py
Labels: Fixed

#14289 bump chia_rs dependency to the latest version
  setup.py
  tests/core/mempool/test_mempool_manager.py
Labels: ready_to_merge, Changed

#13886 Add a daemon heartbeat setting to config.yaml
  chia/daemon/client.py
  chia/daemon/keychain_proxy.py
  chia/daemon/server.py
  chia/rpc/rpc_server.py
  chia/util/initial-config.yaml
  tests/conftest.py
  tests/core/daemon/test_daemon.py
  tests/core/server/test_dos.py
  tests/core/test_daemon_rpc.py
Labels: Added

#14254 Use better check that we are on mainnet when deciding to use default Chia DNS server
  chia/full_node/full_node.py
Labels: Changed

#14282 If self.last_mempool_info is not yet set, return an empty FeeMempoolInfo, rather than None
  chia/full_node/bitcoin_fee_estimator.py
Labels: Clean: caught up to main, Fixed

#14286 Tune Fee Estimator parameter so that lowest suggested fee rate is 5 Mojo per CLVM cost
  chia/full_node/fee_estimator_constants.py
Labels: Clean: caught up to main, Changed

#14288 Fix computation of moving averages
  chia/full_node/fee_tracker.py
Labels: Fixed

#14292 Remove conflicting TXs before adding SpendBundle to Mempool in add_spend_bundle
  chia/full_node/mempool_manager.py
Labels: Changed

#14293 Check if a SpendBundle was included in a block BEFORE removing it from the Mempool
  chia/full_node/mempool_manager.py
Labels: Fixed

#14172 Fix fee and unit amounts when coin splitting or viewing coins
  chia/cmds/coin_funcs.py
  chia/cmds/coins.py
  chia/cmds/wallet.py
Labels: Fixed

#14281 Add proxy support to Data Layer download client
  chia/data_layer/data_layer.py
  chia/data_layer/download_data.py
  chia/util/initial-config.yaml
Labels: Changed

#14290 Call method to process transactions added to mempool in Fee Estimator
  chia/full_node/bitcoin_fee_estimator.py
  chia/full_node/fee_tracker.py
  tests/fee_estimation/test_fee_estimation_integration.py
Labels: Clean: caught up to main, Fixed

#13923 Use Chia-Network/actions/check-commit-signing
  .github/workflows/check-commit-signing.yml
Labels: Added, CI

#13587 include windows coverage
  .github/workflows/test.yml
Labels: Added, CI

#14234 @functools.wraps() for the API request decorators
  chia/util/api_decorators.py
Labels: Changed, Cleanup

#14240 make PR template headings actual markdown headings
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Changed, Cleanup

#14218 chiabip158==1.2
  setup.py
Labels: Fixed, Cleanup

#14217 watchdog==2.2.0
  setup.py
Labels: Fixed, Cleanup

#14216 psutil==5.9.4
  setup.py
Labels: Fixed, Cleanup

#14191 Remove the rest of uvloop
  chia/server/start_service.py
Labels: Changed, Cleanup

#14164 coverage use [run] source_pkgs= instead of source=
  .coveragerc
Labels: Fixed, CI

#14311 tests: Use set literal in `test_subscriptions.py`
  tests/core/full_node/test_subscriptions.py
Labels: Changed, Tests

#14314 Add a unit test for mempool minting coin check
  tests/core/mempool/test_mempool_manager.py
Labels: Added, Cleanup

#14313 full_node: Use `ConsensusConstants.MAX_BLOCK_COUNT_PER_REQUESTS`
  chia/full_node/full_node_api.py
Labels: Changed, Cleanup

#14300 Fix up doc string for get_mempool_item
  chia/full_node/mempool_manager.py
Labels: Changed, Cleanup

#14291 Reduce lower limit of tx per block seen at a certain fee rate, so estimates are produced sooner
  chia/full_node/fee_estimator_constants.py
Labels: Clean: caught up to main, Changed

#14327 Update version of clvm_tools_rs to 0.1.30
  setup.py
Labels: Fixed

#14253 Try each Chia DNS Server in list before trying introducers
  chia/server/node_discovery.py
Labels: ready_to_merge, Clean: caught up to main, Changed

#14297 optimize mempool's potential cache
  chia/full_node/mempool_manager.py
  chia/full_node/pending_tx_cache.py
  chia/types/mempool_item.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_manager.py
Labels: ready_to_merge, Changed

#14305 disallow empty SpendBundles in the mempool
  chia/full_node/mempool_manager.py
  tests/core/mempool/test_mempool_manager.py
Labels: ready_to_merge, Fixed

#14304 Check for valid timeout and log error
  chia/farmer/farmer.py
Labels: Fixed

#14323 Add a unit test for mempool reserve fee check
  tests/core/mempool/test_mempool_manager.py
Labels: Added, Cleanup

#14302 infrastructure for upcoming soft-fork
  chia/consensus/block_body_validation.py
  chia/consensus/blockchain.py
  chia/consensus/constants.py
  chia/consensus/default_constants.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool_check_conditions.py
  tests/blockchain/test_blockchain.py
  tests/blockchain/test_blockchain_transactions.py
  tests/conftest.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/mempool/test_mempool.py
  tests/core/test_cost_calculation.py
  tests/generator/test_rom.py
  tests/util/generator_tools_testing.py
Labels: Changed

#14184 add rate limits numbers to none response type
  chia/server/rate_limit_numbers.py
Labels: bug, Fixed

#14306 Fixed condition to check for wallet_id
  chia/rpc/wallet_rpc_api.py
Labels: RPC, Fixed

#14294 Test get_bucket_index
  chia/full_node/fee_estimator.py
  chia/full_node/fee_estimator_constants.py
  chia/full_node/fee_tracker.py
  tests/fee_estimation/test_fee_estimation_unit_tests.py
Labels: Fixed

#14336 Improve command line info display for fee estimation
  chia/cmds/show_funcs.py
  chia/full_node/fee_estimation.py
  chia/full_node/mempool.py
  chia/rpc/full_node_rpc_api.py
  tests/fee_estimation/test_fee_estimation_rpc.py
Labels: Clean: caught up to main, Changed

#14341 Add a unit test for mempool unknown unspent check
  tests/core/mempool/test_mempool_manager.py
Labels: Added, Cleanup

#14285 It is okay to return a result in some cases when median == -1
  chia/full_node/fee_estimator.py
  tests/fee_estimation/test_fee_estimation_unit_tests.py
Labels: ready_to_merge, Clean: caught up to main, Fixed

#14342 fix offer cancel balance
  chia/wallet/wallet.py
  tests/wallet/cat_wallet/test_trades.py
Labels: ready_to_merge, Fixed

#14358 update copyright year to 2023
  LICENSE
Labels: Changed

#13973 Add a workflow for scanning python deps for chia-blockchain
  .github/workflows/snyk-python-scan.yml
Labels: ready_to_merge, Added

#14329 Nft bulk transfer
  chia/rpc/wallet_rpc_api.py
  chia/wallet/nft_wallet/nft_wallet.py
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: Added

#14363 Fixing snyk secret check
  .github/workflows/snyk-python-scan.yml
Labels: ready_to_merge, Fixed, CI

#14319 Display complete exception info in log file
  chia/util/errors.py
  tests/core/mempool/test_mempool_manager.py
Labels: Clean: caught up to main, Changed, Logging, ready_to_review

#14310 Enable setting time between blocks in full node sim
  chia/simulator/full_node_simulator.py
  tests/simulation/test_simulation.py
Labels: simulator, Changed, ready_to_review

#14122 tests: Drop unused `PeerInfo`s
  tests/core/full_node/test_address_manager.py
Labels: ready_to_merge, Changed, Cleanup, ready_to_review

#14367 Move table of SpendBundle costs to backend
  chia/rpc/full_node_rpc_api.py
  tests/fee_estimation/test_fee_estimation_rpc.py
Labels: RPC, Clean: caught up to main, Changed

#13471 include dev deps for snyk
  setup.py
Labels: PR, Fixed, Tests, ready_to_review

#14361 Setting actions version to latest
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-windows-installer.yml
  .github/workflows/dependency-review.yml
  .github/workflows/require-labels.yml
  .github/workflows/snyk-python-scan.yml
  .github/workflows/super-linter.yml
  build_scripts/build_macos-2-installer.sh
  install-timelord.sh
Labels: Changed, CI, ready_to_review

#14337 Make sure to close the DL WalletRpcClient on DL shutdown
  chia/data_layer/data_layer.py
Labels: Fixed, Cleanup

#14366 Add the expected offer ID to some RPCs that take offer blobs
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  tests/core/data_layer/test_data_rpc.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge, Added

#14369 Change names used to look up estimated spendbundle sizes in get_fee_estimate RPC
  chia/rpc/full_node_rpc_api.py
  tests/fee_estimation/test_fee_estimation_rpc.py
Labels: RPC, Changed

#14372 Fix bulk tx
  chia/rpc/wallet_rpc_api.py
  chia/wallet/nft_wallet/nft_wallet.py
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: Fixed

#14376 Make the `--id` flag on cancel_offer required
  chia/cmds/wallet.py
Labels: Fixed

#14370 Fix target puz hash index for bulk mint nfts with airdrop
  chia/wallet/nft_wallet/nft_wallet.py
  tests/wallet/nft_wallet/test_nft_bulk_mint.py
Labels: bulk_mint, Fixed

#14344 Limit rate of log messages when farmer is disconnected from pool
  chia/farmer/farmer.py
  chia/util/logging.py
  tests/util/test_logging_filter.py
Labels: Clean: caught up to main, Changed, ready_to_review

#14388 Fix chia wallet coins cli bugs
  chia/cmds/coin_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge, Fixed, 1.7.0

#14269 any coverage, (7.0.2 error fixed in 7.0.3)
  setup.py
Labels: Changed, CI

#14384 Fixed wallet state if db is rolled back
  chia/wallet/wallet_state_manager.py
Labels: Fixed

#14387 Add a unit test for sending a spend bundle twice with a different spends order (and a coin eligible for deduplication)
  tests/core/mempool/test_mempool_manager.py
Labels: Added, Cleanup

#14213 Add SigningMode and update verify_signature RPC to work with sign_message_by_* RPCs
  chia/cmds/keys.py
  chia/cmds/keys_funcs.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/types/signing_mode.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet.py
  tests/core/cmds/test_keys.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_wallet.py
Labels: Changed

#14386 dont announce none response capability to peers
  chia/protocols/shared_protocol.py
  chia/server/ws_connection.py
  tests/core/full_node/full_sync/test_full_sync.py
Labels: full_node, Changed

#14398 Add some extra checks for size and existence to notification backend
  chia/wallet/notification_manager.py
  chia/wallet/notification_store.py
  tests/wallet/test_notifications.py
Labels: Fixed

#14394 remove additions() and reserved_fee() from CoinSpend
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_puzzles.py
  chia/pools/pool_wallet.py
  chia/types/coin_spend.py
  chia/types/spend_bundle.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trading/offer.py
  chia/wallet/wallet_state_manager.py
  tests/core/test_full_node_rpc.py
  tests/pools/test_wallet_pool_store.py
  tests/wallet/test_singleton_lifecycle_fast.py
  tests/wallet/test_wallet.py
Labels: ready_to_merge, Changed, Cleanup

#13316 Dl wallet store index fix
  chia/data_layer/dl_wallet_store.py
Labels: data, Fixed, ready_to_review, 1.7.1

#14410 fix sending of the `new_on_chain_notification` state change message
  chia/rpc/wallet_rpc_api.py
Labels: Fixed

#14417 checkpoint: into main from release/1.7.0 @ 6ef40dce4003e76a5a363b249d5f87194fa1c50d
  chia/rpc/wallet_rpc_api.py
Labels: checkpoint_merge, Changed

#14339 Reorganize reusable singleton wallet code
  chia/rpc/wallet_rpc_api.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/did_wallet/did_wallet_puzzles.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/singleton.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/did_wallet/test_did.py
Labels: ready_to_merge, Clean: caught up to main, Changed, Cleanup, ready_to_review, 1.7.1

#11407 Add support for Python 3.11
  .github/workflows/check_wheel_availability.yaml
  .github/workflows/test-single.yml
  Install.ps1
  install.sh
  pyproject.toml
Labels: Changed

#14377 Get memo api
  chia/rpc/wallet_rpc_api.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/test_wallet.py
Labels: ready_to_merge, Added

#14407 remove args passed to super() calls
  chia/util/errors.py
  chia/util/logging.py
  tests/generator/test_compression.py
Labels: Clean: caught up to main, Changed, Cleanup

#14418 Add a persitent id table to notification store
  chia/wallet/notification_store.py
  tests/wallet/test_notifications.py
Labels: ready_to_merge, Fixed

#14391 move SerializedProgram to its own file
  benchmarks/block_ref.py
  benchmarks/block_store.py
  benchmarks/utils.py
  chia/consensus/blockchain.py
  chia/data_layer/data_layer_wallet.py
  chia/full_node/block_store.py
  chia/full_node/bundle_tools.py
  chia/full_node/generator.py
  chia/full_node/mempool_check_conditions.py
  chia/pools/pool_puzzles.py
  chia/pools/pool_wallet.py
  chia/protocols/wallet_protocol.py
  chia/simulator/wallet_tools.py
  chia/types/block_protocol.py
  chia/types/blockchain_format/program.py
  chia/types/blockchain_format/serialized_program.py
  chia/types/coin_spend.py
  chia/types/full_block.py
  chia/types/generator_types.py
  chia/types/unfinished_block.py
  chia/util/chain_utils.py
  chia/util/condition_tools.py
  chia/util/full_block_utils.py
  chia/wallet/nft_wallet/nft_puzzles.py
  chia/wallet/puzzles/load_clvm.py
  chia/wallet/puzzles/rom_bootstrap_generator.py
  chia/wallet/wallet.py
  tests/blockchain/test_blockchain.py
  tests/clvm/test_serialized_program.py
  tests/core/full_node/stores/test_block_store.py
  tests/core/full_node/test_full_node.py
  tests/core/mempool/test_mempool.py
  tests/core/test_cost_calculation.py
  tests/generator/test_compression.py
  tests/generator/test_generator_types.py
  tests/generator/test_rom.py
  tests/pools/test_wallet_pool_store.py
  tests/util/network_protocol_data.py
  tests/util/test_full_block_utils.py
  tests/wallet/cat_wallet/test_cat_outer_puzzle.py
  tests/wallet/test_singleton_lifecycle_fast.py
  tools/manage_clvm.py
  tools/run_block.py
Labels: ready_to_merge, Changed, Cleanup

#14397 Rename notification config
  chia/util/initial-config.yaml
  chia/wallet/notification_manager.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_notifications.py
Labels: ready_to_merge, Changed

#14425 fix negative tests in test_pool_livecycle
  tests/pools/test_pool_puzzles_lifecycle.py
Labels: ready_to_merge, Fixed, Tests

#14429 checkpoint: into main from release/1.7.0 @ 655f6c2292fe806a06d2607c5606a5a382861f92
  chia/wallet/notification_store.py
  tests/wallet/test_notifications.py
Labels: checkpoint_merge, Changed

#14066 Deprecate `curry-and-treehash` and replace it with `curry`.
  chia/wallet/puzzles/curry-and-treehash.clinc
  chia/wallet/puzzles/curry.clib
Labels: ready_to_merge, Fixed, ready_to_review, 1.7.1

#14186 wallet: Avoid duplicates in `get_puzzle_hashes_to_subscribe`
  chia/wallet/wallet_node.py
  tests/wallet/test_wallet_node.py
Labels: Fixed, Cleanup

#14419 Add additional state_changed events to metrics destination
  chia/harvester/harvester.py
  chia/rpc/farmer_rpc_api.py
  chia/rpc/harvester_rpc_api.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/wallet_node.py
Labels: Added

#14439 checkpoint: into main from release/1.7.0 @ 655eaad639588819beeb8bcac1a2d1ab45acf812
  chia/util/initial-config.yaml
  chia/wallet/notification_manager.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_notifications.py
Labels: checkpoint_merge, Changed

#14449 remove bookworm install script testing
  .github/workflows/test-install-scripts.yml
Labels: ready_to_merge, Changed, CI
