Repository Chia-Network/chia-blockchain, pull requests merged in 2023-06, with the labels that each got.

#15374 Add confirmed filter for get_transactions
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/wallet_transaction_store.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_transaction_store.py
Labels: ready_to_merge, Added

#15421 wallet: Drop unused conditions helper/parameter
  chia/wallet/puzzles/puzzle_utils.py
  chia/wallet/wallet.py
Labels: Changed, Cleanup

#15428 bump SOFT_FORK3_HEIGHT to align with the next release cycle
  chia/consensus/default_constants.py
  tests/conftest.py
Labels: Changed

#15434 wallet: Some suggestions for the clawback PR
  chia/rpc/wallet_rpc_api.py
  chia/wallet/puzzles/clawback/drivers.py
  chia/wallet/wallet.py
  chia/wallet/wallet_coin_record.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/test_wallet_coin_store.py
  tests/wallet/test_wallet_state_manager.py
Labels: Changed

#15423 Fix `.get_next_from_coin_spend` on VerifiedCredential and test new puzhashes
  chia/wallet/vc_wallet/vc_drivers.py
  tests/wallet/vc_wallet/test_vc_lifecycle.py
Labels: ready_to_merge, Fixed

#15432 Fix vcs get command when no proofs exist yet
  chia/cmds/wallet_funcs.py
Labels: ready_to_merge, Fixed

#15437 remove unnecessary filtering of state_changed messages for the UI
  chia/rpc/wallet_rpc_api.py
Labels: Fixed

#14348 Clawback Integration
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/util/initial-config.yaml
  chia/wallet/puzzles/augmented_condition.clsp
  chia/wallet/puzzles/augmented_condition.clsp.hex
  chia/wallet/puzzles/clawback/__init__.py
  chia/wallet/puzzles/clawback/drivers.py
  chia/wallet/puzzles/clawback/metadata.py
  chia/wallet/puzzles/clawback/puzzle_decorator.py
  chia/wallet/puzzles/deployed_puzzle_hashes.json
  chia/wallet/puzzles/p2_1_of_n.clsp
  chia/wallet/puzzles/p2_1_of_n.clsp.hex
  chia/wallet/util/puzzle_decorator.py
  chia/wallet/util/puzzle_decorator_type.py
  chia/wallet/util/transaction_type.py
  chia/wallet/util/wallet_types.py
  chia/wallet/wallet.py
  chia/wallet/wallet_coin_record.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/clawback/__init__.py
  tests/wallet/clawback/test_clawback_decorator.py
  tests/wallet/clawback/test_clawback_lifecycle.py
  tests/wallet/clawback/test_clawback_metadata.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_coin_store.py
Labels: ready_to_merge, Added

#15435 reduce the resend timeout to fix flakiness
  tests/wallet/cat_wallet/test_trades.py
Labels: Changed, Tests

#15431 checkpoint: into main from release/1.8.2 @ ef68bf76c1c72302a198888780a19698684b6666
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/wallet_transaction_store.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_transaction_store.py
Labels: checkpoint_merge, Changed

#15427 Check all peers when subscribing/tracking to new DL singleton
  chia/data_layer/data_layer_errors.py
  chia/data_layer/data_layer_wallet.py
  chia/rpc/wallet_rpc_api.py
  tests/wallet/db_wallet/test_dl_wallet.py
  tests/wallet/rpc/test_dl_wallet_rpc.py
Labels: Changed

#15448 checkpoint: into main from release/1.8.2 @ ec28f764632b6c77d35b5720c258d20b7bfdd788
  chia/rpc/wallet_rpc_api.py
Labels: checkpoint_merge, Changed

#15422 wallet: Hint `puzzle_utils.py`
  chia/wallet/puzzles/puzzle_utils.py
  mypy-exclusions.txt
  tests/clvm/test_puzzles.py
Labels: Changed, Cleanup

#15424 wallet: Fix missing hint in `GenesisById.generate_issuance_bundle`
  chia/wallet/puzzles/tails.py
Labels: Fixed

#15426 Add a path in wallets_prefarm test fixture for generating an RPC client
  tests/conftest.py
Labels: ready_to_merge, Added, Tests

#15459 Move CAT_MOD from cat_loader -> cat_utils
  chia/wallet/cat_wallet/cat_outer_puzzle.py
  chia/wallet/cat_wallet/cat_utils.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/puzzles/cat_loader.py
  chia/wallet/puzzles/tails.py
  chia/wallet/util/puzzle_compression.py
  chia/wallet/vc_wallet/cr_cat_drivers.py
  chia/wallet/wallet_state_manager.py
  tests/clvm/test_puzzle_compression.py
  tests/wallet/cat_wallet/test_cat_lifecycle.py
  tests/wallet/cat_wallet/test_cat_outer_puzzle.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/cat_wallet/test_offer_lifecycle.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Changed

#15455 Repin clvm_tools_rs==0.1.34
  chia/wallet/puzzles/block_program_zero.clsp.hex
  chia/wallet/puzzles/calculate_synthetic_public_key.clsp.hex
  chia/wallet/puzzles/cat_v2.clsp.hex
  chia/wallet/puzzles/chialisp_deserialisation.clsp.hex
  chia/wallet/puzzles/create_nft_launcher_from_did.clsp.hex
  chia/wallet/puzzles/decompress_coin_spend_entry.clsp.hex
  chia/wallet/puzzles/decompress_coin_spend_entry_with_prefix.clsp.hex
  chia/wallet/puzzles/decompress_puzzle.clsp.hex
  chia/wallet/puzzles/delegated_tail.clsp.hex
  chia/wallet/puzzles/did_innerpuz.clsp.hex
  chia/wallet/puzzles/everything_with_signature.clsp.hex
  chia/wallet/puzzles/genesis_by_coin_id.clsp.hex
  chia/wallet/puzzles/genesis_by_puzzle_hash.clsp.hex
  chia/wallet/puzzles/graftroot_dl_offers.clsp.hex
  chia/wallet/puzzles/nft_intermediate_launcher.clsp.hex
  chia/wallet/puzzles/nft_metadata_updater_default.clsp.hex
  chia/wallet/puzzles/nft_metadata_updater_updateable.clsp.hex
  chia/wallet/puzzles/nft_ownership_layer.clsp.hex
  chia/wallet/puzzles/nft_ownership_transfer_program_one_way_claim_with_royalties.clsp.hex
  chia/wallet/puzzles/nft_state_layer.clsp.hex
  chia/wallet/puzzles/notification.clsp.hex
  chia/wallet/puzzles/p2_conditions.clsp.hex
  chia/wallet/puzzles/p2_delegated_conditions.clsp.hex
  chia/wallet/puzzles/p2_delegated_puzzle.clsp.hex
  chia/wallet/puzzles/p2_delegated_puzzle_or_hidden_puzzle.clsp.hex
  chia/wallet/puzzles/p2_m_of_n_delegate_direct.clsp.hex
  chia/wallet/puzzles/p2_parent.clsp.hex
  chia/wallet/puzzles/p2_puzzle_hash.clsp.hex
  chia/wallet/puzzles/p2_singleton.clsp.hex
  chia/wallet/puzzles/p2_singleton_or_delayed_puzhash.clsp.hex
  chia/wallet/puzzles/pool_member_innerpuz.clsp.hex
  chia/wallet/puzzles/pool_waitingroom_innerpuz.clsp.hex
  chia/wallet/puzzles/rom_bootstrap_generator.clsp.hex
  chia/wallet/puzzles/rom_bootstrap_generator2.clsp.hex
  chia/wallet/puzzles/settlement_payments.clsp.hex
  chia/wallet/puzzles/settlement_payments_old.clsp.hex
  chia/wallet/puzzles/sha256tree_module.clsp.hex
  chia/wallet/puzzles/singleton_launcher.clsp.hex
  chia/wallet/puzzles/singleton_top_layer.clsp.hex
  chia/wallet/puzzles/singleton_top_layer_v1_1.clsp.hex
  chia/wallet/puzzles/test_generator_deserialize.clsp.hex
  chia/wallet/puzzles/test_multiple_generator_input_arguments.clsp.hex
  chia/wallet/vc_wallet/cr_puzzles/credential_restriction.clsp.hex
  chia/wallet/vc_wallet/cr_puzzles/flag_proofs_checker.clsp.hex
  chia/wallet/vc_wallet/vc_puzzles/covenant_layer.clsp.hex
  chia/wallet/vc_wallet/vc_puzzles/eml_covenant_morpher.clsp.hex
  chia/wallet/vc_wallet/vc_puzzles/eml_transfer_program_covenant_adapter.clsp.hex
  chia/wallet/vc_wallet/vc_puzzles/eml_update_metadata_with_DID.clsp.hex
  chia/wallet/vc_wallet/vc_puzzles/exigent_metadata_layer.clsp.hex
  chia/wallet/vc_wallet/vc_puzzles/p2_announced_delegated_puzzle.clsp.hex
  chia/wallet/vc_wallet/vc_puzzles/standard_vc_backdoor_puzzle.clsp.hex
  chia/wallet/vc_wallet/vc_puzzles/std_parent_morpher.clsp.hex
  chia/wallet/vc_wallet/vc_puzzles/viral_backdoor.clsp.hex
  setup.py
Labels: ready_to_merge, Fixed

#15463 don't measure coverage of CI `tests/**/config.py` files
  .coveragerc
Labels: Changed, CI

#14920 rework `LockQueue` as `PriorityMutex`
  chia/consensus/blockchain.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/lock_queue.py
  chia/rpc/full_node_rpc_api.py
  chia/simulator/full_node_simulator.py
  chia/util/priority_mutex.py
  mypy-exclusions.txt
  tests/util/test_lock_queue.py
  tests/util/test_priority_mutex.py
Labels: Changed, Cleanup

#15452 Add some filter_prefix_bits tests on test blocks
  tests/farmer_harvester/test_filter_prefix_bits.py
Labels: Changed, Cleanup

#15451 checkpoint: into main from release/1.8.2 @ f0071358bf9a226af8adb2ad12105b3e3d015515
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/util/initial-config.yaml
  chia/wallet/puzzles/augmented_condition.clsp
  chia/wallet/puzzles/augmented_condition.clsp.hex
  chia/wallet/puzzles/clawback/__init__.py
  chia/wallet/puzzles/clawback/drivers.py
  chia/wallet/puzzles/clawback/metadata.py
  chia/wallet/puzzles/clawback/puzzle_decorator.py
  chia/wallet/puzzles/deployed_puzzle_hashes.json
  chia/wallet/puzzles/p2_1_of_n.clsp
  chia/wallet/puzzles/p2_1_of_n.clsp.hex
  chia/wallet/util/puzzle_decorator.py
  chia/wallet/util/puzzle_decorator_type.py
  chia/wallet/util/transaction_type.py
  chia/wallet/util/wallet_types.py
  chia/wallet/wallet.py
  chia/wallet/wallet_coin_record.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/clawback/__init__.py
  tests/wallet/clawback/test_clawback_decorator.py
  tests/wallet/clawback/test_clawback_lifecycle.py
  tests/wallet/clawback/test_clawback_metadata.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_coin_store.py
Labels: checkpoint_merge, Changed

#15376 use a more aggresive activation schedule on testnet10
  chia/server/start_full_node.py
  chia/util/initial-config.yaml
  tests/util/test_testnet_overrides.py
Labels: ready_to_merge, Changed

#15362 wallet: Hint `wallet.py`
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#15420 full_node: More set usage in subscription code
  chia/full_node/coin_store.py
  chia/full_node/full_node_api.py
  chia/full_node/subscriptions.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/test_subscriptions.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
Labels: Changed

#15453 coverage: Add `thread` to `concurrency`
  .coveragerc
Labels: Changed, CI

#15473 coverage ignore `if TYPE_CHECKING:`
  .coveragerc
Labels: Fixed, Tests

#15477 wallet: Fix clawback hex files
  chia/wallet/puzzles/augmented_condition.clsp.hex
  chia/wallet/puzzles/p2_1_of_n.clsp.hex
Labels: ready_to_merge, Fixed, CI

#15475 Clawback fixes
  chia/rpc/wallet_rpc_api.py
  chia/wallet/wallet_interested_store.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_interested_store.py
Labels: ready_to_merge, Fixed

#15303 Add reorg rollback to retry store
  chia/wallet/wallet_retry_store.py
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge, Fixed

#15418 util: Drop `chia.util.chunks` and use `chia.util.to_batches` instead
  benchmarks/mempool.py
  chia/full_node/coin_store.py
  chia/full_node/mempool.py
  chia/full_node/weight_proof.py
  chia/util/chunks.py
  chia/wallet/wallet_node.py
  tests/util/test_chunks.py
Labels: Changed, Cleanup

#15460 rename exclude_coin_* -> excluded_coin_* for consistency
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/wallet.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_coin_selection.py
Labels: ready_to_merge, Changed

#15468 Add -l to vcs revoke command
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
Labels: ready_to_merge, Added

#15476 checkpoint: into main from release/1.8.2 @ c55be8e16364750ede9694ebdf58d5d143ecef97
  chia/data_layer/data_layer_errors.py
  chia/data_layer/data_layer_wallet.py
  chia/rpc/wallet_rpc_api.py
  tests/wallet/db_wallet/test_dl_wallet.py
  tests/wallet/rpc/test_dl_wallet_rpc.py
Labels: checkpoint_merge, Changed

#15499 fix flaky `MAX_FUTURE_TIME` test
  tests/blockchain/test_blockchain.py
Labels: ready_to_merge, Fixed, Tests

#15498 seeder: Hint `crawler_api.py`
  chia/seeder/crawler_api.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#14356 Only subscribe to inner wallet puzzle hashes
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/trade_manager.py
  chia/wallet/wallet_interested_store.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_puzzle_store.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge, Fixed

#15489 seeder: Drop `CrawlerAPI.__getattr__`
  chia/seeder/crawler.py
  chia/seeder/crawler_api.py
  chia/simulator/setup_services.py
  tests/conftest.py
  tests/core/test_crawler.py
Labels: Changed, Cleanup

#15240 Add **kwargs to all generate_signed_transaction definitions
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/puzzles/tails.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_protocol.py
  mypy.ini.template
Labels: ready_to_merge, Changed

#15291 daemon plotter RPC tests
  chia/daemon/server.py
  tests/core/daemon/test_daemon.py
Labels: Added, CI, Exclude_Notes

#15466 server: Introduce `ApiProtocol`
  chia/data_layer/data_layer_api.py
  chia/farmer/farmer_api.py
  chia/full_node/full_node_api.py
  chia/harvester/harvester_api.py
  chia/introducer/introducer_api.py
  chia/seeder/crawler_api.py
  chia/seeder/start_crawler.py
  chia/server/api_protocol.py
  chia/server/server.py
  chia/server/start_data_layer.py
  chia/server/start_farmer.py
  chia/server/start_full_node.py
  chia/server/start_harvester.py
  chia/server/start_introducer.py
  chia/server/start_service.py
  chia/server/start_timelord.py
  chia/server/start_wallet.py
  chia/server/ws_connection.py
  chia/simulator/setup_nodes.py
  chia/simulator/setup_services.py
  chia/simulator/simulator_full_node_rpc_api.py
  chia/simulator/start_simulator.py
  chia/timelord/timelord_api.py
  chia/wallet/wallet_node_api.py
  tests/conftest.py
  tests/core/data_layer/test_data_rpc.py
  tests/core/full_node/test_full_node.py
  tests/core/server/test_server.py
  tests/core/test_crawler.py
  tests/core/test_farmer_harvester_rpc.py
  tests/farmer_harvester/test_farmer_harvester.py
  tests/fee_estimation/test_fee_estimation_rpc.py
  tests/plot_sync/test_plot_sync.py
  tests/plot_sync/test_sync_simulated.py
  tests/plot_sync/util.py
  tests/pools/test_pool_rpc.py
Labels: Changed, Cleanup

#15502 Add filters for get_transaction_count API
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/wallet_transaction_store.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_transaction_store.py
Labels: Added

#15483 Add CLI for Clawback
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/puzzles/clawback/metadata.py
  chia/wallet/util/transaction_type.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/test_wallet.py
Labels: ready_to_merge, Added

#15510 tests: Use separate `BlockTools` in farmer/harvester fixtures
  tests/conftest.py
Labels: Changed, Tests

#15512 tests: `job_timeout=40` for `tests.wallet.rpc`
  tests/wallet/rpc/config.py
Labels: Changed, CI

#15508 build: include `puzzles` packages
  setup.py
Labels: Fixed, Cleanup

#15509 rpc: Fix and test `WalletRpcApi.get_coin_records_by_names`
  chia/rpc/wallet_rpc_api.py
  chia/wallet/wallet_coin_store.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Fixed

#15123 tests: Test existance of DID wallets after some operations
  tests/wallet/did_wallet/test_did.py
Labels: Changed, Tests

#15534 Fix vcs get command when no proofs exist yet (#15432)
  chia/cmds/wallet_funcs.py
Labels: Fixed

#15525 checkpoint: into main from release/1.8.2 @ 82c9ed953d8b76936c3005c21831234eba155c8e
  chia/rpc/wallet_rpc_api.py
  chia/wallet/wallet_interested_store.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_interested_store.py
Labels: checkpoint_merge, Changed

#15536 Increase windows install timeout
  .github/workflows/build-windows-installer.yml
Labels: Changed, CI

#15511 tests: Run `build_network_protocol_files` as test
  tests/util/build_network_protocol_files.py
  tests/util/test_build_network_protocol_files.py
Labels: Changed, Tests

#15467 full_node: Add `max_height` to `CoinStore.get_coin_states_by_ids`
  chia/full_node/coin_store.py
  tests/core/full_node/stores/test_coin_store.py
Labels: Changed

#15541 Fix get transactions CLI for Clawback
  chia/cmds/wallet_funcs.py
Labels: Fixed

#15501 Improve error messages in verify_and_get_quality_string() and add unit tests
  chia/types/blockchain_format/proof_of_space.py
  tests/core/custom_types/test_proof_of_space.py
Labels: Added, Cleanup

#15544 full_node: `uint32.MAXIMUM_EXCLUSIVE` -> `uint32.MAXIMUM`
  chia/full_node/coin_store.py
Labels: Fixed

#15545 checkpoint: into main from release/1.8.2 @ 0e569c2610c37bbcdda937309d58181f1bb393d9
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
Labels: checkpoint_merge, Changed

#15538 Rephrase async contextmanager DBConnection to use asynccontextmanager
  mypy-exclusions.txt
  tests/util/db_connection.py
Labels: Changed

#15557 checkpoint: into main from release/1.8.2 @ d97889660ce0e28c29ffbec0c497455bd36b59f0
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/wallet_transaction_store.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_transaction_store.py
Labels: checkpoint_merge, Changed

#15562 mypy: Fix issues introduced by 1.4.0 release
  chia/wallet/util/address_type.py
  tests/core/test_farmer_harvester_rpc.py
Labels: Fixed, CI

#15563 setup: Pin `mypy==1.3.0`
  setup.py
Labels: Fixed, CI

#15564 checkpoint: into main from release/1.8.2 @ 33fa3f47deb29cb7d55463914bce16f6ad774b86
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/puzzles/clawback/metadata.py
  chia/wallet/util/transaction_type.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/test_wallet.py
Labels: checkpoint_merge, Changed

#15569 Annotate test_block_store.py
  mypy-exclusions.txt
  tests/core/full_node/stores/test_block_store.py
Labels: ready_to_merge, Changed, Cleanup

#15567 fix python matrix for release
  .github/workflows/test.yml
Labels: Fixed, CI

#15543 Add config option to accept private network addresses from introducers
  chia/server/node_discovery.py
  chia/util/initial-config.yaml
  tests/core/server/test_node_discovery.py
Labels: ready_to_merge, Added

#15571 Annotate test_coin_store.py
  mypy-exclusions.txt
  tests/core/full_node/stores/test_coin_store.py
Labels: ready_to_merge, Changed, Cleanup

#15517 call fix_ssl() after create_all_ssl() in block tools
  chia/simulator/block_tools.py
Labels: Fixed, Tests

#15560 full_node: Don't send duplicates in `register_interest_in_puzzle_hash`
  chia/full_node/coin_store.py
  chia/full_node/full_node_api.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
Labels: Fixed

#15575 bump chia_rs to 0.2.8
  chia/full_node/mempool_check_conditions.py
  setup.py
Labels: ready_to_merge, Changed

#15573 Annotate test_full_node_store.py
  mypy-exclusions.txt
  tests/core/full_node/stores/test_full_node_store.py
Labels: ready_to_merge, Changed, Cleanup

#15146 Generate a license directory that contains licenses missing from the installers
  build_scripts/build_license_directory.sh
  build_scripts/build_linux_deb-2-installer.sh
  build_scripts/build_linux_rpm-2-installer.sh
  build_scripts/build_macos-2-installer.sh
  build_scripts/build_win_license_dir.sh
  build_scripts/build_windows-2-installer.ps1
Labels: tech-debt, Added

#15481 bump blspy==2.0.0 (blst)
  setup.py
Labels: Changed

#15379 Annotate harvester_rpc_client.py
  chia/rpc/harvester_rpc_client.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#15579 checkpoint: into main from release/1.8.2 @ ca63959ff00a124290ef5d072e2e59ed81abf50b
  .github/workflows/build-windows-installer.yml
Labels: checkpoint_merge, Changed

#15570 allow tests/tools/test_full_sync.py::test_full_sync_test to run on 3.7
  benchmarks/mempool.py
  tests/wallet/test_offer_parsing_performance.py
  tools/generate_chain.py
  tools/test_full_sync.py
Labels: Fixed, Tests

#15588 don't parameterize the blockchain tests on DB version
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/full_node/stores/test_block_store.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/mempool/test_mempool_performance.py
Labels: ready_to_merge, Changed, Tests

#15590 Move harvester_farmer_environment to conftest.py
  tests/conftest.py
  tests/core/test_farmer_harvester_rpc.py
Labels: ready_to_merge, Changed, Cleanup

#15595 blspy 2.0.1
  setup.py
Labels: Changed

#15592 add Command protocol for daemon
  chia/daemon/server.py
  tests/core/daemon/test_daemon.py
Labels: Changed, Cleanup

#15598 wallet: Deduplicate coin states from peers
  chia/wallet/util/wallet_sync_utils.py
  chia/wallet/wallet_node.py
  tests/wallet/test_wallet_utils.py
Labels: Fixed

#15594 Use PKCS#8 format for SSL private keys
  chia/ssl/chia_ca.key
  chia/ssl/create_ssl.py
Labels: Changed

#15180 Auto find setup.py packages
  setup.py
Labels: ready_to_merge, Changed

#15619 fixing flaky clawback test
  tests/wallet/clawback/test_clawback_lifecycle.py
Labels: ready_to_merge, Fixed, Tests

#15630 Update simulator SSL keys to PKCS#8
  chia/simulator/ssl_certs_1.py
  chia/simulator/ssl_certs_10.py
  chia/simulator/ssl_certs_2.py
  chia/simulator/ssl_certs_3.py
  chia/simulator/ssl_certs_4.py
  chia/simulator/ssl_certs_5.py
  chia/simulator/ssl_certs_6.py
  chia/simulator/ssl_certs_7.py
  chia/simulator/ssl_certs_8.py
  chia/simulator/ssl_certs_9.py
Labels: Changed

#15626 cherry-pick #5423
  chia/wallet/vc_wallet/vc_drivers.py
  tests/wallet/vc_wallet/test_vc_lifecycle.py
Labels: ready_to_merge, Changed

#15601 Add some tests for Farmer's respond_signatures
  tests/farmer_harvester/test_farmer_harvester.py
Labels: Added, Cleanup

#15620 Apply Kevin's suggestion to simplify the check for passing plot filter
  chia/types/blockchain_format/proof_of_space.py
Labels: Changed, Cleanup

#15621 Apply Kevin's suggestions to simplify some test checks and fix a couple typos
  chia/types/blockchain_format/proof_of_space.py
  tests/farmer_harvester/test_filter_prefix_bits.py
  tests/weight_proof/test_weight_proof.py
Labels: Changed, Cleanup

#15638 checkpoint: into main from release/1.8.2 @ bde6f3965cbd248a28156eb1d99db9d28dd10aee
  chia/cmds/wallet_funcs.py
Labels: checkpoint_merge, Changed

#15640 checkpoint: into main from release/1.8.2 @ ff11e3e06add4e09b1e576cc63f960b8894decd1
  .github/workflows/test.yml
Labels: checkpoint_merge, Changed

#15642 Eos challenge optimization
  chia/consensus/get_block_challenge.py
  chia/full_node/full_node.py
  chia/full_node/full_node_store.py
  chia/timelord/timelord.py
  chia/timelord/timelord_api.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/full_node/test_full_node.py
Labels: Fixed

#15647 bump version of chiavdf to 1.0.9
  setup.py
Labels: Changed

#15655 1.8.2 changelog
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#15646 checkpoint: into main from release/1.8.2 @ 03943a0e51413f1f7fbd1f9ff852fe7259c0658e
  benchmarks/mempool.py
  tests/wallet/test_offer_parsing_performance.py
  tools/generate_chain.py
  tools/test_full_sync.py
Labels: checkpoint_merge, Changed

#15584 support calling daemon commands from chia rpc CLI
  chia/cmds/rpc.py
  chia/daemon/server.py
  tests/core/daemon/test_daemon.py
Labels: enhancement, Changed

#15657 checkpoint: into main from release/1.8.2 @ 199052fdb23e246ea36707523e06153bc2276bad
  tests/wallet/clawback/test_clawback_lifecycle.py
Labels: checkpoint_merge, Changed

#15660 build: include `puzzles` packages (#15508)
  setup.py
Labels: Fixed

#15654 remove unused run_as_generator function on SerializedProgram
  chia/types/blockchain_format/serialized_program.py
Labels: ready_to_merge, Changed, Cleanup

#15636 Minor improvements to SpendBundle.debug() + test
  chia/wallet/util/debug_spend_bundle.py
  tests/wallet/test_debug_spend_bundle.py
Labels: ready_to_merge, Fixed, Tests

#15547 wallet: Some suggestions from #15274 for #15259
  chia/rpc/wallet_rpc_api.py
  chia/wallet/util/compute_hints.py
  chia/wallet/wallet_state_manager.py
  tests/util/misc.py
  tests/wallet/test_util.py
Labels: Changed, Cleanup

#15554 correct sim test to `x in a and y in a`
  tests/cmds/test_sim.py
Labels: Fixed, Tests

#15526 add build-job-matrix.py --timeout-multiplier
  tests/build-job-matrix.py
  tests/util/test_build_job_matrix.py
Labels: Added, CI

#15615 replace hard coded 0.29.0 with BLOCKS_AND_PLOTS_VERSION
  .github/workflows/test-single.yml
Labels: Changed, CI

#15516 Add DataLayer clear pending roots interfaces
  chia/cmds/data.py
  chia/cmds/data_funcs.py
  chia/data_layer/data_layer_util.py
  chia/data_layer/data_store.py
  chia/rpc/data_layer_rpc_api.py
  chia/rpc/data_layer_rpc_client.py
  tests/core/data_layer/test_data_layer_util.py
  tests/core/data_layer/test_data_rpc.py
  tests/core/data_layer/test_data_store.py
Labels: Added

#15671 checkout plots and blocks for clawback tests
  tests/wallet/clawback/config.py
Labels: Fixed, CI

#15627 Handle VC syncing exceptions better
  chia/wallet/vc_wallet/vc_wallet.py
Labels: Fixed

#15259 Fix hint parsing for CATs and DIDs
  chia/rpc/wallet_rpc_api.py
  chia/wallet/util/compute_hints.py
  chia/wallet/wallet_state_manager.py
  tests/util/misc.py
  tests/wallet/test_util.py
Labels: ready_to_merge, Fixed

#15658 Make output of manage_clvm more readable on failure
  tools/manage_clvm.py
Labels: Clean: caught up to main, Changed, CI, Tests

#15632 use latest blspy
  setup.py
Labels: Changed

#15653 bad trade test fix
  tests/wallet/cat_wallet/test_trades.py
Labels: Fixed, Tests
