Repository Chia-Network/chia-blockchain, pull requests merged in 2023-11, with the labels that each got.

#16680 return List[TransactionRecord] from nft bulk mint functions
  chia/rpc/wallet_rpc_api.py
  chia/wallet/nft_wallet/nft_wallet.py
  tests/wallet/nft_wallet/test_nft_bulk_mint.py
Labels: Fixed

#16637 Speed up test runs by leveraging in-memory databases within reason
  chia/simulator/setup_services.py
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/data_layer/test_data_store.py
  tests/core/full_node/stores/test_block_store.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/db/test_db_wrapper.py
  tests/timelord/test_new_peak.py
  tests/util/blockchain.py
  tests/util/db_connection.py
Labels: Changed, Cleanup

#16728 add `disable_warnings=module-not-measured` to `.coveragerc`
  .coveragerc
Labels: Fixed, CI, Cleanup

#16704 Update to support looking up mnemonic by just the first 4 letters of each word
  chia/util/keychain.py
  tests/core/util/test_keychain.py
  tests/util/bip39_test_vectors.json
Labels: Added

#16747 [ADDED] Allow the daemon to use TLS v1.2 via config flag
  chia/daemon/server.py
  chia/util/initial-config.yaml
Labels: Added

#16749 Update usages of GithHub Glue to authenticate w/ jwt token
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
  .github/workflows/start-release.yml
  .github/workflows/start-sync-test.yml
  .github/workflows/trigger-docker-dev.yml
  .github/workflows/trigger-docker-main.yml
Labels: Changed, CI, Exclude_Notes

#16607 use bash for Windows publish job
  .github/workflows/build-windows-installer.yml
Labels: Changed, CI

#16395 Remove `ignore_max_send_amount`
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/coin_selection.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/wallet.py
  tests/wallet/test_wallet.py
Labels: Changed, Exclude_Notes, vault

#16740 fix flaky dao tests
  chia/wallet/dao_wallet/dao_utils.py
  tests/wallet/dao_wallet/test_dao_wallets.py
Labels: Fixed

#16292 Port VC lifecycle tests to WalletTestFramework
  chia/simulator/full_node_simulator.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/transaction_record.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/vc_wallet.py
  tests/wallet/conftest.py
  tests/wallet/vc_wallet/test_vc_wallet.py
Labels: Changed, Tests, Exclude_Notes

#16716 fixup pylint confusion
  .github/CODEOWNERS
  chia/daemon/server.py
  pylintrc
Labels: Changed, Exclude_Notes

#16771 make sure we set max_sync_wait to 0 in all tests
  chia/full_node/full_node.py
  chia/simulator/setup_nodes.py
Labels: ready_to_merge, Fixed, Tests

#16769 use `"${GITHUB_WORKSPACE}"` for windows bash installer publish
  .github/workflows/build-windows-installer.yml
Labels: Fixed, CI

#16314 Don't autopush txs across RPC
  chia/pools/pool_wallet.py
  chia/rpc/util.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/dao_wallet/test_dao_wallets.py
  tests/wallet/db_wallet/test_dl_offers.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/vc_wallet/test_vc_wallet.py
Labels: Changed, coverage-diff, vault

#16774 add test performing a deep reorg with 3 nodes
  chia/consensus/blockchain.py
  chia/full_node/full_node.py
  chia/simulator/block_tools.py
  tests/core/full_node/test_full_node.py
Labels: ready_to_merge, Fixed

#16293 Port trade test to WalletTestFramework
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/cat_wallet/test_trades.py
Labels: Changed, Tests, Exclude_Notes

#16787 simplify the interface to mempool_manager.new_peak()
  benchmarks/mempool-long-lived.py
  benchmarks/mempool.py
  chia/full_node/full_node.py
  chia/full_node/mempool_manager.py
  tests/core/mempool/test_mempool_manager.py
Labels: ready_to_merge, Changed

#16354 Use TXConfig instead of pending_transactions for coin exclusion in spend_clawback_coins
  chia/rpc/wallet_rpc_api.py
  chia/wallet/wallet_state_manager.py
Labels: Changed, Exclude_Notes, vault

#16782 Fix problems with wallet node discovery
  chia/server/server.py
  tests/core/server/test_rate_limits.py
  tests/core/server/test_server.py
Labels: Fixed, Exclude_Notes

#16776 Fix peak height race
  chia/consensus/blockchain.py
  tests/core/full_node/test_full_node.py
Labels: Fixed

#16797 reduce redundant calls to compute the header hash
  chia/consensus/multiprocess_validation.py
  tests/core/full_node/test_full_node.py
Labels: ready_to_merge, Changed

#16779 Fix invalid sync request
  chia/full_node/full_node.py
Labels: ready_to_merge, Fixed

#16752 Move generate_in_memory_db_uri to the chia/util to avoid importing tests from the chia package
  chia/simulator/setup_services.py
  chia/util/db_wrapper.py
  tests/conftest.py
  tests/core/data_layer/test_data_store.py
  tests/util/blockchain.py
  tests/util/db_connection.py
Labels: Changed, Cleanup

#16803 Add check to github jwt step in publish rpm job
  .github/workflows/build-linux-installer-rpm.yml
Labels: Fixed

#16792 request blocks in batches of 32 instead of 33
  chia/consensus/default_constants.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
Labels: ready_to_merge, Fixed

#16806 Add check to github jwt step in other workflows that call github-glue
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
  .github/workflows/trigger-docker-dev.yml
Labels: Fixed, CI

#16818 Make get_temp_keyring not async
  tests/conftest.py
Labels: ready_to_merge, Changed, Cleanup

#16346 Unify TX pushing
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/simulator/full_node_simulator.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
  tests/core/full_node/test_full_node.py
  tests/core/full_node/test_transactions.py
  tests/simulation/test_simulation.py
  tests/simulation/test_simulator.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/dao_wallet/test_dao_wallets.py
  tests/wallet/db_wallet/test_dl_offers.py
  tests/wallet/db_wallet/test_dl_wallet.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_notifications.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_retry.py
  tests/wallet/vc_wallet/test_vc_wallet.py
Labels: Changed, vault

#16824 increase `tests.core.full_node` timeouts
  tests/core/full_node/config.py
  tests/core/full_node/test_full_node.py
Labels: Fixed, Tests

#16807 Fix mypy types
  mypy-exclusions.txt
  tests/core/full_node/test_conditions.py
  tests/core/make_block_generator.py
  tests/core/test_cost_calculation.py
  tests/wallet/test_sign_coin_spends.py
Labels: Fixed, Tests

#16838 add reviewers to be assigned for dependabot PRs
  .github/dependabot.yml
Labels: Changed, CI

#16594 Fix deep reorgs
  .github/workflows/benchmarks.yml
  .github/workflows/test-single.yml
  chia/consensus/block_body_validation.py
  chia/consensus/blockchain.py
  chia/consensus/blockchain_interface.py
  chia/consensus/find_fork_point.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/block_store.py
  chia/full_node/full_node.py
  chia/simulator/block_tools.py
  chia/util/block_cache.py
  chia/wallet/wallet_blockchain.py
  tests/blockchain/blockchain_test_utils.py
  tests/blockchain/config.py
  tests/blockchain/test_blockchain.py
  tests/blockchain/test_lookup_fork_chain.py
  tests/conftest.py
  tests/core/full_node/stores/test_block_store.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/full_node/test_full_node.py
  tests/plot_sync/util.py
  tests/util/blockchain.py
Labels: ready_to_merge, Fixed

#16796 Simplify a test for mempool manager's new_peak
  tests/core/mempool/test_mempool_manager.py
Labels: Changed, Cleanup

#16843 Change -h to -k for --key flag for datalayer get_value cli command
  chia/cmds/data.py
Labels: Changed

#16670 managers for services
  chia/data_layer/data_layer.py
  chia/farmer/farmer.py
  chia/full_node/full_node.py
  chia/harvester/harvester.py
  chia/introducer/introducer.py
  chia/rpc/rpc_server.py
  chia/seeder/crawler.py
  chia/server/start_service.py
  chia/server/upnp.py
  chia/simulator/setup_services.py
  chia/simulator/simulator_test_tools.py
  chia/timelord/timelord.py
  chia/util/misc.py
  chia/wallet/wallet_node.py
  tests/core/data_layer/test_data_layer.py
  tests/core/data_layer/test_data_rpc.py
  tests/farmer_harvester/test_farmer_harvester.py
  tests/plot_sync/test_plot_sync.py
  tests/plot_sync/test_sync_simulated.py
  tests/plot_sync/util.py
  tests/util/test_misc.py
  tools/test_full_sync.py
Labels: Changed, Cleanup

#16808 clean up `SpendBundle` class
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/types/spend_bundle.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/trade_manager.py
  tests/blockchain/test_blockchain_transactions.py
  tests/core/full_node/test_full_node.py
  tests/core/mempool/test_mempool.py
  tests/wallet/test_singleton_lifecycle_fast.py
  tests/wallet/test_wallet.py
Labels: Changed, Cleanup

#16867 get_block_generator() fork detection
  chia/consensus/blockchain.py
Labels: Fixed

#16874 cleanup assertions of `True` and `False`
  tests/blockchain/test_blockchain.py
  tests/clvm/test_chialisp_deserialization.py
  tests/wallet/dao_wallet/test_dao_wallets.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/test_singleton.py
Labels: Changed, Tests, Cleanup

#16848 Speedup and simplify test_mempool_update_performance
  tests/conftest.py
  tests/core/mempool/test_mempool_performance.py
Labels: Changed, Cleanup

#16860 Fix set_status accidental arg
  chia/wallet/trade_manager.py
Labels: Fixed

#16894 clvm_tools==0.4.7
  setup.py
Labels: Changed

#16868 remove singleton_store
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
Labels: Fixed

#16901 only fail on a coverage diff for PR builds, not commit builds
  .github/workflows/test.yml
Labels: Changed, CI

#16882 Fix SimBlockRecord construction w.r.t. prev_transaction_block_hash
  chia/clvm/spend_sim.py
Labels: Changed, Cleanup

#16864 Return TX records from CATWallet creation
  chia/rpc/wallet_rpc_api.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Added, vault

#16863 Return TX records from offer creation endpoints
  chia/data_layer/data_layer_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/db_wallet/test_dl_offers.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
Labels: Added, vault

#16819 remove special case logic for soft-fork 3 activation
  chia/clvm/spend_sim.py
  chia/consensus/constants.py
  chia/consensus/default_constants.py
  chia/full_node/mempool_check_conditions.py
  chia/util/initial-config.yaml
  tests/clvm/benchmark_costs.py
  tests/conftest.py
  tests/core/full_node/test_conditions.py
  tests/core/mempool/test_mempool.py
  tests/util/test_testnet_overrides.py
Labels: ready_to_merge, Changed, Cleanup

#16793 update the `StateChangeSummary` to not keep full `NPCResult` objects
  chia/consensus/blockchain.py
  chia/full_node/full_node.py
  chia/full_node/hint_management.py
  tests/core/full_node/test_hint_management.py
Labels: ready_to_merge, Changed, Cleanup

#16753 full node just manage
  chia/full_node/full_node.py
Labels: Changed, Exclude_Notes

#16754 farmer just manage
  chia/farmer/farmer.py
Labels: Changed, Exclude_Notes

#16755 harvester just manage
  chia/harvester/harvester.py
Labels: Changed, Exclude_Notes

#16756 datalayer just manage
  chia/data_layer/data_layer.py
Labels: Changed, Exclude_Notes

#16757 introducer just manage
  chia/introducer/introducer.py
Labels: Changed, Exclude_Notes

#16758 crawler just manage
  chia/seeder/crawler.py
Labels: Changed, Exclude_Notes

#16759 timelord just manage
  chia/timelord/timelord.py
Labels: Changed, Exclude_Notes

#16877 remove unneeded `try`/`except`/`raise` from `did_wallet.py`
  chia/wallet/did_wallet/did_wallet.py
Labels: Changed, Cleanup, Exclude_Notes

#16878 remove unneeded `try`/`finally`/`pass` from `load_clvm.py`
  chia/wallet/puzzles/load_clvm.py
Labels: Changed, Cleanup

#16913 " not '
  .github/workflows/test.yml
Labels: Fixed, CI

#16855 avoid redundant list->set and set->list conversions
  benchmarks/coin_store.py
  chia/consensus/blockchain.py
  chia/full_node/coin_store.py
  chia/types/full_block.py
  chia/util/generator_tools.py
  tests/blockchain/test_blockchain.py
  tests/blockchain/test_blockchain_transactions.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/test_conditions.py
  tests/core/full_node/test_full_node.py
  tests/core/mempool/test_mempool.py
  tests/core/test_filter.py
  tests/core/test_full_node_rpc.py
Labels: ready_to_merge, Changed, Cleanup

#16918 Fix propagating spent coins IDs to the mempool on successful generator bundle creation in SpendSim's farm_block
  chia/clvm/spend_sim.py
Labels: Changed, Cleanup

#16879 only forward 4 most recent cached SPs
  chia/full_node/full_node_store.py
Labels: Fixed

#16880 add `DBWrapper2.managed()`
  benchmarks/block_store.py
  benchmarks/coin_store.py
  benchmarks/utils.py
  chia/cmds/check_wallet_db.py
  chia/full_node/full_node.py
  chia/util/db_wrapper.py
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/data_layer/test_data_store.py
  tests/core/full_node/ram_db.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/full_node/test_conditions.py
  tests/core/test_db_conversion.py
  tests/core/test_db_validation.py
  tests/timelord/test_new_peak.py
  tests/util/blockchain.py
  tests/util/db_connection.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/test_notifications.py
Labels: Changed, Exclude_Notes

#16775 add benchmark for loading test chains
  benchmarks/blockchains.py
Labels: Added, Tests

#16850 DL: delete full files for when subscribed to a datastore per config
  chia/data_layer/data_layer.py
Labels: Fixed, DataLayer

#16866 Add systemd init files to CLI-only Linux packages
  build_scripts/assets/systemd/__init__.py
  build_scripts/assets/systemd/chia-crawler@.service
  build_scripts/assets/systemd/chia-daemon@.service
  build_scripts/assets/systemd/chia-data-layer-http@.service
  build_scripts/assets/systemd/chia-data-layer@.service
  build_scripts/assets/systemd/chia-farmer@.service
  build_scripts/assets/systemd/chia-full-node@.service
  build_scripts/assets/systemd/chia-harvester@.service
  build_scripts/assets/systemd/chia-introducer@.service
  build_scripts/assets/systemd/chia-seeder@.service
  build_scripts/assets/systemd/chia-timelord@.service
  build_scripts/assets/systemd/chia-wallet@.service
  build_scripts/build_linux_deb-2-installer.sh
  build_scripts/build_linux_rpm-2-installer.sh
Labels: Added

#16929 factor out repeated logic and fix types in `Program.__eq__()` call
  chia/pools/pool_wallet.py
Labels: ready_to_merge, Fixed, Cleanup

#16941 Revert "Make the sync store tests synchronous (#16529)"
  tests/core/full_node/stores/test_sync_store.py
Labels: Changed, Tests, Exclude_Notes

#16938 checkpoint: into main from release/2.1.2 @ d80b7518502ea409dac913411977becd34df5035
  chia/data_layer/data_layer.py
Labels: checkpoint_merge, Changed, coverage-diff

#16944 `asyncio.create_subprocess_shell()` -> `asyncio.create_subprocess_exec()`
  chia/timelord/timelord_launcher.py
Labels: Fixed

#16945 checkpoint: into main from release/2.1.2 @ dcea5363c695620ec358f95fc95124b225095910
  build_scripts/assets/systemd/__init__.py
  build_scripts/assets/systemd/chia-crawler@.service
  build_scripts/assets/systemd/chia-daemon@.service
  build_scripts/assets/systemd/chia-data-layer-http@.service
  build_scripts/assets/systemd/chia-data-layer@.service
  build_scripts/assets/systemd/chia-farmer@.service
  build_scripts/assets/systemd/chia-full-node@.service
  build_scripts/assets/systemd/chia-harvester@.service
  build_scripts/assets/systemd/chia-introducer@.service
  build_scripts/assets/systemd/chia-seeder@.service
  build_scripts/assets/systemd/chia-timelord@.service
  build_scripts/assets/systemd/chia-wallet@.service
  build_scripts/build_linux_deb-2-installer.sh
  build_scripts/build_linux_rpm-2-installer.sh
Labels: checkpoint_merge, Changed

#16786 DL: remove data from DB on unsubscribe
  chia/data_layer/data_layer.py
  chia/data_layer/data_store.py
  chia/rpc/data_layer_rpc_api.py
  tests/core/data_layer/test_data_store.py
Labels: Fixed, DataLayer

#16932 Fix gh release upload step to work even with the .git repo is not present
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: Fixed, CI, Exclude_Notes

#16935 Add tn11 to initial-config
  chia/util/initial-config.yaml
Labels: Added, Exclude_Notes

#16940 fix typo introduced in the deep-reorg performance fix
  chia/consensus/blockchain.py
  chia/full_node/full_node.py
Labels: Fixed

#16957 checkpoint: into main from release/2.1.2 @ 35e91498440f2ec819ff757880f9be2759924d9b
  tests/core/full_node/stores/test_sync_store.py
Labels: checkpoint_merge, Changed

#16724 dedupe parent_amount_list
  chia/wallet/cat_wallet/dao_cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/puzzles/dao_proposal.clsp
  chia/wallet/puzzles/dao_proposal.clsp.hex
  chia/wallet/puzzles/dao_spend_p2_singleton_v2.clsp
  chia/wallet/puzzles/dao_spend_p2_singleton_v2.clsp.hex
  chia/wallet/puzzles/dao_treasury.clsp
  chia/wallet/puzzles/dao_treasury.clsp.hex
  chia/wallet/puzzles/deployed_puzzle_hashes.json
  tests/wallet/dao_wallet/test_dao_clvm.py
  tests/wallet/dao_wallet/test_dao_wallets.py
Labels: Fixed

#16915 reorg optimization
  chia/consensus/block_body_validation.py
  chia/consensus/blockchain.py
  chia/full_node/full_node.py
  tests/core/full_node/test_full_node.py
Labels: ready_to_merge, Changed

#16959 checkpoint: into main from release/2.1.2 @ 53519801fb924af9a14dea03551ff8ba01e73080
  chia/data_layer/data_layer.py
  chia/data_layer/data_store.py
  chia/rpc/data_layer_rpc_api.py
  tests/core/data_layer/test_data_store.py
Labels: checkpoint_merge, Changed

#16961 checkpoint: into main from release/2.1.2 @ ba6e0720f7decea7ef31525ce6c2e807a5e75d2b
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: checkpoint_merge, Changed

#16962 checkpoint: into main from release/2.1.2 @ aa2fd02a3782cab34d3ce39465c2a7718cb0022e
  chia/util/initial-config.yaml
Labels: checkpoint_merge, Changed

#16965 checkpoint: into main from release/2.1.2 @ 531e01c5d1d001caf88df4de95b340afc722b4d6
  chia/wallet/cat_wallet/dao_cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/puzzles/dao_proposal.clsp
  chia/wallet/puzzles/dao_proposal.clsp.hex
  chia/wallet/puzzles/dao_spend_p2_singleton_v2.clsp
  chia/wallet/puzzles/dao_spend_p2_singleton_v2.clsp.hex
  chia/wallet/puzzles/dao_treasury.clsp
  chia/wallet/puzzles/dao_treasury.clsp.hex
  chia/wallet/puzzles/deployed_puzzle_hashes.json
  tests/wallet/dao_wallet/test_dao_clvm.py
  tests/wallet/dao_wallet/test_dao_wallets.py
Labels: checkpoint_merge, Changed

#16933 `chia/simulator/setup_nodes.py` -> `tests/util/setup_nodes.py`
  tests/conftest.py
  tests/core/data_layer/test_data_rpc.py
  tests/core/full_node/test_full_node.py
  tests/core/mempool/test_mempool_manager.py
  tests/core/mempool/test_mempool_performance.py
  tests/core/server/test_server.py
  tests/core/test_crawler.py
  tests/farmer_harvester/test_filter_prefix_bits.py
  tests/pools/test_pool_rpc.py
  tests/simulation/test_simulation.py
  tests/simulation/test_simulator.py
  tests/util/setup_nodes.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/conftest.py
  tests/wallet/dao_wallet/test_dao_wallets.py
  tests/wallet/db_wallet/test_dl_wallet.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/nft_wallet/test_nft_bulk_mint.py
  tests/wallet/rpc/test_dl_wallet_rpc.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tests/wallet/test_wallet_node.py
  tests/wallet/test_wallet_state_manager.py
Labels: Changed, Tests

#16968 aiohttp 3.9.1 to fix a WebSocket bug introduced in 3.9.0
  setup.py
Labels: Changed

#16971 checkpoint: into main from release/2.1.2 @ 55057dff24acf12ba4ac4b2e5a0cd60c39efec22
  setup.py
Labels: checkpoint_merge, Changed

#16970 add `Service` type variables for each combination
  chia/seeder/start_crawler.py
  chia/server/start_data_layer.py
  chia/server/start_farmer.py
  chia/server/start_full_node.py
  chia/server/start_harvester.py
  chia/server/start_introducer.py
  chia/server/start_timelord.py
  chia/server/start_wallet.py
  chia/simulator/setup_services.py
  chia/simulator/start_simulator.py
  chia/types/aliases.py
  tests/cmds/test_farm_cmd.py
  tests/conftest.py
  tests/core/data_layer/test_data_rpc.py
  tests/core/test_crawler.py
  tests/farmer_harvester/test_farmer.py
  tests/farmer_harvester/test_farmer_harvester.py
  tests/farmer_harvester/test_filter_prefix_bits.py
  tests/fee_estimation/test_fee_estimation_rpc.py
  tests/plot_sync/test_plot_sync.py
  tests/plot_sync/test_sync_simulated.py
  tests/plot_sync/util.py
  tests/pools/test_pool_rpc.py
  tests/timelord/test_timelord.py
  tests/util/setup_nodes.py
Labels: Changed, Exclude_Notes

#16708 avoid recursive_replace() in `block_creation.py`
  chia/consensus/block_creation.py
Labels: ready_to_merge, Changed
