Repository Chia-Network/chia-blockchain, pull requests merged in 2023-05, with the labels that each got.

#15154 wallet: Revert "Add new coin_type & metadata to coin_records (#15013)"
  chia/wallet/util/wallet_types.py
  chia/wallet/wallet_coin_record.py
  chia/wallet/wallet_coin_store.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/test_wallet_coin_store.py
Labels: Changed, Cleanup

#15159 wallet: List the columns for `INSERT` into `coin_record`
  chia/wallet/wallet_coin_store.py
Labels: Changed

#15114 fixup coverage reporting and checking
  .github/workflows/test.yml
  setup.py
Labels: Fixed, CI

#15167 checkpoint: into main from release/1.8.0 @ fd8b85eb61a158c7d6a3e1d0af9c8a163052a73e
  setup.py
Labels: checkpoint_merge, Changed

#15152 add generator2 to the repository
  chia/wallet/puzzles/deployed_puzzle_hashes.json
  chia/wallet/puzzles/rom_bootstrap_generator.py
  chia/wallet/puzzles/rom_bootstrap_generator2.clsp
  chia/wallet/puzzles/rom_bootstrap_generator2.clsp.hex
  chia/wallet/puzzles/rom_bootstrap_generator2.clsp.hex.sha256tree
Labels: ready_to_merge, Changed

#15175 upload to coveralls
  .github/workflows/test.yml
Labels: Added, CI

#15178 checkpoint: into main from release/1.8.0 @ 4e71529422039ff76d6b3af064f8d7653ccead5f
  chia/consensus/block_header_validation.py
  chia/consensus/constants.py
  chia/consensus/default_constants.py
  tests/blockchain/test_blockchain.py
Labels: checkpoint_merge, Changed

#15076 help= not short_help=
  chia/cmds/chia.py
  chia/cmds/coins.py
  chia/cmds/completion.py
  chia/cmds/configure.py
  chia/cmds/data.py
  chia/cmds/db.py
  chia/cmds/farm.py
  chia/cmds/init.py
  chia/cmds/keys.py
  chia/cmds/netspace.py
  chia/cmds/passphrase.py
  chia/cmds/peer.py
  chia/cmds/plotnft.py
  chia/cmds/plots.py
  chia/cmds/plotters.py
  chia/cmds/rpc.py
  chia/cmds/show.py
  chia/cmds/start.py
  chia/cmds/stop.py
  chia/cmds/wallet.py
  tools/test_full_sync.py
Labels: Fixed, Cleanup

#15036 force \n/lf line endings in pre-commit
  .github/ISSUE_TEMPLATE/config.yml
  .pre-commit-config.yaml
  chia/cmds/peer_funcs.py
  chia/cmds/sim.py
  chia/cmds/sim_funcs.py
  chia/wallet/coin_selection.py
Labels: Added, CI

#15003 use type name in `Pulled from queue:` log messages
  chia/wallet/wallet_node.py
Labels: Fixed, Cleanup

#14992 Add flexibility to `log_exceptions()`
  chia/util/log_exceptions.py
  tests/core/util/test_log_exceptions.py
Labels: Added, Cleanup

#15172 wallet: Give `Payment.memos` a default value
  chia/data_layer/data_layer_wallet.py
  chia/simulator/full_node_simulator.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/payment.py
  chia/wallet/puzzles/tails.py
  chia/wallet/trading/offer.py
  chia/wallet/wallet.py
  tests/wallet/cat_wallet/test_offer_lifecycle.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_wallet.py
Labels: Changed, Cleanup

#15099 wallet: Improve `WalletCoinStore.get_coin_records`
  chia/rpc/wallet_rpc_api.py
  chia/util/misc.py
  chia/wallet/trade_manager.py
  chia/wallet/wallet_coin_store.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/test_wallet_coin_store.py
Labels: Changed, Cleanup

#15169 1.8.0 changelog
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#15191 Fix soft fork to 60 days
  chia/consensus/default_constants.py
  chia/server/start_full_node.py
  chia/util/initial-config.yaml
Labels: Changed

#15194 Additional entry to changelog
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#15185 wallet: Cleanup `wallet_protocol` imports
  chia/wallet/util/wallet_sync_utils.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
Labels: Changed, Cleanup

#15186 protocols: Give rust wallet types an alias, don't use `__all__`
  chia/protocols/wallet_protocol.py
  tests/util/test_network_protocol_test.py
Labels: Changed, Cleanup

#15179 Hint to CAT change
  chia/wallet/cat_wallet/cat_wallet.py
  tests/wallet/cat_wallet/test_cat_wallet.py
Labels: Changed

#15193 Move to Discord in docs and install scripts
  CONTRIBUTING.md
  Install.ps1
  install.sh
Labels: Include in next release, Changed, ready_to_review

#15117 Annotate tests/util/blockchain.py
  mypy.ini
  tests/util/blockchain.py
Labels: Changed, Cleanup

#15184 fix GENEARATOR_MOD2 to have the same cost as GENERATOR_MOD
  chia/wallet/puzzles/deployed_puzzle_hashes.json
  chia/wallet/puzzles/rom_bootstrap_generator2.clsp
  chia/wallet/puzzles/rom_bootstrap_generator2.clsp.hex
  chia/wallet/puzzles/rom_bootstrap_generator2.clsp.hex.sha256tree
Labels: ready_to_merge, Fixed

#15189 Comment chialisp assert macro
  chia/wallet/puzzles/utility_macros.clib
Labels: ready_to_merge, Added

#15204 Softfork2 testing
  chia/server/start_full_node.py
  chia/util/initial-config.yaml
  tests/clvm/coin_store.py
  tests/conftest.py
Labels: ready_to_merge, Changed

#15182 Fix chia wallet make_offer short-option collision on -r
  chia/cmds/wallet.py
Labels: Changed

#15205 checkpoint: into main from release/1.8.0 @ 1f8fc6410c795406aedb27e550c7376e027a7c02
  chia/rpc/rpc_server.py
  chia/seeder/crawler.py
  chia/server/node_discovery.py
  chia/server/start_service.py
  chia/timelord/timelord_launcher.py
  chia/util/network.py
  tests/util/test_network.py
Labels: checkpoint_merge, Changed

#15210 Move to Discord in docs and install scripts (#15193)
  CONTRIBUTING.md
  Install.ps1
  install.sh
Labels: Changed

#15211 checkpoint: into main from release/1.8.0 @ ae5f23e51c2aa4bbf4bac1bc7be197cab48c5d8e
  chia/wallet/wallet_state_manager.py
Labels: checkpoint_merge, Changed, Exclude_Notes

#15219 checkpoint: into main from release/1.8.0 @ b0cc1bebdb1990b0dafb369fef699d5ba6a34c77
  chia/wallet/wallet_node.py
Labels: checkpoint_merge, Changed

#15225 checkpoint: into main from release/1.8.0 @ 138154d5cd14c612036502bb2a7127fcdb2fe8c5
  chia/wallet/wallet_coin_store.py
Labels: checkpoint_merge, Changed

#15216 wallet: Avoid dict changes while iterating in `handle_nft`
  chia/wallet/wallet_state_manager.py
Labels: Fixed

#15232 checkpoint: into main from release/1.8.0 @ 70fd5e0facc8049f3f4cd8d5940f203d441e532f
  chia/consensus/default_constants.py
  chia/server/start_full_node.py
  chia/util/initial-config.yaml
Labels: checkpoint_merge, Changed

#15233 checkpoint: into main from release/1.8.0 @ d6f62d121b4e04c055ce4fa9e76e61ebdd6c5a50
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#15209 Remove unused function from daemon service
  chia/daemon/server.py
Labels: Changed, Cleanup

#15212 data_layer: Avoid redundant coin state fetching
  chia/data_layer/data_layer_wallet.py
Labels: Changed

#15176 Subscribe to the change children of CATs
  chia/wallet/wallet_state_manager.py
  tests/wallet/cat_wallet/test_cat_wallet.py
Labels: ready_to_merge, Fixed

#15238 checkpoint: into main from release/1.8.1 @ f100cd2cdf2630b270b88fc03e63f64af50005af
  chia/server/start_full_node.py
  chia/util/initial-config.yaml
  tests/clvm/coin_store.py
  tests/conftest.py
Labels: checkpoint_merge, Changed

#15174 wallet: Use `fetch_coin_spend_for_coin_state` in `DIDWallet.coin_added`
  chia/wallet/did_wallet/did_wallet.py
Labels: Changed, Cleanup

#15165 full_node: Drop `peers_with_peak` removals
  chia/full_node/full_node.py
Labels: Changed, Cleanup

#15229 Increase test_create_coin_duplicates to 1 second
  tests/core/mempool/test_mempool.py
Labels: Changed, CI, Exclude_Notes

#15163 Make Simulator CLI Tests Less Flaky
  tests/cmds/test_sim.py
Labels: CLI, simulator, Fixed, CI

#15164 add comment to reconsider_peak
  chia/consensus/blockchain.py
Labels: documentation, Fixed

#15151 remove unused parts of test_rom.py
  tests/generator/test_compression.py
  tests/generator/test_rom.py
Labels: Changed, Tests, Cleanup

#15122 tests: Simplify block generation in `test_did.py`
  tests/wallet/did_wallet/test_did.py
Labels: Changed, Tests

#15116 wallet: Drop unused `chia.wallet.wallet_action`
  chia/wallet/wallet_action.py
Labels: Changed, Cleanup

#15113 tests: Fix `assert_tx_amounts` in `test_wallet_rpc.py`
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Fixed, Tests

#14152 server: Don't pass the host to `WSChiaConnection`
  chia/server/server.py
  chia/server/ws_connection.py
  tests/connection_utils.py
  tests/core/ssl/test_ssl.py
Labels: Changed, Cleanup

#15243 Don't leverage SQLite's generated column feature for fee_per_cost. We'll hopefully reintroduce it again in the future
  chia/full_node/mempool.py
Labels: Changed, Cleanup

#15208 Add basic test for `get_farmed_amount` wallet RPC
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Added, CI, Cleanup

#15254 checkpoint: into main from release/1.8.1 @ 67bf417944233ab32e1570de60d5a32f89b4890b
  chia/wallet/wallet_state_manager.py
Labels: checkpoint_merge, Changed

#15224 Fix #13393 offer shows network's XCH like TXCH on testnet10
  chia/cmds/wallet_funcs.py
Labels: Fixed

#15127 wallet: Implement `WalletCoinStore.delete_wallet`
  chia/wallet/wallet_coin_store.py
  tests/wallet/test_wallet_coin_store.py
Labels: Added

#15126 wallet: Implement `WalletPoolStore.delete_wallet`
  chia/wallet/wallet_pool_store.py
  tests/pools/test_wallet_pool_store.py
Labels: Added

#15125 wallet: Implement `WalletPuzzleStore.delete_wallet`
  chia/wallet/wallet_puzzle_store.py
  tests/wallet/test_puzzle_store.py
Labels: Added

#15150 wallet: Move `WalletPeers` init to the end of `_start_with_fingerprint`
  chia/wallet/wallet_node.py
Labels: Fixed

#15124 wallet: Fix coin state sorting
  chia/wallet/util/wallet_sync_utils.py
  chia/wallet/wallet_node.py
  tests/wallet/test_wallet_utils.py
Labels: Fixed

#15166 Refactor mutiproc prevalidation
  chia/consensus/multiprocess_validation.py
Labels: tech-debt, Fixed

#15257 Changed: output plotid when we find an invalid proof of space
  chia/farmer/farmer_api.py
Labels: Changed

#15059 Introduce Verifiable Credentials Primitive
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/puzzles/deployed_puzzle_hashes.json
  chia/wallet/puzzles/utility_macros.clib
  chia/wallet/util/wallet_types.py
  chia/wallet/vc_wallet/__init__.py
  chia/wallet/vc_wallet/cr_cat_drivers.py
  chia/wallet/vc_wallet/cr_puzzles/__init__.py
  chia/wallet/vc_wallet/cr_puzzles/credential_restriction.clsp
  chia/wallet/vc_wallet/cr_puzzles/credential_restriction.clsp.hex
  chia/wallet/vc_wallet/cr_puzzles/flag_proofs_checker.clsp
  chia/wallet/vc_wallet/cr_puzzles/flag_proofs_checker.clsp.hex
  chia/wallet/vc_wallet/vc_drivers.py
  chia/wallet/vc_wallet/vc_puzzles/__init__.py
  chia/wallet/vc_wallet/vc_puzzles/covenant_layer.clsp
  chia/wallet/vc_wallet/vc_puzzles/covenant_layer.clsp.hex
  chia/wallet/vc_wallet/vc_puzzles/eml_covenant_morpher.clsp
  chia/wallet/vc_wallet/vc_puzzles/eml_covenant_morpher.clsp.hex
  chia/wallet/vc_wallet/vc_puzzles/eml_transfer_program_covenant_adapter.clsp
  chia/wallet/vc_wallet/vc_puzzles/eml_transfer_program_covenant_adapter.clsp.hex
  chia/wallet/vc_wallet/vc_puzzles/eml_update_metadata_with_DID.clsp
  chia/wallet/vc_wallet/vc_puzzles/eml_update_metadata_with_DID.clsp.hex
  chia/wallet/vc_wallet/vc_puzzles/exigent_metadata_layer.clsp
  chia/wallet/vc_wallet/vc_puzzles/exigent_metadata_layer.clsp.hex
  chia/wallet/vc_wallet/vc_puzzles/p2_announced_delegated_puzzle.clsp
  chia/wallet/vc_wallet/vc_puzzles/p2_announced_delegated_puzzle.clsp.hex
  chia/wallet/vc_wallet/vc_puzzles/standard_vc_backdoor_puzzle.clsp
  chia/wallet/vc_wallet/vc_puzzles/standard_vc_backdoor_puzzle.clsp.hex
  chia/wallet/vc_wallet/vc_puzzles/std_parent_morpher.clsp
  chia/wallet/vc_wallet/vc_puzzles/std_parent_morpher.clsp.hex
  chia/wallet/vc_wallet/vc_puzzles/viral_backdoor.clsp
  chia/wallet/vc_wallet/vc_puzzles/viral_backdoor.clsp.hex
  chia/wallet/vc_wallet/vc_store.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
  setup.py
  tests/wallet/vc_wallet/__init__.py
  tests/wallet/vc_wallet/test_vc_lifecycle.py
  tests/wallet/vc_wallet/test_vc_wallet.py
Labels: ready_to_merge, Added

#15249 Remove unused alert server test code and support files
  chia/util/create_alert_file.py
  chia/util/validate_alert.py
  mypy.ini
  tests/util/alert_server.py
Labels: Changed, CI, Cleanup

#15262 datacases
  tests/core/daemon/test_daemon.py
  tests/util/misc.py
Labels: Changed, Tests

#15264 don't add transactions to the mempool before it has a valid peak
  chia/full_node/full_node.py
Labels: Fixed

#13799 Identical spend aggregation
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/types/eligible_coin_spends.py
  chia/types/internal_mempool_item.py
  chia/types/mempool_item.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_manager.py
Labels: Changed

#15266 checkpoint: into main from release/1.8.1 @ c6863fd92bfaf2838117a38656b0ac0d47d1e970
  chia/full_node/full_node.py
Labels: checkpoint_merge, Changed

#15265 add `datacases()` and `named_datacases()`
  pytest.ini
  tests/util/misc.py
  tests/util/test_tests_misc.py
Labels: Added, Tests

#15215 Add some more daemon "rpc" tests
  tests/core/daemon/test_daemon.py
Labels: Added, CI

#15196 Add type filter for get_transactions
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/util/query_filter.py
  chia/wallet/wallet_coin_store.py
  chia/wallet/wallet_transaction_store.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_transaction_store.py
Labels: ready_to_merge, Added

#15286 Pass VC fee parameter all the way through and check balances in tests
  chia/wallet/vc_wallet/vc_wallet.py
  tests/wallet/vc_wallet/test_vc_wallet.py
Labels: Fixed

#15287 Decorrelate forwards_compat and reuse_puzhash from trade test params
  tests/wallet/cat_wallet/test_trades.py
Labels: ready_to_merge, Changed, Cleanup

#15293 hardcode `num` param when listing NFTs from CLI
  chia/rpc/wallet_rpc_client.py
Labels: Changed

#15296 checkpoint: into main from release/1.8.1 @ 2aadff68ab5b57e6fa884dddf70ba1c3516dfb8d
  chia/rpc/wallet_rpc_client.py
Labels: checkpoint_merge, Changed

#15297 Improve help text for deprecated 'chia show' commands.
  chia/cmds/show.py
Labels: Changed

#15304 optimize compact proofs
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  tests/core/full_node/test_full_node.py
Labels: ready_to_merge, Changed

#15313 Adding signed commit requirment info
  CONTRIBUTING.md
Labels: ready_to_merge, Added, Exclude_Notes

#15157 Have simulator not rely on chia_root as originally implemented. & fix simulator tests
  .github/workflows/test-single.yml
  chia/util/default_root.py
  tests/cmds/test_sim.py
Labels: Changed

#15311 1.8.1 changelog
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#15324 checkpoint: into main from release/1.8.1 @ c61129d3b10abd4128cd6f99bdcf8dd08ff116d0
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#15323 full_node: Refactor `get_puzzle_and_solution_for_coin`
  chia/clvm/spend_sim.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool_check_conditions.py
  chia/rpc/full_node_rpc_api.py
  chia/types/coin_spend.py
  tests/clvm/test_spend_sim.py
  tests/core/mempool/test_mempool.py
  tests/core/test_cost_calculation.py
  tests/generator/test_compression.py
Labels: Changed, Cleanup

#15331 Enable signing for PRs that have secret access
  build_scripts/build_macos-2-installer.sh
Labels: Fixed

#15299 Fork infrastructure
  chia/consensus/block_body_validation.py
  chia/consensus/constants.py
  chia/consensus/default_constants.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
  chia/full_node/mempool_check_conditions.py
  chia/full_node/mempool_manager.py
  chia/server/start_full_node.py
  chia/util/condition_tools.py
  chia/util/initial-config.yaml
  tests/conftest.py
  tests/core/mempool/test_mempool.py
  tools/analyze-chain.py
Labels: ready_to_merge, Changed

#15330 server: Store `Version` objects instead of `str` in `WSChiaConnection`
  chia/server/ws_connection.py
  chia/wallet/wallet_node.py
  tests/core/server/test_server.py
Labels: Changed, Cleanup

#15327 Update --fee options to indicate units are in XCH
  chia/cmds/wallet.py
Labels: ready_to_merge, Changed

#15316 Weight proof typing
  chia/full_node/weight_proof.py
  mypy.ini
  tests/core/custom_types/test_proof_of_space.py
Labels: ready_to_merge, Fixed, Cleanup

#15340 have pyinstaller include all chia modules and .hex files
  chia/pyinstaller.spec
Labels: Fixed, CI

#15355 hint and test dump keyring
  chia/util/dump_keyring.py
  mypy.ini
  tests/util/test_dump_keyring.py
Labels: Added, Tests

#15158 mypy: Build `mypy.ini` config with exclusions dynamically
  .github/workflows/pre-commit.yml
  .github/workflows/upload-pypi-source.yml
  .gitignore
  .pre-commit-config.yaml
  manage-mypy.py
  mypy-exclusions.txt
  mypy.ini
  mypy.ini.template
Labels: Changed, CI

#15346 Fix Farmer imports in plot sync tests
  tests/plot_sync/test_plot_sync.py
  tests/plot_sync/test_sync_simulated.py
Labels: ready_to_merge, Changed, Cleanup

#15353 Add notification for VC
  chia/wallet/vc_wallet/vc_wallet.py
Labels: Added

#15334 use WalletStateManager.get_wallet() in wallet_rpc_api
  chia/rpc/wallet_rpc_api.py
Labels: Changed, Cleanup

#15351 fix timelord mypy type hints
  chia/timelord/timelord.py
  chia/timelord/timelord_api.py
  chia/timelord/timelord_state.py
  mypy-exclusions.txt
Labels: ready_to_merge, Fixed, Cleanup

#15100 wallet: Implement `/get_coin_records` RPC command
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Added

#15348 Annotate chia/timelord/iters_from_block.py
  chia/timelord/iters_from_block.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#15350 Annotate test_farmer_harvester.py
  mypy-exclusions.txt
  tests/farmer_harvester/test_farmer_harvester.py
Labels: Changed, Cleanup

#15349 Annotate chia/simulator/block_tools.py
  chia/simulator/block_tools.py
  mypy-exclusions.txt
Labels: ready_to_merge, Changed, Cleanup

#15363 Annotate chia/plotters/chiapos.py
  chia/plotters/chiapos.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#15364 make sure tests that use BlockTools use a single source of consensus constants
  chia/simulator/setup_nodes.py
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/full_node/full_sync/test_full_sync.py
  tests/core/full_node/stores/test_block_store.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/full_node/test_full_node.py
  tests/core/server/test_rate_limits.py
  tests/core/test_cost_calculation.py
  tests/core/test_full_node_rpc.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_wallet_blockchain.py
  tests/weight_proof/test_weight_proof.py
Labels: ready_to_merge, Fixed, Tests

#14943 Typecheck chia/util/safe_cancel_task.py
  chia/util/safe_cancel_task.py
  mypy-exclusions.txt
Labels: Clean: caught up to main, Changed, Cleanup

#14941 Typecheck log_exceptions.py
  chia/util/log_exceptions.py
  mypy-exclusions.txt
Labels: Clean: caught up to main, Changed, Cleanup

#14939 Remove test_setproctitle.py from mypy exclusions
  mypy-exclusions.txt
  tests/core/test_setproctitle.py
Labels: Clean: caught up to main, Changed, Cleanup

#15354 always report coverage diff
  .github/workflows/test.yml
Labels: Fixed, CI

#15369 actions/git-mark-workspace-safe in upload-pypi-source.yml
  .github/workflows/upload-pypi-source.yml
Labels: Fixed, CI

#15273 pools: Drop `PoolWallet.get_next_interesting_coin`
  chia/pools/pool_wallet.py
  chia/wallet/wallet_state_manager.py
Labels: Changed, Cleanup

#15345 update build_network_protocol_files.py
  .github/workflows/upload-pypi-source.yml
  mypy-exclusions.txt
  tests/util/build_network_protocol_files.py
  tests/util/test_network_protocol_files.py
Labels: Fixed, Tests

#14940 Typecheck node_height.py
  mypy-exclusions.txt
  tests/core/node_height.py
Labels: Clean: caught up to main, Changed, Cleanup

#14945 Typecheck chia/wallet/secret_key_store.py
  chia/wallet/secret_key_store.py
  mypy-exclusions.txt
Labels: Clean: caught up to main, Changed, Cleanup

#14947 Typecheck tests/tools/test_full_sync.py
  mypy-exclusions.txt
  tests/tools/test_full_sync.py
Labels: Clean: caught up to main, Changed, Cleanup

#14853 Give a type to tuple representing peak (height and block hash) of peer
  chia/wallet/wallet_node.py
  chia/wallet/wallet_node_api.py
Labels: Changed, Cleanup

#15361 wallet: Refactor `WalletStateManager.get_keys`
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/test_wallet_state_manager.py
Labels: Changed, Cleanup

#15377 Annotate test_farmer_harvester_rpc.py
  chia/rpc/farmer_rpc_api.py
  chia/rpc/farmer_rpc_client.py
  mypy-exclusions.txt
  tests/core/test_farmer_harvester_rpc.py
Labels: Changed, Cleanup

#15378 Annotate harvester_rpc_api.py
  chia/rpc/harvester_rpc_api.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#15352 Use spendable instead of confirmed balance for offers
  chia/wallet/wallet.py
Labels: Fixed

#15357 Type hint
  chia/util/dump_keyring.py
Labels: Changed, Cleanup

#15375 remove unused test functions
  tests/weight_proof/test_weight_proof.py
Labels: Fixed, Tests, Cleanup

#15384 Convert blockchain_constants's consensus_mode param into a fixture and use it to skip some simulation related tests in HARD_FORK_2_0 mode
  tests/conftest.py
  tests/simulation/test_simulation.py
Labels: Changed, Cleanup

#15389 catchup: into long_lived/compression from main @ fbe7daa32e6090d7b440024cba0087d117d04611
  .github/workflows/test.yml
  .github/workflows/upload-pypi-source.yml
  chia/pools/pool_wallet.py
  chia/rpc/farmer_rpc_api.py
  chia/rpc/farmer_rpc_client.py
  chia/rpc/harvester_rpc_api.py
  chia/simulator/setup_services.py
  chia/util/dump_keyring.py
  chia/util/log_exceptions.py
  chia/util/safe_cancel_task.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/secret_key_store.py
  chia/wallet/wallet.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_node_api.py
  chia/wallet/wallet_state_manager.py
  mypy-exclusions.txt
  setup.py
  tests/conftest.py
  tests/core/full_node/test_full_node.py
  tests/core/node_height.py
  tests/core/test_farmer_harvester_rpc.py
  tests/core/test_setproctitle.py
  tests/simulation/test_simulation.py
  tests/tools/test_full_sync.py
  tests/util/build_network_protocol_files.py
  tests/util/test_network_protocol_files.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/test_wallet_state_manager.py
  tests/weight_proof/test_weight_proof.py
Labels: checkpoint_merge, Changed

#15381 switch to deques
  chia/consensus/blockchain.py
  chia/full_node/lock_queue.py
  tests/util/test_lock_queue.py
Labels: Changed

#15396 Fix linting
  tests/core/test_farmer_harvester_rpc.py
Labels: Changed, Cleanup

#15398 Fix rebase artifact in blockchain_constants
  tests/conftest.py
Labels: Changed, Cleanup

#15409 Add some cases to test_calculate_prefix_bits_default
  tests/weight_proof/test_weight_proof.py
Labels: Changed, Cleanup
