Repository Chia-Network/chia-blockchain, pull requests merged in 2023-08, with the labels that each got.

#15892 cudaplot fix
  chia/plotters/bladebit.py
  chia/plotters/plotters.py
Labels: Fixed

#15919 disable running benchmarks on CI
  .github/workflows/benchmarks.yml
Labels: ready_to_merge, Fixed, Tests

#14877 Update README badges
  README.md
Labels: Changed, Cleanup

#15909 checkpoint: into main from release/2.0.0 @ e5431cf91e3c4bcf01120933aeb43425a87bc4d2
  tests/core/data_layer/test_data_rpc.py
Labels: checkpoint_merge, Changed

#15908 allow `_ProactorBasePipeTransport.__del__` failures in tests
  tests/core/data_layer/test_data_rpc.py
Labels: Fixed, Tests

#15889 Add condition opcodes for agg sigs to condition_codes.clib
  chia/wallet/puzzles/condition_codes.clib
  tests/clvm/test_condition_codes.py
Labels: Fixed

#15918 Fixed `chia plotnft show` command
  chia/cmds/plotnft_funcs.py
  chia/rpc/wallet_rpc_client.py
Labels: Fixed

#15921 Fixed an issue where insufficient block interval was used to calculate average block time
  chia/rpc/full_node_rpc_api.py
Labels: Fixed

#15920 Fixed python3-venv into install.sh
  install.sh
Labels: Changed

#15923 checkpoint: into main from release/2.0.0 @ e37bd47e6457ade1087db975e53d1686ea4c1b86
  setup.py
Labels: checkpoint_merge, Changed

#15895 drop support for database schema v1
  chia/clvm/spend_sim.py
  chia/consensus/blockchain.py
  chia/full_node/block_height_map.py
  chia/full_node/block_store.py
  chia/full_node/coin_store.py
  chia/full_node/hint_store.py
  tests/conftest.py
  tests/core/full_node/ram_db.py
  tests/core/full_node/stores/test_block_store.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/stores/test_hint_store.py
  tests/core/full_node/test_block_height_map.py
  tests/core/test_db_conversion.py
Labels: ready_to_merge, Changed

#15411 Credential Restricted CATs
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/cat_wallet/cat_info.py
  chia/wallet/cat_wallet/cat_outer_puzzle.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/outer_puzzles.py
  chia/wallet/puzzles/deployed_puzzle_hashes.json
  chia/wallet/trade_manager.py
  chia/wallet/trading/offer.py
  chia/wallet/transaction_record.py
  chia/wallet/util/transaction_type.py
  chia/wallet/util/wallet_types.py
  chia/wallet/vc_wallet/cr_cat_drivers.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/cr_outer_puzzle.py
  chia/wallet/vc_wallet/cr_puzzles/conditions_w_fee_announce.clsp
  chia/wallet/vc_wallet/cr_puzzles/conditions_w_fee_announce.clsp.hex
  chia/wallet/vc_wallet/vc_store.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_coin_record.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_protocol.py
  chia/wallet/wallet_state_manager.py
  tests/conftest.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/db_wallet/test_dl_wallet.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_wallet.py
  tests/wallet/vc_wallet/test_cr_outer_puzzle.py
  tests/wallet/vc_wallet/test_vc_lifecycle.py
  tests/wallet/vc_wallet/test_vc_wallet.py
Labels: ready_to_merge, Added

#15342 Added: Support CLI NFT Pagination
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_client.py
Labels: Added

#15885 introduce SOFT_FORK4_HEIGHT and tie CHIP-13 to it
  chia/consensus/block_body_validation.py
  chia/consensus/block_header_validation.py
  chia/consensus/constants.py
  chia/consensus/default_constants.py
  chia/server/start_full_node.py
  chia/simulator/block_tools.py
  chia/util/initial-config.yaml
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/full_node/test_conditions.py
  tests/core/test_full_node_rpc.py
  tests/plotting/test_plot_manager.py
  tests/util/test_testnet_overrides.py
Labels: Changed

#15938 bump soft-fork3 activation height
  chia/consensus/default_constants.py
  tests/conftest.py
Labels: ready_to_merge, Changed

#15939 Update chiapos to full release
  setup.py
Labels: Changed

#15941 Consolidate workflow to fetch bladebit
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: Fixed, CI

#15947 Revert "Add fields to BlockRecord. (#15695)"
  benchmarks/block_store.py
  chia/cmds/db_validate_func.py
  chia/consensus/block_record.py
  chia/consensus/full_block_to_block_record.py
  chia/full_node/block_store.py
  chia/util/full_block_utils.py
  tests/core/full_node/stores/test_block_store.py
  tests/util/test_full_block_utils.py
Labels: Changed

#15928 Skip problematic test
  tests/cmds/test_sim.py
Labels: ready_to_merge, Fixed

#15952 test install scripts both dev and not
  .github/workflows/test-install-scripts.yml
Labels: Added, CI

#15963 Fixed an issue where `-t` option was required in cudaplot
  chia/plotters/plotters.py
Labels: Fixed

#15903 Add coverage failure as comment to PR
  .github/workflows/test.yml
Labels: Changed, CI, ready_to_review

#15946 fixup block store and coin store benchmarks
  benchmarks/block_store.py
  benchmarks/coin_store.py
  benchmarks/streamable.py
Labels: ready_to_merge, Fixed, Tests

#15965 checkpoint: into main from release/2.0.0 @ 51d3a5a7f65efe6912f3066ba83efa4ba0abe765
  chia/plotters/bladebit.py
  chia/plotters/plotters.py
Labels: checkpoint_merge, Changed

#15959 simplify db connection helper (more simply)
  tests/util/db_connection.py
Labels: Fixed, Tests

#15969 checkpoint: into main from release/2.0.0 @ d13538d02561a13ce13b318dc4efb7dddc959a46
  chia/cmds/plotnft_funcs.py
  chia/rpc/wallet_rpc_client.py
Labels: checkpoint_merge, Changed

#15979 Fixing conditional execution
  .github/workflows/test.yml
Labels: Fixed, CI

#15968 Update nft_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
Labels: ready_to_merge, Fixed

#15937 Add ALLOW_BACKREFS as a flag to get_puzzle_and_solution_for_coin in full_node_api.py
  chia/full_node/full_node_api.py
  chia/rpc/full_node_rpc_api.py
Labels: Fixed

#15859 Simplify get_max_send_amount for XCH and CATs
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/wallet.py
Labels: Changed

#15978 checkpoint: into main from release/2.0.0 @ a5a988c32098d8a3f56d4c284680f20aeed2fccb
  chia/rpc/full_node_rpc_api.py
Labels: checkpoint_merge, Changed

#15973 Update chia_rs to 0.2.10
  setup.py
Labels: Changed

#15943 Bladebit3 as the default plotter to install
  Install-plotter.ps1
  install-plotter.sh
Labels: Changed

#15991 Use ephemeral credentials from AWS OIDC provider
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: Changed

#15990 Re-enable benchmark runner
  .github/workflows/benchmarks.yml
Labels: Changed, CI

#15986 Remove pipefail
  .github/workflows/test.yml
Labels: Fixed, CI

#15987 checkpoint: into main from release/2.0.0 @ b1ecb5e15443787b3929fd9f8d99c566f0ab396a
  setup.py
Labels: checkpoint_merge, Changed

#15948 optimize blockchain DB for Chip-13
  chia/full_node/block_store.py
  chia/util/full_block_utils.py
  tests/core/full_node/stores/test_block_store.py
Labels: ready_to_merge, Changed, Performance

#15998 checkpoint: into main from release/2.0.0 @ 6c2c7bd6af519fb6194edc18630b3264b6969f56
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: checkpoint_merge, Changed

#15995 Fixing start-sync-tests
  .github/workflows/start-sync-test.yml
Labels: Fixed, CI

#15809 use venv for pre-commit black
  .pre-commit-config.yaml
Labels: Changed, CI

#15807 let pre-commit pick isort files
  .pre-commit-config.yaml
Labels: Changed, CI

#16006 Pin mypy to v1.4.1
  setup.py
Labels: Changed, Cleanup

#16008 pin direct dev dependencies
  setup.py
Labels: Changed, Tests

#16007 fix bug in recent BlockStore optimization patch
  chia/full_node/block_store.py
  tests/core/full_node/stores/test_block_store.py
Labels: ready_to_merge, Fixed

#16011 Use 'Completed writing plot' as the magic final words for cudaplot
  chia/daemon/server.py
  chia/plotters/bladebit.py
Labels: Changed

#15781 Refactor Seeder & Crawler code + add tests
  chia/seeder/crawl_store.py
  chia/seeder/crawler.py
  chia/seeder/dns_server.py
  chia/seeder/peer_record.py
  chia/seeder/start_crawler.py
  chia/simulator/setup_services.py
  chia/util/initial-config.yaml
  mypy-exclusions.txt
  tests/conftest.py
  tests/core/data_layer/conftest.py
  tests/core/test_crawler.py
  tests/core/test_crawler_rpc.py
  tests/core/test_seeder.py
Labels: Fixed

#15936 Simplify BlockStore and CoinStore
  chia/full_node/block_store.py
  chia/full_node/coin_store.py
  tests/core/full_node/stores/test_block_store.py
  tests/core/full_node/stores/test_hint_store.py
  tests/core/full_node/test_block_height_map.py
Labels: ready_to_merge, Changed, Cleanup

#16012 correct --insecure flag to cancel_offer command line
  chia/cmds/wallet.py
Labels: CLI, ready_to_merge, Fixed

#16004 Don't farm compressed plots if context count is 0
  chia/plotting/manager.py
Labels: Fixed

#15967 fix testnet10 sync-from-scratch
  chia/consensus/block_body_validation.py
  chia/consensus/constants.py
  chia/consensus/default_constants.py
  chia/full_node/mempool_check_conditions.py
  chia/server/start_full_node.py
  chia/util/initial-config.yaml
  tests/util/test_testnet_overrides.py
Labels: ready_to_merge, Fixed, coverage-diff

#15886 Add Wallet CLI Unit tests
  chia/cmds/cmds_util.py
  chia/cmds/coin_funcs.py
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  tests/cmds/cmd_test_utils.py
  tests/cmds/test_show.py
  tests/cmds/wallet/__init__.py
  tests/cmds/wallet/config.py
  tests/cmds/wallet/test_coins.py
  tests/cmds/wallet/test_consts.py
  tests/cmds/wallet/test_did.py
  tests/cmds/wallet/test_nft.py
  tests/cmds/wallet/test_notifications.py
  tests/cmds/wallet/test_offer.toffer
  tests/cmds/wallet/test_vcs.py
  tests/cmds/wallet/test_wallet.py
  tests/cmds/wallet/test_wallet_check.py
Labels: Wallet, CLI, Added, coverage-diff

#16015 Update remaining references to installer upload keys to OIDC provider
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: Fixed, CI

#16020 Fixed an issue where chiapos recognized `t2` as required option
  chia/daemon/server.py
Labels: Fixed

#16024 checkpoint: into main from release/2.0.0 @ ca10d053991a99c550ee3754698a51f192f07c56
  chia/plotters/plotters.py
Labels: checkpoint_merge, Changed

#16033 checkpoint: into main from release/2.0.0 @ 0101ae11b4e7b7ffd1ec12faa46c643938517aaa
  chia/full_node/full_node_api.py
  chia/rpc/full_node_rpc_api.py
Labels: checkpoint_merge, Changed, coverage-diff

#16032 New windows signing cert
  .github/workflows/build-windows-installer.yml
  build_scripts/build_windows-2-installer.ps1
Labels: Changed, CI

#16034 checkpoint: into main from release/2.0.0 @ 7299cfa104946fc92e6b8369e481fe4ce0cf5083
  setup.py
Labels: checkpoint_merge, Changed

#16017 Deprecate minting CATs via RPC
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  tests/pools/test_pool_rpc.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Changed

#16038 checkpoint: into main from release/2.0.0 @ 17659b80396c3e87fa60415a6ff3fcc2983c0b52
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/test_wallet.py
Labels: checkpoint_merge, Changed

#16010 Remove pointless outgoing TX for CR-CAT claim
  chia/wallet/vc_wallet/cr_cat_wallet.py
  tests/wallet/vc_wallet/test_vc_wallet.py
Labels: Fixed

#15992 Fix timelord-install.sh for CentOS\RHEL
  install-timelord.sh
Labels: Fixed

#15200 rpc: Hint `wallet_rpc_api.py`
  chia/rpc/wallet_rpc_api.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#16053 checkpoint: into main from release/2.0.0 @ f1ed16bd6f48706bb2ce120ae61fd1b3a3bef223
  .github/workflows/start-sync-test.yml
Labels: checkpoint_merge, Changed

#16064 use unhashable interface before from_json_dict
  chia/util/streamable.py
  tests/core/util/test_streamable.py
Labels: ready_to_merge, Changed

#16072 checkpoint: into main from release/2.0.0 @ 231bc4638d18db855bc837aef79e0b3b3627526d
  chia/daemon/server.py
  chia/plotters/bladebit.py
Labels: checkpoint_merge, Changed

#15883 Add ergonomic condition classes
  chia/wallet/conditions.py
  tests/wallet/test_conditions.py
Labels: ready_to_merge, Added

#16074 Skip flaky seeder tests while a fix is being worked on
  tests/core/test_seeder.py
Labels: Changed, CI, Exclude_Notes

#16076 checkpoint: into main from release/2.0.0 @ cbf971e7f5bbbbcf64d3e8571fb82c14592c53b2
  chia/plotting/manager.py
Labels: checkpoint_merge, Changed

#16025 cleanup coverage-diff comment
  .github/workflows/test.yml
Labels: Changed, CI

#16055 Fix Core Test Flake
  chia/seeder/crawl_store.py
  chia/seeder/dns_server.py
  tests/core/test_seeder.py
Labels: Fixed, Tests, coverage-diff

#16047 Timeout for retrieving a decompressor.
  chia/harvester/harvester.py
  chia/harvester/harvester_api.py
  chia/plotting/check_plots.py
  chia/plotting/manager.py
  chia/plotting/util.py
  chia/util/initial-config.yaml
  setup.py
Labels: Added

#16084 checkpoint: into main from release/2.0.0 @ 914505f9456a17534272c8be8a0ce18e26534aa8
  chia/daemon/server.py
Labels: checkpoint_merge, Changed

#15997 Dao chialisp fixes
  chia/wallet/cat_wallet/puzzles/genesis_by_coin_id_or_singleton.clsp
  chia/wallet/cat_wallet/puzzles/genesis_by_coin_id_or_singleton.clsp.hex
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/puzzles/dao_proposal.clsp
  chia/wallet/puzzles/dao_proposal.clsp.hex
  chia/wallet/puzzles/dao_spend_p2_singleton_v2.clsp
  chia/wallet/puzzles/dao_spend_p2_singleton_v2.clsp.hex
  chia/wallet/puzzles/dao_treasury.clsp
  chia/wallet/puzzles/dao_treasury.clsp.hex
  chia/wallet/puzzles/deployed_puzzle_hashes.json
  chia/wallet/puzzles/p2_singleton_aggregator.clsp
  chia/wallet/puzzles/p2_singleton_aggregator.clsp.hex
  tests/wallet/dao_wallet/test_dao_clvm.py
Labels: Fixed, Cleanup

#16068 adjust timing thresholds for some benchmarks
  tests/core/mempool/test_mempool.py
Labels: Fixed, Tests

#16071 Parallel CI
  tests/core/cmds/config.py
  tests/core/consensus/config.py
  tests/core/custom_types/config.py
  tests/generator/config.py
  tests/simulation/config.py
  tests/testconfig.py
  tests/wallet/cat_wallet/config.py
Labels: Changed, CI

#16090 checkpoint: into main from release/2.0.0 @ f1ad0d29d2de8ae94b02a8c5edf9456e593d125a
  chia/data_layer/data_layer.py
  tests/core/data_layer/test_data_rpc.py
Labels: checkpoint_merge, Changed

#16088 revive test-full-sync benchmark
  tools/run_benchmark.sh
Labels: Fixed, Tests

#16077 Don't raise on duplicate VC proof insertion
  chia/wallet/vc_wallet/vc_store.py
  tests/wallet/vc_wallet/test_vc_wallet.py
Labels: ready_to_merge, Fixed

#16078 Added wallet id showing when using the 'chia plotnft show'.
  chia/cmds/plotnft_funcs.py
Labels: enhancement, Changed

#16051 Add self revocation path to VC wallet
  chia/wallet/vc_wallet/vc_drivers.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet_protocol.py
  tests/wallet/vc_wallet/test_vc_lifecycle.py
  tests/wallet/vc_wallet/test_vc_wallet.py
Labels: ready_to_merge, Fixed

#16093 checkpoint: into main from release/2.0.0 @ 0deb8e6dc625b7247945e4d2c081554491686035
  chia/harvester/harvester.py
  chia/harvester/harvester_api.py
  chia/plotting/check_plots.py
  chia/plotting/manager.py
  chia/plotting/util.py
  chia/util/initial-config.yaml
  setup.py
Labels: checkpoint_merge, Changed, coverage-diff

#16092 Trusted publishing for pypi
  .github/workflows/upload-pypi-source.yml
Labels: Changed, CI

#16095 add missing method to FullNodeRpcClient mock
  tests/cmds/cmd_test_utils.py
Labels: ready_to_merge, Fixed, Tests

#16100 Adjust harvester warning to 8 seconds from 5
  chia/harvester/harvester_api.py
  chia/plotting/check_plots.py
Labels: Changed

#15899 various typing fixes
  blspy-stubs/blspy-stubs/__init__.pyi
  blspy-stubs/setup.py
  chia/cmds/keys_funcs.py
  chia/consensus/block_header_validation.py
  chia/full_node/full_node.py
  chia/plotting/create_plots.py
  chia/rpc/wallet_rpc_api.py
  chia/simulator/block_tools.py
  chia/util/cached_bls.py
  chia/util/keychain.py
  install.sh
  tests/blockchain/test_blockchain.py
  tests/clvm/test_puzzles.py
  tests/pools/test_pool_rpc.py
  tests/util/benchmark_cost.py
  tests/util/key_tool.py
  tests/util/network_protocol_data.py
  tests/wallet/clawback/test_clawback_lifecycle.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_sign_coin_spends.py
  tools/legacy_keyring.py
Labels: ready_to_merge, Fixed, Cleanup

#16099 Always use at least one worker for `chia plots check`
  chia/plotting/check_plots.py
Labels: Fixed, Exclude_Notes

#16104 Update to chiapos 2.0.2
  setup.py
Labels: Changed

#16109 checkpoint: into main from release/2.0.0 @ 34314c1abb36b1088898cd83b7809133b93eb834
  .github/workflows/upload-pypi-source.yml
Labels: checkpoint_merge, Changed

#16080 remove `cls` parameter hinting from conditions classes
  chia/wallet/conditions.py
Labels: Changed, Cleanup

#16082 Update conditions.py
  chia/wallet/conditions.py
Labels: Changed, Cleanup

#15666 Introduce TXConfig and CoinSelectionConfig
  chia/cmds/cmds_util.py
  chia/cmds/coin_funcs.py
  chia/cmds/coins.py
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/util.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/simulator/full_node_simulator.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/coin_selection.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/notification_manager.py
  chia/wallet/puzzles/tails.py
  chia/wallet/trade_manager.py
  chia/wallet/util/tx_config.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_protocol.py
  chia/wallet/wallet_state_manager.py
  tests/cmds/cmd_test_utils.py
  tests/cmds/test_tx_config_args.py
  tests/cmds/wallet/test_coins.py
  tests/cmds/wallet/test_did.py
  tests/cmds/wallet/test_nft.py
  tests/cmds/wallet/test_vcs.py
  tests/cmds/wallet/test_wallet.py
  tests/core/full_node/test_full_node.py
  tests/core/full_node/test_transactions.py
  tests/core/mempool/test_mempool_manager.py
  tests/core/mempool/test_mempool_performance.py
  tests/pools/test_pool_rpc.py
  tests/simulation/test_simulation.py
  tests/simulation/test_simulator.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/db_wallet/test_dl_offers.py
  tests/wallet/db_wallet/test_dl_wallet.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_bulk_mint.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_coin_selection.py
  tests/wallet/test_notifications.py
  tests/wallet/test_util.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_retry.py
  tests/wallet/vc_wallet/test_vc_wallet.py
Labels: ready_to_merge, Changed

#15888 Add the option for arbitrary conditions to make_solution
  chia/data_layer/data_layer_wallet.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/vc_wallet/vc_drivers.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
Labels: ready_to_merge, Added

#16112 checkpoint: into main from release/2.0.0 @ b59315836dd086e6506f10fd2bef3e620baabff0
  chia/harvester/harvester_api.py
  chia/plotting/check_plots.py
Labels: checkpoint_merge, Changed, coverage-diff

#16103 Support calling get_routes via wss
  chia/rpc/rpc_server.py
Labels: Fixed

#16117 Fix VC mypy issues
  chia/wallet/vc_wallet/vc_wallet.py
  tests/wallet/vc_wallet/test_vc_wallet.py
Labels: Fixed

#16115 checkpoint: into main from release/2.0.0 @ 10d09e6cd554a7f6a2b61b5373cdf5ac9cf82a21
  chia/plotting/check_plots.py
Labels: checkpoint_merge, Changed, coverage-diff

#16121 checkpoint: into main from release/2.0.0 @ 493cc16659261a59c3d168f7166cfddcb7560d5b
  setup.py
Labels: checkpoint_merge, Changed

#16124 Update codeowner for .github to a group
  .github/CODEOWNERS
Labels: Changed, CI

#16122 Notify glue of completed prerelease, and fix permissions
  .github/workflows/build-linux-arm64-installer.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
  .github/workflows/start-release.yml
Labels: Changed, CI

#16114 consolidate `--fingerprint` definitions
  chia/cmds/coins.py
  chia/cmds/keys.py
  chia/cmds/options.py
  chia/cmds/plotnft.py
  chia/cmds/sim.py
  chia/cmds/wallet.py
Labels: Changed, Cleanup

#16116 Make sure reuse_puzhash works for nft1 offers
  chia/wallet/nft_wallet/nft_wallet.py
Labels: ready_to_merge, Fixed

#16091 Change NFT tests to cover bulk transfer/DID set of multiple NFTs at once
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: Added, Tests

#16133 Adding 2.0.0 changelog
  CHANGELOG.md
Labels: Added, Exclude_Notes

#16141 Make sure to sign all EXEs
  build_scripts/build_windows-2-installer.ps1
Labels: Fixed, Exclude_Notes

#16130 Use pytest's monkeypatch fixture instead of unittest's MagicMock
  tests/core/full_node/full_sync/test_full_sync.py
Labels: ready_to_merge, Changed, Cleanup

#16108 try again a few times if the temporary DB file can't be removed
  chia/simulator/setup_services.py
Labels: Fixed, Tests

#16094 tidy the `DataLayer._update_confirmation_status()` usage pattern
  chia/data_layer/data_layer.py
Labels: Changed, Cleanup

#16079 Do not enable seeder signal handlers in tests
  chia/seeder/dns_server.py
Labels: Fixed, Tests

#16119 Print JSON for all DL commands.
  chia/cmds/data_funcs.py
Labels: Changed, DataLayer

#16145 bumping date
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#16146 checkpoint: into main from release/2.0.0 @ 9093c4013b67ab7cae8d50493ff8fdeaf9ac712a
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#16143 Fix black pre-commit config
  .pre-commit-config.yaml
Labels: Fixed, CI

#16037 wallet: Fix comment in `WalletNode.validate_received_state_from_peer`
  chia/wallet/wallet_node.py
Labels: Changed, Cleanup

#16045 full_node: More use of `FullNode.get_peers_with_peak`
  chia/full_node/full_node.py
Labels: Changed, Cleanup

#16107 full_node: Drop unused `get_fork_point_no_validations`
  chia/full_node/weight_proof.py
Labels: Changed, Cleanup

#16150 checkpoint: into main from release/2.0.0 @ 9c1d28509179bac89fb6831803d939897acd47da
  build_scripts/build_windows-2-installer.ps1
Labels: checkpoint_merge, Changed

#16153 checkpoint: into main from release/2.0.0 @ dc46f46b9a30628b208d38fd7dd0ca085e820781
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#16149 create and upload individual and combined junit reports
  .github/workflows/test-single.yml
  .github/workflows/test.yml
Labels: Added, CI

#16131 Add flags to CR-CAT offer summary
  chia/rpc/wallet_rpc_api.py
  tests/wallet/cat_wallet/test_trades.py
Labels: ready_to_merge, Added

#16029 Improve testnet connectivity.
  chia/server/node_discovery.py
Labels: Added

#16156 Add get_public_key and get_public_keys daemon RPCs
  chia/daemon/keychain_server.py
  tests/core/daemon/test_daemon.py
Labels: ready_to_merge, Added

#16148 `@pytest.mark.limit_consensus_modes`
  pytest.ini
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/data_layer/test_data_rpc.py
  tests/core/full_node/stores/test_block_store.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/mempool/test_mempool_performance.py
  tests/core/test_full_node_rpc.py
  tests/plotting/test_plot_manager.py
  tests/simulation/test_simulation.py
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Tests

#16139 increase windows pytest threads to 3
  tests/build-job-matrix.py
Labels: Changed, CI, Exclude_Notes

#16138 Improve wallet rpc test consistency
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Changed, CI, Exclude_Notes

#16185 simplify a test the no longer needs to cover pre-soft-fork2 cases
  tests/blockchain/test_blockchain.py
Labels: ready_to_merge, Changed, Tests

#16181 Annotate test_block_height_map.py
  mypy-exclusions.txt
  tests/core/full_node/test_block_height_map.py
Labels: Changed, Cleanup

#16159 type mismatch for last_time_farmed
  chia/rpc/wallet_rpc_api.py
Labels: Fixed

#16101 demote log level for TIMESTAMP_TOO_FAR_IN_FUTURE errors
  chia/full_node/full_node.py
  chia/server/ws_connection.py
  chia/util/errors.py
Labels: Changed

#15911 Add `extra_conditions` as an option to transaction endpoints
  chia/cmds/cmds_util.py
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/util.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/notification_manager.py
  chia/wallet/trade_manager.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/vc_drivers.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
  tests/cmds/test_timelock_args.py
Labels: ready_to_merge, Added

#16027 Add bad peak cache
  chia/consensus/block_body_validation.py
  chia/consensus/block_header_validation.py
  chia/full_node/full_node.py
  chia/util/errors.py
  chia/util/initial-config.yaml
  tests/blockchain/test_blockchain.py
  tests/core/full_node/full_sync/test_full_sync.py
  tools/test_full_sync.py
Labels: full_node, sync, Added

#15794 Rename Mode enum to ConsensusMode
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/full_node/test_conditions.py
  tests/core/mempool/test_mempool_performance.py
  tests/core/test_full_node_rpc.py
Labels: Changed, Cleanup

#15472 Optimize and simplify farmer RPC get_signage_point()
  chia/rpc/farmer_rpc_api.py
Labels: Changed, Cleanup

#16019 Add a full node RPC endpoint, get_mempool_items_by_coin_name
  chia/rpc/full_node_rpc_api.py
  chia/rpc/full_node_rpc_client.py
  tests/core/test_full_node_rpc.py
Labels: Added

#16183 override class variables in limits tests in order to speed up test
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Changed, CI, Exclude_Notes

#15735 Prevent redundant peer calls in coin_added
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/cat_wallet/cat_info.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_info.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/nft_wallet/uncurry_nft.py
  chia/wallet/util/wallet_types.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/vc_drivers.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_protocol.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/test_wallet_state_manager.py
Labels: Changed

#16147 Add some tests related to the state of the height-to-hash cache file
  tests/core/full_node/test_block_height_map.py
Labels: Changed, Cleanup

#16209 Adapt recent full sync tests to ConsensusMode
  tests/core/full_node/full_sync/test_full_sync.py
Labels: Changed, Cleanup

#16205 add -s passthrough for .github/actions/install/
  .github/actions/install/action.yml
  .github/workflows/test-install-scripts.yml
Labels: Added, CI
