Repository Chia-Network/chia-blockchain, pull requests merged in 2024-12, with the labels that each got.

#18305 use the lock file for pinning dependencies, not the project definition
  poetry.lock
  pyproject.toml
Labels: Changed

#18831 fix trusted wallet sync on deep reorg
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/full_node/full_node.py
  chia/simulator/add_blocks_in_batches.py
  chia/wallet/wallet_node.py
Labels: Wallet, full_node, sync, Fixed

#18926 explicitly set option parameter name based on field name for cmd classes
  chia/_tests/cmds/test_cmd_framework.py
  chia/cmds/cmd_classes.py
Labels: Changed, Exclude_Notes

#18937 remove dangling pylint comment reference
  chia/rpc/data_layer_rpc_util.py
Labels: Changed, Exclude_Notes

#18948 remove implementation from `BlockRecordProtocol.is_transaction_block()`
  chia/consensus/block_record.py
Labels: Changed, Exclude_Notes

#18964 Add simulator to installers
  build_scripts/pyinstaller.spec
Labels: Added

#18893 add new configuration option to log the first 6 hex digits of coins
  chia/_tests/util/blockchain.py
  chia/_tests/util/setup_nodes.py
  chia/_tests/wallet/conftest.py
  chia/consensus/block_body_validation.py
  chia/consensus/blockchain.py
  chia/full_node/full_node.py
  chia/util/initial-config.yaml
Labels: Changed

#18960 use poetry 1.8.3
  Setup-poetry.ps1
  poetry.lock
  requirements-poetry.txt
  setup-poetry.sh
Labels: Changed, Exclude_Notes

#18963 [CHIA-1731] Add comments about PLR6201
  chia/_tests/core/util/test_keychain.py
Labels: ready_to_merge, Changed

#18962 actionlint without `VALIDATE_GITHUB_ACTIONS: true`
  .github/actionlint.yaml
  .github/workflows/benchmarks.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
  .github/workflows/mozilla-ca-cert.yml
  .github/workflows/reflow-publish-installer.yml
  .github/workflows/reflow-version.yml
  .github/workflows/test-install-scripts.yml
  .github/workflows/test-single.yml
  .github/workflows/test.yml
  .github/workflows/upload-pypi-source.yml
  .shellcheckrc
Labels: Added, CI

#18833 CHIA-1730: port `chia plotnft` to `@chia_commands` framework
  chia/_tests/cmds/test_cmd_framework.py
  chia/_tests/conftest.py
  chia/_tests/pools/test_pool_cli_parsing.py
  chia/_tests/pools/test_pool_cmdline.py
  chia/_tests/pools/test_pool_wallet.py
  chia/cmds/plotnft.py
  chia/cmds/plotnft_funcs.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  mypy-exclusions.txt
Labels: Changed

#18974 fixup `dont_prompt`
  chia/cmds/plotnft.py
Labels: Fixed, Exclude_Notes

#18938 no more pre-commit conditional versioning
  poetry.lock
  pyproject.toml
Labels: Changed, Exclude_Notes

#18961 add `root_path` parameter to `initialize_service_logging()`
  chia/daemon/server.py
  chia/seeder/dns_server.py
  chia/seeder/start_crawler.py
  chia/server/start_data_layer.py
  chia/server/start_farmer.py
  chia/server/start_full_node.py
  chia/server/start_harvester.py
  chia/server/start_introducer.py
  chia/server/start_timelord.py
  chia/server/start_wallet.py
  chia/simulator/start_simulator.py
  chia/timelord/timelord_launcher.py
  chia/util/chia_logging.py
  chia/util/default_root.py
Labels: Changed, Exclude_Notes

#18966 add test for a 1-block reorg in short_sync_backtrack()
  chia/_tests/core/full_node/test_full_node.py
Labels: Changed, Tests

#18951 fix short_sync_backtrack
  chia/_tests/core/full_node/test_full_node.py
  chia/full_node/full_node.py
Labels: ready_to_merge, full_node, sync, Fixed

#18957 [CHIA-1659] Delete unnecessary `TODO` in `auto_claim_coins`
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge, Changed

#18965 [CHIA-1933] Remove `get_new` methods from `CATWallet`
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/dao_wallet/test_dao_wallets.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/puzzles/tails.py
  chia/wallet/trade_manager.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
Labels: ready_to_merge, Changed

#18968 [CHIA-1934] Remove `get_new_*` from `DIDWallet`
  chia/wallet/did_wallet/did_wallet.py
Labels: ready_to_merge, Changed

#18985 less `DEFAULT_ROOT_PATH` for base chia command
  chia/cmds/chia.py
Labels: Changed, Exclude_Notes

#18982 less `DEFAULT_ROOT_PATH` for farm commands
  chia/cmds/farm.py
  chia/cmds/farm_funcs.py
Labels: Changed, Exclude_Notes

#18984 less `DEFAULT_ROOT_PATH` for rpc commands
  chia/cmds/rpc.py
Labels: Changed, Exclude_Notes, coverage-diff

#18987 Add override for dependency license
  .repo-content-updater.yml
Labels: Fixed

#18989 backport Remove 3.8 from release
  .github/workflows/check_wheel_availability.yaml
  .github/workflows/pre-commit.yml
  .github/workflows/test-install-scripts.yml
  .github/workflows/test-single.yml
  .github/workflows/upload-pypi-source.yml
  Install.ps1
  chia/_tests/core/ssl/test_ssl.py
  chia/full_node/full_node.py
  install.sh
  poetry.lock
  pyproject.toml
Labels: ready_to_merge, Changed

#18991 Update Managed Files
  .github/workflows/dependency-review.yml
Labels: Changed, Exclude_Notes

#18983 no more `python -m chia.cmds.init`
  chia/cmds/init.py
Labels: Changed

#18988 [CHIA-1976] bump chia_rs to 0.16.0 and introduce soft-fork6
  chia/_tests/conftest.py
  chia/_tests/core/full_node/test_generator_tools.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/fee_estimation/test_fee_estimation_integration.py
  chia/_tests/util/test_condition_tools.py
  chia/_tests/util/test_replace_str_to_bytes.py
  chia/_tests/util/test_testnet_overrides.py
  chia/cmds/sim_funcs.py
  chia/consensus/default_constants.py
  chia/full_node/mempool_check_conditions.py
  chia/rpc/wallet_rpc_api.py
  chia/util/initial-config.yaml
  poetry.lock
  pyproject.toml
  tools/analyze-chain.py
Labels: ready_to_merge, Changed

#18875 fix: typos in documentation files
  README.md
Labels: Fixed, community-pr

#18952 chore: fix 404 status URL
  chia/_tests/README.md
Labels: Fixed, community-pr

#18997 fixup installer workflow version coherence with poetry
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: Fixed, Exclude_Notes

#18995 checkpoint: into main from release/2.5.0 @ f9b7ddcfcf50b8a0cf7a39a9c9f5f53214702319
  chia/_tests/conftest.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/util/test_replace_str_to_bytes.py
  chia/_tests/util/test_testnet_overrides.py
  chia/cmds/sim_funcs.py
  chia/consensus/default_constants.py
  chia/util/initial-config.yaml
Labels: checkpoint_merge, Changed, coverage-diff

#19006 Addendum to 100% block fill rate.
  chia/_tests/core/mempool/test_mempool_manager.py
Labels: Changed, Cleanup

#19002 checkpoint: into main from release/2.5.0 @ 0d40f9f27dcef5ad235d516b793244aaa6a87720
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: checkpoint_merge, Changed

#18979 Update .repo-content-updater.yml to use default rebase setting
  .repo-content-updater.yml
Labels: Changed, Exclude_Notes

#19004 CHIA-2020 Simplify add_block_batch
  chia/_tests/util/full_sync.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/full_node/full_node.py
  chia/simulator/add_blocks_in_batches.py
  tools/test_full_sync.py
Labels: ready_to_merge, Changed, Cleanup

#18422 Unconfirmed tx cache - CHIA-785
  chia/_tests/environments/wallet.py
  chia/_tests/wallet/dao_wallet/test_dao_wallets.py
  chia/_tests/wallet/test_transaction_store.py
  chia/simulator/full_node_simulator.py
  chia/wallet/transaction_record.py
  chia/wallet/wallet_state_manager.py
  chia/wallet/wallet_transaction_store.py
Labels: Fixed, Performance

#18980 Optimize add node hashes.
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/data_store.py
Labels: Fixed, DataLayer

#18981 add some validation of `fork_info` in Blockchain.add_block()
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/blockchain/test_blockchain_transactions.py
  chia/_tests/core/full_node/stores/test_block_store.py
  chia/_tests/core/full_node/stores/test_coin_store.py
  chia/_tests/core/full_node/stores/test_full_node_store.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/pools/test_pool_rpc.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/consensus/blockchain.py
  chia/full_node/full_node.py
  chia/simulator/add_blocks_in_batches.py
  chia/simulator/full_node_simulator.py
Labels: Changed, Tests

#19012 Update Managed Files
  .github/dependabot.yml
Labels: Changed

#18990 [CHIA-1829] don't drop outgoing response messages
  chia/_tests/core/server/test_rate_limits.py
  chia/full_node/full_node_api.py
  chia/protocols/protocol_timing.py
  chia/server/rate_limit_numbers.py
  chia/server/rate_limits.py
  chia/server/ws_connection.py
Labels: Fixed

#18896 Track weight proof tasks
  chia/full_node/full_node.py
Labels: full_node, sync, Fixed, coverage-diff

#19007 use height to hash in short sync
  chia/full_node/full_node.py
Labels: ready_to_merge, full_node, sync, Fixed

#19026 Attempt to clarify why we add many aggsig conditions in make_and_send_big_cost_sb
  chia/_tests/core/mempool/test_mempool_manager.py
Labels: Changed, Cleanup

#19030 Update changelog for 2.5.0
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#18970 [CHIA-1316] Port VC Endpoints to `@marshal` decorator
  chia/_tests/cmds/wallet/test_vcs.py
  chia/_tests/wallet/cat_wallet/test_trades.py
  chia/_tests/wallet/vc_wallet/test_vc_wallet.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_request_types.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
Labels: ready_to_merge, Changed

#19011 revert super set rule
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/full_node/mempool_manager.py
Labels: ready_to_merge, Changed

#19027 correct short license text to SPDX standard `Apache-2.0`
  pyproject.toml
Labels: Changed, Exclude_Notes

#18996 convert test_change_pools to WalletTestFramework
  chia/_tests/pools/test_pool_cmdline.py
  chia/_tests/pools/test_pool_rpc.py
Labels: Changed, CI, Exclude_Notes, coverage-diff

#19035 fix wrong param in prevalidate
  chia/full_node/full_node.py
Labels: full_node, Fixed

#19014 CHIA-2022: Fix problems with startup timing and the Datalayer processing loop
  chia/data_layer/data_layer.py
Labels: Fixed

#19005 remove the block fill rate limit of 70% when farming a block
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/full_node/mempool_manager.py
Labels: ready_to_merge, Changed

#19031 more less default root path
  chia/_tests/cmds/cmd_test_utils.py
  chia/cmds/cmd_classes.py
  chia/cmds/cmds_util.py
  chia/cmds/coin_funcs.py
  chia/cmds/coins.py
  chia/cmds/dao.py
  chia/cmds/dao_funcs.py
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
Labels: Changed

#19039 avoid set for test parametrization
  chia/_tests/rpc/test_rpc_client.py
Labels: Fixed, Tests

#19040 first pass at using `@chia_command` without a group
  chia/_tests/cmds/test_cmd_framework.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/cmds/chia.py
  chia/cmds/cmd_classes.py
  chia/cmds/plotnft.py
  chia/cmds/signer.py
  chia/cmds/wallet.py
Labels: Changed, Exclude_Notes

#19046 checkpoint: into main from release/2.5.0 @ 40ca4f94fc44fafc422b5cf20bfbd2db2b883f06
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#19049 less `DEFAULT_ROOT_PATH` for `get_any_service_client()`
  chia/_tests/cmds/cmd_test_utils.py
  chia/_tests/farmer_harvester/test_farmer_harvester.py
  chia/cmds/cmds_util.py
  chia/cmds/data_funcs.py
  chia/cmds/farm.py
  chia/cmds/farm_funcs.py
  chia/cmds/netspace.py
  chia/cmds/netspace_funcs.py
  chia/cmds/peer_funcs.py
  chia/cmds/plotnft.py
  chia/cmds/plotnft_funcs.py
  chia/cmds/show_funcs.py
  chia/cmds/sim_funcs.py
Labels: Changed, Exclude_Notes

#18641 [CHIA-1348] Port `chia wallet coin` commands to `@chia_command` framework
  chia/_tests/cmds/test_cmd_framework.py
  chia/_tests/cmds/wallet/test_coins.py
  chia/_tests/cmds/wallet/test_tx_decorators.py
  chia/_tests/cmds/wallet/test_wallet.py
  chia/_tests/environments/wallet.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/test_coin_management.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/cmds/cmd_classes.py
  chia/cmds/cmds_util.py
  chia/cmds/coin_funcs.py
  chia/cmds/coins.py
  chia/cmds/signer.py
Labels: ready_to_merge, Changed, Exclude_Notes

#19065 CHIA-2091 Use boost v1.85 when compiling chiavdf from source on macos-intel
  install-timelord.sh
Labels: Changed, Cleanup

#19063 move ruff check right after ruff format in pre-commit since it is fast and changing stuff now
  .pre-commit-config.yaml
Labels: Changed, Exclude_Notes

#18923 CHIA-1862 Fix FullNodeAPI's request_block_headers returned filter
  chia/_tests/util/test_full_block_utils.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/full_node/full_node_api.py
  chia/util/full_block_utils.py
Labels: Changed, Cleanup

#19025 ignore errors in daemon plotter process cleanup
  chia/daemon/server.py
Labels: Fixed, CI, Exclude_Notes

#18969 CHIA-1945 Avoid computing a transactions filter with just reward coins when the filter is not requested from get_block_header
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/util/test_full_block_utils.py
  chia/_tests/wallet/test_wallet_blockchain.py
  chia/_tests/weight_proof/test_weight_proof.py
  chia/consensus/blockchain.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node_api.py
  chia/util/generator_tools.py
Labels: Changed, Cleanup

#18919 use a class for the chia cli context data
  chia/_tests/cmds/test_click_types.py
  chia/_tests/cmds/test_cmd_framework.py
  chia/_tests/pools/test_pool_cli_parsing.py
  chia/_tests/pools/test_pool_cmdline.py
  chia/cmds/beta.py
  chia/cmds/check_wallet_db.py
  chia/cmds/chia.py
  chia/cmds/cmd_classes.py
  chia/cmds/cmd_helpers.py
  chia/cmds/configure.py
  chia/cmds/dao.py
  chia/cmds/db.py
  chia/cmds/farm.py
  chia/cmds/init.py
  chia/cmds/keys.py
  chia/cmds/netspace.py
  chia/cmds/param_types.py
  chia/cmds/passphrase.py
  chia/cmds/peer.py
  chia/cmds/plotnft.py
  chia/cmds/plots.py
  chia/cmds/plotters.py
  chia/cmds/rpc.py
  chia/cmds/show.py
  chia/cmds/sim.py
  chia/cmds/start.py
  chia/cmds/stop.py
  chia/cmds/wallet.py
Labels: Changed, Exclude_Notes

#18922 add chia dev gh test for launching configured test runs
  .github/workflows/conflict-check.yml
  chia/_tests/cmds/test_dev_gh.py
  chia/cmds/dev.py
  chia/cmds/gh.py
Labels: Added, Exclude_Notes

#19066 Remove unnecessary action_scope edit
  chia/rpc/wallet_rpc_api.py
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge, Changed

#19073 fix gh command setup
  chia/cmds/gh.py
Labels: Fixed, Exclude_Notes

#19075 to multiline string literal
  chia/_tests/wallet/test_debug_spend_bundle.py
Labels: Fixed, Tests, Cleanup

#18955 Minor grammatical correction in wallet_rpc_api.py
  chia/rpc/wallet_rpc_api.py
Labels: Fixed, community-pr

#19083 Update chiavdf to 1.1.9
  poetry.lock
Labels: Changed
