Repository Chia-Network/chia-blockchain, pull requests merged in 2024-11, with the labels that each got.

#18773 Replace `class_for_type` function with a `dict`
  chia/_tests/connection_utils.py
  chia/_tests/core/ssl/test_ssl.py
  chia/apis.py
  chia/seeder/start_crawler.py
  chia/server/server.py
  chia/server/start_data_layer.py
  chia/server/start_farmer.py
  chia/server/start_full_node.py
  chia/server/start_harvester.py
  chia/server/start_introducer.py
  chia/server/start_service.py
  chia/server/start_timelord.py
  chia/server/start_wallet.py
  chia/server/ws_connection.py
  chia/simulator/start_simulator.py
  chia/util/network.py
Labels: ready_to_merge, Changed, Exclude_Notes

#18801 (Mostly) Replace flake8 with Ruff
  .flake8
  benchmarks/block_ref.py
  benchmarks/block_store.py
  benchmarks/coin_store.py
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/conftest.py
  chia/_tests/core/full_node/full_sync/test_full_sync.py
  chia/_tests/core/full_node/test_performance.py
  chia/_tests/core/server/test_dos.py
  chia/_tests/core/test_full_node_rpc.py
  chia/_tests/generator/test_compression.py
  chia/_tests/pools/test_pool_cmdline.py
  chia/_tests/pools/test_pool_config.py
  chia/_tests/util/benchmark_cost.py
  chia/_tests/util/build_network_protocol_files.py
  chia/_tests/util/network_protocol_data.py
  chia/_tests/util/protocol_messages_json.py
  chia/_tests/util/test_network_protocol_files.py
  chia/_tests/util/test_network_protocol_json.py
  chia/_tests/util/test_network_protocol_test.py
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/cmds/keys_funcs.py
  chia/cmds/show_funcs.py
  chia/full_node/block_height_map.py
  chia/full_node/full_node.py
  chia/full_node/mempool_manager.py
  chia/full_node/weight_proof.py
  chia/plotting/check_plots.py
  chia/rpc/wallet_rpc_client.py
  chia/simulator/block_tools.py
  chia/util/profiler.py
  chia/util/streamable.py
  chia/util/task_timing.py
  pyproject.toml
  tools/analyze_memory_profile.py
  tools/cpu_utilization.py
  tools/generate_chain.py
Labels: ready_to_merge, Changed

#18729 [CHIA-1638] Pace block requests
  chia/_tests/plot_sync/test_sender.py
  chia/full_node/full_node.py
Labels: ready_to_merge, Changed

#18805 reduce 60 minute timeout for single assert
  chia/_tests/farmer_harvester/test_third_party_harvesters.py
Labels: Changed, Tests, Cleanup, Exclude_Notes

#18808 use `brew install --formula`
  install-timelord.sh
Labels: Changed, Exclude_Notes

#18777 Update Managed Files
  .github/workflows/dependency-review.yml
Labels: Changed

#18807 test more services terminate
  chia/_tests/core/services/test_services.py
Labels: Added, Tests

#18810 allow backcompat mode for logging
  chia/util/chia_logging.py
  chia/util/initial-config.yaml
Labels: Changed

#18811 only attempt poetry install when not present
  Install.ps1
  install.sh
Labels: Changed

#18813 [CHIA-1681] Replace black with Ruff
  .github/workflows/upload-pypi-source.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  chia/_tests/blockchain/test_augmented_chain.py
  chia/_tests/core/daemon/test_daemon.py
  chia/_tests/core/full_node/stores/test_full_node_store.py
  chia/_tests/core/full_node/test_conditions.py
  chia/_tests/core/mempool/test_mempool_fee_protocol.py
  chia/_tests/core/server/test_server.py
  chia/_tests/environments/wallet.py
  chia/_tests/farmer_harvester/test_farmer_harvester.py
  chia/_tests/fee_estimation/test_fee_estimation_integration.py
  chia/_tests/fee_estimation/test_fee_estimation_rpc.py
  chia/_tests/plot_sync/test_plot_sync.py
  chia/_tests/util/build_network_protocol_files.py
  chia/_tests/util/test_network_protocol_files.py
  chia/_tests/wallet/dao_wallet/test_dao_clvm.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/_tests/wallet/test_conditions.py
  chia/_tests/wallet/test_new_wallet_protocol.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/_tests/wallet/test_util.py
  chia/_tests/wallet/test_wallet.py
  chia/_tests/wallet/test_wallet_coin_store.py
  chia/cmds/cmds_util.py
  chia/cmds/keys_funcs.py
  chia/cmds/wallet_funcs.py
  chia/consensus/blockchain.py
  chia/consensus/multiprocess_validation.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_wallet.py
  chia/data_layer/util/benchmark.py
  chia/full_node/full_node.py
  chia/full_node/full_node_store.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/util/action_scope.py
  chia/util/augmented_chain.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_spend_bundle.py
  chia/wallet/wallet_state_manager.py
  poetry.lock
  pyproject.toml
  tools/run_block.py
Labels: ready_to_merge, Changed

#18762 Use #!/usr/bin/env bash
  activated.sh
  build_scripts/build_license_directory.sh
  build_scripts/build_linux_deb-1-gui.sh
  build_scripts/build_linux_deb-2-installer.sh
  build_scripts/build_linux_rpm-1-gui.sh
  build_scripts/build_linux_rpm-2-installer.sh
  build_scripts/build_macos-1-gui.sh
  build_scripts/build_macos-2-installer.sh
  build_scripts/build_win_license_dir.sh
  build_scripts/clean-runner.sh
  install-gui.sh
  install-timelord.sh
  install.sh
  setup-poetry.sh
  start-gui.sh
  tools/run_benchmark.sh
Labels: Changed

#18775 more `start_*` service starting consistency
  chia/server/start_data_layer.py
  chia/server/start_farmer.py
  chia/server/start_full_node.py
  chia/server/start_harvester.py
  chia/server/start_introducer.py
  chia/server/start_timelord.py
  chia/server/start_wallet.py
  chia/util/initial-config.yaml
  chia/util/task_timing.py
Labels: Changed, Cleanup

#18787 CHIA-1684 Move obtain_current_passphrase next to KeyringWrapper
  chia/_tests/core/util/test_keyring_wrapper.py
  chia/cmds/keys_funcs.py
  chia/cmds/passphrase_funcs.py
  chia/util/dump_keyring.py
  chia/util/file_keyring.py
  chia/util/keyring_wrapper.py
Labels: Changed, Cleanup

#18798 CHIA-1692 Annotate chia/rpc/util.py
  chia/rpc/util.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#18817 [CHIA-1689] Miscellaneous ruff cleanups
  .isort.cfg
  .pre-commit-config.yaml
  CONTRIBUTING.md
  pyproject.toml
  ruff.toml
Labels: ready_to_merge, Changed, Exclude_Notes

#18823 Fix pre-commit in chia/rpc/util.py
  chia/rpc/util.py
Labels: Fixed, Exclude_Notes

#18829 CHIA-1716 Speedup get_header_blocks_in_range w.r.t. blocks with no transactions
  chia/consensus/blockchain.py
Labels: Changed, Cleanup

#18772 Await self_is_synced()
  chia/simulator/full_node_simulator.py
Labels: Changed, Exclude_Notes

#18821 Update Managed Files
  .github/workflows/dependency-review.yml
Labels: Changed

#18803 CHIA-1697: Add new flag to support recursively scanning and following links
  chia/_tests/plotting/test_plot_manager.py
  chia/plotting/util.py
  chia/util/initial-config.yaml
Labels: Added

#18812 [CHIA-1562] move signature validation into `run_block_generator()`
  chia/_tests/blockchain/blockchain_test_utils.py
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/clvm/test_puzzles.py
  chia/_tests/core/full_node/stores/test_coin_store.py
  chia/_tests/core/full_node/stores/test_full_node_store.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/full_node/test_subscriptions.py
  chia/_tests/core/test_db_conversion.py
  chia/_tests/core/test_db_validation.py
  chia/_tests/farmer_harvester/test_third_party_harvesters.py
  chia/_tests/wallet/conftest.py
  chia/consensus/block_body_validation.py
  chia/consensus/block_creation.py
  chia/consensus/blockchain.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
  chia/simulator/full_node_simulator.py
Labels: Changed, Exclude_Notes

#18800 explicitly collect api methods instead of later using getattr
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/server/test_api_protocol.py
  chia/_tests/core/server/test_server.py
  chia/_tests/farmer_harvester/test_third_party_harvesters.py
  chia/_tests/util/misc.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/_tests/wallet/test_wallet_node.py
  chia/data_layer/data_layer_api.py
  chia/farmer/farmer_api.py
  chia/full_node/full_node_api.py
  chia/harvester/harvester_api.py
  chia/introducer/introducer_api.py
  chia/seeder/crawler_api.py
  chia/server/api_protocol.py
  chia/server/ws_connection.py
  chia/timelord/timelord_api.py
  chia/util/api_decorators.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet_node_api.py
Labels: Changed, Cleanup

#18830 CHIA-1717 Handle index error on empty peers with peak in request_validate_wp
  chia/full_node/full_node.py
Labels: Changed, Cleanup

#18834 [CHIA-1703] ignore ephemeral spends in mempool superset rule
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/full_node/mempool_manager.py
Labels: ready_to_merge, Changed

#18842 the mempool thread pool should not set the process name
  chia/full_node/mempool_manager.py
Labels: Fixed

#18838 Add `Timelock` restriction
  chia/_tests/clvm/test_restrictions.py
  chia/wallet/puzzles/custody/restriction_puzzles/restrictions.py
  chia/wallet/puzzles/custody/restriction_puzzles/wrappers/__init__.py
  chia/wallet/puzzles/custody/restriction_puzzles/wrappers/timelock.clsp
  chia/wallet/puzzles/custody/restriction_puzzles/wrappers/timelock.clsp.hex
  chia/wallet/puzzles/deployed_puzzle_hashes.json
Labels: Added, coverage-diff

#18836 [CHIA-1655] simplify pre_validate_blocks_multiprocessing()
  chia/_tests/blockchain/blockchain_test_utils.py
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/farmer_harvester/test_third_party_harvesters.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
  chia/simulator/full_node_simulator.py
Labels: Changed, Exclude_Notes

#18832 [CHIA-1616] Add passkey member puzzle
  chia/_tests/clvm/test_member_puzzles.py
  chia/wallet/puzzles/custody/member_puzzles/member_puzzles.py
  chia/wallet/puzzles/custody/member_puzzles/passkey_member.clsp
  chia/wallet/puzzles/custody/member_puzzles/passkey_member.clsp.hex
  chia/wallet/puzzles/deployed_puzzle_hashes.json
Labels: Added, coverage-diff

#18790 CHIA-1685 Simplify return values for validate_block_body
  chia/_tests/wallet/conftest.py
  chia/consensus/block_body_validation.py
  chia/consensus/blockchain.py
Labels: Changed, Cleanup

#18809 CHIA-1645: Some daemon start cleanup
  chia/cmds/start_funcs.py
  chia/daemon/client.py
  chia/daemon/keychain_proxy.py
  chia/daemon/server.py
Labels: Fixed

#18824 [CHIA-1236] Sort offers in CLI by `RELEVANCE`
  chia/_tests/cmds/wallet/test_wallet.py
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
Labels: ready_to_merge, Changed

#18864 add arch emojis 🌀💪✳️
  .github/workflows/test-install-scripts.yml
  .github/workflows/test-single.yml
  .github/workflows/test.yml
  .github/workflows/upload-pypi-source.yml
Labels: Changed, CI

#18863 Secp256r1 Member Puzzle
  chia/_tests/clvm/test_member_puzzles.py
  chia/wallet/puzzles/custody/member_puzzles/member_puzzles.py
  chia/wallet/puzzles/custody/member_puzzles/secp256r1_member.clsp
  chia/wallet/puzzles/custody/member_puzzles/secp256r1_member.clsp.hex
  chia/wallet/puzzles/deployed_puzzle_hashes.json
Labels: Added

#18840 CHIA-1734 Annotate spend_bundles as a sequence in WalletSpendBundle's aggregate
  chia/wallet/wallet_spend_bundle.py
Labels: Changed, Cleanup

#18849 check network errors and their `.__cause__` for expected error types
  chia/server/ws_connection.py
Labels: Changed

#18870 Add SECP256K1 Member Puzzle
  chia/_tests/clvm/test_member_puzzles.py
  chia/wallet/puzzles/custody/member_puzzles/member_puzzles.py
  chia/wallet/puzzles/custody/member_puzzles/secp256k1_member.clsp
  chia/wallet/puzzles/custody/member_puzzles/secp256k1_member.clsp.hex
  chia/wallet/puzzles/deployed_puzzle_hashes.json
Labels: Added, coverage-diff

#18868 use the vars for the test parameters too
  chia/_tests/core/mempool/test_mempool_manager.py
Labels: Changed, Exclude_Notes

#18879 save tasks for TX processing
  chia/full_node/full_node.py
Labels: Fixed, coverage-diff

#18877 Fix a few chialisp bugs
  chia/_tests/clvm/test_restrictions.py
  chia/wallet/puzzles/custody/restriction_puzzles/enforce_dpuz_wrappers.clsp
  chia/wallet/puzzles/custody/restriction_puzzles/enforce_dpuz_wrappers.clsp.hex
  chia/wallet/puzzles/custody/restriction_puzzles/wrappers/timelock.clsp
  chia/wallet/puzzles/custody/restriction_puzzles/wrappers/timelock.clsp.hex
  chia/wallet/puzzles/deployed_puzzle_hashes.json
Labels: clvm, Fixed

#18882 If 0 peers to crawl, sleep before trying to crawl again
  chia/seeder/crawler.py
Labels: Changed

#18866 `# TODO: stop dropping tasks on the floor`
  chia/_tests/core/full_node/test_full_node.py
  chia/daemon/client.py
  chia/daemon/server.py
  chia/farmer/farmer.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/rpc/rpc_server.py
  chia/seeder/dns_server.py
  chia/server/server.py
  chia/server/ws_connection.py
  chia/wallet/wallet_node.py
Labels: Changed, Exclude_Notes

#18884 Add a Singleton Member puzzle for multisig drivers
  chia/_tests/clvm/test_member_puzzles.py
  chia/wallet/puzzles/custody/member_puzzles/member_puzzles.py
  chia/wallet/puzzles/custody/member_puzzles/singleton_member.clsp
  chia/wallet/puzzles/custody/member_puzzles/singleton_member.clsp.hex
  chia/wallet/puzzles/deployed_puzzle_hashes.json
Labels: Added

#18865 [CHIA-1720] Add a restriction mimicking vault recovery
  chia/_tests/clvm/puzzles/__init__.py
  chia/_tests/clvm/puzzles/conditions_banned.clsp
  chia/_tests/clvm/puzzles/conditions_banned.clsp.hex
  chia/_tests/clvm/puzzles/self_destruct.clsp
  chia/_tests/clvm/puzzles/self_destruct.clsp.hex
  chia/_tests/clvm/test_custody_architecture.py
  chia/_tests/clvm/test_restrictions.py
  chia/wallet/puzzles/custody/custody_architecture.py
  chia/wallet/puzzles/custody/restriction_puzzles/restrictions.py
  chia/wallet/puzzles/custody/restriction_puzzles/wrappers/force_1_of_2_w_restricted_variable.clsp
  chia/wallet/puzzles/custody/restriction_puzzles/wrappers/force_1_of_2_w_restricted_variable.clsp.hex
  chia/wallet/puzzles/deployed_puzzle_hashes.json
Labels: clvm, Added, coverage-diff

#18887 [CHIA-1696] Show an `INCOMING_TX` for pool reward claims
  chia/_tests/pools/test_pool_rpc.py
  chia/pools/pool_wallet.py
Labels: ready_to_merge, Fixed

#18898 Add a Fixed Puzzle Member which only approves the curried in puzzlehash
  chia/_tests/clvm/test_member_puzzles.py
  chia/wallet/puzzles/custody/member_puzzles/fixed_puzzle_member.clsp
  chia/wallet/puzzles/custody/member_puzzles/fixed_puzzle_member.clsp.hex
  chia/wallet/puzzles/custody/member_puzzles/member_puzzles.py
  chia/wallet/puzzles/deployed_puzzle_hashes.json
Labels: Added

#18886 [CHIA-1722] Add a version of a passkey puzzle that only asserts puzzle hash
  chia/_tests/clvm/test_member_puzzles.py
  chia/wallet/puzzles/custody/member_puzzles/member_puzzles.py
  chia/wallet/puzzles/custody/member_puzzles/passkey_member_puzzle_assert.clsp
  chia/wallet/puzzles/custody/member_puzzles/passkey_member_puzzle_assert.clsp.hex
  chia/wallet/puzzles/deployed_puzzle_hashes.json
Labels: Added

#18818 CHIA-1709 Pass a ValidationState to validate_unfinished_block_header
  chia/consensus/block_header_validation.py
  chia/consensus/blockchain.py
Labels: Changed, Cleanup

#18839 move `get_name_puzzle_conditions()` into test utils
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/clvm/benchmark_costs.py
  chia/_tests/clvm/coin_store.py
  chia/_tests/core/full_node/stores/test_coin_store.py
  chia/_tests/core/full_node/test_subscriptions.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_item_queries.py
  chia/_tests/core/test_cost_calculation.py
  chia/_tests/generator/test_rom.py
  chia/_tests/util/generator_tools_testing.py
  chia/_tests/util/get_name_puzzle_conditions.py
  chia/_tests/wallet/cat_wallet/test_trades.py
  chia/full_node/mempool_check_conditions.py
Labels: Changed, Tests, Exclude_Notes

#18873 fix the rollback of fork_info when validating a block fails
  chia/consensus/blockchain.py
  chia/full_node/full_node.py
Labels: Fixed

#18890 Add support for a static list of peers to always have available in the dns_server
  chia/_tests/core/test_seeder.py
  chia/seeder/dns_server.py
  chia/util/initial-config.yaml
Labels: Added

#18899 enable ruff flake8 async
  chia/_tests/core/server/flood.py
  chia/_tests/core/server/serve.py
  chia/_tests/core/server/test_loop.py
  chia/daemon/server.py
  chia/farmer/farmer.py
  chia/plot_sync/sender.py
  chia/seeder/dns_server.py
  chia/server/chia_policy.py
  chia/simulator/setup_services.py
  ruff.toml
Labels: Added, Exclude_Notes

#18908 flake8 implicit str concat
  chia/_tests/core/cmds/test_keys.py
  chia/cmds/wallet_funcs.py
  chia/full_node/block_store.py
  chia/full_node/full_node.py
  chia/timelord/timelord_api.py
  chia/wallet/trading/trade_store.py
  ruff.toml
Labels: Changed, Exclude_Notes

#18871 less set
  chia/_tests/core/test_full_node_rpc.py
Labels: Changed, Exclude_Notes

#18894 improve sync timeouts by being more conservative the fewer peers we have
  chia/full_node/full_node.py
Labels: Changed

#18903 more use of `RpcClient.create_as_context()`
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/core/test_full_node_rpc.py
  chia/_tests/wallet/dao_wallet/test_dao_wallets.py
  chia/_tests/wallet/nft_wallet/test_nft_bulk_mint.py
  chia/_tests/wallet/rpc/test_dl_wallet_rpc.py
  chia/cmds/cmds_util.py
Labels: Changed, Exclude_Notes

#18905 put `None` at the end in `Union`s - incoming RUF036
  chia/_tests/core/data_layer/util.py
  chia/server/chia_policy.py
  chia/simulator/full_node_simulator.py
  chia/util/streamable.py
  chia/wallet/nft_wallet/nft_puzzles.py
Labels: Changed, Exclude_Notes

#18907 improve logging of rate limits
  chia/_tests/core/server/test_dos.py
  chia/_tests/core/server/test_rate_limits.py
  chia/server/rate_limits.py
  chia/server/ws_connection.py
Labels: Changed

#18913 enable flake8-tidy-imports
  chia/_tests/clvm/test_puzzles.py
  chia/_tests/core/full_node/test_conditions.py
  chia/_tests/core/test_cost_calculation.py
  chia/cmds/coins.py
  chia/cmds/dao.py
  chia/cmds/farm.py
  chia/cmds/init.py
  chia/cmds/keys.py
  chia/cmds/netspace.py
  chia/cmds/passphrase.py
  chia/cmds/plotnft.py
  chia/cmds/start.py
  chia/cmds/wallet.py
  chia/consensus/default_constants.py
  chia/server/start_service.py
  chia/types/blockchain_format/program.py
  chia/types/spend_bundle.py
  chia/wallet/puzzles/p2_conditions.py
  chia/wallet/puzzles/p2_delegated_conditions.py
  chia/wallet/puzzles/p2_delegated_puzzle.py
  chia/wallet/puzzles/p2_delegated_puzzle_or_hidden_puzzle.py
  chia/wallet/puzzles/p2_m_of_n_delegate_direct.py
  chia/wallet/puzzles/p2_puzzle_hash.py
  ruff.toml
Labels: Changed, Exclude_Notes

#18918 skip simulator terminates on signal test for now
  chia/_tests/core/services/test_services.py
Labels: Changed, Tests

#18920 Update systemd templates to check if RPCs are up by using the chia rpc commands instead of nc
  build_scripts/assets/systemd/chia-daemon@.service
  build_scripts/assets/systemd/chia-wallet@.service
Labels: Fixed

#18921 adjust cmd class help parameters
  chia/_tests/cmds/test_cmd_framework.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/cmds/cmd_classes.py
  chia/cmds/signer.py
Labels: Changed, Exclude_Notes

#18897 [CHIA-1773] Add better `reuse_puzhash` checking to `WalletTestFramework`
  chia/_tests/environments/wallet.py
  chia/_tests/wallet/conftest.py
  chia/_tests/wallet/did_wallet/test_did.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/vc_wallet/test_vc_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/puzzles/tails.py
  chia/wallet/wallet_puzzle_store.py
  chia/wallet/wallet_state_manager.py
Labels: Changed, coverage-diff

#18925 [CHIA-1830] in deep-reorg tests, ensure the resulting coin set is correct
  chia/_tests/core/full_node/test_full_node.py
Labels: ready_to_merge, Changed, Tests

#18927 show cli defaults by default
  chia/cmds/chia.py
Labels: Changed

#18911 squash emoji-suppressing typo
  .github/workflows/test-single.yml
Labels: Fixed, CI

#18906 Optimize DL benchmark.
  chia/data_layer/data_layer_errors.py
  chia/data_layer/data_store.py
  chia/data_layer/util/benchmark.py
Labels: Changed, coverage-diff, DataLayer

#18933 Fix DL index
  chia/data_layer/data_store.py
Labels: Fixed, DataLayer

#18915 Fix DL migration
  chia/data_layer/data_store.py
Labels: Fixed, DataLayer

#18939 `**/*.lock linguist-generated=false`
  .gitattributes
Labels: Changed, CI

#18949 Optimize DL query.
  chia/data_layer/data_store.py
Labels: Fixed, DataLayer
