Repository Chia-Network/chia-blockchain, pull requests merged in 2024-02, with the labels that each got.

#17446 Annotate test_wallet_sync.py
  mypy-exclusions.txt
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#17449 Remove no longer needed TestTaproot class
  tests/wallet/test_taproot.py
Labels: Changed, Cleanup

#17451 Augment conditions_dict_for_solution and conditions_for_solution to accept both types of programs
  chia/full_node/mempool_check_conditions.py
  chia/simulator/wallet_tools.py
  chia/util/condition_tools.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/sign_coin_spends.py
  chia/wallet/wallet_singleton_store.py
  tests/util/key_tool.py
  tests/wallet/clawback/test_clawback_lifecycle.py
  tests/wallet/did_wallet/test_did.py
Labels: Changed, Cleanup

#17452 Don't convert serialized programs to programs before passing them to get_inner_puzzle_from_singleton
  chia/rpc/wallet_rpc_api.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/wallet_state_manager.py
Labels: Changed, Cleanup

#17454 Convert a get_name() call and some asserts on string and bytes32 values into actual checks in test_dao_creation
  tests/wallet/dao_wallet/test_dao_wallets.py
Labels: Changed, Cleanup

#17302 Improve timelord skip peak logic.
  chia/timelord/timelord_api.py
Labels: Fixed

#17463 Speedup test_bad_peak_mismatch
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#17462 Speedup test_basic_sync_wallet
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#17461 Speedup test_long_sync_wallet
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#17453 DAOWallet creation functions do not return optional values
  tests/wallet/dao_wallet/test_dao_wallets.py
Labels: Changed, Cleanup

#17444 Fix negative plot sync durations not crashing the harvester
  chia/plot_sync/sender.py
  tests/plot_sync/test_sender.py
Labels: Fixed

#17411 Daemon: use msg queue and specific task for handling status messages
  chia/daemon/server.py
  tests/core/daemon/test_daemon.py
Labels: Changed, Cleanup, Exclude_Notes

#17480 move `RecordingWebServer` to `tests.util.misc`
  tests/conftest.py
  tests/core/data_layer/test_data_layer.py
  tests/util/misc.py
  tests/util/test_misc.py
Labels: Changed, Tests

#16883 Wallet Signer Protocol
  build_scripts/check_dependency_artifacts.py
  chia/util/streamable.py
  chia/wallet/signer_protocol.py
  chia/wallet/util/clvm_streamable.py
  setup.py
  tests/wallet/test_signer_protocol.py
Labels: Added, vault

#16845 Add support for generating and verifying DataLayer Proofs of Inclusions
  chia/cmds/data.py
  chia/cmds/data_funcs.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_errors.py
  chia/data_layer/data_layer_util.py
  chia/rpc/data_layer_rpc_api.py
  chia/rpc/data_layer_rpc_client.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  tests/core/data_layer/test_data_rpc.py
  tests/wallet/rpc/test_dl_wallet_rpc.py
Labels: Added, DataLayer

#17466 Speedup test_request_block_headers
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#17467 Speedup test_long_sync_untrusted_break
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#17468 Speedup test_wallet_reorg_sync
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#17469 Speedup test_short_batch_sync_wallet
  tests/wallet/sync/test_wallet_sync.py
Labels: ready_to_merge, Changed, Cleanup

#17470 Speedup test_request_block_headers_rejected
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#17471 Speedup test_subscribe_for_hint_long_sync
  tests/wallet/simple_sync/test_simple_sync_protocol.py
Labels: Changed, Cleanup

#17472 Speedup test_wallet_blockchain
  tests/wallet/test_wallet_blockchain.py
Labels: Changed, Cleanup

#17473 Speedup test_get_balance
  tests/wallet/test_wallet_node.py
Labels: Changed, Cleanup

#17493 Speedup test_large_trade_record_query
  tests/wallet/test_wallet_trade_store.py
Labels: Changed, Cleanup

#17492 Speedup TradeStore's _get_new_trade_records_from_old
  chia/wallet/trading/trade_store.py
Labels: Changed, Cleanup

#17491 Speedup TradeStore's add_trade_record
  chia/wallet/trading/trade_store.py
Labels: Changed, Cleanup

#17481 Rate Limit Adjustment for RequestSignedValues
  chia/server/rate_limit_numbers.py
Labels: Changed

#17489 Set 10 as the maximum number of items that get skipped if they won't fit in the block we're trying to create
  chia/full_node/mempool.py
Labels: Changed, Cleanup

#17465 Speedup test_almost_recent
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#17458 Unify transaction pushing
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/simulator/full_node_simulator.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
  tests/core/full_node/test_full_node.py
  tests/core/full_node/test_transactions.py
  tests/simulation/test_simulation.py
  tests/simulation/test_simulator.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/dao_wallet/test_dao_wallets.py
  tests/wallet/db_wallet/test_dl_offers.py
  tests/wallet/db_wallet/test_dl_wallet.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_notifications.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_node.py
  tests/wallet/test_wallet_retry.py
  tests/wallet/vc_wallet/test_vc_wallet.py
Labels: ready_to_merge, Changed

#17495 Remove no longer used dataclasses import
  chia/wallet/trading/trade_store.py
Labels: Changed, Cleanup

#17494 checkpoint: into main from release/2.2.0 @ 63417e765aaff91fb30485577f86a4af55aba029
  chia/cmds/data.py
  chia/cmds/data_funcs.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_errors.py
  chia/data_layer/data_layer_util.py
  chia/rpc/data_layer_rpc_api.py
  chia/rpc/data_layer_rpc_client.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  tests/core/data_layer/test_data_rpc.py
  tests/wallet/rpc/test_dl_wallet_rpc.py
Labels: checkpoint_merge, Changed

#16831 add time out assert data collection and presentation
  .github/CODEOWNERS
  .github/workflows/benchmarks.yml
  .github/workflows/test.yml
  chia/util/misc.py
  tests/conftest.py
  tests/ether.py
  tests/process_benchmarks.py
  tests/process_junit.py
  tests/util/misc.py
  tests/util/time_out_assert.py
Labels: Changed, Tests

#17508 Fix flaky trade test
  tests/wallet/cat_wallet/test_trades.py
Labels: ready_to_merge, Fixed, Exclude_Notes

#17509 Fix flaky DID test
  tests/wallet/did_wallet/test_did.py
Labels: ready_to_merge, Fixed, Exclude_Notes

#17510 allow non-ssl rpc clients (2)
  chia/cmds/cmds_util.py
  chia/rpc/rpc_client.py
  tests/cmds/cmd_test_utils.py
  tests/cmds/test_cmds_util.py
  tests/rpc/__init__.py
  tests/rpc/test_rpc_client.py
Labels: Changed

#17512 Instruct the use of coin_puzzle_hash index to get_unspent_lineage_info_for_puzzle_hash
  chia/full_node/coin_store.py
Labels: ready_to_merge, Changed, Cleanup

#17496 catchup: long_lived/vault from main @ 07fcecd
  build_scripts/build_linux_rpm-2-installer.sh
  chia/consensus/blockchain.py
  chia/daemon/server.py
  chia/farmer/farmer.py
  chia/full_node/mempool_check_conditions.py
  chia/harvester/harvester.py
  chia/plot_sync/sender.py
  chia/plotting/check_plots.py
  chia/pools/pool_config.py
  chia/rpc/wallet_rpc_api.py
  chia/simulator/wallet_tools.py
  chia/timelord/timelord_api.py
  chia/util/beta_metrics.py
  chia/util/condition_tools.py
  chia/util/misc.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/dao_wallet/dao_info.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/lineage_proof.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/puzzles/p2_delegated_conditions.py
  chia/wallet/puzzles/p2_puzzle_hash.py
  chia/wallet/sign_coin_spends.py
  chia/wallet/trading/offer.py
  chia/wallet/trading/trade_store.py
  chia/wallet/wallet_singleton_store.py
  chia/wallet/wallet_state_manager.py
  mypy-exclusions.txt
  setup.py
  tests/blockchain/test_blockchain.py
  tests/conftest.py
  tests/core/daemon/test_daemon.py
  tests/core/data_layer/test_data_layer.py
  tests/core/test_cost_calculation.py
  tests/farmer_harvester/test_farmer.py
  tests/plot_sync/test_sender.py
  tests/util/key_tool.py
  tests/util/misc.py
  tests/util/test_misc.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/clawback/test_clawback_lifecycle.py
  tests/wallet/dao_wallet/test_dao_wallets.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_taproot.py
  tests/wallet/test_wallet_blockchain.py
  tests/wallet/test_wallet_node.py
  tests/wallet/test_wallet_trade_store.py
Labels: Changed, Exclude_Notes, coverage-diff, vault

#17505 Bump chia rs 0.5.2
  benchmarks/mempool-long-lived.py
  chia/consensus/constants.py
  chia/full_node/mempool_manager.py
  chia/full_node/weight_proof.py
  chia/types/eligible_coin_spends.py
  chia/types/spend_bundle_conditions.py
  chia/util/condition_tools.py
  chia/util/generator_tools.py
  chia/wallet/cat_wallet/dao_cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
  setup.py
  tests/core/consensus/test_block_creation.py
  tests/core/custom_types/test_coin.py
  tests/core/custom_types/test_spend_bundle.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/test_hint_management.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_manager.py
  tests/core/mempool/test_singleton_fast_forward.py
  tests/core/test_cost_calculation.py
  tests/farmer_harvester/test_third_party_harvesters.py
  tests/util/test_condition_tools.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/cat_wallet/test_offer_lifecycle.py
  tests/wallet/dao_wallet/test_dao_clvm.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tests/wallet/test_debug_spend_bundle.py
  tests/wallet/test_sign_coin_spends.py
  tests/wallet/test_singleton_store.py
  tests/wallet/test_wallet_node.py
  tests/wallet/test_wallet_state_manager.py
  tests/wallet/test_wallet_utils.py
Labels: ready_to_merge, Changed

#17506 Return TXs from CATWallet and Offer creation
  chia/data_layer/data_layer_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/db_wallet/test_dl_offers.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Changed

#17518 Update the version formatting used for the cli .deb
  build_scripts/assets/deb/control.j2
  build_scripts/build_linux_deb-2-installer.sh
Labels: Fixed, Exclude_Notes

#17521 undo some unnecessary int type casts
  chia/consensus/block_body_validation.py
  chia/consensus/block_header_validation.py
  chia/consensus/full_block_to_block_record.py
  chia/consensus/make_sub_epoch_summary.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/weight_proof.py
  chia/simulator/block_tools.py
  chia/timelord/iters_from_block.py
  chia/timelord/timelord.py
  chia/timelord/timelord_state.py
  chia/types/full_block.py
  chia/types/header_block.py
  chia/types/unfinished_block.py
  chia/types/unfinished_header_block.py
  chia/wallet/util/peer_request_cache.py
  chia/wallet/wallet_blockchain.py
  chia/wallet/wallet_node.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/stores/test_full_node_store.py
Labels: ready_to_merge, Changed

#17498 checkpoint: into main from release/2.2.0 @ cbf3d7f252e93dcb8f02c2184931f257dce4656a
  chia/full_node/mempool_manager.py
  tests/core/mempool/test_mempool_manager.py
Labels: checkpoint_merge, Changed

#17537 checkpoint: into main from release/2.2.0 @ 35ab75309e901ad57e54b6256923f831c577d215
  chia/full_node/mempool.py
Labels: checkpoint_merge, Changed

#17529 Speedup WalletTransactionStore's _get_new_tx_records_from_old
  chia/wallet/wallet_transaction_store.py
Labels: Changed, Cleanup

#17539 checkpoint: into main from release/2.2.0 @ 7747a0ddd1ca11085ed7cf67e2e2ea10e93df8a9
  tests/wallet/cat_wallet/test_trades.py
Labels: checkpoint_merge, Changed

#17533 Fix a typo in primary key creation in SpendSim's block_data
  chia/clvm/spend_sim.py
Labels: Changed, Cleanup

#17531 Remove redundant index on primary key in trade_records
  chia/wallet/trading/trade_store.py
Labels: Changed, Cleanup

#17538 use click.Path for make_offer command filename
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  tests/cmds/wallet/test_wallet.py
Labels: Fixed

#16895 Implement Wallet Signer Protocol in Chia Wallet
  chia/rpc/util.py
  chia/rpc/wallet_request_types.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/simulator/full_node_simulator.py
  chia/util/initial-config.yaml
  chia/wallet/trading/trade_store.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_signer_protocol.py
Labels: Added, vault

#17535 Add missing index on transaction_record's trade_id for get_transactions_by_trade_id, sort the others and remove a redundant one
  chia/wallet/wallet_transaction_store.py
Labels: Changed, Cleanup

#17534 Remove redundant index on primary key in key_val_store
  chia/wallet/key_val_store.py
Labels: Changed, Cleanup

#17528 Speedup WalletTransactionStore's add_transaction_record
  chia/wallet/wallet_transaction_store.py
Labels: Changed, Cleanup

#17520 Augment match_dl_singleton to accept both types of puzzles
  chia/data_layer/data_layer_wallet.py
  chia/wallet/db_wallet/db_wallet_puzzles.py
Labels: Changed, Cleanup

#17546 add forced ruby dotenv version for arm64 installer build
  build_scripts/build_linux_deb-2-installer.sh
Labels: Fixed, CI, Exclude_Notes

#17553 Kyle's add forced ruby dotenv version for arm64 installer build
  build_scripts/build_linux_deb-2-installer.sh
Labels: Changed, Cleanup

#17507 Fix flaky trade test
  tests/wallet/cat_wallet/test_trades.py
Labels: Fixed, Exclude_Notes

#17347 DL RPC pagination.
  chia/cmds/data.py
  chia/cmds/data_funcs.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_util.py
  chia/data_layer/data_store.py
  chia/rpc/data_layer_rpc_api.py
  chia/rpc/data_layer_rpc_client.py
  tests/core/data_layer/test_data_rpc.py
  tests/core/data_layer/test_data_store.py
Labels: Added, DataLayer

#17543 checkpoint: into main from release/2.2.0 @ fce56b945752d426f75665e12806669358305ffd
  tests/wallet/did_wallet/test_did.py
Labels: checkpoint_merge, Changed

#17541 Remove no longer needed index_for_puzzle_hash_and_wallet
  chia/wallet/wallet_puzzle_store.py
Labels: Changed, Cleanup

#17532 Add indices on used and hardened for derivation_paths, sort the others and remove a redundant one
  chia/wallet/wallet_puzzle_store.py
Labels: Changed, Cleanup

#17519 Augment match_clawback_puzzle to accept both types of programs
  chia/wallet/puzzles/clawback/drivers.py
Labels: Changed, Cleanup

#17515 Use Datalayer banning logic for HTTP download failures
  chia/data_layer/download_data.py
  tests/core/data_layer/test_data_store.py
Labels: Fixed

#17435 Send RewardChainBlockUnfinished to third-party harvesters
  chia/farmer/farmer_api.py
  chia/full_node/full_node_api.py
  chia/protocols/farmer_protocol.py
  chia/protocols/harvester_protocol.py
  chia/server/rate_limit_numbers.py
  tests/farmer_harvester/test_third_party_harvesters.py
  tests/util/network_protocol_data.py
  tests/util/protocol_messages_bytes-v1.0
  tests/util/protocol_messages_json.py
Labels: Farming, harvester, Changed

#17375 Introduce satisfies_hint to check objects against type hints, use it in from_kwargs and fix all the incorrect and missing cases
  chia/util/misc.py
  tests/util/test_misc.py
  tests/wallet/test_singleton_lifecycle_fast.py
Labels: Changed, Cleanup

#16000 Remove all install.sh code that installs python and leave it to the user
  .github/workflows/test-install-scripts.yml
  install.sh
Labels: Changed

#17561 remove old unhashable special case in Streamable
  chia/types/blockchain_format/program.py
  chia/util/streamable.py
Labels: ready_to_merge, Changed

#17559 bump chia_rs
  setup.py
Labels: ready_to_merge, Fixed

#17527 Fix DID update metadata bug #17412
  chia/wallet/did_wallet/did_wallet.py
  tests/wallet/did_wallet/test_did.py
Labels: Fixed

#17523 Handle when xch_target_address in config doesn't decode correctly
  chia/rpc/wallet_rpc_api.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Fixed

#17568 Add testnet11 constants to config if missing when configuring to run on testnet
  chia/cmds/configure.py
Labels: Added

#17490 Hint support for SpendSim
  chia/clvm/spend_sim.py
  tests/clvm/test_spend_sim.py
Labels: Added

#17536 avoid datalayer manage data loop delay for self subscriptions
  chia/data_layer/data_layer.py
Labels: Changed

#17560 optimize `validate_removals()`
  chia/wallet/util/wallet_sync_utils.py
  mypy-exclusions.txt
  tests/core/test_merkle_set.py
Labels: ready_to_merge, Changed

#17566 remove config todo comment from a long time ago
  chia/util/initial-config.yaml
Labels: Changed, Cleanup, Exclude_Notes

#17558 checkpoint: into main from release/2.2.0 @ 654d32772931851ba2814b13c705518c27b850a7
  chia/full_node/coin_store.py
Labels: checkpoint_merge, Changed

#17575 `clvm_tools==0.4.8`
  chia/rpc/wallet_rpc_api.py
  chia/wallet/puzzle_drivers.py
  chia/wallet/puzzles/prefarm/make_prefarm_ph.py
  chia/wallet/puzzles/prefarm/spend_prefarm.py
  setup.py
  tests/core/full_node/test_conditions.py
  tests/core/test_cost_calculation.py
  tests/core/test_program.py
  tests/core/util/test_streamable.py
  tests/generator/test_compression.py
  tests/generator/test_rom.py
  tests/wallet/nft_wallet/test_ownership_outer_puzzle.py
  tests/wallet/test_singleton.py
  tests/wallet/test_singleton_lifecycle_fast.py
Labels: Changed

#16896 Remove signing from wallet
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/util.py
  chia/rpc/wallet_rpc_api.py
  chia/simulator/full_node_simulator.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/cat_wallet/dao_cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/puzzles/tails.py
  chia/wallet/sign_coin_spends.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
  tests/core/data_layer/test_data_rpc.py
  tests/core/full_node/test_full_node.py
  tests/core/full_node/test_transactions.py
  tests/core/mempool/test_mempool_manager.py
  tests/core/mempool/test_mempool_performance.py
  tests/simulation/test_simulation.py
  tests/simulation/test_simulator.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/dao_wallet/test_dao_wallets.py
  tests/wallet/db_wallet/test_dl_offers.py
  tests/wallet/db_wallet/test_dl_wallet.py
  tests/wallet/did_wallet/test_did.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_bulk_mint.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_notifications.py
  tests/wallet/test_sign_coin_spends.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_node.py
  tests/wallet/test_wallet_retry.py
  tests/wallet/vc_wallet/test_vc_wallet.py
Labels: Changed, vault

#17582 test linux installers on arm
  .github/workflows/test-install-scripts.yml
Labels: Added, CI

#17517 remove support for migrating peers from legacy file format
  chia/full_node/full_node.py
  chia/server/address_manager_sqlite_store.py
  chia/server/node_discovery.py
  chia/server/peer_store_resolver.py
  chia/util/config.py
  chia/wallet/wallet_node.py
  mypy-exclusions.txt
  tests/core/full_node/test_peer_store_resolver.py
  tests/core/server/test_node_discovery.py
Labels: Changed

#17525 transition FullBlock and BlockRecord to rust
  chia/cmds/show_funcs.py
  chia/consensus/block_record.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool_manager.py
  chia/full_node/weight_proof.py
  chia/types/full_block.py
  chia/types/unfinished_block.py
  tests/core/full_node/stores/test_block_store.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/full_node/test_full_node.py
  tests/core/full_node/test_performance.py
  tests/core/large_block.py
  tests/util/blockchain.py
  tools/analyze-chain.py
  tools/test_full_sync.py
Labels: Changed

#17574 checkpoint: into main from release/2.2.0 @ 0e6e2b6ff0dae08383e3c1b5cb05dc4933c03821
  build_scripts/assets/deb/control.j2
  build_scripts/build_linux_deb-2-installer.sh
Labels: checkpoint_merge, Changed

#17592 Set unique peer filenames when swapping to/from testnets
  chia/cmds/configure.py
Labels: Changed

#17544 Extract RPC push logic into `@tx_endpoint` wrapper
  chia/rpc/util.py
  chia/rpc/wallet_rpc_api.py
Labels: ready_to_merge, Changed, Exclude_Notes

#17545 remove forced ruby public_suffix version for arm64 installer build
  build_scripts/build_linux_deb-2-installer.sh
Labels: Fixed, CI, Exclude_Notes

#17460 cleaner cli output for rpc client fetch errors
  chia/cmds/cmds_util.py
  chia/rpc/rpc_client.py
  tests/cmds/test_cmds_util.py
  tests/rpc/test_rpc_client.py
Labels: Changed

#17414 DL multiple batch updates.
  chia/cmds/data.py
  chia/cmds/data_funcs.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_util.py
  chia/data_layer/data_store.py
  chia/rpc/data_layer_rpc_api.py
  chia/rpc/data_layer_rpc_client.py
  tests/core/data_layer/test_data_rpc.py
  tests/core/data_layer/test_data_store.py
Labels: ready_to_merge, Added, DataLayer

#17607 increase arm debian publish timeout
  .github/workflows/build-linux-installer-deb.yml
Labels: Fixed, CI

#16967 Allow public-key-only entries in keyring
  chia/cmds/keys_funcs.py
  chia/cmds/sim_funcs.py
  chia/daemon/keychain_proxy.py
  chia/daemon/keychain_server.py
  chia/daemon/server.py
  chia/rpc/wallet_rpc_api.py
  chia/simulator/block_tools.py
  chia/simulator/setup_services.py
  chia/simulator/simulator_test_tools.py
  chia/util/keychain.py
  chia/wallet/derive_keys.py
  setup.py
  tests/core/cmds/test_keys.py
  tests/core/daemon/test_daemon.py
  tests/core/daemon/test_keychain_proxy.py
  tests/core/data_layer/test_data_rpc.py
  tests/core/util/test_keychain.py
  tests/farmer_harvester/test_farmer_harvester.py
  tests/wallet/test_wallet_node.py
Labels: Changed, vault

#17550 use `QueuedAsyncPool` for `DataLayer.periodically_manage_data()` subscription handling
  chia/data_layer/data_layer.py
  chia/util/async_pool.py
  tests/util/test_async_pool.py
Labels: Changed

#17613 Updated License
  LICENSE
Labels: Changed, Exclude_Notes

#17611 Update CHANGELOG.md
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#17618 Update Managed Files
  .github/workflows/dependency-review.yml
Labels: Changed, CI, Exclude_Notes

#17617 Update code to find packaged plotters in _internal directory
  chia/plotters/bladebit.py
  chia/plotters/madmax.py
Labels: Fixed

#16897 Make WalletStateManager.private_key optional
  chia/cmds/keys_funcs.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/wallet.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
  tests/core/cmds/test_keys.py
  tests/pools/test_pool_rpc.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_sign_coin_spends.py
  tests/wallet/test_signer_protocol.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_node.py
  tests/wallet/test_wallet_state_manager.py
Labels: Changed, vault
