Repository Chia-Network/chia-blockchain, pull requests merged in 2024-10, with the labels that each got.

#18647 CHIA-1525 Make PreValidationResult take SpendBundleConditions instead of NPCResult
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/core/full_node/test_full_node.py
  chia/consensus/block_body_validation.py
  chia/consensus/blockchain.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
Labels: Changed, Cleanup

#18662 Fix DID balance reporting, and port DID tests to WalletTestFramwork
  chia/_tests/wallet/did_wallet/test_did.py
  chia/_tests/wallet/nft_wallet/test_nft_wallet.py
  chia/_tests/wallet/vc_wallet/test_vc_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/wallet_state_manager.py
Labels: Fixed

#18661 CHIA-1554 Annotate test_taproot.py
  chia/_tests/wallet/test_taproot.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#18637 CHIA-1472 Augment get_mirror_info to accept both types of programs
  chia/data_layer/data_layer_wallet.py
  chia/wallet/db_wallet/db_wallet_puzzles.py
Labels: Changed, Cleanup

#18651 [CHIA-1308] Port wallet node RPC endpoints to `@marshal` decorator
  chia/_tests/cmds/cmd_test_utils.py
  chia/_tests/cmds/wallet/test_coins.py
  chia/_tests/cmds/wallet/test_wallet.py
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/test_wallet_state_manager.py
  chia/cmds/cmds_util.py
  chia/cmds/coin_funcs.py
  chia/cmds/plotnft_funcs.py
  chia/cmds/signer.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_request_types.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
Labels: Changed, Exclude_Notes

#18665 CHIA-1568: fix object has no attribute code errors
  chia/server/ws_connection.py
Labels: Fixed

#18669 CHIA-1570 Annotate generator_tools_testing.py
  chia/_tests/util/generator_tools_testing.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#18663 CHIA-1567: Update aiohttp to 3.10.4
  poetry.lock
  pyproject.toml
Labels: Changed

#18670 checkpoint: into main from release/2.4.4 @ b353a398fef5d04e0da45de8310e322aaddd6cef
  chia/_tests/core/data_layer/test_data_layer_util.py
Labels: checkpoint_merge, Changed

#18666 CHIA-1564 Simplify WalletSpendBundle class by leveraging some parent class methods
  chia/wallet/wallet_spend_bundle.py
Labels: Changed, Cleanup

#18660 simplify passing around difficulty, sub slot iterators and prev_ses_block
  chia/_tests/blockchain/blockchain_test_utils.py
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/farmer_harvester/test_third_party_harvesters.py
  chia/_tests/util/full_sync.py
  chia/_tests/util/misc.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
  chia/simulator/full_node_simulator.py
  chia/types/validation_state.py
  tools/test_full_sync.py
Labels: ready_to_merge, Changed, Cleanup

#18655 [CHIA-621] Add a configurable limit to the amount of DIDs that can be automatically added to the users wallet from transfer
  chia/_tests/wallet/did_wallet/test_did.py
  chia/rpc/wallet_rpc_api.py
  chia/util/initial-config.yaml
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/wallet_state_manager.py
Labels: Wallet, ready_to_merge, Changed

#18679 [CHIA-1569] Fix fee behavior with `chia wallet coins combine`
  chia/_tests/cmds/wallet/test_coins.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/cmds/coin_funcs.py
  chia/cmds/coins.py
  chia/rpc/wallet_rpc_api.py
Labels: Fixed

#18652 catchup: long_lived/vault from main @ b4137651b6b2107f88b4a83e64b7b2c918c5c3f3
  .github/workflows/build-macos-installers.yml
  .github/workflows/check_wheel_availability.yaml
  .github/workflows/pre-commit.yml
  .github/workflows/test-install-scripts.yml
  .github/workflows/test.yml
  .github/workflows/upload-pypi-source.yml
  chia/_tests/blockchain/blockchain_test_utils.py
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/clvm/test_program.py
  chia/_tests/cmds/test_cmd_framework.py
  chia/_tests/core/data_layer/test_data_store.py
  chia/_tests/core/full_node/test_conditions.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/environments/wallet.py
  chia/_tests/farmer_harvester/test_third_party_harvesters.py
  chia/_tests/wallet/nft_wallet/test_nft_wallet.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/_tests/wallet/test_wallet_interested_store.py
  chia/_tests/wallet/test_wallet_key_val_store.py
  chia/_tests/wallet/test_wallet_test_framework.py
  chia/_tests/wallet/vault/test_vault_wallet.py
  chia/cmds/cmds_util.py
  chia/consensus/block_body_validation.py
  chia/consensus/blockchain.py
  chia/consensus/multiprocess_validation.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_store.py
  chia/data_layer/download_data.py
  chia/full_node/full_node.py
  chia/full_node/mempool_manager.py
  chia/rpc/full_node_rpc_api.py
  chia/rpc/wallet_request_types.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/simulator/full_node_simulator.py
  chia/types/blockchain_format/program.py
  mypy-exclusions.txt
  poetry.lock
  pyproject.toml
Labels: Changed, Exclude_Notes, coverage-diff

#18682 CHIA-1602 Remove no longer needed TestNetwork class
  chia/_tests/util/test_network.py
Labels: Changed, Cleanup

#18678 CHIA-1593 Annotate test_cached_bls.py
  chia/_tests/core/util/test_cached_bls.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#18676 checkpoint: into main from release/2.4.4 @ 74536ba7813bbf91746ca95ab0065c8bbcb1f608
  chia/server/ws_connection.py
Labels: checkpoint_merge, Changed

#18684 checkpoint: into main from release/2.4.4 @ 0912c377e71c6ddc36f50c0d73688d503921452a
  poetry.lock
  pyproject.toml
Labels: checkpoint_merge, Changed

#18616 [CHIA-598] virtual project structure
  .pre-commit-config.yaml
  chia/_tests/tools/test_virtual_project.py
  chia/util/virtual_project_analysis.py
  virtual_project.yaml
Labels: ready_to_merge, Changed, CI, Tests

#18690 [CHIA-1619] Introduce a 1 of N optimization for multi sig drivers
  chia/_tests/clvm/test_custody_architecture.py
  chia/wallet/puzzles/custody/custody_architecture.py
  chia/wallet/puzzles/custody/optimization_puzzles/1_of_n.clsp
  chia/wallet/puzzles/custody/optimization_puzzles/1_of_n.clsp.hex
  chia/wallet/puzzles/custody/optimization_puzzles/__init__.py
  chia/wallet/puzzles/deployed_puzzle_hashes.json
Labels: clvm, Added

#18673 Fix install.sh upgrade issue
  install.sh
Labels: Fixed, community-pr

#18695 bump chia_rs dependency
  chia/_tests/core/full_node/test_generator_tools.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/fee_estimation/test_fee_estimation_integration.py
  chia/_tests/util/test_condition_tools.py
  chia/full_node/mempool_check_conditions.py
  poetry.lock
  pyproject.toml
  tools/analyze-chain.py
Labels: Changed

#18694 [CHIA-1622] Introduce an N of N optimization for multi sig drivers
  chia/wallet/puzzles/custody/custody_architecture.py
  chia/wallet/puzzles/custody/optimization_puzzles/n_of_n.clsp
  chia/wallet/puzzles/custody/optimization_puzzles/n_of_n.clsp.hex
  chia/wallet/puzzles/deployed_puzzle_hashes.json
Labels: clvm, Added

#18700 Update changelog for 2.4.4
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#18403 standalone merkle blob for datalayer
  chia/_tests/conftest.py
  chia/_tests/core/data_layer/test_merkle_blob.py
  chia/data_layer/util/merkle_blob.py
Labels: Added, DataLayer

#18709 Add support for `PuzzleWithRestrictions` with no MofN
  chia/_tests/clvm/test_custody_architecture.py
  chia/wallet/puzzles/custody/architecture_puzzles/delegated_puzzle_feeder.clsp
  chia/wallet/puzzles/custody/architecture_puzzles/delegated_puzzle_feeder.clsp.hex
  chia/wallet/puzzles/custody/architecture_puzzles/m_of_n.clsp
  chia/wallet/puzzles/custody/architecture_puzzles/m_of_n.clsp.hex
  chia/wallet/puzzles/custody/custody_architecture.py
  chia/wallet/puzzles/custody/optimization_puzzles/1_of_n.clsp
  chia/wallet/puzzles/custody/optimization_puzzles/1_of_n.clsp.hex
  chia/wallet/puzzles/custody/optimization_puzzles/n_of_n.clsp
  chia/wallet/puzzles/custody/optimization_puzzles/n_of_n.clsp.hex
  chia/wallet/puzzles/deployed_puzzle_hashes.json
Labels: Fixed

#18689 Require fewer arguments for `chia wallet coins split` in the CLI
  chia/_tests/cmds/wallet/test_coins.py
  chia/cmds/coin_funcs.py
  chia/cmds/coins.py
Labels: CLI, Changed

#18713 checkpoint: into main from release/2.4.4 @ ef11555e45c4222f1ac481479cda3d2f731ca523
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#18702 Add `combine_coins` Known Issue to changelog
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#18704 [CHIA-1635] Add default for `number_of_coins` in `CombineCoins`
  chia/rpc/wallet_request_types.py
Labels: Changed

#18699 [CHIA-1634] catchup: long_lived/vault from main @ d678131ded709e6264127984ae5fc12c6823cafa
  .pre-commit-config.yaml
  chia/_tests/blockchain/blockchain_test_utils.py
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/cmds/cmd_test_utils.py
  chia/_tests/cmds/wallet/test_coins.py
  chia/_tests/cmds/wallet/test_wallet.py
  chia/_tests/core/data_layer/test_data_layer_util.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/full_node/test_generator_tools.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/util/test_cached_bls.py
  chia/_tests/farmer_harvester/test_third_party_harvesters.py
  chia/_tests/fee_estimation/test_fee_estimation_integration.py
  chia/_tests/tools/test_virtual_project.py
  chia/_tests/util/full_sync.py
  chia/_tests/util/generator_tools_testing.py
  chia/_tests/util/misc.py
  chia/_tests/util/test_condition_tools.py
  chia/_tests/util/test_network.py
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/did_wallet/test_did.py
  chia/_tests/wallet/nft_wallet/test_nft_wallet.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/_tests/wallet/test_taproot.py
  chia/_tests/wallet/test_wallet_state_manager.py
  chia/_tests/wallet/vault/test_vault_wallet.py
  chia/_tests/wallet/vc_wallet/test_vc_wallet.py
  chia/cmds/cmds_util.py
  chia/cmds/coin_funcs.py
  chia/cmds/coins.py
  chia/cmds/plotnft_funcs.py
  chia/cmds/signer.py
  chia/cmds/wallet_funcs.py
  chia/consensus/block_body_validation.py
  chia/consensus/blockchain.py
  chia/consensus/multiprocess_validation.py
  chia/data_layer/data_layer_wallet.py
  chia/full_node/full_node.py
  chia/full_node/mempool_check_conditions.py
  chia/rpc/wallet_request_types.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/server/ws_connection.py
  chia/simulator/full_node_simulator.py
  chia/types/validation_state.py
  chia/util/initial-config.yaml
  chia/util/virtual_project_analysis.py
  chia/wallet/db_wallet/db_wallet_puzzles.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/wallet_spend_bundle.py
  chia/wallet/wallet_state_manager.py
  install.sh
  mypy-exclusions.txt
  poetry.lock
  pyproject.toml
  tools/analyze-chain.py
  tools/test_full_sync.py
  virtual_project.yaml
Labels: Changed, Exclude_Notes, coverage-diff

#18725 Fix bluebox shutdown
  chia/timelord/timelord.py
  chia/util/vdf_prover.py
  poetry.lock
  pyproject.toml
Labels: Fixed, coverage-diff

#18722 Fix members with restrictions inside of MofNs
  chia/_tests/clvm/test_custody_architecture.py
  chia/wallet/puzzles/custody/architecture_puzzles/restrictions.clsp
  chia/wallet/puzzles/custody/architecture_puzzles/restrictions.clsp.hex
  chia/wallet/puzzles/custody/custody_architecture.py
  chia/wallet/puzzles/deployed_puzzle_hashes.json
Labels: Fixed

#18727 Rework restrictions to restrict dpuzs in and member conditions out
  chia/_tests/clvm/test_custody_architecture.py
  chia/wallet/puzzles/custody/architecture_puzzles/restrictions.clsp
  chia/wallet/puzzles/custody/architecture_puzzles/restrictions.clsp.hex
  chia/wallet/puzzles/custody/custody_architecture.py
  chia/wallet/puzzles/deployed_puzzle_hashes.json
Labels: Fixed

#18465 Move some files closer to where they should live.
  chia/_tests/util/test_network.py
  chia/_tests/util/test_pprint.py
  chia/cmds/check_wallet_db.py
  chia/full_node/full_node.py
  chia/full_node/util/__init__.py
  chia/full_node/util/safe_cancel_task.py
  chia/server/node_discovery.py
  chia/types/peer_info.py
  chia/util/ip_address.py
  chia/util/network.py
  chia/wallet/util/pprint.py
Labels: Changed

#18717 checkpoint: into main from release/2.4.4 @ 39739520211670d398173f87cd1e97c755274195
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#18730 [CHIA-1561] validate UnfinishedBlocks and signature in thread pool
  chia/consensus/blockchain.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
Labels: Changed, coverage-diff

#18692 CHIA-1626 Move some modules to the utils virtual project
  chia/util/batches.py
  chia/util/bech32m.py
  chia/util/byte_types.py
  chia/util/collection.py
  chia/util/cpu.py
  chia/util/db_synchronous.py
  chia/util/db_version.py
  chia/util/db_wrapper.py
  chia/util/default_root.py
  chia/util/errors.py
  chia/util/file_keyring.py
  chia/util/files.py
  chia/util/hash.py
  chia/util/inline_executor.py
  chia/util/keychain.py
  chia/util/keyring_wrapper.py
  chia/util/limited_semaphore.py
  chia/util/lock.py
  chia/util/log_exceptions.py
  chia/util/logging.py
  chia/util/lru_cache.py
  chia/util/math.py
  chia/util/paginator.py
  chia/util/path.py
  chia/util/permissions.py
  chia/util/priority_mutex.py
  chia/util/profiler.py
  chia/util/recursive_replace.py
  chia/util/setproctitle.py
  chia/util/significant_bits.py
  chia/util/streamable.py
  chia/util/task_timing.py
  chia/util/timing.py
  chia/util/virtual_project_analysis.py
Labels: Changed, Cleanup

#18728 Use feeder pattern for MofNs as well
  chia/_tests/clvm/test_custody_architecture.py
  chia/wallet/puzzles/custody/architecture_puzzles/m_of_n.clsp
  chia/wallet/puzzles/custody/architecture_puzzles/m_of_n.clsp.hex
  chia/wallet/puzzles/custody/custody_architecture.py
  chia/wallet/puzzles/custody/optimization_puzzles/1_of_n.clsp
  chia/wallet/puzzles/custody/optimization_puzzles/1_of_n.clsp.hex
  chia/wallet/puzzles/custody/optimization_puzzles/n_of_n.clsp
  chia/wallet/puzzles/custody/optimization_puzzles/n_of_n.clsp.hex
  chia/wallet/puzzles/deployed_puzzle_hashes.json
Labels: Changed

#18733 remove node `.index` attributes
  chia/_tests/core/data_layer/test_merkle_blob.py
  chia/data_layer/util/merkle_blob.py
Labels: Changed, Exclude_Notes

#18744 CHIA-1663 Simplify duplicate output validation in validate_block_body
  chia/consensus/block_body_validation.py
Labels: Changed, Cleanup

#18743 Move `spend_sim.py` into tests
  chia/_tests/clvm/test_singletons.py
  chia/_tests/clvm/test_spend_sim.py
  chia/_tests/conftest.py
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  chia/_tests/fee_estimation/test_mempoolitem_height_added.py
  chia/_tests/util/spend_sim.py
  chia/_tests/wallet/cat_wallet/test_cat_lifecycle.py
  chia/_tests/wallet/cat_wallet/test_offer_lifecycle.py
  chia/_tests/wallet/clawback/test_clawback_lifecycle.py
  chia/_tests/wallet/dao_wallet/test_dao_clvm.py
  chia/_tests/wallet/db_wallet/test_db_graftroot.py
  chia/_tests/wallet/nft_wallet/test_nft_lifecycle.py
  chia/_tests/wallet/vc_wallet/test_vc_lifecycle.py
Labels: Changed, Tests, Cleanup

#18584 refactor full_node add_block
  chia/_tests/blockchain/blockchain_test_utils.py
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/blockchain/test_blockchain_transactions.py
  chia/_tests/core/full_node/stores/test_full_node_store.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/test_db_conversion.py
  chia/_tests/core/test_db_validation.py
  chia/_tests/core/test_full_node_rpc.py
  chia/_tests/environments/wallet.py
  chia/_tests/farmer_harvester/test_third_party_harvesters.py
  chia/_tests/process_junit.py
  chia/_tests/util/full_sync.py
  chia/_tests/util/misc.py
  chia/_tests/util/time_out_assert.py
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/nft_wallet/test_nft_wallet.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/consensus/blockchain.py
  chia/full_node/full_node.py
  chia/simulator/full_node_simulator.py
  tools/test_full_sync.py
Labels: Blockchain team, ready_to_merge, full_node, Fixed, Cleanup

#18741 Additions removals
  chia/consensus/block_body_validation.py
  chia/consensus/blockchain.py
  chia/full_node/full_node_api.py
Labels: ready_to_merge, Changed

#18712 CHIA-1565 Pass a ValidationState to validate_finished_header_block
  chia/_tests/blockchain/test_blockchain.py
  chia/consensus/block_header_validation.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/weight_proof.py
  chia/wallet/wallet_blockchain.py
Labels: ready_to_merge, Changed, Cleanup

#18698 tests as its own subproject
  chia/util/virtual_project_analysis.py
Labels: ready_to_merge, Changed, CI

#18750 move add_blocks_in_batches() out of tests
  chia/_tests/blockchain/test_blockchain_transactions.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/mempool/test_mempool_performance.py
  chia/_tests/core/test_full_node_rpc.py
  chia/_tests/util/misc.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/_tests/wallet/test_wallet_blockchain.py
  chia/_tests/wallet/test_wallet_node.py
  chia/simulator/add_blocks_in_batches.py
  chia/simulator/full_node_simulator.py
Labels: ready_to_merge, Fixed, CI

#18738 Add a BLSMember puzzle, a corresponding class, and a test
  chia/_tests/clvm/test_member_puzzles.py
  chia/wallet/puzzles/custody/custody_architecture.py
  chia/wallet/puzzles/custody/member_puzzles/__init__.py
  chia/wallet/puzzles/custody/member_puzzles/bls_member.clsp
  chia/wallet/puzzles/custody/member_puzzles/bls_member.clsp.hex
  chia/wallet/puzzles/custody/member_puzzles/member_puzzles.py
  chia/wallet/puzzles/deployed_puzzle_hashes.json
Labels: Added

#18753 use signed integers for keys and values
  chia/_tests/core/data_layer/test_merkle_blob.py
  chia/data_layer/util/merkle_blob.py
Labels: Changed

#18751 Add basic framework for delegated puzzle validators
  chia/_tests/clvm/test_custody_architecture.py
  chia/_tests/clvm/test_member_puzzles.py
  chia/_tests/clvm/test_restrictions.py
  chia/wallet/puzzles/custody/architecture_puzzles/restrictions.clsp
  chia/wallet/puzzles/custody/architecture_puzzles/restrictions.clsp.hex
  chia/wallet/puzzles/custody/custody_architecture.py
  chia/wallet/puzzles/custody/restriction_puzzles/__init__.py
  chia/wallet/puzzles/custody/restriction_puzzles/add_dpuz_wrapper.clsp
  chia/wallet/puzzles/custody/restriction_puzzles/add_dpuz_wrapper.clsp.hex
  chia/wallet/puzzles/custody/restriction_puzzles/enforce_dpuz_wrappers.clsp
  chia/wallet/puzzles/custody/restriction_puzzles/enforce_dpuz_wrappers.clsp.hex
  chia/wallet/puzzles/custody/restriction_utilities.py
  chia/wallet/puzzles/deployed_puzzle_hashes.json
Labels: clvm, Added

#18737 more lowercase types such as in comments
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/farmer_harvester/test_farmer.py
  chia/_tests/util/gen_ssl_certs.py
  chia/_tests/wallet/test_singleton_lifecycle_fast.py
  chia/_tests/wallet/test_transaction_store.py
  chia/cmds/wallet_funcs.py
  chia/consensus/block_body_validation.py
  chia/data_layer/util/plugin.py
  chia/full_node/full_node_store.py
  chia/full_node/mempool_manager.py
  chia/full_node/weight_proof.py
  chia/protocols/wallet_protocol.py
  chia/rpc/data_layer_rpc_api.py
  chia/rpc/farmer_rpc_api.py
  chia/types/eligible_coin_spends.py
  chia/util/streamable.py
  chia/wallet/puzzles/clawback/drivers.py
  chia/wallet/trade_manager.py
  chia/wallet/util/merkle_tree.py
  chia/wallet/util/merkle_utils.py
  chia/wallet/wallet_state_manager.py
Labels: Changed, Cleanup

#18745 CHIA-1664 Deduplicate cancel_task_safe
  chia/daemon/server.py
  chia/full_node/full_node.py
  chia/server/node_discovery.py
  chia/util/safe_cancel_task.py
Labels: Changed, Cleanup

#18754 add vpa virtual project package
  chia/util/virtual_project_analysis.py
Labels: Added, CI

#18758 CHIA-1669 Simplify tx_additions and tx_removals in validate_block_merkle_roots
  chia/consensus/block_root_validation.py
Labels: Changed, Cleanup

#18761 Update clvm_tools_rs to 0.1.45
  poetry.lock
  pyproject.toml
Labels: Changed

#18703 [CHIA-1566] pipeline block validation in sync_from_fork_point()
  chia/_tests/blockchain/blockchain_test_utils.py
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/farmer_harvester/test_third_party_harvesters.py
  chia/_tests/util/full_sync.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/consensus/blockchain.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
  chia/simulator/add_blocks_in_batches.py
  chia/simulator/full_node_simulator.py
  chia/util/augmented_chain.py
  tools/test_full_sync.py
Labels: ready_to_merge, Changed

#18767 remove unnecessary use of `.__members__` on `ConditionOpcode` iteration
  chia/_tests/clvm/test_condition_codes.py
  chia/wallet/util/debug_spend_bundle.py
Labels: Changed, Cleanup

#18769 Keep track of all long sync task references
  chia/full_node/full_node.py
Labels: Fixed

#18759 [CHIA-1553] Replace pylint with ruff
  .github/CODEOWNERS
  .github/workflows/dependency-review.yml
  .github/workflows/upload-pypi-source.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  benchmarks/block_ref.py
  benchmarks/streamable.py
  chia/_tests/build-init-files.py
  chia/_tests/cmds/cmd_test_utils.py
  chia/_tests/cmds/test_show.py
  chia/_tests/cmds/wallet/test_coins.py
  chia/_tests/cmds/wallet/test_dao.py
  chia/_tests/cmds/wallet/test_did.py
  chia/_tests/cmds/wallet/test_nft.py
  chia/_tests/cmds/wallet/test_notifications.py
  chia/_tests/cmds/wallet/test_vcs.py
  chia/_tests/cmds/wallet/test_wallet.py
  chia/_tests/process_junit.py
  chia/_tests/util/misc.py
  chia/_tests/util/time_out_assert.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/test_wallet_state_manager.py
  chia/cmds/chia.py
  chia/cmds/cmd_classes.py
  chia/cmds/signer.py
  chia/daemon/windows_signal.py
  chia/data_layer/data_store.py
  chia/full_node/full_node.py
  chia/rpc/data_layer_rpc_util.py
  chia/rpc/wallet_request_types.py
  chia/rpc/wallet_rpc_api.py
  chia/server/chia_policy.py
  chia/util/db_wrapper.py
  chia/util/dump_keyring.py
  chia/util/task_timing.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/nft_wallet/nft_puzzles.py
  chia/wallet/util/blind_signer_tl.py
  chia/wallet/wallet.py
  chia/wallet/wallet_protocol.py
  poetry.lock
  pylintrc
  pyproject.toml
  tools/analyze-chain.py
  tools/analyze_memory_profile.py
  tools/cpu_utilization.py
  tools/generate_chain.py
  tools/run_block.py
  tools/test_full_sync.py
Labels: Added

#18757 CHIA-1668 Move validate_block_merkle_roots next to validate_block_body
  chia/consensus/block_body_validation.py
  chia/consensus/block_root_validation.py
Labels: Changed, Cleanup

#18770 CHIA-1674 Remove no longer needed get_symmetric_key
  chia/util/file_keyring.py
Labels: Changed, Cleanup

#18763 Try updating to psutil 6.1.0
  poetry.lock
  pyproject.toml
Labels: Changed

#18768 correct wallet rpc api for get spendable coins with specified excluded coins
  chia/rpc/wallet_rpc_api.py
Labels: Fixed

#18693 CHIA-1628 Annotate test_network.py
  chia/_tests/util/test_network.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#18742 Don't import a `wallet` file from `util`.
  chia/_tests/wallet/test_util.py
  chia/util/json_util.py
  chia/wallet/util/wallet_types.py
Labels: Changed

#18780 [CHIA-1676] Make ruff an optional dependency
  poetry.lock
  pyproject.toml
Labels: ready_to_merge, Changed

#18789 Replace Isort with Ruff
  .pre-commit-config.yaml
  CONTRIBUTING.md
  chia/_tests/core/full_node/test_full_node.py
  chia/full_node/mempool_check_conditions.py
  chia/wallet/dao_wallet/dao_wallet.py
  poetry.lock
  pyproject.toml
Labels: ready_to_merge, Changed

#18764 [CHIA-1672] Add parsing for JSON formatted spend bundles in `/push_tx`
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/rpc/wallet_request_types.py
  chia/rpc/wallet_rpc_api.py
Labels: ready_to_merge, Added

#18755 remove `prompt_yes_no()`
  chia/cmds/beta_funcs.py
  chia/cmds/cmds_util.py
  chia/cmds/passphrase_funcs.py
  chia/legacy/keyring.py
Labels: Changed, Exclude_Notes

#18783 [CHIA-1673] Comment out a manual `._finish_sync()` call
  chia/simulator/add_blocks_in_batches.py
Labels: Fixed, Tests

#18778 tidy venv usage in `install.sh`
  install.sh
Labels: Changed, Exclude_Notes

#18785 explicitly check `ApiProtocol` classes
  chia/data_layer/data_layer_api.py
  chia/farmer/farmer_api.py
  chia/full_node/full_node_api.py
  chia/harvester/harvester_api.py
  chia/introducer/introducer_api.py
  chia/seeder/crawler_api.py
  chia/timelord/timelord_api.py
  chia/wallet/wallet_node_api.py
Labels: Changed, Exclude_Notes

#18786 explicitly check `RpcApiProtocol` classes
  chia/rpc/crawler_rpc_api.py
  chia/rpc/data_layer_rpc_api.py
  chia/rpc/farmer_rpc_api.py
  chia/rpc/full_node_rpc_api.py
  chia/rpc/harvester_rpc_api.py
  chia/rpc/timelord_rpc_api.py
  chia/rpc/wallet_rpc_api.py
Labels: Changed, Exclude_Notes

#18796 less `int(somefloatliteral)`
  chia/_tests/clvm/test_puzzles.py
  chia/_tests/generator/test_rom.py
  chia/_tests/wallet/test_singleton_lifecycle_fast.py
Labels: Changed, Cleanup

#18776 add native linux arm install script testing
  .github/workflows/test-install-scripts.yml
Labels: Added, CI

#18795 [CHIA-1679] Replace Pyupgrade with Ruff
  .pre-commit-config.yaml
  chia/_tests/cmds/test_click_types.py
  chia/_tests/core/test_seeder.py
  chia/_tests/generator/test_rom.py
  chia/_tests/util/split_managers.py
  chia/wallet/trade_manager.py
  poetry.lock
  pyproject.toml
Labels: ready_to_merge, Changed
