Repository Chia-Network/chia-blockchain, pull requests merged in 2024-05, with the labels that each got.

#17940 Update changelog for 2.3.0
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#17941 Filter out duplicate coins returned by RequestPuzzleState
  chia/_tests/core/full_node/stores/test_coin_store.py
  chia/full_node/coin_store.py
Labels: Fixed

#17943 Correct version numbers for dependant packages and add known issue
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#17947 Use python 3.11 for Arch install tests
  .github/workflows/test-install-scripts.yml
Labels: Changed, CI, Exclude_Notes

#17934 expand matrices to include ubuntu 24.04 noble numbat
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/test-install-scripts.yml
Labels: Added, Tests

#17948 checkpoint: into main from release/2.3.0 @ 861280f08c801138762d5fae8402b5311fdd649a
  chia/_tests/conftest.py
  chia/consensus/default_constants.py
Labels: checkpoint_merge, Changed

#17962 Adapt test_create_bundle_from_mempool_on_max_cost
  chia/_tests/core/mempool/test_mempool_manager.py
Labels: Changed

#17966 checkpoint: into main from release/2.3.0 @ 11a2e29426a42d692075fe90cf6bdc0bacecd5d3
  .github/workflows/pre-commit.yml
  .github/workflows/test-install-scripts.yml
  .github/workflows/upload-pypi-source.yml
Labels: checkpoint_merge, Changed

#17960 bump timeout for publishing macOS installers to avoid timeout
  .github/workflows/build-macos-installers.yml
Labels: Changed, CI

#17953 add ability to profile the farmer process
  chia/farmer/farmer.py
  chia/util/initial-config.yaml
Labels: ready_to_merge, Changed

#17965 remove unused current_inner from PoolState
  chia/pools/pool_wallet.py
  chia/pools/pool_wallet_info.py
Labels: ready_to_merge, Changed

#17951 fix confusion between prompt and don't prompt in the plotnft CLI
  chia/cmds/plotnft.py
  chia/cmds/plotnft_funcs.py
Labels: CLI, ready_to_merge, Fixed

#17959 drop deprecated `authentication_public_key` from pool config
  chia/farmer/farmer.py
  chia/pools/pool_config.py
Labels: Fixed

#17977 checkpoint: into main from release/2.3.0 @ 5ec14169475030d00767a821b674f76407f7f075
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#17979 checkpoint: into main from release/2.3.0 @ 6d5eca2cffa0363863a619fba224108225533377
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#17961 optimize launcher_id_to_p2_puzzle_hash()
  chia/_tests/pools/test_pool_puzzles_lifecycle.py
  chia/pools/pool_puzzles.py
Labels: ready_to_merge, Changed

#17927 remove ignore for loop argument deprecation warning
  pytest.ini
Labels: Fixed, Cleanup

#17929 remove ignore for no current event loop deprecation warning
  pytest.ini
Labels: Fixed, Cleanup

#17932 remove ignore for `keyring.util` deprecation warning
  pytest.ini
Labels: Fixed, Cleanup

#17964 use ubuntu-latest for all publishing
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: Changed, CI

#17987 Set repo content updater actions reviewers
  .repo-content-updater.yml
Labels: Added, CI, Exclude_Notes

#17937 more macos arm and intel matrixing
  .github/workflows/build-macos-installers.yml
  .github/workflows/test-install-scripts.yml
Labels: Fixed, CI

#17860 chore: fix two typos
  chia/consensus/blockchain.py
  chia/protocols/shared_protocol.py
Labels: Fixed, community-pr

#17958 Make sure to use no more than 61 cpus on windows
  chia/util/misc.py
Labels: 1.6.0, Fixed

#17973 Update coins_to_offer values type in _create_offer_for_ids to avoid needlessly converting selected_coins to a set
  chia/wallet/trade_manager.py
Labels: Changed, Cleanup

#17975 Remove no longer needed softfork_fixture
  chia/_tests/core/mempool/test_mempool.py
Labels: Changed, Cleanup

#17930 remove ignore for 'u' format deprecation warning
  pytest.ini
Labels: Fixed, Cleanup

#17883 Optimize DL autoinserts.
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_store.py
  chia/util/initial-config.yaml
Labels: ready_to_merge, Added, DataLayer

#17928 remove ignore for distutils deprecation warning
  pytest.ini
Labels: Fixed, Cleanup

#17842 Add @tx_out_cmd decorator
  chia/_tests/cmds/wallet/test_tx_decorators.py
  chia/cmds/cmds_util.py
Labels: Added, vault

#18000 Add genesis challenge to get_network_info rpcs
  chia/_tests/core/daemon/test_daemon.py
  chia/_tests/core/test_full_node_rpc.py
  chia/daemon/server.py
  chia/rpc/rpc_server.py
Labels: Changed

#17995 Puzzle hash optimizations
  chia/_tests/clvm/test_curry_and_treehash.py
  chia/_tests/wallet/did_wallet/test_did.py
  chia/pools/pool_puzzles.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/did_wallet/did_wallet_puzzles.py
  chia/wallet/puzzles/p2_delegated_puzzle_or_hidden_puzzle.py
  chia/wallet/singleton.py
  chia/wallet/util/curry_and_treehash.py
  chia/wallet/wallet_state_manager.py
Labels: Changed

#17864 change datalayer python and logging from tree id to store id
  chia/_tests/core/data_layer/conftest.py
  chia/_tests/core/data_layer/test_data_cli.py
  chia/_tests/core/data_layer/test_data_layer.py
  chia/_tests/core/data_layer/test_data_layer_util.py
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/core/data_layer/test_data_store.py
  chia/_tests/core/data_layer/test_data_store_schema.py
  chia/_tests/core/data_layer/util.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_errors.py
  chia/data_layer/data_layer_util.py
  chia/data_layer/data_store.py
  chia/data_layer/download_data.py
  chia/data_layer/s3_plugin_service.py
  chia/data_layer/util/benchmark.py
  chia/rpc/data_layer_rpc_api.py
Labels: Changed, Exclude_Notes

#17991 optimize key derivation in the wallet
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge, Changed

#17837 Remove leftover BlockRecord print in test_assert_height_pending
  chia/_tests/core/mempool/test_mempool.py
Labels: Changed, Cleanup

#17911 Simplify gen_and_send_sb and make it type safe
  chia/_tests/core/mempool/test_mempool.py
Labels: Changed, Cleanup

#17912 Improve spend bundle checks in test_dao_proposal_partial_vote
  chia/_tests/wallet/dao_wallet/test_dao_wallets.py
Labels: Changed, Cleanup

#17925 Remove no longer needed isinstance assert in mint_from_did and mint_from_xch for mypy's sake
  chia/wallet/nft_wallet/nft_wallet.py
Labels: Changed, Cleanup

#18005 fix macos installer test matrix
  .github/workflows/build-macos-installers.yml
Labels: Fixed, CI, Exclude_Notes

#18002 [CHIA-423] Port `chia wallet send` to @tx_out_cmd
  chia/_tests/cmds/wallet/test_wallet.py
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
Labels: Added, vault

#17921 Adjust farmer service SSL tests for increased reliability
  chia/_tests/core/ssl/test_ssl.py
Labels: Changed, CI

#17933 CHIA-420 remove ignore for `pkg_resources` deprecation warning
  chia/_tests/clvm/test_condition_codes.py
  chia/_tests/cmds/wallet/test_wallet.py
  chia/_tests/core/daemon/test_daemon.py
  chia/_tests/core/util/test_keychain.py
  chia/_tests/simulation/test_simulation.py
  chia/_tests/util/benchmarks.py
  chia/plotters/chiapos.py
  chia/ssl/create_ssl.py
  chia/timelord/timelord_launcher.py
  chia/util/config.py
  chia/util/keychain.py
  chia/wallet/puzzles/load_clvm.py
  install-timelord.sh
  installhelper.py
  pytest.ini
  setup.py
Labels: Fixed, Cleanup

#17992 [CHIA-302] Handle reorgs in data layer wallet
  chia/_tests/wallet/db_wallet/test_dl_offers.py
  chia/_tests/wallet/db_wallet/test_dl_wallet.py
  chia/_tests/wallet/rpc/test_dl_wallet_rpc.py
  chia/data_layer/data_layer_wallet.py
  chia/data_layer/dl_wallet_store.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge, Fixed, DataLayer

#17982 [CHIA-292] Modify VerifiedCredential.launch to handle multiple source coins
  chia/_tests/wallet/vc_wallet/test_vc_lifecycle.py
  chia/_tests/wallet/vc_wallet/test_vc_wallet.py
  chia/wallet/vc_wallet/vc_drivers.py
  chia/wallet/vc_wallet/vc_wallet.py
Labels: Fixed, VC

#17999 [CHIA-387] DL batch upsert optimization.
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/data_store.py
Labels: ready_to_merge, Changed, DataLayer

#18031 temporarily exclude focal and jammy installer script testing on arm
  .github/workflows/test-install-scripts.yml
Labels: Changed, CI

#18023 [CHIA-424] Port `chia wallet coins` to @tx_out_cmd
  chia/_tests/cmds/cmd_test_utils.py
  chia/_tests/cmds/wallet/test_coins.py
  chia/cmds/coin_funcs.py
  chia/cmds/coins.py
Labels: Added, vault

#18033 Revert "temporarily exclude focal and jammy installer script testing on arm"
  .github/workflows/test-install-scripts.yml
Labels: Fixed, CI

#18036 [CHIA-426] Port `chia wallet clawback` to @tx_out_cmd
  chia/_tests/cmds/wallet/test_wallet.py
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_client.py
Labels: Added, coverage-diff, vault

#18024 [CHIA-508] Add tx_config and extra_conditions to DID creation endpoint
  chia/_tests/cmds/wallet/test_did.py
  chia/_tests/wallet/cat_wallet/test_trades.py
  chia/_tests/wallet/did_wallet/test_did.py
  chia/_tests/wallet/nft_wallet/test_nft_1_offers.py
  chia/_tests/wallet/nft_wallet/test_nft_bulk_mint.py
  chia/_tests/wallet/nft_wallet/test_nft_wallet.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/vc_wallet/test_vc_wallet.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/did_wallet/did_wallet.py
Labels: Fixed

#18038 [CHIA-427] Port `chia wallet take/cancel_offer` to @tx_out_cmd
  chia/_tests/cmds/wallet/test_wallet.py
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
Labels: Added, coverage-diff

#18041 [CHIA-428] Port `chia wallet did ...` to @tx_out_cmd
  chia/_tests/cmds/wallet/test_did.py
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
Labels: Added, coverage-diff

#18043 also upload sha256 for PRs
  .github/workflows/build-macos-installers.yml
Labels: Fixed, CI

#18044 [CHIA-429] Port `chia wallet nft ...` to @tx_out_cmd
  chia/_tests/cmds/wallet/test_nft.py
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
Labels: Added, coverage-diff

#17786 CHIA-414 fixup datalayer benchmark
  chia/_tests/core/data_layer/test_data_store.py
  chia/_tests/util/misc.py
  setup.py
Labels: Fixed, Tests

#17990 CHIA-420 remove coin solutions deprecation ignores
  pytest.ini
Labels: Changed, Tests

#18037 bump chia_rs to 0.8.0 and update G1Element handling
  chia/_tests/clvm/test_puzzles.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  chia/_tests/core/util/test_cached_bls.py
  chia/_tests/util/key_tool.py
  chia/_tests/util/test_condition_tools.py
  chia/_tests/wallet/clawback/test_clawback_lifecycle.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/consensus/block_body_validation.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/mempool_manager.py
  chia/util/cached_bls.py
  chia/util/condition_tools.py
  chia/wallet/signer_protocol.py
  chia/wallet/util/debug_spend_bundle.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
  setup.py
  tools/analyze-chain.py
Labels: Changed

#18048 setuptools<70 for now
  setup.py
Labels: Fixed, CI

#18039 [CHIA-365] Return exception and error from get_kv_diff when either of the hashes has no data
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/data_store.py
Labels: Fixed

#18054 Revert "CHIA-414 fixup datalayer benchmark"
  chia/_tests/core/data_layer/test_data_store.py
  chia/_tests/util/misc.py
  setup.py
Labels: Changed, CI, Exclude_Notes

#18047 [CHIA-430] Port `chia wallet notifications send` to @tx_out_cmd
  chia/_tests/cmds/wallet/test_notifications.py
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_client.py
Labels: Added

#18020 Leverage serialized program for nonce creation in VCWallet's revoke_vc
  chia/wallet/vc_wallet/vc_wallet.py
Labels: Changed, Cleanup

#18061 CHIA-595: update test fixture ConsensusMode to be ordered
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/conftest.py
  chia/_tests/core/full_node/test_conditions.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/test_full_node_rpc.py
Labels: ready_to_merge, Changed, Tests

#18062 [CHIA-431] Port `chia wallet vcs ...` to @tx_out_cmd
  chia/_tests/cmds/wallet/test_vcs.py
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
Labels: Added, coverage-diff

#18063 Revert `final_pubkey: G1Element` from main
  chia/_tests/wallet/test_signer_protocol.py
  chia/wallet/signer_protocol.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge, Fixed

#16898 clvm mypie
  benchmarks/mempool-long-lived.py
  chia/_tests/core/data_layer/test_data_store.py
  chia/_tests/core/data_layer/util.py
  chia/_tests/generator/test_compression.py
  chia/_tests/generator/test_rom.py
  chia/_tests/wallet/cat_wallet/test_offer_lifecycle.py
  chia/_tests/wallet/dao_wallet/test_dao_clvm.py
  chia/_tests/wallet/nft_wallet/test_ownership_outer_puzzle.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/_tests/wallet/test_singleton_lifecycle_fast.py
  chia/data_layer/data_layer_util.py
  chia/data_layer/data_store.py
  chia/pools/pool_puzzles.py
  chia/rpc/wallet_rpc_api.py
  chia/types/blockchain_format/program.py
  chia/types/blockchain_format/tree_hash.py
  chia/types/coin_spend.py
  chia/wallet/cat_wallet/cat_outer_puzzle.py
  chia/wallet/cat_wallet/cat_utils.py
  chia/wallet/conditions.py
  chia/wallet/dao_wallet/dao_utils.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/did_wallet/did_wallet_puzzles.py
  chia/wallet/lineage_proof.py
  chia/wallet/nft_wallet/metadata_outer_puzzle.py
  chia/wallet/nft_wallet/nft_puzzles.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/nft_wallet/ownership_outer_puzzle.py
  chia/wallet/nft_wallet/singleton_outer_puzzle.py
  chia/wallet/nft_wallet/transfer_program_puzzle.py
  chia/wallet/nft_wallet/uncurry_nft.py
  chia/wallet/puzzles/clawback/drivers.py
  chia/wallet/puzzles/p2_delegated_conditions.py
  chia/wallet/puzzles/p2_puzzle_hash.py
  chia/wallet/puzzles/singleton_top_layer.py
  chia/wallet/util/compute_hints.py
  chia/wallet/util/debug_spend_bundle.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
  setup.py
Labels: Changed, Exclude_Notes, coverage-diff

#18067 Correct version numbers for dependant packages and add known issue (#17943)
  CHANGELOG.md
Labels: Fixed, Exclude_Notes

#18066 setuptools<70 for now (#18048)
  setup.py
Labels: Fixed, CI

#18064 [CHIA-593] - Add bridge CATs to known CAT list
  chia/wallet/cat_wallet/cat_constants.py
Labels: Added

#18030 Do without more_itertools's partition in get_singleton_and_remaining_coins
  chia/_tests/core/mempool/test_singleton_fast_forward.py
Labels: Changed, Cleanup

#18070 Update changelog for 2.3.1
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#18065 [CHIA-432] Port `chia dao ...` to @tx_out_cmd (and exclude DL and pooling)
  chia/_tests/cmds/wallet/test_dao.py
  chia/cmds/dao.py
  chia/cmds/dao_funcs.py
  chia/cmds/data.py
  chia/cmds/plotnft.py
  chia/rpc/wallet_rpc_client.py
Labels: Added, coverage-diff, vault

#18079 checkpoint: into main from release/2.3.1 @ 9f207c2c2b0564e74ed0864e0d9bd3f9c3f91869
  chia/wallet/cat_wallet/cat_constants.py
Labels: checkpoint_merge, Changed

#17976 Add unfinished block to state change event
  chia/full_node/full_node.py
  chia/rpc/full_node_rpc_api.py
Labels: RPC, Added, community-pr

#18089 checkpoint: into main from release/2.3.1 @ b29ae6367486a874dae45d685a565ff8e7640b00
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#18073 [CHIA-602] Add bech32m option for adding public keys
  chia/_tests/core/util/test_keychain.py
  chia/util/keychain.py
Labels: Added

#18095 simplify mempool coin spends
  chia/full_node/mempool_manager.py
  chia/types/eligible_coin_spends.py
Labels: ready_to_merge, Changed, Cleanup

#18094 Add optional trusted CIDR list
  chia/_tests/util/test_trusted_peer.py
  chia/cmds/peer_funcs.py
  chia/cmds/wallet_funcs.py
  chia/server/server.py
  chia/util/network.py
Labels: Changed

#18021 CHIA-616 Annotate test_blockchain.py
  chia/_tests/blockchain/test_blockchain.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#18072 CHIA-595: Soft fork 5
  chia/_tests/conftest.py
  chia/_tests/core/full_node/test_conditions.py
  chia/_tests/util/test_replace_str_to_bytes.py
  chia/_tests/util/test_testnet_overrides.py
  chia/consensus/default_constants.py
  chia/full_node/mempool_check_conditions.py
  chia/util/initial-config.yaml
Labels: ready_to_merge, Changed

#18053 [CHIA-615] make BLSCache a proper class
  chia/_tests/blockchain/blockchain_test_utils.py
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/core/test_db_conversion.py
  chia/_tests/core/test_db_validation.py
  chia/_tests/core/util/test_cached_bls.py
  chia/_tests/farmer_harvester/test_third_party_harvesters.py
  chia/_tests/util/full_sync.py
  chia/consensus/block_body_validation.py
  chia/consensus/blockchain.py
  chia/full_node/full_node.py
  chia/full_node/mempool_manager.py
  chia/simulator/full_node_simulator.py
  chia/util/cached_bls.py
Labels: Changed
