Repository Chia-Network/chia-blockchain, pull requests merged in 2024-07, with the labels that each got.

#18255 CHIA-826 Simplify get_items_by_coin_id and make it return an iterator
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/rpc/full_node_rpc_api.py
Labels: Changed, Cleanup

#18242 CHIA-817 Properly order HARD_FORK_2_0 and SOFT_FORK_4 in ConsensusMode
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/conftest.py
Labels: Changed, Cleanup

#18267 [CHIA-884] Fix timelord log spam.
  chia/timelord/timelord.py
Labels: Fixed

#18263 [CHIA-885] Send different uncompact buckets to blueboxes.
  chia/full_node/full_node.py
Labels: Changed

#18268 [CHIA-883] Fix duplicate connection log spam.
  chia/server/start_service.py
Labels: Fixed, coverage-diff

#18208 [CHIA-786] simplify hard-fork consensus rules
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/core/full_node/test_conditions.py
  chia/_tests/core/mempool/test_mempool.py
  chia/full_node/mempool_check_conditions.py
  chia/simulator/block_tools.py
Labels: Changed

#18143 [CHIA-691] simplify `MempoolItem`
  benchmarks/mempool-long-lived.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_item_queries.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  chia/_tests/fee_estimation/test_fee_estimation_integration.py
  chia/clvm/spend_sim.py
  chia/full_node/full_node.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/rpc/full_node_rpc_api.py
  chia/types/eligible_coin_spends.py
  chia/types/internal_mempool_item.py
  chia/types/mempool_item.py
Labels: ready_to_merge, Changed

#18262 ad.fee_estimation_fixes
  chia/_tests/fee_estimation/test_fee_estimation_unit_tests.py
  chia/full_node/fee_estimator.py
  chia/full_node/fee_tracker.py
Labels: bug, Wallet, Fixed

#18260 checkpoint: into main from release/2.4.0 @ 4ce568b129899591bdb26e5fcba7d16785054646
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#17430 use rust version of SpendBundle
  chia/_tests/core/custom_types/test_spend_bundle.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/fee_estimation/test_fee_estimation_rpc.py
  chia/_tests/wallet/cat_wallet/test_trades.py
  chia/data_layer/data_layer_wallet.py
  chia/types/spend_bundle.py
  chia/wallet/trading/offer.py
Labels: ready_to_merge, Changed

#18240 move gather_signing_info to main wallet
  chia/wallet/wallet.py
  chia/wallet/wallet_protocol.py
  chia/wallet/wallet_state_manager.py
Labels: Fixed

#18247 CHIA-818 Add Soft Fork options to simulator config
  chia/cmds/sim_funcs.py
  chia/util/initial-config.yaml
Labels: simulator, Added

#18274 checkpoint: into main from release/2.4.1 @ 7c54e60910c6db80c2a7d92ed4f2d500e8e7179c
  .github/workflows/build-macos-installers.yml
Labels: checkpoint_merge, Changed

#18222 [CHIA-683] Drop unknown tables when resetting wallet sync DB
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/wallet/wallet_node.py
Labels: ready_to_merge, Changed

#18277 increase linting timeouts to account for slow fmt bandwidth to github
  .github/workflows/upload-pypi-source.yml
Labels: Changed, CI

#18276 checkpoint: into main from release/2.4.1 @ 4b2f9f0c7e7e575dd266c238a017b9856b254a1f
  chia/types/weight_proof.py
Labels: checkpoint_merge, Changed

#18209 [CHIA-786] remove the original block compression
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/test_full_node_rpc.py
  chia/_tests/generator/test_compression.py
  chia/_tests/generator/test_scan.py
  chia/full_node/bundle_tools.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/full_node_store.py
  chia/full_node/generator.py
  chia/simulator/block_tools.py
  chia/simulator/full_node_simulator.py
  chia/types/generator_types.py
  mypy-exclusions.txt
Labels: ready_to_merge, Changed

#18275 [CHIA-839] Refactor KeywringWrapper/FileKeyring for better ergonomics
  chia/_tests/core/util/test_file_keyring_synchronization.py
  chia/_tests/core/util/test_keychain.py
  chia/_tests/core/util/test_keyring_wrapper.py
  chia/util/file_keyring.py
  chia/util/keychain.py
  chia/util/keyring_wrapper.py
Labels: Changed, Exclude_Notes

#18280 checkpoint: into main from release/2.4.1 @ 406550e4ccd1b3d683d58b537f1cab3a307a4b54
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#18284 Update changelog for 2.4.2
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#11057 CHIA-597: Use `poetry` for package management
  .coveragerc
  .github/workflows/check_wheel_availability.yaml
  .github/workflows/dependency-review.yml
  .github/workflows/reflow-version.yml
  .github/workflows/test-single.yml
  .github/workflows/upload-pypi-source.yml
  .gitignore
  Install.ps1
  Setup-poetry.ps1
  activated.ps1
  activated.sh
  build_scripts/check_dependency_artifacts.py
  build_scripts/installer-version.py
  build_scripts/pyinstaller.spec
  chia/_tests/core/data_layer/util.py
  chia/_tests/util/test_installed.py
  install-timelord.sh
  install.sh
  installhelper.py
  poetry.lock
  poetry.toml
  pyproject.toml
  setup-poetry.sh
  setup.py
Labels: Changed

#18289 checkpoint: into main from release/2.4.2 @ bcbc7a7b50cf1a3a81b7548e602412ea2167f26f
  chia/_tests/core/util/test_keychain.py
  chia/util/keychain.py
Labels: checkpoint_merge, Changed

#18290 Update Managed Files
  .github/workflows/dependency-review.yml
Labels: Changed, CI, Exclude_Notes

#18253 remove dependency on twine
  poetry.lock
  pyproject.toml
Labels: Changed, Cleanup

#18214 remove unclosed client session warning ignore
  pytest.ini
Labels: Changed, Exclude_Notes

#18126 [CHIA-712] Fix CATWallet pending_change calculation
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/cat_wallet/test_trades.py
  chia/_tests/wallet/vc_wallet/test_vc_wallet.py
  chia/wallet/cat_wallet/cat_wallet.py
Labels: ready_to_merge, Fixed

#18244 root hash, does `None` mean empty or unspecified?
  chia/cmds/data_funcs.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_util.py
  chia/data_layer/data_store.py
  chia/rpc/data_layer_rpc_api.py
Labels: Changed, Exclude_Notes

#18130 less `tree_id`
  chia/data_layer/data_store.py
Labels: Changed, Exclude_Notes

#18296 checkpoint: into main from release/2.4.2 @ b6b61999ea5ace43ea4d625fa2156593081d93df
  .github/workflows/build-macos-installers.yml
Labels: checkpoint_merge, Changed

#18298 Target macos-13-arm64 runners instead of [MacOS, arm64]
  .github/workflows/build-macos-installers.yml
  .github/workflows/check_wheel_availability.yaml
  .github/workflows/pre-commit.yml
  .github/workflows/upload-pypi-source.yml
Labels: Changed, CI

#18300 Switch curl requests to github-glue action
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
  .github/workflows/start-release.yml
  .github/workflows/start-sync-test.yml
  .github/workflows/trigger-docker-dev.yml
  .github/workflows/trigger-docker-main.yml
Labels: Changed, CI

#18303 checkpoint: into main from release/2.4.2 @ 6ae45b70369eae3ab23391867846bb84d010a30b
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#18287 [CHIA-902] default flags for `Program.run()` and `Program.run_with_cost()`
  chia/_tests/clvm/test_program.py
  chia/types/blockchain_format/program.py
Labels: Changed

#18141 [CHIA-738] Add a better clawback auto claim test and fix related issue
  chia/_tests/wallet/test_wallet.py
  chia/wallet/wallet_node.py
Labels: ready_to_merge, Fixed

#18297 attempt to "commonize" prettier config
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  .prettierrc.yaml
  BUILD_TIMELORD.md
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  LEGACY-SUPPORT-POLICY.md
  PRETTY_GOOD_PRACTICES.md
  README.md
Labels: Changed, CI

#17996 chore: remove repetitive words
  chia/_tests/plot_sync/test_receiver.py
  chia/_tests/wallet/dao_wallet/test_dao_clvm.py
  chia/cmds/init.py
Labels: stale-pr, Fixed, community-pr

#17872 Trusted wallet peer enhancements
  chia/cmds/peer_funcs.py
Labels: Added, Logging, community-pr

#18307 prettier again
  CHANGELOG.md
Labels: Fixed, Exclude_Notes

#18278 tidy `import aiosqlite as aiosqlite`
  chia/data_layer/data_layer_util.py
Labels: Changed, Cleanup

#18310 Add prune old peers functionality for crawler
  chia/_tests/core/test_crawler.py
  chia/seeder/crawl_store.py
  chia/seeder/crawler.py
  chia/seeder/start_crawler.py
  chia/util/initial-config.yaml
Labels: Changed, Crawler

#18221 use Chia-Network/actions/git-ssh-to-https@main in windows
  .github/workflows/build-windows-installer.yml
Labels: Changed, Exclude_Notes

#18312 ** for actions-reviewers
  .github/CODEOWNERS
Labels: Changed, CI

#18311 add reflow-publish-installer
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
  .github/workflows/reflow-publish-installer.yml
Labels: Changed, CI

#18308 Update Managed Files
  .github/dependabot.yml
  .prettierrc.yml
Labels: Changed, CI, Exclude_Notes

#18027 Remove ALERTS_URL and CHIA_ALERTS_PUBKEY
  chia/util/initial-config.yaml
Labels: Changed

#17998 Update all selected_network config values when setting up simulator
  chia/cmds/sim_funcs.py
Labels: Changed

#17893 DL Increase test RPC timeout
  chia/_tests/core/data_layer/test_data_rpc.py
Labels: Fixed, Tests, DataLayer

#17711 Changed: Enhance DataLayer Plugin Registration System for Improved Third-Party Integration
  chia/_tests/core/data_layer/test_plugin.py
  chia/data_layer/data_layer_util.py
  chia/data_layer/util/plugin.py
  chia/server/start_data_layer.py
Labels: Changed, DataLayer, community-pr

#18127 [CHIA-713] Add action_scope: WalletActionScope to all tx endpoints
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/full_node/test_transactions.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/mempool/test_mempool_performance.py
  chia/_tests/pools/test_pool_rpc.py
  chia/_tests/simulation/test_simulation.py
  chia/_tests/simulation/test_simulator.py
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/cat_wallet/test_trades.py
  chia/_tests/wallet/dao_wallet/test_dao_wallets.py
  chia/_tests/wallet/db_wallet/test_dl_offers.py
  chia/_tests/wallet/db_wallet/test_dl_wallet.py
  chia/_tests/wallet/did_wallet/test_did.py
  chia/_tests/wallet/nft_wallet/test_nft_1_offers.py
  chia/_tests/wallet/nft_wallet/test_nft_bulk_mint.py
  chia/_tests/wallet/nft_wallet/test_nft_offers.py
  chia/_tests/wallet/nft_wallet/test_nft_wallet.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/simple_sync/test_simple_sync_protocol.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/_tests/wallet/test_notifications.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/_tests/wallet/test_wallet.py
  chia/_tests/wallet/test_wallet_node.py
  chia/_tests/wallet/test_wallet_retry.py
  chia/_tests/wallet/test_wallet_state_manager.py
  chia/_tests/wallet/vc_wallet/test_vc_wallet.py
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/util.py
  chia/rpc/wallet_rpc_api.py
  chia/simulator/full_node_simulator.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/cat_wallet/dao_cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/notification_manager.py
  chia/wallet/puzzles/tails.py
  chia/wallet/trade_manager.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
  pylintrc
Labels: ready_to_merge, Added

#18324 Add testneta to initial config
  chia/util/initial-config.yaml
Labels: Added, Exclude_Notes

#18128 [CHIA-714] Add usage of action scope throughout wallet codebase
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/full_node/test_transactions.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/mempool/test_mempool_performance.py
  chia/_tests/pools/test_pool_rpc.py
  chia/_tests/simulation/test_simulation.py
  chia/_tests/simulation/test_simulator.py
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/cat_wallet/test_trades.py
  chia/_tests/wallet/dao_wallet/test_dao_wallets.py
  chia/_tests/wallet/db_wallet/test_dl_offers.py
  chia/_tests/wallet/db_wallet/test_dl_wallet.py
  chia/_tests/wallet/did_wallet/test_did.py
  chia/_tests/wallet/nft_wallet/test_nft_1_offers.py
  chia/_tests/wallet/nft_wallet/test_nft_bulk_mint.py
  chia/_tests/wallet/nft_wallet/test_nft_offers.py
  chia/_tests/wallet/nft_wallet/test_nft_wallet.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/simple_sync/test_simple_sync_protocol.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/_tests/wallet/test_notifications.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/_tests/wallet/test_wallet.py
  chia/_tests/wallet/test_wallet_action_scope.py
  chia/_tests/wallet/test_wallet_node.py
  chia/_tests/wallet/test_wallet_retry.py
  chia/_tests/wallet/test_wallet_state_manager.py
  chia/_tests/wallet/vc_wallet/test_vc_wallet.py
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/util.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/simulator/full_node_simulator.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/cat_wallet/dao_cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/notification_manager.py
  chia/wallet/puzzles/tails.py
  chia/wallet/trade_manager.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
Labels: Added, coverage-diff

#18329 Crawler Loop Fix + Test Improvements
  chia/_tests/conftest.py
  chia/_tests/core/test_crawler.py
  chia/seeder/crawl_store.py
  chia/seeder/crawler.py
  chia/seeder/start_crawler.py
  chia/simulator/setup_services.py
Labels: Fixed, Exclude_Notes

#18332 publish torrent for prereleases as well as full releases
  .github/workflows/reflow-publish-installer.yml
Labels: Changed, CI

#18331 correct secret passing to new `reflow-publish-installer`
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: Fixed, CI

#18333 [CHIA-959] Conform to CHIP-0029
  chia/_tests/core/test_rpc_util.py
  chia/_tests/wallet/test_clvm_streamable.py
  chia/wallet/util/clvm_streamable.py
Labels: Fixed

#18334 [CHIA-958] In cmd class framework: help -> short_help
  chia/cmds/cmd_classes.py
Labels: Changed

#18335 consistently use concurrency-name (including correcting errors)
  .github/workflows/reflow-publish-installer.yml
  .github/workflows/test-single.yml
  .github/workflows/test.yml
Labels: Fixed, CI

#18336 friendly name for installer publishing jobs
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
Labels: Changed, CI

#18338 only upload torrent for gui installers
  .github/workflows/reflow-publish-installer.yml
Labels: Changed, CI

#18342 disable keyring for poetry
  poetry.toml
Labels: Fixed, Exclude_Notes

#18328 more variable quoting in `setup-poetry.sh`
  setup-poetry.sh
Labels: Fixed, Exclude_Notes

#18341 CHIA-942 Use launcher_id as the primary key when updating (current) pool config.
  chia/pools/pool_config.py
Labels: Fixed

#17196 Add keychain support and placeholder for vault wallet
  chia/_tests/cmds/wallet/test_vault.py
  chia/_tests/core/util/test_keychain.py
  chia/_tests/wallet/test_main_wallet_protocol.py
  chia/_tests/wallet/vault/test_vault_clsp.py
  chia/_tests/wallet/vault/test_vault_lifecycle.py
  chia/_tests/wallet/vault/test_vault_wallet.py
  chia/cmds/chia.py
  chia/cmds/vault.py
  chia/cmds/vault_funcs.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/util/keychain.py
  chia/wallet/puzzles/deployed_puzzle_hashes.json
  chia/wallet/puzzles/p2_singleton_via_delegated_puzzle_safe.clsp
  chia/wallet/puzzles/p2_singleton_via_delegated_puzzle_safe.clsp.hex
  chia/wallet/puzzles/singleton_top_layer_v1_1.py
  chia/wallet/puzzles/vault_p2_recovery.clsp
  chia/wallet/puzzles/vault_p2_recovery.clsp.hex
  chia/wallet/vault/vault_drivers.py
  chia/wallet/vault/vault_info.py
  chia/wallet/vault/vault_root.py
  chia/wallet/vault/vault_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_puzzle_store.py
  chia/wallet/wallet_singleton_store.py
  chia/wallet/wallet_state_manager.py
Labels: Added, coverage-diff

#18344 update cryptography, remove ecdsa dependency
  chia/_tests/wallet/vault/test_vault_clsp.py
  chia/_tests/wallet/vault/test_vault_lifecycle.py
  chia/_tests/wallet/vault/test_vault_wallet.py
  chia/ssl/create_ssl.py
  chia/wallet/vault/vault_wallet.py
  setup.py
Labels: Fixed

#18339 CHIA-590: Add in connect timeout to DL http download
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/data_layer.py
  chia/data_layer/download_data.py
  chia/util/initial-config.yaml
Labels: Added

#18325 Remove dangling reference to twine
  poetry.lock
  pyproject.toml
Labels: Fixed

#18358 update link for chia guide during install
  Install.ps1
  install.sh
Labels: Fixed, Exclude_Notes

#18360 move poetry plugin installation to poetry setup scripts
  Install.ps1
  Setup-poetry.ps1
  install.sh
  setup-poetry.sh
Labels: Changed, Exclude_Notes

#18359 [CHIA-1008] Make vault endpoints more paradigmatic
  chia/_tests/cmds/wallet/test_vault.py
  chia/_tests/wallet/vault/test_vault_wallet.py
  chia/cmds/vault_funcs.py
  chia/rpc/wallet_request_types.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
Labels: Changed, coverage-diff

#16881 refactor new_peak_timelord
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/timelord/test_new_peak.py
  chia/consensus/blockchain.py
  chia/simulator/block_tools.py
  chia/timelord/timelord_api.py
Labels: timelord, Fixed

#18365 [CHIA-1032] Add a config slot in action scopes and use it for wallets
  chia/_tests/util/test_action_scope.py
  chia/rpc/util.py
  chia/rpc/wallet_rpc_api.py
  chia/util/action_scope.py
  chia/wallet/wallet_action_scope.py
Labels: Added, Exclude_Notes

#18357 add `poetry check` ... well, check
  .github/workflows/upload-pypi-source.yml
  .pre-commit-config.yaml
  activated.ps1
  activated.py
  activated.sh
Labels: Added, CI

#18356 build both sdist and wheel for upload to pypi
  .github/workflows/upload-pypi-source.yml
Labels: Added

#18361 [CHIA-1024] Fix wallet observer mode log in while non-observer keys are present
  chia/_tests/wallet/test_wallet_node.py
  chia/daemon/keychain_proxy.py
  chia/wallet/wallet_node.py
Labels: Fixed

#18167 Send harvester version in pool partial header
  chia/_tests/farmer_harvester/test_farmer.py
  chia/farmer/farmer_api.py
Labels: Added, community-pr

#18369 [CHIA-1033] Fix flaky pool RPC test
  chia/_tests/pools/test_pool_rpc.py
Labels: ready_to_merge, Fixed, Exclude_Notes

#18327 CHIA-945 Remove no longer needed TestWalletKeyValStore class
  chia/_tests/wallet/test_wallet_key_val_store.py
Labels: Changed, Cleanup

#18326 CHIA-944 Simplify Mempool's get_items_by_coin_ids
  chia/full_node/mempool.py
Labels: Changed, Cleanup

#18368 convert make_solution to async
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/test_main_wallet_protocol.py
  chia/_tests/wallet/vault/test_vault_wallet.py
  chia/data_layer/data_layer_wallet.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/cat_wallet/dao_cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/puzzles/tails.py
  chia/wallet/vault/vault_wallet.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_protocol.py
  chia/wallet/wallet_state_manager.py
Labels: Added

#18366 Add get version RPC method for all services
  chia/_tests/core/test_full_node_rpc.py
  chia/_tests/util/rpc.py
  chia/rpc/rpc_server.py
Labels: RPC, Added

#18371 checkpoint: into main from release/2.4.3 @ 6a5d84d17d49a1a65520c8b56a413b648441d482
  chia/_tests/wallet/test_wallet_node.py
  chia/daemon/keychain_proxy.py
  chia/wallet/wallet_node.py
Labels: checkpoint_merge, Changed

#18346 Fixed missing partial count was incorrectly incremented on solo plotNFT farming
  chia/_tests/farmer_harvester/test_farmer.py
  chia/farmer/farmer_api.py
Labels: Fixed

#18372 [CHIA-1009] Add @tx_out_cmd to vault_create and dedup transaction output code
  chia/_tests/cmds/wallet/test_vault.py
  chia/cmds/cmds_util.py
  chia/cmds/vault.py
  chia/cmds/vault_funcs.py
Labels: Changed, coverage-diff, vault

#18381 Update Managed Files
  .prettierrc.yaml
Labels: Changed, Exclude_Notes
