Repository Chia-Network/chia-blockchain, pull requests merged in 2024-09, with the labels that each got.

#18543 Bump chia rs 0.13.0
  chia/_tests/util/test_replace_str_to_bytes.py
  chia/consensus/default_constants.py
  poetry.lock
  pyproject.toml
Labels: ready_to_merge, Changed

#18517 update long-reorg tests along with the reorg test chains
  .github/workflows/benchmarks.yml
  .github/workflows/test-single.yml
  chia/_tests/conftest.py
  chia/_tests/core/full_node/test_full_node.py
Labels: ready_to_merge, Changed

#18547 comment out test code that's not executed
  chia/_tests/blockchain/test_blockchain.py
Labels: ready_to_merge, Changed, Tests

#18540 [CHIA-1234] Add bech32m options to some key functions
  chia/_tests/core/cmds/test_keys.py
  chia/cmds/keys.py
  chia/cmds/keys_funcs.py
Labels: ready_to_merge, Added

#18538 [CHIA-1218] Raise on too much decimal precision in CLI
  chia/_tests/cmds/test_click_types.py
  chia/_tests/cmds/wallet/test_vcs.py
  chia/cmds/param_types.py
Labels: ready_to_merge, Fixed

#18500 Remove the coin amount from state layer solution
  chia/wallet/nft_wallet/metadata_outer_puzzle.py
Labels: Wallet, ready_to_merge, NFT, Fixed

#18530 [CHIA-1164] Port `test_nft_wallet.py` to `WalletTestFramework`
  chia/_tests/wallet/nft_wallet/test_nft_wallet.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge, Changed, Tests, Exclude_Notes

#18534 CHIA-1247 Use blockchain_constants to ensure hard fork behavior in test_fill_rate_block_validation
  chia/_tests/core/mempool/test_mempool_manager.py
Labels: Changed, Cleanup

#18551 increase compatibility with upload action v4.4.0
  .github/workflows/test-single.yml
Labels: Fixed, CI

#18546 Fix BrokenProcessPool error for Windows installer blueboxing
  chia/timelord/timelord.py
Labels: Fixed

#18525 add test targets just for pre-generating the test chains
  chia/_tests/blockchain/test_build_chains.py
  pytest.ini
Labels: Added, Tests

#18557 CHIA-1291 Switch mempool TX prevalidation to the Rust version
  benchmarks/mempool-long-lived.py
  benchmarks/mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/clvm/spend_sim.py
  chia/full_node/full_node.py
  chia/full_node/mempool_manager.py
  chia/rpc/full_node_rpc_api.py
  chia/types/eligible_coin_spends.py
Labels: Changed

#18501 [CHIA-1165] Add `--valid-at/--expires-at` to all CLI transaction endpoints (mostly hidden)
  chia/_tests/cmds/cmd_test_utils.py
  chia/_tests/cmds/test_timelock_args.py
  chia/_tests/cmds/wallet/test_coins.py
  chia/_tests/cmds/wallet/test_dao.py
  chia/_tests/cmds/wallet/test_did.py
  chia/_tests/cmds/wallet/test_nft.py
  chia/_tests/cmds/wallet/test_notifications.py
  chia/_tests/cmds/wallet/test_tx_decorators.py
  chia/_tests/cmds/wallet/test_vcs.py
  chia/_tests/cmds/wallet/test_wallet.py
  chia/cmds/cmds_util.py
  chia/cmds/coin_funcs.py
  chia/cmds/coins.py
  chia/cmds/dao.py
  chia/cmds/dao_funcs.py
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_client.py
Labels: ready_to_merge, Added

#18559 Remove chia-seeder.h9.com
  chia/util/initial-config.yaml
Labels: Changed, Exclude_Notes

#18563 Remove initial_freeze_period from RPCs
  chia/rpc/full_node_rpc_api.py
  chia/rpc/wallet_rpc_api.py
Labels: ready_to_merge, Changed

#18536 [CHIA-1174] Extract coin combining logic from CLI to RPC
  chia/_tests/cmds/wallet/test_coins.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/cmds/coin_funcs.py
  chia/cmds/coins.py
  chia/rpc/wallet_request_types.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/wallet_coin_store.py
Labels: ready_to_merge, Changed

#18531 Refactor `get_block_generator()`
  benchmarks/block_ref.py
  benchmarks/block_store.py
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/blockchain/test_get_block_generator.py
  chia/_tests/core/full_node/stores/test_block_store.py
  chia/_tests/util/blockchain_mock.py
  chia/consensus/blockchain.py
  chia/consensus/blockchain_interface.py
  chia/consensus/get_block_generator.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/block_store.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/rpc/full_node_rpc_api.py
Labels: ready_to_merge, Changed, Cleanup

#18469 refactor pre_validate_blocks_multiprocessing
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/full_node/test_node_load.py
  chia/_tests/core/mempool/test_mempool_performance.py
  chia/_tests/util/full_sync.py
  chia/_tests/util/misc.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/_tests/wallet/test_wallet_blockchain.py
  chia/_tests/wallet/test_wallet_node.py
  chia/_tests/wallet/wallet_block_tools.py
  chia/consensus/block_body_validation.py
  chia/consensus/block_header_validation.py
  chia/consensus/blockchain.py
  chia/consensus/difficulty_adjustment.py
  chia/consensus/full_block_to_block_record.py
  chia/consensus/make_sub_epoch_summary.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
  chia/wallet/wallet_blockchain.py
  tools/test_full_sync.py
Labels: Blockchain team, ready_to_merge, full_node, Fixed, Cleanup, Performance

#18561 [CHIA-1302] Check to confirm external TXs submitted by wallet
  chia/_tests/wallet/test_wallet_state_manager.py
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge, Fixed

#18564 [CHIA-687] Remove dummy TX from trade manager take_offer
  chia/wallet/trade_manager.py
Labels: Changed, Exclude_Notes

#18571 [CHIA-1357] Correctly set `start_index` in `create_more_puzzle_hashes`
  chia/wallet/wallet_state_manager.py
Labels: Fixed

#18535 `AugmentedBlockchain`
  chia/_tests/blockchain/test_augmented_chain.py
  chia/_tests/blockchain/test_get_block_generator.py
  chia/consensus/blockchain.py
  chia/consensus/blockchain_interface.py
  chia/consensus/get_block_generator.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
  chia/util/augmented_chain.py
Labels: ready_to_merge, Changed

#18569 clean add block and prevalidation
  chia/_tests/blockchain/blockchain_test_utils.py
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/test_db_conversion.py
  chia/_tests/core/test_db_validation.py
  chia/_tests/farmer_harvester/test_third_party_harvesters.py
  chia/_tests/wallet/wallet_block_tools.py
  chia/_tests/weight_proof/test_weight_proof.py
  chia/consensus/blockchain.py
  chia/consensus/full_block_to_block_record.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
  chia/simulator/block_tools.py
  chia/simulator/full_node_simulator.py
Labels: Blockchain team, Fixed, Cleanup

#18510 optimize datalayer hashing
  chia/_tests/core/data_layer/test_data_layer_util.py
  chia/data_layer/data_layer_util.py
Labels: Changed, Exclude_Notes

#18580 [CHIA-1346] Add a full node RPC client to `WalletTestFramework`
  chia/_tests/environments/wallet.py
  chia/_tests/wallet/conftest.py
  chia/_tests/wallet/test_wallet_test_framework.py
Labels: ready_to_merge, Added, Tests

#18579 [CHIA-1069] Use smarter coin selection algorithm for DAO wallet `select_coins_for_asset_type`
  chia/wallet/dao_wallet/dao_wallet.py
Labels: Changed

#18578 [CHIA-1204] Add missing client endpoints for corresponding Wallet RPC endpoints
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/did_wallet/test_did.py
  chia/_tests/wallet/nft_wallet/test_nft_wallet.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/test_wallet.py
  chia/rpc/wallet_request_types.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
Labels: Added

#18572 [CHIA-1359] Fix action scope callbacks across multiple `.use` calls
  chia/_tests/util/test_action_scope.py
  chia/util/action_scope.py
Labels: Fixed, Exclude_Notes

#18516 [CHIA-1211] Use better key resolution logic in derivation commands
  chia/_tests/core/cmds/test_keys.py
  chia/cmds/keys.py
  chia/cmds/keys_funcs.py
Labels: ready_to_merge, Fixed

#18452 chore: fix some comments
  chia/_tests/clvm/test_program.py
  chia/_tests/util/test_action_scope.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/cmds/signer.py
  chia/wallet/vc_wallet/vc_puzzles/eml_covenant_morpher.clsp
Labels: Fixed, ready_to_review, community-pr

#18485 chore: fix some comments
  benchmarks/streamable.py
  build_scripts/remove_brew_rpaths.sh
  chia/server/server.py
  chia/util/action_scope.py
Labels: Changed, community-pr

#18487 chore: fix some comments
  chia/rpc/wallet_rpc_api.py
Labels: Fixed, community-pr

#18521 Fix new pool url detection
  chia/farmer/farmer.py
  chia/pools/pool_config.py
Labels: Fixed, ready_to_review, community-pr

#18558 Fixed logging for fast bluebox timelord and added Visual Studio (.vs)…
  .gitignore
  chia/timelord/timelord_launcher.py
Labels: Fixed, community-pr

#18466 [CHIA-1128] Generalize Keychain to support multiple key types
  chia/_tests/core/daemon/test_daemon.py
  chia/_tests/core/daemon/test_keychain_proxy.py
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/core/util/test_keychain.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/test_wallet_node.py
  chia/_tests/wallet/vault/test_vault_wallet.py
  chia/cmds/init_funcs.py
  chia/cmds/keys.py
  chia/cmds/keys_funcs.py
  chia/cmds/sim_funcs.py
  chia/daemon/keychain_proxy.py
  chia/daemon/keychain_server.py
  chia/daemon/server.py
  chia/farmer/farmer.py
  chia/plotting/check_plots.py
  chia/plotting/create_plots.py
  chia/rpc/wallet_rpc_api.py
  chia/simulator/block_tools.py
  chia/simulator/simulator_test_tools.py
  chia/util/keychain.py
  chia/wallet/wallet_node.py
Labels: ready_to_merge, Changed, vault

#18586 CHIA-1387 Simplify fetching TX data in create_bundle_from_mempool_items
  chia/full_node/mempool.py
Labels: Changed, Cleanup

#18585 CHIA-1377 Remove no longer needed tx_bytes in add_transaction
  chia/full_node/full_node.py
Labels: Changed, Cleanup

#18608 Add version number to every log line
  chia/util/chia_logging.py
Labels: Added

#18590 Port `test_trades.py` to `WalletTestFramework`
  chia/_tests/environments/wallet.py
  chia/_tests/wallet/cat_wallet/test_trades.py
  chia/wallet/trade_manager.py
Labels: Changed, Tests

#18541 multiprocess_validation refactor
  chia/_tests/blockchain/blockchain_test_utils.py
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/farmer_harvester/test_third_party_harvesters.py
  chia/consensus/blockchain.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
  chia/simulator/full_node_simulator.py
Labels: ready_to_merge, Changed

#18574 CHIA-1362 Deduct block overhead from the mempool's maximum block clvm cost limit
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/full_node/mempool_manager.py
Labels: ready_to_merge, Changed

#18622 CHIA-1454 Extend coins without building lists on each step in combine_coins
  chia/rpc/wallet_rpc_api.py
Labels: Changed, Cleanup

#18621 CHIA-1451 Remove no longer needed TestWalletInterestedStore class
  chia/_tests/wallet/test_wallet_interested_store.py
Labels: Changed, Cleanup

#18603 CHIA-1413 Annotate test_wallet_key_val_store.py
  chia/_tests/wallet/test_wallet_key_val_store.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#18623 [CHIA-1453] catchup: long_lived/vault from main @ 111b0e57d5995d760cac877c45ef8822506800b6
  chia/_tests/environments/wallet.py
  chia/_tests/wallet/cat_wallet/test_trades.py
  chia/full_node/full_node.py
  chia/full_node/mempool.py
  chia/util/chia_logging.py
  chia/wallet/trade_manager.py
  poetry.lock
  pyproject.toml
Labels: Changed, Exclude_Notes

#18593 [CHIA-1307] Port key management RPCs to `@marshal` decorator
  chia/_tests/cmds/test_cmd_framework.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/test_wallet_test_framework.py
  chia/cmds/cmds_util.py
  chia/data_layer/data_layer.py
  chia/rpc/wallet_request_types.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
Labels: ready_to_merge, Changed, Exclude_Notes

#18609 Revert "CHIA-645 Optimize build ancestors table. (#18100)"
  chia/data_layer/data_store.py
Labels: Changed

#18640 [CHIA-1486] Update to macOS 13 for build and test
  .github/workflows/build-macos-installers.yml
  .github/workflows/check_wheel_availability.yaml
  .github/workflows/pre-commit.yml
  .github/workflows/test-install-scripts.yml
  .github/workflows/test.yml
  .github/workflows/upload-pypi-source.yml
Labels: Changed

#18628 CHIA-1465 Simplify double spend validation in validate_block_body
  chia/consensus/block_body_validation.py
Labels: Changed, Cleanup

#18643 Bump chia rs 0.14.0
  chia/_tests/clvm/test_program.py
  chia/_tests/core/full_node/test_conditions.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/mempool_manager.py
  chia/types/blockchain_format/program.py
  poetry.lock
  pyproject.toml
Labels: Changed

#18602 [CHIA-1087] Simplify batch pre validate blocks
  chia/consensus/block_body_validation.py
  chia/consensus/blockchain.py
  chia/consensus/multiprocess_validation.py
Labels: ready_to_merge, Changed

#18632 remove no-wallet-found traceback from `/dl_owned_singletons`
  chia/rpc/wallet_rpc_api.py
Labels: Fixed

#18610 [CHIA-1437]: Reduce level log spam when downloading DAT files
  chia/data_layer/download_data.py
Labels: Changed

#18644 CHIA-1491 Annotate test_wallet_interested_store.py
  chia/_tests/wallet/test_wallet_interested_store.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#18639 CHIA-1485 Simplify calling pre_validate_spendbundle and avoid spend vs spend bundle confusion
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/full_node/mempool_manager.py
  chia/rpc/full_node_rpc_api.py
Labels: Changed, Cleanup

#18612 [CHIA-1427]: Limit full file creation when processing subscription generations
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/data_layer.py
  chia/data_layer/download_data.py
Labels: Changed

#18645 maybe fixup main coverage diff
  .github/workflows/test.yml
Labels: Fixed, CI
