Repository Chia-Network/chia-blockchain, pull requests merged in 2024-08, with the labels that each got.

#18367 Explore logging the time create_bundle_from_mempool_items takes
  chia/full_node/mempool.py
Labels: Changed, Cleanup

#18340 CHIA-982 Simplify Mempool's items_by_feerate
  chia/full_node/mempool.py
Labels: Changed, Cleanup

#18286 CHIA-907 Augment uncurry_puzzle to accept both types of programs
  chia/_tests/wallet/did_wallet/test_did.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/vc_wallet/test_vc_lifecycle.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/cat_wallet/cat_outer_puzzle.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/singleton_outer_puzzle.py
  chia/wallet/trading/offer.py
  chia/wallet/uncurried_puzzle.py
  chia/wallet/vc_wallet/cr_cat_drivers.py
  chia/wallet/vc_wallet/vc_drivers.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet_state_manager.py
Labels: Changed, Cleanup

#17688 [CHIA-299] DL separate DAT files in folders by store id
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_server.py
  chia/data_layer/download_data.py
  chia/data_layer/s3_plugin_service.py
  chia/util/initial-config.yaml
Labels: Changed, DataLayer

#18379 Resolve problems on Windows running the sub processes when in editable mode
  chia/_tests/cmds/test_daemon.py
  chia/cmds/start_funcs.py
  chia/daemon/server.py
Labels: Fixed, Exclude_Notes

#18378 [CHIA-1015] Add a `fee` option to `push_transactions`
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
Labels: ready_to_merge, Added

#18302 remove `block_height_list` from `BlockGenerator`
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/core/full_node/stores/test_coin_store.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/test_cost_calculation.py
  chia/_tests/generator/test_generator_types.py
  chia/_tests/generator/test_rom.py
  chia/_tests/util/generator_tools_testing.py
  chia/_tests/util/run_block.py
  chia/consensus/block_creation.py
  chia/consensus/blockchain.py
  chia/full_node/bundle_tools.py
  chia/full_node/generator.py
  chia/simulator/block_tools.py
  chia/types/generator_types.py
  tools/generate_chain.py
Labels: Changed

#18383 checkpoint: into main from release/2.4.3 @ c0a2db44dc3662c428b0ea93e102e285f15f620d
  chia/_tests/farmer_harvester/test_farmer.py
  chia/farmer/farmer_api.py
Labels: checkpoint_merge, Changed

#18391 checkpoint: into main from release/2.4.3 @ d260e816f01e1d63d68c82d4be8af82d0f8ac222
  chia/_tests/pools/test_pool_rpc.py
Labels: checkpoint_merge, Changed

#18385 Add wEURC.b to the list of known assets
  chia/wallet/cat_wallet/cat_constants.py
Labels: Added, community-pr

#18393 checkpoint: into main from release/2.4.3 @ 7e057ca5fdd1c2917f2fcfb260dc22a1b85d5f75
  chia/_tests/core/test_full_node_rpc.py
  chia/_tests/util/rpc.py
  chia/rpc/rpc_server.py
Labels: checkpoint_merge, Changed

#18388 Display sync percentage in 'chia show -s'
  chia/cmds/show_funcs.py
Labels: Changed

#18405 [CHIA-1065] Set public key when you find private key in wallet node
  chia/_tests/wallet/test_wallet_node.py
  chia/wallet/wallet_node.py
Labels: ready_to_merge, Fixed

#18386 Set correct empty/default value for pool_public_keys
  chia/util/initial-config.yaml
Labels: Changed, Exclude_Notes

#18401 checkpoint: into main from release/2.4.3 @ 7b777e7db7c7de0e53f30ba36198f56c9dc1a584
  chia/_tests/cmds/test_daemon.py
  chia/cmds/start_funcs.py
  chia/daemon/server.py
Labels: checkpoint_merge, Changed

#18392 Increase timeout for test_create_coins_with_amounts
  chia/_tests/simulation/test_simulator.py
Labels: Fixed, CI, Exclude_Notes

#18421 checkpoint: into main from release/2.4.3 @ 508917f71a79af3f52852d3cfb518b45e3553504
  chia/wallet/cat_wallet/cat_constants.py
Labels: checkpoint_merge, Changed

#18409 [CHIA-1010] Add cost logging to vault CLVM tests
  chia/_tests/wallet/vault/test_vault_lifecycle.py
Labels: Added, Tests

#18387 Make 'chia plotnft -f fingerprint -i wallet_id' output JSON
  chia/cmds/plotnft_funcs.py
Labels: Changed

#18423 checkpoint: into main from release/2.4.3 @ fd5f794e2de54681a5e9df6a621fd7a7dc0a760e
  chia/_tests/wallet/test_wallet_node.py
  chia/wallet/wallet_node.py
Labels: checkpoint_merge, Changed

#18166 CHIA-783: Stop auto-subscribing to local stores
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/data_layer/data_layer.py
Labels: Changed

#18408 Remove unused (kinda) functionality
  chia/data_layer/data_layer_wallet.py
Labels: ready_to_merge, Changed, Exclude_Notes

#18425 checkpoint: into main from release/2.4.3 @ 9c49b1e61e6095758d5f1793cebdade06ad9ac6a
  chia/util/initial-config.yaml
Labels: checkpoint_merge, Changed

#18370 CHIA-902 make Program.run() and Program.run_with_cost() default to enabling all the most recent features
  chia/_tests/clvm/test_program.py
  chia/types/blockchain_format/program.py
Labels: Changed

#18429 bump chia_rs to 0.11.0
  chia/full_node/mempool_check_conditions.py
  chia/types/blockchain_format/program.py
  poetry.lock
  pyproject.toml
Labels: Changed

#18430 checkpoint: into main from release/2.4.3 @ d1464da947f04554e8680009539b80723c65cef7
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/data_layer/data_layer.py
Labels: checkpoint_merge, Changed

#18427 CHIA-1084: Address some problems launching the daemon from the GUI on Windows
  chia/cmds/start_funcs.py
Labels: Fixed, Exclude_Notes

#18384 Update wallets for mandatory action_scope in make_solution
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/test_main_wallet_protocol.py
  chia/data_layer/data_layer_wallet.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/cat_wallet/dao_cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/puzzles/tails.py
  chia/wallet/vault/vault_wallet.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_protocol.py
  chia/wallet/wallet_state_manager.py
Labels: Added, vault

#18444 checkpoint: into main from release/2.4.3 @ 3d0bc95341fe56f8e37f8ed3194f63c176b598f6
  chia/cmds/start_funcs.py
Labels: checkpoint_merge, Changed

#18407 remove soft-fork 4 special cases
  chia/_tests/conftest.py
  chia/_tests/core/full_node/test_conditions.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/util/test_replace_str_to_bytes.py
  chia/_tests/util/test_testnet_overrides.py
  chia/cmds/sim_funcs.py
  chia/consensus/default_constants.py
  chia/full_node/mempool_check_conditions.py
  chia/util/initial-config.yaml
Labels: Changed

#18459 wait for it
  chia/_tests/simulation/test_simulator.py
Labels: Fixed, Tests

#18442 CHIA-1087: log the rate at which blocks are added during long sync
  chia/full_node/full_node.py
Labels: Changed

#18439 [CHIA-1092] Port `test_cat_wallet.py` to `WalletTestFramework`
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/conftest.py
  chia/simulator/full_node_simulator.py
Labels: Changed, Exclude_Notes

#18112 CHIA-420 remove `Backend*` warning ignores
  poetry.lock
  pytest.ini
Labels: stale-pr, Changed

#18448 [CHIA-1102] catchup: long_lived/vault from main @ 495593089b106371bf9dacd2ee5ece7f156a25f1
  chia/_tests/clvm/test_program.py
  chia/_tests/clvm/test_puzzle_drivers.py
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/core/data_layer/util.py
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/cmds/plotnft_funcs.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_wallet.py
  chia/full_node/mempool_check_conditions.py
  chia/types/blockchain_format/program.py
  chia/util/initial-config.yaml
  chia/util/streamable.py
  chia/wallet/util/clvm_streamable.py
  poetry.lock
  pyproject.toml
Labels: Changed, Exclude_Notes

#18453 [CHIA-1123] Add `SecretInfo` and `Signature` to key scheme protocols
  chia/util/observation_root.py
  chia/util/secret_info.py
Labels: Added, Exclude_Notes, vault

#18455 [CHIA-1124] Deduplicate keychain code a bit
  chia/cmds/passphrase_funcs.py
  chia/legacy/keyring.py
  chia/util/keychain.py
Labels: Changed, Exclude_Notes, vault

#18471 Deduplicate keychain code a bit
  chia/cmds/passphrase_funcs.py
  chia/legacy/keyring.py
  chia/util/keychain.py
Labels: ready_to_merge, Changed, Exclude_Notes

#18468 CHIA-1122 Simplify validate_block_body
  chia/consensus/block_body_validation.py
  chia/consensus/blockchain.py
Labels: Changed, Cleanup

#18445 refine streamable field typing to avoid an ignore
  chia/wallet/util/clvm_streamable.py
Labels: Fixed, Exclude_Notes

#18415 [CHIA-1068] Utilize streamable for `WalletSideEffects` serialization
  chia/wallet/wallet_action_scope.py
Labels: ready_to_merge, Changed, Exclude_Notes

#18446 more `bytes32.from_hexstr()`
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/cmds/plotnft_funcs.py
  chia/pools/pool_wallet_info.py
  chia/rpc/data_layer_rpc_api.py
  chia/rpc/farmer_rpc_api.py
  chia/rpc/full_node_rpc_client.py
  chia/rpc/wallet_rpc_api.py
  chia/simulator/simulator_full_node_rpc_client.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/cat_wallet/dao_cat_wallet.py
Labels: Changed, Exclude_Notes

#18473 bump chia_rs to 0.12.0
  chia/full_node/mempool_check_conditions.py
  chia/types/blockchain_format/program.py
  chia/types/spend_bundle_conditions.py
  poetry.lock
  pyproject.toml
Labels: Changed

#18470 [CHIA-1115] Optimize `create_coins_with_amounts` a bit
  chia/simulator/full_node_simulator.py
Labels: ready_to_merge, Fixed, Exclude_Notes

#18467 Timelord logging: Updated peak to hex from bytestring
  chia/timelord/timelord_state.py
Labels: timelord, Fixed, Logging, ready_to_review

#18435 Replace `get_flags_for_height_and_constants()` with Rust version
  chia/full_node/mempool_check_conditions.py
Labels: Changed

#18309 simplify the concurrency group
  .github/workflows/benchmarks.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
  .github/workflows/check-commit-signing.yml
  .github/workflows/check_wheel_availability.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/pre-commit.yml
  .github/workflows/super-linter.yml
  .github/workflows/test-install-scripts.yml
  .github/workflows/test-single.yml
  .github/workflows/test.yml
  .github/workflows/trigger-docker-dev.yml
  .github/workflows/trigger-docker-main.yml
  .github/workflows/upload-pypi-source.yml
Labels: Changed, CI

#18456 [CHIA-1125] Implement secp256r1 wrappers
  chia/_tests/util/test_secp256r1.py
  chia/util/key_types.py
Labels: Added, vault

#18479 poetry cache
  .github/workflows/benchmarks.yml
  .github/workflows/build-windows-installer.yml
  .github/workflows/test-single.yml
Labels: Changed, Exclude_Notes

#18424 [CHIA-1067] Integrate coin selection with action scopes
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/dao_wallet/test_dao_wallets.py
  chia/_tests/wallet/did_wallet/test_did.py
  chia/_tests/wallet/nft_wallet/test_nft_bulk_mint.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/_tests/wallet/test_wallet.py
  chia/_tests/wallet/test_wallet_action_scope.py
  chia/_tests/wallet/test_wallet_state_manager.py
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/cat_wallet/dao_cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/notification_manager.py
  chia/wallet/puzzles/tails.py
  chia/wallet/trade_manager.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_action_scope.py
  chia/wallet/wallet_protocol.py
Labels: ready_to_merge, Changed, Exclude_Notes

#18494 Source offer confirmed height from original coin state
  chia/wallet/trade_manager.py
Labels: Fixed

#18495 [CHIA-1182] catchup: long_lived/vault from main @ 0a76e22489513ac0add5e31ca27b78a1c074536b
  chia/_tests/conftest.py
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/core/full_node/test_conditions.py
  chia/_tests/core/full_node/test_generator_tools.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/fee_estimation/test_fee_estimation_integration.py
  chia/_tests/generator/test_rom.py
  chia/_tests/simulation/test_simulator.py
  chia/_tests/util/test_condition_tools.py
  chia/_tests/util/test_replace_str_to_bytes.py
  chia/_tests/util/test_testnet_overrides.py
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/conftest.py
  chia/cmds/plotnft_funcs.py
  chia/cmds/sim_funcs.py
  chia/cmds/start_funcs.py
  chia/consensus/block_body_validation.py
  chia/consensus/blockchain.py
  chia/consensus/default_constants.py
  chia/full_node/full_node.py
  chia/full_node/mempool_check_conditions.py
  chia/pools/pool_wallet_info.py
  chia/rpc/data_layer_rpc_api.py
  chia/rpc/farmer_rpc_api.py
  chia/rpc/full_node_rpc_client.py
  chia/rpc/wallet_rpc_api.py
  chia/simulator/full_node_simulator.py
  chia/simulator/simulator_full_node_rpc_client.py
  chia/timelord/timelord_state.py
  chia/types/blockchain_format/program.py
  chia/types/spend_bundle_conditions.py
  chia/util/condition_tools.py
  chia/util/initial-config.yaml
  chia/util/keychain.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/cat_wallet/dao_cat_wallet.py
  chia/wallet/util/clvm_streamable.py
  chia/wallet/wallet_action_scope.py
  poetry.lock
  pyproject.toml
  pytest.ini
Labels: Changed, Exclude_Notes, coverage-diff

#18458 [CHIA-1126] Remove `PrivateKey` type from wallet
  chia/_tests/wallet/test_main_wallet_protocol.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/_tests/wallet/test_wallet.py
  chia/_tests/wallet/test_wallet_node.py
  chia/_tests/wallet/test_wallet_state_manager.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/derivation_record.py
  chia/wallet/vault/vault_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_protocol.py
  chia/wallet/wallet_puzzle_store.py
  chia/wallet/wallet_state_manager.py
Labels: Changed, Exclude_Notes, vault

#18498 correct concurrency groups
  .github/workflows/benchmarks.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
  .github/workflows/check-commit-signing.yml
  .github/workflows/check_wheel_availability.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/pre-commit.yml
  .github/workflows/super-linter.yml
  .github/workflows/test-install-scripts.yml
  .github/workflows/test-single.yml
  .github/workflows/test.yml
  .github/workflows/trigger-docker-dev.yml
  .github/workflows/trigger-docker-main.yml
  .github/workflows/upload-pypi-source.yml
Labels: Fixed, CI

#18434 get_puzzle_and_solution_for_coin()
  chia/full_node/mempool_check_conditions.py
Labels: Changed

#18464 [CHIA-1127] Add Secp256r1 to `KeyTypes`
  chia/_tests/core/util/test_keychain.py
  chia/util/keychain.py
Labels: Added, vault

#18476 [CHIA-1156] Tweak `gather_signing_info` to work with multiple vaults and finish TXs
  chia/wallet/vault/vault_drivers.py
  chia/wallet/vault/vault_wallet.py
Labels: Changed, coverage-diff, vault

#18503 updated changelog for 2.4.3
  CHANGELOG.md
Labels: Changed

#18215 maybe re-enable wallet ignore block validation autouse fixture
  chia/_tests/wallet/conftest.py
Labels: stale-pr, Fixed, Tests

#18484 `pre_validate_blocks_multiprocessing` Warm up the cache once per batch
  chia/consensus/multiprocess_validation.py
Labels: ready_to_merge, Changed

#18477 [CHIA-1036] Refer to separate recovery transactions by IDs
  chia/_tests/cmds/wallet/test_vault.py
  chia/cmds/vault_funcs.py
  chia/rpc/util.py
  chia/rpc/wallet_request_types.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/vault/vault_wallet.py
Labels: Changed, Exclude_Notes, coverage-diff, vault

#18486 `BlockchainInterface` as a protocol
  chia/_tests/core/full_node/stores/test_full_node_store.py
  chia/_tests/util/blockchain_mock.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/_tests/weight_proof/test_weight_proof.py
  chia/consensus/block_creation.py
  chia/consensus/block_header_validation.py
  chia/consensus/blockchain.py
  chia/consensus/blockchain_interface.py
  chia/consensus/difficulty_adjustment.py
  chia/consensus/full_block_to_block_record.py
  chia/consensus/get_block_challenge.py
  chia/consensus/make_sub_epoch_summary.py
  chia/consensus/vdf_info_computation.py
  chia/full_node/full_node_store.py
  chia/full_node/weight_proof.py
  chia/simulator/block_tools.py
  chia/util/block_cache.py
  chia/util/prev_transaction_block.py
  chia/wallet/wallet_blockchain.py
Labels: ready_to_merge, Changed

#18508 CHIA-1101: update `BlockGenerator` type
  chia/_tests/core/full_node/stores/test_block_store.py
  chia/_tests/generator/test_rom.py
  chia/_tests/util/run_block.py
  chia/_tests/util/test_full_block_utils.py
  chia/consensus/blockchain.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/block_store.py
  chia/full_node/mempool_check_conditions.py
  chia/simulator/block_tools.py
  chia/types/generator_types.py
  chia/util/full_block_utils.py
  tools/analyze-chain.py
Labels: ready_to_merge, Changed

#18514 fix long sync cache
  chia/_tests/core/full_node/test_full_node.py
  chia/consensus/blockchain.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
Labels: Blockchain team, full_node, Fixed

#18515 checkpoint: into main from release/2.4.3 @ 85ca5802143f6a7a0ec4e7c17c84e1ed9875770b
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#18526 CHIA-1214 Simplify Mempool::size()
  chia/full_node/mempool.py
Labels: Changed, Cleanup

#18509 CHIA-1198 Add an end to end test for mempool bundle fill rate and the resulting block validation
  chia/_tests/core/mempool/test_mempool_manager.py
Labels: ready_to_merge, Changed, Cleanup

#18480 [CHIA-1129] Extract coin splitting logic from CLI -> RPC
  chia/_tests/cmds/wallet/test_coins.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/cmds/coin_funcs.py
  chia/cmds/coins.py
  chia/rpc/wallet_request_types.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
Labels: ready_to_merge, Changed

#18482 Fix `request_fee_estimates`
  chia/full_node/full_node_api.py
Labels: Fixed, community-pr

#18264 CHIA-210 Introduce WalletSpendBundle and use it across code related to wallets
  benchmarks/mempool.py
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/cmds/cmd_test_utils.py
  chia/_tests/cmds/wallet/test_consts.py
  chia/_tests/cmds/wallet/test_did.py
  chia/_tests/cmds/wallet/test_nft.py
  chia/_tests/cmds/wallet/test_wallet.py
  chia/_tests/core/full_node/stores/test_block_store.py
  chia/_tests/core/full_node/stores/test_hint_store.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/test_full_node_rpc.py
  chia/_tests/wallet/cat_wallet/test_cat_lifecycle.py
  chia/_tests/wallet/cat_wallet/test_offer_lifecycle.py
  chia/_tests/wallet/cat_wallet/test_trades.py
  chia/_tests/wallet/clawback/test_clawback_lifecycle.py
  chia/_tests/wallet/dao_wallet/test_dao_clvm.py
  chia/_tests/wallet/db_wallet/test_db_graftroot.py
  chia/_tests/wallet/did_wallet/test_did.py
  chia/_tests/wallet/nft_wallet/test_nft_bulk_mint.py
  chia/_tests/wallet/nft_wallet/test_nft_lifecycle.py
  chia/_tests/wallet/nft_wallet/test_nft_wallet.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/test_debug_spend_bundle.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/_tests/wallet/test_singleton_lifecycle_fast.py
  chia/_tests/wallet/test_wallet_action_scope.py
  chia/_tests/wallet/test_wallet_retry.py
  chia/_tests/wallet/test_wallet_state_manager.py
  chia/_tests/wallet/test_wallet_trade_store.py
  chia/_tests/wallet/vc_wallet/test_vc_lifecycle.py
  chia/_tests/wallet/vc_wallet/test_vc_wallet.py
  chia/clvm/spend_sim.py
  chia/cmds/signer.py
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/util.py
  chia/rpc/wallet_request_types.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/types/spend_bundle.py
  chia/wallet/cat_wallet/cat_utils.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/cat_wallet/dao_cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/notification_manager.py
  chia/wallet/puzzles/tails.py
  chia/wallet/trade_manager.py
  chia/wallet/trading/offer.py
  chia/wallet/transaction_record.py
  chia/wallet/util/compute_memos.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_action_scope.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_protocol.py
  chia/wallet/wallet_spend_bundle.py
  chia/wallet/wallet_state_manager.py
Labels: Changed, Cleanup

#18539 [CHIA-1220] Fix confusing amount-related CLI help messages
  chia/cmds/coins.py
  chia/cmds/dao.py
  chia/cmds/wallet.py
Labels: Fixed
