Repository Chia-Network/chia-blockchain, pull requests merged in 2024-03, with the labels that each got.

#17628 checkpoint: into main from release/2.2.0 @ d3d0f1b9810309c81881718e44edda27d4a62d24
  chia/data_layer/download_data.py
  tests/core/data_layer/test_data_store.py
Labels: checkpoint_merge, Changed

#17652 checkpoint: into main from release/2.2.0 @ 1baff679fe8eaaf88a72716fbce149bd0921f617
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#17650 Various test flakiness fixes
  chia/full_node/full_node.py
  chia/simulator/full_node_simulator.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/conftest.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Fixed, Tests, Exclude_Notes

#17649 Delete incomplete test_singleton_lifecycle test
  mypy-exclusions.txt
  tests/wallet/test_singleton_lifecycle.py
Labels: ready_to_merge, Added, Tests, Exclude_Notes

#17648 remove fee-estimator command line tests
  tests/fee_estimation/cmdline_test.py
Labels: Fixed, Tests

#17630 Use WalletTestFramework for `test_cat_wallet::test_cat_spend`
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/wallet.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: ready_to_merge, Changed, Tests, Exclude_Notes

#17614 Update README.md links for wiki & faq sunset
  README.md
Labels: Changed

#17600 saturate aiosqlite, filelock, and watchdog logging at info level while testing
  tests/conftest.py
Labels: Changed, Tests

#17653 checkpoint: into main from release/2.2.1 @ b5ab1dd243812dd5296235f2683ed82ce69fdd52
  chia/plotters/bladebit.py
  chia/plotters/madmax.py
Labels: checkpoint_merge, Changed

#17642 Update CHANGELOG.md
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#17658 checkpoint: into main from release/2.2.1 @ 98cf7b472c87586f9c29c6f452f4459dd947b060
  SECURITY.md
Labels: checkpoint_merge, Changed

#17651 Port `test_nft_wallet.py::test_nft_wallet_creation_and_transfer` to `WalletTestFramework`
  chia/wallet/nft_wallet/nft_wallet.py
  tests/wallet/nft_wallet/test_nft_1_offers.py
  tests/wallet/nft_wallet/test_nft_offers.py
  tests/wallet/nft_wallet/test_nft_wallet.py
  tests/wallet/sync/test_wallet_sync.py
Labels: ready_to_merge, Changed, Tests, Exclude_Notes

#17663 checkpoint: into main from release/2.2.1 @ b98219687331fc6c8121d0c0243a49d2427ccd60
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#17666 `watchdog==4.0.0`
  chia/util/file_keyring.py
  setup.py
Labels: Changed, Exclude_Notes

#17662 Move get_network_info endpoint to the base rpc server class
  chia/rpc/full_node_rpc_api.py
  chia/rpc/rpc_server.py
  chia/rpc/wallet_rpc_api.py
  tests/core/test_full_node_rpc.py
  tests/util/rpc.py
Labels: Changed

#17669 fix non-development source install
  .github/actions/install/action.yml
  .github/workflows/test-install-scripts.yml
  Install.ps1
Labels: Fixed

#17667 Update README formatting and links
  README.md
Labels: Changed

#16454 Delete unconfirmed Clawback TX
  chia/wallet/wallet_state_manager.py
  tests/wallet/test_wallet.py
Labels: Fixed

#14423 Add Python 3.12 support
  .github/workflows/check_wheel_availability.yaml
  .github/workflows/test-single.yml
  Install.ps1
  chia/ssl/create_ssl.py
  install.sh
  setup.py
  tests/core/mempool/test_mempool_fee_protocol.py
Labels: Added

#17681 Revert "Delete unconfirmed Clawback TX"
  chia/wallet/wallet_state_manager.py
  tests/wallet/test_wallet.py
Labels: Fixed, Exclude_Notes

#17682 exclude 3.12 from main matrix
  .github/workflows/test-single.yml
Labels: Fixed, CI

#17580 Wallet Block Tools
  chia/simulator/full_node_simulator.py
  pytest.ini
  tests/simulation/test_simulation.py
  tests/wallet/conftest.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
  tests/wallet/sync/test_wallet_sync.py
  tests/wallet/test_wallet_blockchain.py
  tests/wallet/test_wallet_key_val_store.py
  tests/wallet/test_wallet_node.py
  tests/wallet/wallet_block_tools.py
Labels: Changed, Tests, Exclude_Notes

#17606 tighten up the check for duplicate UnfinishedBlocks before requesting
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/full_node_store.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/full_node/test_full_node.py
Labels: ready_to_merge, Fixed

#17499 Update black to 24.1.1 and update source as needed
  .flake8
  chia/cmds/cmds_util.py
  chia/cmds/wallet_funcs.py
  chia/consensus/block_record.py
  chia/daemon/server.py
  chia/data_layer/data_layer_wallet.py
  chia/farmer/farmer_api.py
  chia/full_node/full_node_api.py
  chia/full_node/weight_proof.py
  chia/plot_sync/sender.py
  chia/plotters/chiapos.py
  chia/pools/pool_wallet.py
  chia/rpc/data_layer_rpc_util.py
  chia/rpc/rpc_server.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/server/api_protocol.py
  chia/server/chia_policy.py
  chia/server/ws_connection.py
  chia/simulator/block_tools.py
  chia/simulator/full_node_simulator.py
  chia/simulator/simulator_test_tools.py
  chia/util/async_pool.py
  chia/util/hash.py
  chia/util/keyring_wrapper.py
  chia/util/misc.py
  chia/util/struct_stream.py
  chia/util/timing.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/conditions.py
  chia/wallet/driver_protocol.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/puzzles/p2_delegated_conditions.py
  chia/wallet/puzzles/p2_delegated_puzzle_or_hidden_puzzle.py
  chia/wallet/trade_manager.py
  chia/wallet/util/puzzle_decorator.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_nft_store.py
  chia/wallet/wallet_protocol.py
  chia/wallet/wallet_state_manager.py
  pylintrc
  setup.py
  tests/conftest.py
  tests/core/data_layer/util.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/server/serve.py
  tests/core/services/test_services.py
  tests/core/util/test_keyring_wrapper.py
  tests/environments/common.py
  tests/environments/wallet.py
  tests/farmer_harvester/test_farmer.py
  tests/util/misc.py
  tests/util/test_network_protocol_files.py
  tests/wallet/cat_wallet/test_trades.py
  tests/wallet/conftest.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_wallet.py
  tests/wallet/vc_wallet/test_vc_lifecycle.py
  tools/manage_clvm.py
Labels: Changed, Exclude_Notes

#17396 prettier
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/benchmarks.yml
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
  .github/workflows/check-commit-signing.yml
  .github/workflows/check_wheel_availability.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependency-review.yml
  .github/workflows/pre-commit.yml
  .github/workflows/stale-issue.yml
  .github/workflows/super-linter.yml
  .github/workflows/test-install-scripts.yml
  .github/workflows/test-single.yml
  .github/workflows/test.yml
  .github/workflows/trigger-docker-dev.yml
  .github/workflows/trigger-docker-main.yml
  .github/workflows/upload-pypi-source.yml
  .markdown-lint.yml
  .pre-commit-config.yaml
  .prettierrc.yaml
  build_scripts/electron-builder.json
  chia/wallet/puzzles/deployed_puzzle_hashes.json
  tests/farmer_harvester/test_third_party_harvesters_data.json
  tests/tools/1315537.json
  tests/tools/1315544.json
  tests/tools/1315630.json
  tests/tools/300000.json
  tests/tools/466212.json
  tests/util/bip39_test_vectors.json
Labels: Changed, Cleanup

#17695 Speedup test_large_tx_record_query
  tests/wallet/test_transaction_store.py
Labels: Changed, Cleanup

#17700 flake8 ignore E226
  .flake8
  chia/cmds/wallet_funcs.py
  chia/consensus/block_header_validation.py
  chia/full_node/full_node.py
  chia/simulator/block_tools.py
Labels: Changed, CI, Exclude_Notes

#17684 new_unfinished_block2 support in seeder
  chia/seeder/crawler_api.py
Labels: Fixed

#17699 update black target versions
  pyproject.toml
Labels: Changed, CI

#17676 turned concatenation of strings to f-strings (from eukub)
  chia/seeder/dns_server.py
Labels: Changed

#17680 Optimize DL get key by node.
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/data_store.py
Labels: Fixed, DataLayer

#17573 Add `use_delta_sync` option
  chia/_tests/conftest.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/util/initial-config.yaml
  chia/wallet/wallet_node.py
Labels: enhancement, Wallet, Added

#17717 Add get_network_info to daemon
  chia/_tests/core/daemon/test_daemon.py
  chia/daemon/client.py
  chia/daemon/server.py
Labels: Added

#17704 Added `chia start daemon`
  chia/_tests/util/test_service_groups.py
  chia/cmds/stop.py
  chia/util/service_groups.py
Labels: Changed

#17710 use overrides for prettier config
  .prettierrc.yaml
Labels: Changed, Exclude_Notes

#17713 match manage clvm build indent to 2 spaces like prettier.io
  tools/manage_clvm.py
Labels: Fixed, Exclude_Notes

#17720 remove dead code in `multiprocess_validation`
  chia/consensus/multiprocess_validation.py
Labels: ready_to_merge, Changed

#17725 remove `blockchain_test*` from `.gitignore`
  .gitignore
Labels: Changed, Exclude_Notes

#17723 add Python 3.12 to mypy matrix
  .github/workflows/upload-pypi-source.yml
Labels: Added, CI

#17694 Rust HeaderBlock
  chia/_tests/wallet/test_wallet_blockchain.py
  chia/_tests/wallet/test_wallet_node.py
  chia/consensus/multiprocess_validation.py
  chia/types/header_block.py
Labels: ready_to_merge, Changed

#17687 Port `tests/wallet/test_wallet.py` to `WalletTestFramework`
  chia/_tests/environments/wallet.py
  chia/_tests/wallet/conftest.py
  chia/_tests/wallet/test_wallet.py
  chia/simulator/full_node_simulator.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge, Changed, Tests, Exclude_Notes

#17718 fix reorg from 0
  chia/_tests/blockchain/test_lookup_fork_chain.py
  chia/consensus/blockchain.py
  chia/consensus/find_fork_point.py
  chia/full_node/full_node.py
Labels: ready_to_merge, Fixed

#17646 test installers find plotters main
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
  chia/cmds/dev.py
  chia/cmds/installers.py
Labels: Added, CI, Tests

#17752 Fix defaults in send_transaction_multi
  chia/rpc/wallet_rpc_api.py
Labels: Fixed, Exclude_Notes

#17731 improve logging of the height-to-hash and sub-epoch-summaries cache
  chia/full_node/block_height_map.py
Labels: Changed

#17761 pip_cache_workaround
  .github/workflows/benchmarks.yml
Labels: Fixed, CI

#16903 Update key functions to handle observer only functionality
  chia/cmds/keys.py
  chia/cmds/keys_funcs.py
  chia/daemon/server.py
  chia/util/keychain.py
  chia/wallet/wallet.py
  tests/core/cmds/test_keys.py
  tests/wallet/test_signer_protocol.py
Labels: Changed, vault

#17756 use `cache-pip` action
  .github/workflows/benchmarks.yml
  .github/workflows/build-windows-installer.yml
  .github/workflows/test-single.yml
Labels: Changed, CI

#17764 Add test for observance of melted CAT balance
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/wallet/wallet_state_manager.py
Labels: ready_to_merge, Fixed

#17665 Some proof optimizations - use get_ancestors_optimized
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/data_layer/data_store.py
  chia/rpc/data_layer_rpc_api.py
Labels: Changed

#17664 Really fix Data layer download banning
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/data_store.py
  chia/data_layer/download_data.py
Labels: Fixed

#17753 correct testing of bans
  chia/_tests/conftest.py
  chia/_tests/core/server/test_dos.py
Labels: Fixed, Tests

#17758 Speedup key_hash in data_layer_util.py
  chia/data_layer/data_layer_util.py
Labels: Changed, Cleanup

#17759 Speedup leaf_hash in data_layer_util.py
  chia/data_layer/data_layer_util.py
Labels: Changed, Cleanup

#17729 chore: fix typos
  chia/_tests/core/util/test_files.py
  chia/_tests/util/test_trusted_peer.py
  chia/wallet/dao_wallet/dao_wallet.py
Labels: Changed, Exclude_Notes

#17698 matrix pre-commit ci against python version
  .github/workflows/pre-commit.yml
  activated.py
Labels: Added, CI

#17726 update to aiohttp 3.9.2
  chia/server/ws_connection.py
  setup.py
Labels: Changed

#17740 Correct launcher_id type in singleton_puzzle, p2_singleton_puzzle and their users
  chia/_tests/wallet/test_singleton.py
Labels: Changed, Cleanup

#17741 Properly construct CATCoinData's mod and tail program hashes in CATWallet's coin_added
  chia/wallet/cat_wallet/cat_wallet.py
Labels: Changed, Cleanup

#17743 Properly construct uint64 amounts for UnspentLineageInfo in get_unspent_lineage_info_for_puzzle_hash
  chia/full_node/coin_store.py
Labels: Changed, Cleanup

#17744 Improve UncurriedNFT construction through uncurry
  chia/wallet/nft_wallet/uncurry_nft.py
Labels: Changed, Cleanup

#17745 Properly construct uint64 objects for Coin amounts
  chia/_tests/core/test_cost_calculation.py
  chia/_tests/util/run_block.py
  chia/full_node/mempool_check_conditions.py
  chia/simulator/block_tools.py
  chia/simulator/wallet_tools.py
  chia/types/coin_spend.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/util/compute_memos.py
  chia/wallet/wallet_singleton_store.py
Labels: Changed, Cleanup

#17748 Handle some atoms' optionality in WalletStateManager's determine_coin_type
  chia/wallet/wallet_state_manager.py
Labels: Changed, Cleanup

#17770 switch to legacy-keyring as the extra name so it works
  install.sh
  setup.py
Labels: Fixed

#17747 Properly construct uint64 objects for LineageProof amounts in WalletSingletonStore's add_spend
  chia/wallet/wallet_singleton_store.py
Labels: Changed, Cleanup

#17746 Improve get_seconds_and_delayed_puzhash_from_p2_singleton_puzzle
  chia/pools/pool_puzzles.py
Labels: Changed, Cleanup

#16953 Broaden the `Keychain` definition of public keys to include more than BLS
  chia/_tests/core/daemon/test_daemon.py
  chia/_tests/core/daemon/test_keychain_proxy.py
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/core/util/test_keychain.py
  chia/_tests/wallet/test_wallet_node.py
  chia/cmds/keys_funcs.py
  chia/cmds/sim_funcs.py
  chia/daemon/keychain_proxy.py
  chia/daemon/keychain_server.py
  chia/daemon/server.py
  chia/legacy/keyring.py
  chia/rpc/wallet_rpc_api.py
  chia/simulator/block_tools.py
  chia/simulator/simulator_test_tools.py
  chia/util/keychain.py
  chia/util/observation_root.py
  chia/wallet/wallet_node.py
Labels: Changed, vault

#13374 DL: stop using fee config setting and remove from initial config
  chia/rpc/data_layer_rpc_api.py
  chia/util/initial-config.yaml
Labels: Changed, DataLayer

#17709 add foreign key delay
  chia/_tests/db/test_db_wrapper.py
  chia/_tests/util/db_connection.py
  chia/_tests/util/misc.py
  chia/util/db_wrapper.py
Labels: ready_to_merge, Added, Exclude_Notes, DataLayer

#17779 Optimize clean_node_table's query
  chia/data_layer/data_store.py
Labels: ready_to_merge, Changed, DataLayer

#17790 Wait for synced in NFT test
  chia/_tests/wallet/nft_wallet/test_nft_wallet.py
Labels: ready_to_merge, Fixed, Tests, Exclude_Notes

#17730 Don't download DL existing DAT files.
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/download_data.py
Labels: ready_to_merge, Fixed, DataLayer

#15679 Pass full version in `Handshake`
  chia/_tests/core/server/test_server.py
  chia/_tests/util/test_chia_version.py
  chia/cmds/init_funcs.py
  chia/daemon/server.py
  chia/plotters/plotters_util.py
  chia/seeder/crawler.py
  chia/server/start_service.py
  chia/server/ws_connection.py
  chia/util/chia_logging.py
  chia/util/chia_version.py
Labels: Changed

#17769 Speedup clean_node_table by leveraging relaxed foreign_keys
  chia/data_layer/data_layer.py
  chia/data_layer/data_store.py
Labels: Changed

#17772 message conditions
  chia/_tests/conftest.py
  chia/_tests/core/full_node/test_conditions.py
  chia/_tests/util/test_testnet_overrides.py
  chia/_tests/wallet/test_conditions.py
  chia/consensus/constants.py
  chia/consensus/default_constants.py
  chia/full_node/full_node.py
  chia/full_node/mempool_check_conditions.py
  chia/types/condition_opcodes.py
  chia/util/errors.py
  chia/util/initial-config.yaml
  chia/wallet/conditions.py
  chia/wallet/puzzles/condition_codes.clib
  setup.py
Labels: ready_to_merge, Changed

#17715 Redesign `@clvm_streamable`
  chia/_tests/build-init-files.py
  chia/_tests/check_pytest_monitor_output.py
  chia/_tests/check_sql_statements.py
  chia/_tests/chia-start-sim
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/test_clvm_streamable.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/rpc/util.py
  chia/rpc/wallet_rpc_client.py
  chia/util/streamable.py
  chia/wallet/signer_protocol.py
  chia/wallet/util/clvm_streamable.py
Labels: Changed, vault

#17794 less order sensitivity in `test_plotter_stop_plotting()`
  chia/_tests/core/daemon/test_daemon.py
Labels: Fixed, Tests

#17799 Rename softfork
  chia/_tests/conftest.py
  chia/_tests/core/full_node/full_sync/test_full_sync.py
  chia/_tests/core/full_node/test_conditions.py
  chia/_tests/util/test_testnet_overrides.py
  chia/consensus/constants.py
  chia/consensus/default_constants.py
  chia/full_node/mempool_check_conditions.py
  chia/util/initial-config.yaml
Labels: ready_to_merge, Changed

#17340 New subscription and wallet sync protocol
  chia/_tests/core/full_node/stores/test_coin_store.py
  chia/_tests/core/full_node/stores/test_hint_store.py
  chia/_tests/core/full_node/test_subscriptions.py
  chia/_tests/core/server/test_server.py
  chia/_tests/util/build_network_protocol_files.py
  chia/_tests/util/network_protocol_data.py
  chia/_tests/util/protocol_messages_bytes-v1.0
  chia/_tests/util/protocol_messages_json.py
  chia/_tests/util/test_network_protocol_files.py
  chia/_tests/util/test_network_protocol_json.py
  chia/_tests/util/test_network_protocol_test.py
  chia/_tests/wallet/test_new_wallet_protocol.py
  chia/full_node/coin_store.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/hint_store.py
  chia/full_node/subscriptions.py
  chia/protocols/protocol_message_types.py
  chia/protocols/protocol_state_machine.py
  chia/protocols/shared_protocol.py
  chia/protocols/wallet_protocol.py
  chia/server/rate_limit_numbers.py
Labels: ready_to_merge, full_node, Added

#17793 Optimized v1 to v2 DB upgrade
  chia/_tests/core/test_db_conversion.py
  chia/cmds/db_upgrade_func.py
Labels: ready_to_merge, Changed

#17801 only print warnings about protocol mismatches for farmer and harvester
  chia/server/ws_connection.py
Labels: ready_to_merge, Fixed

#17803 Only log rollback if heights are actually deleted
  chia/full_node/block_height_map.py
Labels: Fixed

#17802 Fall back to default values for peer file path
  chia/full_node/full_node.py
  chia/wallet/wallet_node.py
Labels: ready_to_merge, Fixed
