Repository Chia-Network/chia-blockchain, pull requests merged in 2024-06, with the labels that each got.

#18060 `pyinstaller==6.7.0`
  setup.py
Labels: Fixed, CI

#18102 add installed test for `chia init` and fix `importlib_resources` uses
  chia/_tests/cmds/wallet/test_wallet.py
  chia/_tests/util/benchmarks.py
  chia/cmds/installers.py
  chia/ssl/create_ssl.py
  chia/util/config.py
  chia/util/keychain.py
Labels: Added, Tests

#17398 [CHIA-433] Make execute_signing_instructions RPC
  chia/_tests/wallet/test_signer_protocol.py
  chia/rpc/wallet_request_types.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
Labels: Added, vault

#18096 CHIA-623: Split capabilities for each service
  chia/_tests/connection_utils.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/ssl/test_ssl.py
  chia/protocols/shared_protocol.py
  chia/server/start_service.py
  chia/simulator/setup_services.py
Labels: ready_to_merge, Changed

#18032 CHIA-582 Use kv compressed in DL batch update
  chia/data_layer/data_store.py
Labels: Changed, DataLayer

#18088 CHIA-620 Construct the solution as a serialized program in spend_bundle_from_conditions
  chia/_tests/core/mempool/test_mempool_manager.py
Labels: Changed, Cleanup

#17974 CHIA-211 better return paths, more logs
  chia/full_node/weight_proof.py
Labels: Added, Cleanup

#18108 introduce `ComparableEnum` for tests
  chia/_tests/conftest.py
  chia/_tests/util/misc.py
Labels: Changed, Tests

#18052 CHIA-437: Add coin id index to coin state batching
  chia/full_node/coin_store.py
Labels: Fixed

#16993 [CHIA-434] Add translation layer for blind signing
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/test_clvm_streamable.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/rpc/util.py
  chia/util/streamable.py
  chia/wallet/util/blind_signer_tl.py
  chia/wallet/util/clvm_streamable.py
Labels: Added, coverage-diff, vault

#17980 CHIA-194: CHIP-0026 Mempool Updates
  benchmarks/mempool.py
  chia/_tests/connection_utils.py
  chia/_tests/core/full_node/test_subscriptions.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_item_queries.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/util/build_network_protocol_files.py
  chia/_tests/util/network_protocol_data.py
  chia/_tests/util/protocol_messages_bytes-v1.0
  chia/_tests/util/protocol_messages_json.py
  chia/_tests/util/test_network_protocol_files.py
  chia/_tests/util/test_network_protocol_json.py
  chia/_tests/util/test_network_protocol_test.py
  chia/_tests/wallet/test_new_wallet_protocol.py
  chia/clvm/spend_sim.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/hint_store.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/full_node/subscriptions.py
  chia/protocols/protocol_message_types.py
  chia/protocols/protocol_state_machine.py
  chia/protocols/shared_protocol.py
  chia/protocols/wallet_protocol.py
  chia/server/rate_limit_numbers.py
Labels: Added

#18101 CHIA-685 Remove homebrew rpaths from _ssl.cpython.so on macOS during build
  .github/workflows/build-macos-installers.yml
  build_scripts/build_macos-2-installer.sh
  build_scripts/remove_brew_rpaths.sh
Labels: Fixed

#18075 CHIA-603: drop support for testnet10
  chia/_tests/conftest.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/test_cost_calculation.py
  chia/_tests/util/test_replace_str_to_bytes.py
  chia/_tests/util/test_testnet_overrides.py
  chia/consensus/block_body_validation.py
  chia/consensus/default_constants.py
  chia/full_node/mempool_check_conditions.py
  chia/simulator/block_tools.py
  chia/util/initial-config.yaml
Labels: ready_to_merge, Changed

#18077 CHIA-672 common version picking job for builds
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/build-windows-installer.yml
  .github/workflows/reflow-version.yml
Labels: Fixed, CI

#18085 [CHIA-615] Rust BLS cache
  chia/_tests/blockchain/blockchain_test_utils.py
  chia/_tests/core/util/test_cached_bls.py
  chia/consensus/block_body_validation.py
  chia/consensus/blockchain.py
  chia/full_node/full_node.py
  chia/full_node/mempool_manager.py
  chia/util/cached_bls.py
Labels: ready_to_merge, Changed

#18100 CHIA-645 Optimize build ancestors table.
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/data_store.py
Labels: ready_to_merge, Changed, DataLayer

#18111 tidy data store
  chia/data_layer/data_store.py
Labels: Changed, Exclude_Notes

#18120 CHIA-684 Simplify and speedup test_double_spend_with_higher_fee
  chia/_tests/core/mempool/test_mempool.py
Labels: Changed, Cleanup

#17399 [CHIA-435] Add `chia wallet signer` commands
  chia/_tests/wallet/test_signer_protocol.py
  chia/cmds/chia.py
  chia/cmds/signer.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/signer_protocol.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
Labels: Added, coverage-diff, vault

#17447 CHIA-619 Annotate test_trades.py
  chia/_tests/wallet/cat_wallet/test_trades.py
  mypy-exclusions.txt
Labels: ready_to_merge, Changed, Cleanup

#18145 [CHIA-740] Annotate chia_and_cat_for_something
  chia/_tests/wallet/cat_wallet/test_trades.py
Labels: Changed, Cleanup

#18147 checkpoint: into main from release/2.4.0 @ 1e677831c11c99e927de97b01e59996e1a6cc08c
  .gitignore
  build_scripts/npm_linux/package-lock.json
  build_scripts/npm_linux/package.json
  build_scripts/npm_macos/package-lock.json
  build_scripts/npm_macos/package.json
  build_scripts/npm_windows/package-lock.json
  build_scripts/npm_windows/package.json
Labels: checkpoint_merge, Changed

#18135 Bump chia rs 0.10.0
  chia/_tests/core/full_node/test_conditions.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/tools/test_run_block.py
  chia/_tests/util/test_condition_tools.py
  chia/_tests/util/test_replace_str_to_bytes.py
  chia/consensus/constants.py
  chia/consensus/default_constants.py
  chia/full_node/mempool_check_conditions.py
  chia/util/condition_tools.py
  setup.py
  tools/analyze-chain.py
Labels: Changed

#18149 Update Managed Files
  .github/dependabot.yml
Labels: Changed, Exclude_Notes

#18152 Use TYPE_CHECKING to work around python 3.8 limitations with generics
  chia/_tests/wallet/test_new_wallet_protocol.py
Labels: Fixed, CI

#18131 minor fix for make_spend function
  chia/types/coin_spend.py
Labels: Changed, community-pr

#18139 pylint disable `contextmanager-generator-missing-cleanup`
  pylintrc
Labels: Changed, Exclude_Notes

#18164 CHIA-752 - set permissions in postinst.sh for chrome-sandbox
  .github/workflows/build-linux-installer-deb.yml
  build_scripts/assets/deb/postinst.sh
Labels: Fixed

#18182 checkpoint: into main from release/2.4.0 @ 2fe28180762ac7f3cb49d54d6b40e3245862b4e1
  chia/_tests/wallet/test_new_wallet_protocol.py
Labels: checkpoint_merge, Changed

#18163 Remove `chia.clvm.singleton`
  chia/clvm/singleton.py
  chia/pools/pool_puzzles.py
  chia/pools/pool_wallet.py
Labels: ready_to_merge, Changed, Exclude_Notes

#18124 [CHIA-710] Add the concept of 'action scopes'
  chia/_tests/util/test_action_scope.py
  chia/util/action_scope.py
Labels: Added

#18181 avoid interpolating values into sql queries
  chia/data_layer/data_store.py
Labels: Changed, Exclude_Notes

#18180 Removed `lerna` from build_scripts
  build_scripts/build_linux_deb-1-gui.sh
  build_scripts/build_linux_deb-2-installer.sh
  build_scripts/build_linux_rpm-1-gui.sh
  build_scripts/build_linux_rpm-2-installer.sh
  build_scripts/build_macos-1-gui.sh
  build_scripts/build_macos-2-installer.sh
  build_scripts/build_windows-1-gui.ps1
  build_scripts/build_windows-2-installer.ps1
  build_scripts/npm_linux/package-lock.json
  build_scripts/npm_linux/package.json
  build_scripts/npm_macos/package-lock.json
  build_scripts/npm_macos/package.json
  build_scripts/npm_windows/package-lock.json
  build_scripts/npm_windows/package.json
Labels: Fixed

#18168 add install action editable option test
  .github/workflows/test-install-scripts.yml
Labels: Changed, Exclude_Notes

#18140 remove some pylint ignores
  benchmarks/block_ref.py
  benchmarks/blockchains.py
  benchmarks/mempool.py
  benchmarks/streamable.py
  chia/_tests/blockchain/blockchain_test_utils.py
  chia/_tests/cmds/wallet/test_dao.py
  chia/_tests/core/cmds/test_beta.py
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/core/full_node/test_transactions.py
  chia/_tests/core/util/test_cached_bls.py
  chia/_tests/util/key_tool.py
  chia/_tests/wallet/cat_wallet/test_cat_lifecycle.py
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/cat_wallet/test_offer_lifecycle.py
  chia/_tests/wallet/nft_wallet/test_nft_1_offers.py
  chia/_tests/wallet/nft_wallet/test_nft_offers.py
  chia/_tests/wallet/nft_wallet/test_nft_wallet.py
  chia/_tests/wallet/rpc/test_dl_wallet_rpc.py
  chia/_tests/wallet/simple_sync/test_simple_sync_protocol.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/_tests/wallet/test_coin_selection.py
  chia/_tests/wallet/test_notifications.py
  chia/_tests/wallet/test_singleton_lifecycle_fast.py
  chia/cmds/cmds_util.py
  chia/cmds/dao_funcs.py
  chia/cmds/keys_funcs.py
  chia/cmds/rpc.py
  chia/daemon/server.py
  chia/full_node/full_node.py
  chia/rpc/rpc_server.py
  chia/rpc/wallet_rpc_api.py
  chia/server/address_manager.py
  chia/simulator/block_tools.py
  chia/simulator/wallet_tools.py
  chia/util/profiler.py
  chia/util/streamable.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/puzzles/load_clvm.py
  chia/wallet/trade_manager.py
  chia/wallet/trading/offer.py
  chia/wallet/trading/trade_store.py
  chia/wallet/util/wallet_sync_utils.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_blockchain.py
  chia/wallet/wallet_state_manager.py
  installhelper.py
  pylintrc
  setup.py
  tools/chialispp.py
Labels: Changed, Exclude_Notes

#18137 remove unused `tree_id` parameter from `DataStore.batch_upsert()`
  chia/data_layer/data_store.py
Labels: Changed, Cleanup

#18113 CHIA-420 remove coroutine never awaited warning ignore
  pytest.ini
Labels: Changed

#18107 Revert "Revert "CHIA-414 fixup datalayer benchmark""
  chia/_tests/core/data_layer/test_data_store.py
  chia/_tests/process_junit.py
  chia/_tests/util/misc.py
  setup.py
Labels: Fixed, Tests

#18200 Update Changelog for 2.4.0 release
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#18136 CHIA-617 Annotate test_mempool.py
  chia/_tests/core/mempool/test_mempool.py
  mypy-exclusions.txt
Labels: ready_to_merge, Changed, Cleanup

#18207 (pylint) `==` -> `is`
  chia/_tests/util/test_action_scope.py
Labels: ready_to_merge, Fixed

#18169 [CHIA-754] Use tx_config in cancel_pending_trades
  chia/wallet/trade_manager.py
Labels: ready_to_merge, Fixed

#18138 CHIA-736 Annotate trade_manager.py
  chia/wallet/trade_manager.py
Labels: ready_to_merge, Changed, Cleanup

#18172 CHIA-763 Inline additions_for_npc into MempoolItem's additions
  chia/types/mempool_item.py
  chia/util/generator_tools.py
Labels: ready_to_merge, Changed, Cleanup

#18173 CHIA-764 Make mk_item aware of bundle_coin_spends
  chia/_tests/core/mempool/test_mempool_manager.py
Labels: ready_to_merge, Changed, Cleanup

#18223 Revert "Revert "Revert "CHIA-414 fixup datalayer benchmark"""
  chia/_tests/core/data_layer/test_data_store.py
  chia/_tests/process_junit.py
  chia/_tests/util/misc.py
  setup.py
Labels: Changed, Tests

#18227 correct release case on mac
  .github/workflows/build-macos-installers.yml
Labels: Fixed, CI

#18231 Revert "use rust types for RecentChainData, ProofBlockHeader and WeightProof" #17738
  chia/types/weight_proof.py
Labels: Fixed

#18238 CHIA-802: Update to macos-12 for build and remove macos-11
  .github/workflows/build-macos-installers.yml
  .github/workflows/check_wheel_availability.yaml
Labels: Changed

#18232 Fixed an issue where `npx --no lerna clean -f` didn't work
  build_scripts/build_linux_deb-1-gui.sh
  build_scripts/build_linux_rpm-1-gui.sh
  build_scripts/build_macos-1-gui.sh
  build_scripts/build_windows-1-gui.ps1
Labels: Fixed

#18193 [CHIA-690] Add offer expiration to CLI
  chia/_tests/cmds/wallet/test_wallet.py
  chia/cmds/wallet_funcs.py
Labels: Added

#18146 DL query multiple ancestors in upsert.
  chia/data_layer/data_store.py
Labels: Added, DataLayer

#18174 CHIA-765 Add the ability to set a fee in make_item
  chia/_tests/core/mempool/test_mempool.py
Labels: Changed, Cleanup

#17994 Fix for freebsd suggested by user alghmma
  chia/util/timing.py
Labels: Fixed

#18224 remove no-op semver action from rpm build
  .github/workflows/build-linux-installer-rpm.yml
Labels: Changed, CI, Cleanup

#18175 CHIA-766 Deduplicate sb mempool asserts
  chia/_tests/core/mempool/test_mempool.py
Labels: ready_to_merge, Changed, Cleanup

#18125 [CHIA-711] Add `WalletActionScope`
  chia/_tests/wallet/test_wallet_action_scope.py
  chia/_tests/wallet/test_wallet_state_manager.py
  chia/wallet/wallet_action_scope.py
  chia/wallet/wallet_state_manager.py
Labels: Added

#18237 Fix backwards compatibility for `add_private_key`
  chia/daemon/keychain_server.py
Labels: Fixed

#18236 Resolve light wallet syncing regression
  CHANGELOG.md
Labels: Fixed, Exclude_Notes

#15718 Refactor CLI by adding add new click types for fees, amounts, addresses and bytes32
  chia/_tests/cmds/test_click_types.py
  chia/_tests/cmds/test_tx_config_args.py
  chia/_tests/cmds/wallet/test_coins.py
  chia/_tests/cmds/wallet/test_wallet.py
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/pools/test_pool_cmdline.py
  chia/cmds/cmds_util.py
  chia/cmds/coin_funcs.py
  chia/cmds/coins.py
  chia/cmds/dao.py
  chia/cmds/dao_funcs.py
  chia/cmds/data.py
  chia/cmds/data_funcs.py
  chia/cmds/options.py
  chia/cmds/param_types.py
  chia/cmds/plotnft.py
  chia/cmds/plotnft_funcs.py
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/trading/offer.py
Labels: Changed, CI

#18245 Add 12-word mnemonic known issue
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#18235 CHIA-801 Cover AGG_SIG_ME_ADDITIONAL_DATA in message construction for test_agg_sig_illegal_suffix
  chia/_tests/core/full_node/test_conditions.py
Labels: Changed, Cleanup

#18199 [CHIA-504] Add support for external signers (PLEASE SQUASH)
  chia/_tests/cmds/cmd_test_utils.py
  chia/_tests/cmds/wallet/test_coins.py
  chia/_tests/cmds/wallet/test_consts.py
  chia/_tests/cmds/wallet/test_dao.py
  chia/_tests/cmds/wallet/test_did.py
  chia/_tests/cmds/wallet/test_nft.py
  chia/_tests/cmds/wallet/test_notifications.py
  chia/_tests/cmds/wallet/test_tx_decorators.py
  chia/_tests/cmds/wallet/test_vcs.py
  chia/_tests/cmds/wallet/test_wallet.py
  chia/_tests/pools/test_pool_rpc.py
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/cat_wallet/test_trades.py
  chia/_tests/wallet/conftest.py
  chia/_tests/wallet/dao_wallet/test_dao_wallets.py
  chia/_tests/wallet/did_wallet/test_did.py
  chia/_tests/wallet/nft_wallet/test_nft_bulk_mint.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/test_clvm_streamable.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/_tests/wallet/vc_wallet/test_vc_wallet.py
  chia/cmds/chia.py
  chia/cmds/cmds_util.py
  chia/cmds/coin_funcs.py
  chia/cmds/coins.py
  chia/cmds/dao.py
  chia/cmds/dao_funcs.py
  chia/cmds/data.py
  chia/cmds/plotnft.py
  chia/cmds/signer.py
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  chia/data_layer/data_layer.py
  chia/rpc/util.py
  chia/rpc/wallet_request_types.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/util/streamable.py
  chia/wallet/signer_protocol.py
  chia/wallet/transaction_record.py
  chia/wallet/util/blind_signer_tl.py
  chia/wallet/util/clvm_streamable.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
Labels: Added

#18246 [CHIA-819] Fix 12-word mnemonic support in keychain
  chia/_tests/core/util/test_keychain.py
  chia/util/keychain.py
Labels: Fixed

#18249 correct more macos casing
  .github/workflows/build-macos-installers.yml
Labels: Fixed, CI

#18257 Update to macos-12 for build and remove macos-11 (cherrypick from main)
  .github/workflows/build-macos-installers.yml
  .github/workflows/check_wheel_availability.yaml
Labels: Changed

#18196 avoid some diff coverage processing failures
  .github/workflows/test.yml
Labels: Fixed, CI

#18256 Fix backwards compatibility for add_private_key (cherrypick from main)
  chia/daemon/keychain_server.py
Labels: Fixed
