Repository Chia-Network/chia-blockchain, pull requests merged in 2024-04, with the labels that each got.

#16976 Add support in wallet for non-G1Element observation roots
  chia/_tests/core/util/test_keychain.py
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/test_sign_coin_spends.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/cmds/keys_funcs.py
  chia/daemon/keychain_proxy.py
  chia/daemon/keychain_server.py
  chia/util/keychain.py
  chia/wallet/wallet.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_state_manager.py
Labels: Changed, vault

#17808 avoid 3.9+ type indexing in runtime code, relegate to hints
  chia/_tests/util/test_async_pool.py
  chia/data_layer/data_layer.py
  chia/full_node/full_node_api.py
Labels: Fixed

#17805 checkpoint: into main from release/2.3.0 @ 1ff7e09a5aa635c90e73d428ccff598ee455441b
  chia/full_node/block_height_map.py
Labels: checkpoint_merge, Changed

#17809 checkpoint: into main from release/2.3.0 @ 07bc1f33e829c1eb907853c91ad10ec1da01774b
  chia/full_node/full_node.py
  chia/wallet/wallet_node.py
Labels: ready_to_merge, checkpoint_merge, Changed

#17815 checkpoint: into main from release/2.3.0 @ f1f4ab2f22d879481ec9975d3473067f966e2c1f
  chia/_tests/util/test_async_pool.py
  chia/data_layer/data_layer.py
  chia/full_node/full_node_api.py
Labels: checkpoint_merge, Changed

#17834 checkpoint: into main from release/2.3.0 @ 7966d96b10abff2bb206164f0d8750a50396b5a9
  chia/_tests/core/full_node/test_full_node.py
Labels: checkpoint_merge, Changed

#17822 Increase in-memory DB URI randomness
  chia/util/db_wrapper.py
Labels: Changed, Cleanup

#17817 remove redundant ci boost install step
  .github/workflows/test-single.yml
Labels: Changed, CI

#17757 add macOS arm to ci tests
  .github/workflows/test-single.yml
  .github/workflows/test.yml
Labels: Added, CI

#17433 add bytes type to DerivationRecord.pubkey
  chia/_tests/wallet/db_wallet/test_dl_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/derivation_record.py
Labels: Fixed

#17828 make junit collection optional and disable for now
  .github/workflows/test-single.yml
  .github/workflows/test.yml
Labels: Added, CI

#16978 Wallet -> MainWalletProtocol
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/environments/wallet.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/_tests/wallet/vc_wallet/test_vc_wallet.py
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/simulator/full_node_simulator.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/cat_wallet/dao_cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_protocol.py
  chia/wallet/wallet_state_manager.py
Labels: Changed, vault

#17835 checkpoint: into main from release/2.3.0 @ 65ef0f4ec416a0b161bf5bce854e1d6df66a074a
  chia/_tests/conftest.py
  chia/_tests/core/full_node/test_conditions.py
  chia/_tests/core/mempool/test_mempool.py
  chia/util/errors.py
Labels: checkpoint_merge, Changed

#17393 Convert wallet RPC client to deserialized types
  chia/_tests/cmds/cmd_test_utils.py
  chia/_tests/cmds/wallet/test_consts.py
  chia/_tests/cmds/wallet/test_dao.py
  chia/_tests/cmds/wallet/test_did.py
  chia/_tests/cmds/wallet/test_nft.py
  chia/_tests/cmds/wallet/test_vcs.py
  chia/_tests/cmds/wallet/test_wallet.py
  chia/_tests/pools/test_pool_rpc.py
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/cat_wallet/test_trades.py
  chia/_tests/wallet/dao_wallet/test_dao_wallets.py
  chia/_tests/wallet/did_wallet/test_did.py
  chia/_tests/wallet/nft_wallet/test_nft_bulk_mint.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/vc_wallet/test_vc_wallet.py
  chia/cmds/cmds_util.py
  chia/cmds/coin_funcs.py
  chia/cmds/dao_funcs.py
  chia/cmds/wallet_funcs.py
  chia/data_layer/data_layer.py
  chia/rpc/wallet_request_types.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/transaction_record.py
Labels: Changed, Exclude_Notes, vault

#17836 only exclude arm _timelord_ needing jobs
  .github/workflows/test-single.yml
Labels: Fixed, CI

#17807 Remove unused files
  chia/_tests/wallet/test_chialisp.py
  chia/full_node/fee_estimator_example.py
  chia/types/coin_solution.py
  chia/wallet/chialisp.py
  chia/wallet/puzzles/prefarm/__init__.py
  chia/wallet/puzzles/prefarm/make_prefarm_ph.py
  chia/wallet/puzzles/prefarm/spend_prefarm.py
  chia/wallet/util/json_clvm_utils.py
  mypy-exclusions.txt
Labels: Changed

#17814 DL migrate DB.
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_store.py
Labels: Fixed, DataLayer

#17831 improve legibility of source vs. installed test checks
  .github/workflows/test-single.yml
Labels: Changed, CI

#17838 Make generate_test_spend_bundle accept a named wallet param
  chia/_tests/core/mempool/test_mempool.py
Labels: Changed, Cleanup

#17841 checkpoint: into main from release/2.3.0 @ 6c9636b2ad2c74d40aef265d85ed67758af4f749
  .github/workflows/test-single.yml
  .github/workflows/test.yml
Labels: ready_to_merge, checkpoint_merge, Changed

#17853 Make a couple of DAOWallet methods return lists of transaction records
  chia/_tests/wallet/dao_wallet/test_dao_wallets.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/cat_wallet/dao_cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
Labels: Changed

#17861 simplify MerkleSet by making it immutable
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/core/test_merkle_set.py
  chia/full_node/full_node_api.py
  chia/util/merkle_set.py
Labels: Changed

#17873 exclude `config.py` from diff-cover as well
  .diffcover.toml
  .github/workflows/test.yml
Labels: Fixed, CI

#17871 Run core util tests sequential
  chia/_tests/core/util/config.py
Labels: Fixed, CI

#17847 Use as_iter instead of as_python in get_delayed_puz_info_from_launcher_spend and construct return values with proper types
  chia/pools/pool_puzzles.py
Labels: Changed, Cleanup

#17874 Combine Annotation.parse tests into a parameterized one
  chia/_tests/tools/test_virtual_project.py
Labels: Changed, Cleanup

#17881 checkpoint: into main from release/2.3.0 @ a441eb1db77e879be34a444ebb8b5eb5b28e335e
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_store.py
Labels: checkpoint_merge, Changed

#17869 Combine Annotation.is_annotated tests into a parameterized one.
  chia/_tests/tools/test_virtual_project.py
Labels: Changed, Cleanup

#17875 Move SimulatorFullNodeService type alias to start_simulator
  chia/_tests/cmds/test_farm_cmd.py
  chia/_tests/conftest.py
  chia/_tests/farmer_harvester/test_third_party_harvesters.py
  chia/_tests/fee_estimation/test_fee_estimation_rpc.py
  chia/_tests/pools/test_pool_rpc.py
  chia/_tests/util/setup_nodes.py
  chia/_tests/wallet/test_new_wallet_protocol.py
  chia/simulator/setup_services.py
  chia/simulator/start_simulator.py
  chia/types/aliases.py
Labels: Changed, Cleanup

#17894 update `example.net` IPs (`release/2.3.0`)
  chia/_tests/util/test_network.py
Labels: ready_to_merge, Fixed, Tests

#17897 update `example.net` IPs (`main`)
  chia/_tests/util/test_network.py
Labels: Fixed, Tests

#17884 Reading the first line of a file in ChiaFile's parse should be enough
  chia/util/virtual_project_analysis.py
Labels: Changed, Cleanup

#17892 push out soft-fork 4 activation point to 5716000
  chia/_tests/conftest.py
  chia/consensus/default_constants.py
Labels: Changed

#17851 Add new command class framework for easier testing
  chia/_tests/cmds/test_cmd_framework.py
  chia/cmds/cmd_classes.py
Labels: Added, Exclude_Notes

#17898 Skip problem test_every_simulator_command
  chia/_tests/cmds/test_sim.py
Labels: ready_to_merge, Changed, CI

#17850 Do not return unexpected coins from `get_coin_state`
  chia/_tests/wallet/test_wallet_node.py
  chia/wallet/wallet_node.py
Labels: Fixed

#17806 DL Multistore batch update.
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/wallet/rpc/test_dl_wallet_rpc.py
  chia/cmds/data.py
  chia/cmds/data_funcs.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_store.py
  chia/rpc/data_layer_rpc_api.py
  chia/rpc/data_layer_rpc_client.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
Labels: ready_to_merge, Added, DataLayer

#17909 bump chia_rs to 0.7.0
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/conftest.py
  chia/_tests/core/consensus/test_pot_iterations.py
  chia/_tests/core/full_node/stores/test_full_node_store.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/farmer_harvester/test_farmer.py
  chia/_tests/farmer_harvester/test_filter_prefix_bits.py
  chia/_tests/fee_estimation/test_mempoolitem_height_added.py
  chia/_tests/simulation/test_simulation.py
  chia/_tests/tools/test_run_block.py
  chia/_tests/util/constants.py
  chia/_tests/util/full_sync.py
  chia/_tests/util/test_struct_stream.py
  chia/_tests/wallet/wallet_block_tools.py
  chia/_tests/weight_proof/test_weight_proof.py
  chia/consensus/constants.py
  chia/consensus/default_constants.py
  chia/rpc/util.py
  chia/rpc/wallet_rpc_api.py
  chia/seeder/start_crawler.py
  chia/server/start_farmer.py
  chia/server/start_full_node.py
  chia/server/start_harvester.py
  chia/server/start_timelord.py
  chia/server/start_wallet.py
  chia/simulator/block_tools.py
  chia/simulator/setup_services.py
  chia/types/blockchain_format/proof_of_space.py
  chia/types/blockchain_format/sized_bytes.py
  chia/types/spend_bundle.py
  chia/util/byte_types.py
  chia/util/ints.py
  chia/util/struct_stream.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/trading/offer.py
  setup.py
  tools/run_block.py
  tools/test_full_sync.py
Labels: ready_to_merge, Changed

#17918 introduce early continue/exit to reduce the indentation level
  chia/farmer/farmer.py
  chia/pools/pool_config.py
Labels: ready_to_merge, Changed, Cleanup

#17917 remove unnecessary function, dataclass_to_json_dict()
  chia/rpc/farmer_rpc_client.py
  chia/util/misc.py
Labels: ready_to_merge, Changed, Cleanup

#17818 add dispatch options for test workflow
  .github/workflows/test-single.yml
  .github/workflows/test.yml
Labels: Added, CI

#17910 Use txs values in test_add_eviction
  chia/_tests/core/mempool/test_mempool.py
Labels: Changed, Cleanup

#17895 checkpoint: into main from release/2.3.0 @ cfa218dd8288945a454da3f56ed03356d45a43a6
  chia/_tests/cmds/test_daemon.py
  chia/cmds/sim_funcs.py
  chia/cmds/start.py
  chia/cmds/start_funcs.py
Labels: checkpoint_merge, Changed

#17908 Use Rust version of MerkleSet
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/core/test_merkle_set.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/full_node/full_node_api.py
  chia/util/merkle_set.py
  chia/wallet/util/wallet_sync_utils.py
Labels: Changed

#17926 Remove unused assert_sb_in_pool and inline assert_sb_not_in_pool as it's used only once
  chia/_tests/wallet/test_wallet_retry.py
Labels: Changed, Cleanup

#17936 Change `macos-latest` to `macos-12` in runners
  .github/workflows/pre-commit.yml
  .github/workflows/test-install-scripts.yml
  .github/workflows/test.yml
  .github/workflows/upload-pypi-source.yml
Labels: Changed, CI

#17924 improve legibility of matrix mode selection
  .github/workflows/test.yml
Labels: Changed, CI, Cleanup

#17856 Fix memo plotid
  chia/plotting/create_plots.py
Labels: Fixed
