Repository Chia-Network/chia-blockchain, pull requests merged in 2024-01, with the labels that each got.

#17167 remove redundant cost field in NPCResults
  chia/clvm/spend_sim.py
  chia/consensus/block_body_validation.py
  chia/consensus/block_creation.py
  chia/consensus/cost_calculator.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/mempool.py
  chia/full_node/mempool_check_conditions.py
  chia/full_node/mempool_manager.py
  chia/rpc/full_node_rpc_api.py
  chia/types/mempool_item.py
  tests/clvm/benchmark_costs.py
  tests/core/full_node/test_full_node.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_manager.py
  tests/core/test_cost_calculation.py
  tests/fee_estimation/test_fee_estimation_integration.py
  tests/generator/test_rom.py
Labels: ready_to_merge, Changed, Cleanup

#17140 Remove coin_solutions from SpendBundle entirely
  chia/types/spend_bundle.py
  tests/core/custom_types/test_spend_bundle.py
  tests/fee_estimation/test_fee_estimation_rpc.py
Labels: Changed

#17187 correct condition for `coverage-diff` label removal
  .github/workflows/test.yml
Labels: Fixed, CI

#16865 Add a marshaller for RPC APIs
  chia/rpc/util.py
  tests/core/test_rpc_util.py
Labels: Added, Exclude_Notes, vault

#17166 Spin slower `send_transaction()`
  chia/full_node/full_node_api.py
Labels: Fixed

#17126 make sure keyring file gets closed
  chia/util/file_keyring.py
Labels: Fixed, Exclude_Notes

#17127 enable ssl_context deprecation warning and fix it
  chia/daemon/client.py
  chia/daemon/keychain_proxy.py
  chia/rpc/rpc_client.py
  chia/rpc/rpc_server.py
  pytest.ini
  tests/core/daemon/test_daemon.py
  tests/core/daemon/test_daemon_register.py
  tests/simulation/test_simulation.py
Labels: Fixed, Exclude_Notes

#16849 vault puzzles
  chia/wallet/puzzles/deployed_puzzle_hashes.json
  chia/wallet/puzzles/p2_delegated_or_hidden_secp.clsp
  chia/wallet/puzzles/p2_delegated_or_hidden_secp.clsp.hex
  chia/wallet/puzzles/vault_p2_recovery.clsp
  chia/wallet/puzzles/vault_p2_recovery.clsp.hex
  chia/wallet/puzzles/vault_recovery_finish.clsp
  chia/wallet/puzzles/vault_recovery_finish.clsp.hex
  chia/wallet/vault/__init__.py
  chia/wallet/vault/vault_drivers.py
  setup.py
  tests/wallet/vault/__init__.py
  tests/wallet/vault/p2_delegated_or_hidden_secp.clsp
  tests/wallet/vault/test_vault_clsp.py
  tests/wallet/vault/test_vault_lifecycle.py
Labels: Added, vault

#17199 apply language labels to dependabot PRs
  .github/dependabot.yml
Labels: Changed, CI

#17161 Mempool logging
  chia/consensus/blockchain.py
  chia/full_node/full_node.py
  chia/full_node/mempool_manager.py
  chia/full_node/weight_proof.py
Labels: ready_to_merge, Added

#17185 FIXED: Fixed old links that just linked to links, to the new direct links in…
  README.md
Labels: Fixed

#17191 Use self_hostname fixture in test_nft_bulk_transfer
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: Changed, Cleanup

#17152 Remove debug prints from DID's test_creation_from_coin_spend and test_create_did_with_recovery_list
  tests/wallet/did_wallet/test_did.py
Labels: Changed, Cleanup

#17151 Remove DID wallet's get_frozen_amount
  chia/wallet/did_wallet/did_wallet.py
Labels: Changed, Cleanup

#17148 Simplify get_new_did_innerpuz
  chia/wallet/did_wallet/did_wallet.py
Labels: Changed, Cleanup

#17147 Remove leftover None prints in test_trade_bad_spend
  tests/wallet/cat_wallet/test_trades.py
Labels: Changed, Cleanup

#17145 No need to return None in dl_track_new and dl_stop_tracking
  chia/rpc/wallet_rpc_client.py
Labels: Changed, Cleanup

#17197 Update chia_rs to 0.2.15 for AMD K10 fix
  setup.py
Labels: Fixed

#17188 Remove no longer needed TestCATWallet class
  tests/wallet/cat_wallet/test_cat_wallet.py
Labels: Changed, Cleanup

#17153 Annotate did_wallet_puzzles.py
  chia/wallet/did_wallet/did_wallet_puzzles.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#17202 Skip flaky test on windows and python 3.8
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: Changed, CI, Exclude_Notes

#17210 Annotate test_nft_wallet.py
  mypy-exclusions.txt
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: Changed, Cleanup

#17149 Annotate test_offer_lifecycle.py
  mypy-exclusions.txt
  tests/wallet/cat_wallet/test_offer_lifecycle.py
Labels: Changed, Cleanup

#17168 add feature to profile just the block validation
  chia/full_node/full_node.py
  chia/util/initial-config.yaml
  chia/util/profiler.py
Labels: Added

#17102 use rust types for VDFInfo, VDFProof and ClassgroupElement
  chia/consensus/block_header_validation.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/full_node_store.py
  chia/full_node/weight_proof.py
  chia/simulator/block_tools.py
  chia/timelord/timelord.py
  chia/types/blockchain_format/classgroup.py
  chia/types/blockchain_format/vdf.py
  chia/util/recursive_replace.py
  tests/blockchain/test_blockchain.py
  tests/util/test_recursive_replace.py
Labels: Changed

#17220 Add --override flage to make_offer
  chia/cmds/wallet.py
  tests/cmds/wallet/test_wallet.py
Labels: ready_to_merge, Added

#17219 Fix endless recursion in list_to_binary_tree
  chia/wallet/util/merkle_utils.py
  tests/wallet/test_util.py
Labels: ready_to_merge, Fixed, Exclude_Notes

#17207 evict entries continuously from `seen_unfinished_blocks`
  chia/full_node/full_node.py
  chia/full_node/full_node_store.py
  tests/core/full_node/stores/test_full_node_store.py
Labels: ready_to_merge, Changed

#16830 add measured sizes for plot check
  chia/plotting/cache.py
Labels: Fixed

#17226 simplify get_unfinished_blocks()
  chia/full_node/full_node_store.py
  chia/rpc/full_node_rpc_api.py
Labels: ready_to_merge, Changed, Cleanup

#17043 Add a few missing type annotations
  chia/cmds/check_wallet_db.py
  chia/util/keyring_wrapper.py
Labels: ready_to_merge, Fixed

#17146 Annotate test_cat_wallet.py
  chia/rpc/wallet_rpc_client.py
  mypy-exclusions.txt
  tests/wallet/cat_wallet/test_cat_wallet.py
Labels: Changed, Cleanup

#17217 checkpoint: into main from release/2.1.4 @ 66683b957d24b4fc7a44da3e6df63536fd19da41
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: checkpoint_merge, Changed

#17240 Import BetaMetricsLogger only when needed
  chia/daemon/server.py
Labels: Changed, Cleanup

#17093 Endpoint for vault singleton creation
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/vault/vault_drivers.py
  chia/wallet/wallet_state_manager.py
  tests/wallet/vault/config.py
  tests/wallet/vault/test_vault_wallet.py
Labels: Added, vault

#17213 Remove unused wallet_height_at_least
  tests/wallet/simple_sync/test_simple_sync_protocol.py
Labels: Changed, Cleanup

#17214 Simplify updates construction in dl_update_multiple
  chia/rpc/wallet_rpc_client.py
Labels: Changed, Cleanup

#17215 Annotate test_bech32m.py
  mypy-exclusions.txt
  tests/wallet/test_bech32m.py
Labels: Changed, Cleanup

#17216 Remove no longer needed TestPuzzleStore class
  tests/wallet/test_puzzle_store.py
Labels: Changed, Cleanup

#17225 more `pkg_resources` in tests
  tests/cmds/wallet/test_wallet.py
  tests/core/server/test_loop.py
  tests/core/util/test_keychain.py
Labels: Fixed, Tests

#17212 Document the fact that we should be using tx_config and taking a fee in DID's create_attestment
  chia/wallet/did_wallet/did_wallet.py
Labels: Changed, Cleanup

#17252 move `tools/legacy_keyring.py` to `chia/legacy/keyring.py`
  chia/legacy/__init__.py
  chia/legacy/keyring.py
  tests/tools/test_legacy_keyring.py
Labels: Changed

#17254 Annotate test_wallet_node.py
  tests/wallet/test_wallet_node.py
Labels: Changed, Cleanup

#17241 Add ability to get the aggsig additional data from full node RPC
  chia/rpc/full_node_rpc_api.py
  chia/rpc/full_node_rpc_client.py
  tests/core/test_full_node_rpc.py
Labels: CLI, Added

#17251 move `benchmarks/util.py` to `tests/util/benchmarks.py`
  benchmarks/block_store.py
  benchmarks/coin_store.py
  benchmarks/streamable.py
  benchmarks/utils.py
  tests/blockchain/test_lookup_fork_chain.py
  tests/core/test_coins.py
  tests/pools/test_pool_wallet.py
  tests/util/benchmarks.py
  tests/util/clvm_generator.bin
  tests/util/test_full_block_utils.py
Labels: Changed, Tests

#17269 move `run_json_block()` to `tests/`
  tests/tools/test_run_block.py
  tests/util/run_block.py
  tools/run_block.py
Labels: Changed, Tests

#17268 move `run_full_sync()` to `tests/`
  mypy-exclusions.txt
  tests/tools/test_full_sync.py
  tests/util/constants.py
  tests/util/full_sync.py
  tools/generate_chain.py
  tools/test_full_sync.py
Labels: Changed, Tests

#17249 Refactor subscriptions and add remove functionality
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/hint_management.py
  chia/full_node/subscriptions.py
  tests/core/full_node/test_subscriptions.py
  tests/wallet/cat_wallet/test_cat_wallet.py
  tests/wallet/simple_sync/test_simple_sync_protocol.py
Labels: full_node, Changed, Cleanup

#17280 checkpoint: into main from release/2.1.4 @ f6522969dd6a4bc5a60bf000551a757b975659a7
  tests/wallet/nft_wallet/test_nft_wallet.py
Labels: checkpoint_merge, Changed

#17286 checkpoint: into main from release/2.1.4 @ b5fe5020ec75b29e91a399b6648ff0a1a683ca04
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#17256 Annotate test_puzzle_store.py
  mypy-exclusions.txt
  tests/wallet/test_puzzle_store.py
Labels: Changed, Cleanup

#17257 Fix wallet RPC client's get_transaction_count return type
  chia/rpc/wallet_rpc_client.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Changed, Cleanup

#17260 Annotate test_wallet_user_store.py
  mypy-exclusions.txt
  tests/wallet/test_wallet_user_store.py
Labels: Changed, Cleanup

#17261 Explicitly check that (optional) memos is not None in cat_spend
  chia/rpc/wallet_rpc_client.py
Labels: Changed, Cleanup

#17278 Tweak wallet RPC test that wasn't working
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Fixed, Tests, Exclude_Notes

#17253 Remove no longer needed TestWalletSync class
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#17255 Don't needlessly call spend_bundle.additions() in test_subscribe_for_coin_id
  tests/wallet/simple_sync/test_simple_sync_protocol.py
Labels: Changed, Cleanup

#17258 Extract and reuse wallet_height_at_least
  tests/core/full_node/test_full_node.py
  tests/core/mempool/test_mempool_performance.py
  tests/util/misc.py
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#17218 Rust proof-of-space, reward chain and foliage types
  chia/cmds/show_funcs.py
  chia/consensus/block_body_validation.py
  chia/consensus/block_creation.py
  chia/consensus/block_header_validation.py
  chia/consensus/full_block_to_block_record.py
  chia/consensus/make_sub_epoch_summary.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/weight_proof.py
  chia/simulator/block_tools.py
  chia/timelord/iters_from_block.py
  chia/timelord/timelord.py
  chia/timelord/timelord_state.py
  chia/types/blockchain_format/foliage.py
  chia/types/blockchain_format/pool_target.py
  chia/types/blockchain_format/proof_of_space.py
  chia/types/blockchain_format/reward_chain_block.py
  chia/types/full_block.py
  chia/types/header_block.py
  chia/types/unfinished_block.py
  chia/types/unfinished_header_block.py
  chia/util/full_block_utils.py
  chia/util/struct_stream.py
  chia/wallet/util/peer_request_cache.py
  chia/wallet/wallet_blockchain.py
  chia/wallet/wallet_node.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/wallet/test_wallet_node.py
Labels: Changed

#17276 Add fork height & rolled_back_records to block event for metrics
  chia/full_node/full_node.py
Labels: Added

#17284 Pass the bytes32 representation of metadata_updater_hash to nft_puzzles.create_full_puzzle
  chia/rpc/wallet_rpc_api.py
Labels: Changed, Cleanup

#17282 Pass seconds_delay to create_p2_singleton_puzzle without converting it to bytes
  chia/pools/pool_puzzles.py
Labels: Changed, Cleanup

#17285 Clarify to_program handling of args in UnknownCondition
  chia/wallet/conditions.py
Labels: Changed, Cleanup

#17293 Clarify the inner solution's type in generate_secure_bundle
  tests/wallet/cat_wallet/test_offer_lifecycle.py
Labels: Changed, Cleanup

#17294 Return genesis_id instead of its bytes representation in GenesisByIdOrSingleton's match
  chia/wallet/puzzles/tails.py
Labels: Changed, Cleanup

#17295 Fix run_with_cost calls in benchmark_cost.py
  tests/util/benchmark_cost.py
Labels: Changed, Cleanup

#17291 construct_exigent_metadata_layer's metadata is an optional Program
  chia/wallet/vc_wallet/vc_drivers.py
Labels: Changed, Cleanup

#17301 Introduce and use LineageProof.from_program
  chia/wallet/lineage_proof.py
  chia/wallet/vc_wallet/cr_cat_drivers.py
  tests/wallet/test_util.py
Labels: Changed, Cleanup

#17259 Annotate test_singleton.py
  mypy-exclusions.txt
  tests/wallet/test_singleton.py
Labels: Changed, Cleanup

#17304 Log string header_hash on long validation warnings
  chia/full_node/full_node.py
Labels: Fixed, Logging

#17307 add test for detecting clashing message IDs
  tests/util/test_network_protocol_test.py
Labels: ready_to_merge, Added, Tests

#17299 Subscribe to DIDs that come into wallet
  chia/wallet/did_wallet/did_wallet.py
  tests/wallet/did_wallet/test_did.py
Labels: Fixed

#17243 DL Compress get_keys_values output by hash.
  chia/data_layer/data_layer_util.py
  chia/data_layer/data_store.py
  chia/data_layer/util/benchmark.py
  tests/core/data_layer/test_data_store.py
Labels: ready_to_merge, Changed, DataLayer

#17103 Add test for DL kv_diff for upsert.
  tests/core/data_layer/test_data_store.py
Labels: Added, Tests, DataLayer

#17125 Add DL mirrors test.
  tests/core/data_layer/test_data_rpc.py
Labels: Added, Tests, DataLayer

#17158 Check dependencies to avoid a useless sudo on Archlinux
  install.sh
Labels: Changed, Cleanup

#17195 replace hardcoded value for `db_readers`
  chia/full_node/full_node.py
Labels: Changed

#17270 Fix sorted for dictionary keys of both bytes/xch
  chia/wallet/trade_manager.py
  tests/wallet/nft_wallet/test_nft_offers.py
Labels: Fixed

#17239 extend measured sizes for plot check with value for k39
  chia/plotting/cache.py
Labels: Fixed

#17313 No need to return lineage_proof from launcher_conditions_and_spend_bundle
  tests/wallet/test_singleton_lifecycle.py
Labels: Changed, Cleanup

#17317 Remove no longer needed TestWalletBlockchain class
  tests/wallet/test_wallet_blockchain.py
Labels: Changed, Cleanup

#17319 Fix inaccurate test
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Fixed, Tests, Exclude_Notes

#17320 Fetch only value in get_object
  chia/wallet/key_val_store.py
Labels: Changed, Cleanup

#17322 Reuse launcher_id in launcher_conditions_and_spend_bundle
  tests/wallet/test_singleton_lifecycle_fast.py
Labels: Changed, Cleanup

#17321 find_interesting_singletons doesn't need to take puzzle_db
  tests/wallet/test_singleton_lifecycle_fast.py
Labels: Changed, Cleanup

#17309 Extract and reuse get_tx_count
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#17305 switch transaction queue completion to a new `ValuedEvent`
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/types/transaction_queue_entry.py
  chia/util/misc.py
  tests/util/test_misc.py
Labels: Fixed

#17310 Simplify getting wallet spendable coins' count in test_dusted_wallet (and correct its type)
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#17312 Clarify checking compute_memos results
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#17315 Remove unneeded singleton_wallet in filter_p2_singleton
  tests/wallet/test_singleton_lifecycle_fast.py
Labels: Changed, Cleanup

#17325 remove unused `chia.wallet.block_record` module
  chia/wallet/block_record.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#17316 Annotate wallet_rpc_client.py
  chia/rpc/wallet_rpc_client.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#17298 use rust types for slots, SubEpochSummary and SubEpochData
  chia/consensus/full_block_to_block_record.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/weight_proof.py
  chia/simulator/block_tools.py
  chia/timelord/timelord_state.py
  chia/types/blockchain_format/slots.py
  chia/types/blockchain_format/sub_epoch_summary.py
  chia/types/end_of_slot_bundle.py
  chia/types/weight_proof.py
  chia/wallet/wallet_blockchain.py
  tests/blockchain/test_blockchain.py
  tests/core/full_node/test_full_node.py
  tests/core/util/test_streamable.py
Labels: Changed

#17339 remove old work-around for a bug in version 1.1.4 and earlier
  chia/full_node/full_node.py
Labels: ready_to_merge, Changed

#17341 bump chia_rs dependency to 0.4.0
  setup.py
Labels: ready_to_merge, Changed

#17292 Compute authorized providers list and pass it to construct_cr_layer
  chia/wallet/vc_wallet/cr_cat_drivers.py
Labels: Changed, Cleanup

#17351 Wait for wallet_node_maker to sync before creating nft_wallet_maker in test_nft_mint_from_xch_rpc
  tests/wallet/nft_wallet/test_nft_bulk_mint.py
Labels: Changed, Cleanup

#17352 Wait for wallet_node_maker to sync before creating nft_wallet_maker in test_nft_mint_from_did_rpc
  tests/wallet/nft_wallet/test_nft_bulk_mint.py
Labels: Changed, Cleanup

#17353 Wait for wallet_node_maker to sync before creating nft_wallet_maker in test_nft_mint_from_did_rpc_no_royalties
  tests/wallet/nft_wallet/test_nft_bulk_mint.py
Labels: Changed, Cleanup

#17311 Use Monkeypatching for request_proof_of_weight and request_block_header in test_bad_peak_mismatch
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#17359 Remove no longer needed TestSimpleSyncProtocol class
  tests/wallet/simple_sync/test_simple_sync_protocol.py
Labels: Changed, Cleanup

#17361 Annotate test_wallet_blockchain.py
  mypy-exclusions.txt
  tests/wallet/test_wallet_blockchain.py
Labels: Changed, Cleanup

#17363 Simplify checking for all unspent coins' count in test_dusted_wallet
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#15138 Fixed an issue where `chia wallet did transfer` command mistreats the type of `fee`
  chia/cmds/wallet.py
  chia/cmds/wallet_funcs.py
  tests/cmds/wallet/test_did.py
Labels: Fixed

#17297 use rust implementation of SerializedProgram
  chia/types/blockchain_format/serialized_program.py
  tests/wallet/dao_wallet/test_dao_clvm.py
Labels: Changed

#17365 Parallelize tests up to 4 instead of 6 for Windows
  tests/build-job-matrix.py
Labels: Changed, Cleanup

#17275 extend Block validation timing logs to measure just the CLVM and conditions
  chia/consensus/blockchain.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
  tests/blockchain/blockchain_test_utils.py
  tests/blockchain/test_blockchain.py
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/test_db_conversion.py
  tests/core/test_db_validation.py
Labels: Added

#17367 Pull smtools from downloads since digicert is being flaky
  .github/workflows/build-windows-installer.yml
Labels: Fixed, CI, Exclude_Notes

#17350 measured new_signage_point_harvester size with 100 pools for limit
  chia/server/rate_limit_numbers.py
Labels: Fixed

#17360 Compute and reuse launcher_id
  tests/wallet/test_singleton_lifecycle.py
Labels: Changed, Cleanup

#17354 fix duplicates file and upload name uniqueness
  .github/workflows/test-single.yml
  tests/build-job-matrix.py
Labels: Fixed, Exclude_Notes

#17376 Remove duplicate short option from make_offer command
  chia/cmds/wallet.py
Labels: ready_to_merge, Fixed

#17362 Annotate test_singleton_lifecycle_fast.py
  mypy-exclusions.txt
  tests/wallet/test_singleton_lifecycle_fast.py
Labels: Changed, Cleanup

#17369 Add support for defining a list of full node peers to connect to
  chia/server/start_full_node.py
  chia/util/initial-config.yaml
Labels: Added

#17364 Annotate test_simple_sync_protocol.py
  mypy-exclusions.txt
  tests/wallet/simple_sync/test_simple_sync_protocol.py
Labels: ready_to_merge, Changed, Cleanup

#17357 Remove confusing claim_coinsol value in spend_to_delayed_puzzle
  chia/wallet/puzzles/singleton_top_layer.py
Labels: Changed, Cleanup

#17355 Remove unused ignore_size_limit from get_nft_info_from_puzzle
  chia/rpc/wallet_rpc_api.py
  chia/wallet/nft_wallet/nft_puzzles.py
Labels: Changed, Cleanup

#17300 Add way to get coin states in batches
  chia/full_node/coin_store.py
  tests/core/full_node/stores/test_coin_store.py
Labels: full_node, Added

#17356 Annotate nft_puzzles.py
  chia/wallet/nft_wallet/nft_puzzles.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#16909 undo BlockRecord cache insert, when DB fails
  chia/consensus/block_body_validation.py
  chia/consensus/blockchain.py
Labels: Fixed

#17370 improve mempool reorg logic when the peak is a non-transaction block
  chia/consensus/blockchain.py
  chia/full_node/full_node.py
  chia/full_node/mempool_manager.py
  tests/blockchain/test_blockchain.py
Labels: Added

#17223 add test that chia is installed when in ci
  tests/util/test_installed.py
Labels: Changed

#17333 Add additions and removals to get_offer_summary API response
  chia/rpc/wallet_rpc_api.py
  chia/wallet/trade_manager.py
  tests/wallet/rpc/test_wallet_rpc.py
Labels: Added

#17383 Remove no longer needed remove_singleton_truth_wrapper
  chia/wallet/puzzles/singleton_top_layer.py
  chia/wallet/puzzles/singleton_top_layer_v1_1.py
Labels: Changed, Cleanup

#17358 Annotate singleton_top_layer.py
  chia/wallet/puzzles/singleton_top_layer.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#17346 Explore looking beyond mempool items that hit the maximum cost limit
  chia/full_node/mempool.py
  tests/core/mempool/test_mempool_manager.py
Labels: Changed, Cleanup

#16206 Warn if running `install-plotter.sh` as root
  install-plotter.sh
Labels: Fixed

#17401 fix typo in logging
  chia/wallet/wallet_node_api.py
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed

#17404 Explicitly check that mempool manager's peak (optional) is not None in SimClient's push_tx
  chia/clvm/spend_sim.py
Labels: Changed, Cleanup

#17403 Simplify mempool item's starting cost at create_bundle_from_mempool_items
  chia/full_node/mempool.py
Labels: Changed, Cleanup

#17379 just use `os.cpu_count()`
  chia/consensus/blockchain.py
  chia/harvester/harvester.py
  chia/plotting/check_plots.py
  tests/blockchain/test_blockchain.py
Labels: Changed, Cleanup

#16136 Code Cleanup: Fix overly broad exception handler
  chia/rpc/wallet_rpc_api.py
Labels: Changed, Cleanup, Exclude_Notes, coverage-diff

#17247 improve handling of `UnfinishedBlock`s
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/full_node_store.py
  chia/protocols/full_node_protocol.py
  chia/protocols/protocol_message_types.py
  chia/protocols/protocol_state_machine.py
  chia/protocols/shared_protocol.py
  chia/server/rate_limit_numbers.py
  chia/server/server.py
  chia/simulator/block_tools.py
  chia/util/initial-config.yaml
  install-timelord.sh
  tests/core/full_node/stores/test_full_node_store.py
  tests/core/full_node/test_full_node.py
  tests/util/build_network_protocol_files.py
  tests/util/full_sync.py
  tests/util/network_protocol_data.py
  tests/util/protocol_messages_bytes-v1.0
  tests/util/protocol_messages_json.py
  tests/util/test_network_protocol_files.py
  tests/util/test_network_protocol_json.py
  tests/util/test_network_protocol_test.py
Labels: ready_to_merge, Added

#16919 Singleton fast forward
  benchmarks/mempool.py
  chia/clvm/spend_sim.py
  chia/full_node/coin_store.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/simulator/full_node_simulator.py
  chia/types/eligible_coin_spends.py
  chia/types/internal_mempool_item.py
  chia/types/mempool_item.py
  tests/blockchain/test_blockchain_transactions.py
  tests/core/full_node/stores/test_coin_store.py
  tests/core/full_node/test_performance.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_manager.py
  tests/core/mempool/test_singleton_fast_forward.py
Labels: ready_to_merge, Added

#16717 Support for third-party, farmer-rewarded, Harvesters
  chia/farmer/farmer.py
  chia/farmer/farmer_api.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/harvester/harvester_api.py
  chia/protocols/farmer_protocol.py
  chia/protocols/harvester_protocol.py
  chia/simulator/block_tools.py
  tests/conftest.py
  tests/farmer_harvester/test_farmer.py
  tests/farmer_harvester/test_farmer_harvester.py
  tests/farmer_harvester/test_third_party_harvesters.py
  tests/farmer_harvester/test_third_party_harvesters_data.json
  tests/util/network_protocol_data.py
  tests/util/protocol_messages_bytes-v1.0
  tests/util/protocol_messages_json.py
  tests/util/test_network_protocol_test.py
Labels: Farming, harvester, full_node, Added

#17408 use rust implementation of CoinSpend
  chia/data_layer/data_layer_wallet.py
  chia/types/coin_spend.py
  chia/wallet/vc_wallet/vc_wallet.py
  tests/core/test_full_node_rpc.py
  tests/wallet/cat_wallet/test_offer_lifecycle.py
Labels: ready_to_merge, Changed

#17377 Remove `Announcement` class in favor of `Condition` subclasses
  chia/cmds/wallet_funcs.py
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/simulator/wallet_tools.py
  chia/types/announcement.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/cat_wallet/dao_cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/notification_manager.py
  chia/wallet/trade_manager.py
  chia/wallet/trading/offer.py
  chia/wallet/vc_wallet/cr_cat_drivers.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/vc_drivers.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_state_manager.py
  tests/blockchain/test_blockchain_transactions.py
  tests/cmds/wallet/test_did.py
  tests/core/data_layer/test_data_rpc.py
  tests/core/full_node/test_conditions.py
  tests/core/mempool/test_mempool.py
  tests/core/mempool/test_mempool_manager.py
  tests/wallet/cat_wallet/test_offer_lifecycle.py
  tests/wallet/nft_wallet/test_nft_lifecycle.py
  tests/wallet/rpc/test_wallet_rpc.py
  tests/wallet/test_singleton.py
  tests/wallet/test_singleton_lifecycle.py
  tests/wallet/test_singleton_lifecycle_fast.py
  tests/wallet/vc_wallet/test_vc_lifecycle.py
Labels: ready_to_merge, Changed

#17417 fix `Install.ps1` for pwsh 7.4
  Install.ps1
Labels: Fixed

#17418 Remove `ignore_max_send_amount`
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/coin_selection.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/wallet.py
  tests/wallet/test_wallet.py
Labels: Changed

#17419 Use Monkeypatching for register_interest_in_puzzle_hash in test_long_sync_untrusted_break
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#17420 ProposalInfo's passed and closed are not optional
  chia/wallet/dao_wallet/dao_info.py
Labels: Changed, Cleanup

#17421 No need to readd consensus_mode fixture in DAO wallet tests
  tests/wallet/dao_wallet/test_dao_wallets.py
Labels: Changed, Cleanup

#17422 Annotate lineage_proof.py
  chia/wallet/lineage_proof.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#17423 Annotate p2_delegated_conditions.py
  chia/wallet/puzzles/p2_delegated_conditions.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#17424 Annotate p2_puzzle_hash.py
  chia/wallet/puzzles/p2_puzzle_hash.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#17425 Improve test_get_puzzle_and_solution_for_coin_performance
  tests/core/test_cost_calculation.py
Labels: Changed, Cleanup

#17426 Improve did_get_info
  chia/rpc/wallet_rpc_api.py
Labels: Changed, Cleanup

#17428 Remove no longer needed TestCATTrades class
  tests/wallet/cat_wallet/test_trades.py
Labels: Changed, Cleanup

#17429 Produce flakiness in a type-friendly way in test_retry_store
  tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#17445 Kyle's Install.ps1 fix for pwsh 7.4
  Install.ps1
Labels: Changed, Cleanup
