Repository Chia-Network/chia-blockchain, pull requests merged in 2025-04, with the labels that each got.

#19443 Fix double slashes in s3 urls
  .github/workflows/reflow-publish-installer.yml
Labels: Fixed, CI, Exclude_Notes

#19397 [CHIA-2540] Compute block cost
  .github/workflows/test-single.yml
  chia/_tests/core/consensus/test_block_creation.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/consensus/block_creation.py
  chia/full_node/mempool.py
  chia/rpc/full_node_rpc_api.py
  chia/simulator/block_tools.py
  chia/types/generator_types.py
Labels: ready_to_merge, Changed

#19461 correct proxy url hinting for datalayer downloads
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/download_data.py
Labels: Fixed, Exclude_Notes

#19447 CHIA-2644 Annotate test_full_sync.py
  chia/_tests/core/full_node/full_sync/test_full_sync.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#19464 bump clvm to version 0.9.12
  poetry.lock
  pyproject.toml
Labels: ready_to_merge, Changed

#19283 [CHIA-1251] Add puzzle hash generation to action scopes
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/full_node/test_transactions.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/mempool/test_mempool_performance.py
  chia/_tests/core/test_filter.py
  chia/_tests/fee_estimation/test_fee_estimation_rpc.py
  chia/_tests/pools/test_pool_cmdline.py
  chia/_tests/pools/test_pool_rpc.py
  chia/_tests/pools/test_pool_wallet.py
  chia/_tests/simulation/test_simulation.py
  chia/_tests/simulation/test_simulator.py
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/cat_wallet/test_trades.py
  chia/_tests/wallet/clawback/test_clawback_decorator.py
  chia/_tests/wallet/clawback/test_clawback_metadata.py
  chia/_tests/wallet/db_wallet/test_dl_wallet.py
  chia/_tests/wallet/did_wallet/test_did.py
  chia/_tests/wallet/nft_wallet/test_nft_1_offers.py
  chia/_tests/wallet/nft_wallet/test_nft_bulk_mint.py
  chia/_tests/wallet/nft_wallet/test_nft_wallet.py
  chia/_tests/wallet/rpc/test_dl_wallet_rpc.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/simple_sync/test_simple_sync_protocol.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/_tests/wallet/test_notifications.py
  chia/_tests/wallet/test_wallet.py
  chia/_tests/wallet/test_wallet_action_scope.py
  chia/_tests/wallet/test_wallet_retry.py
  chia/_tests/wallet/test_wallet_state_manager.py
  chia/_tests/wallet/vc_wallet/test_vc_wallet.py
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/simulator/full_node_simulator.py
  chia/util/action_scope.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/derivation_record.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/puzzles/tails.py
  chia/wallet/trade_manager.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_action_scope.py
  chia/wallet/wallet_state_manager.py
  chia/wallet/wsm_apis.py
Labels: ready_to_merge, Changed

#19446 [CHIA-2636] Remove direct secret key access from pool wallet
  chia/_tests/pools/test_pool_cmdline.py
  chia/_tests/pools/test_pool_rpc.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/wallet.py
Labels: ready_to_merge, Changed

#19468 use chia_rs directly for slots
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/farmer_harvester/test_third_party_harvesters.py
  chia/_tests/util/network_protocol_data.py
  chia/_tests/util/test_full_block_utils.py
  chia/consensus/block_header_validation.py
  chia/consensus/full_block_to_block_record.py
  chia/full_node/weight_proof.py
  chia/protocols/farmer_protocol.py
  chia/simulator/block_tools.py
  chia/timelord/timelord.py
  chia/timelord/timelord_state.py
  chia/types/blockchain_format/slots.py
Labels: Changed, Exclude_Notes

#19427 Add ContextManager to FullNodePeers
  chia/_tests/core/server/test_node_discovery.py
  chia/full_node/full_node.py
  chia/server/address_manager.py
  chia/server/node_discovery.py
  chia/wallet/wallet_node.py
Labels: Changed

#19470 use chia_rs directly for spend bundle conditions
  chia/_tests/core/full_node/test_generator_tools.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/fee_estimation/test_fee_estimation_integration.py
  chia/_tests/generator/test_rom.py
  chia/_tests/util/test_condition_tools.py
  chia/consensus/cost_calculator.py
  chia/full_node/mempool_check_conditions.py
  chia/full_node/mempool_manager.py
  chia/full_node/subscriptions.py
  chia/rpc/full_node_rpc_api.py
  chia/types/internal_mempool_item.py
  chia/types/mempool_item.py
  chia/types/spend_bundle_conditions.py
  chia/util/condition_tools.py
  chia/util/generator_tools.py
Labels: Changed, Exclude_Notes

#19471 remove unused function on AddressManager
  chia/server/address_manager.py
Labels: Changed, Cleanup

#19450 CHIA-2646 Fix create_block_generator2 to perform identical spend deduplication using the mempool item's potentially fast forwarded coin spends data
  chia/full_node/mempool.py
Labels: Changed

#19473 CHIA-2675 Simplify transaction skipping eligibility check in create_bundle_from_mempool_items
  chia/full_node/mempool.py
Labels: Changed, Cleanup

#19463 [CHIA-2541] validate more of cached test chains
  .github/workflows/benchmarks.yml
  .github/workflows/test-single.yml
  chia/_tests/blockchain/test_build_chains.py
  chia/_tests/conftest.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/util/blockchain.py
  chia/consensus/block_creation.py
  chia/simulator/block_tools.py
Labels: ready_to_merge, Fixed, Tests

#19495 Use smctl util to sync windows signing certificate
  .github/workflows/build-windows-installer.yml
Labels: Fixed, CI

#19439 CHIA-2604 Separate identical spend deduplication and singleton fast forward into their own classes
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  chia/full_node/mempool.py
  chia/types/eligible_coin_spends.py
Labels: ready_to_merge, Changed

#19493 chore: fix some comments
  PRETTY_GOOD_PRACTICES.md
  chia/consensus/blockchain.py
  chia/consensus/default_constants.py
  chia/types/blockchain_format/program.py
  tools/chialispp.py
Labels: Changed, community-pr

#19498 CHIA-2734 Build a new bundle coin spends map as we process fast forward spends
  chia/types/eligible_coin_spends.py
Labels: Changed

#19295 Set app minimum macos version to 13
  build_scripts/build_macos-2-installer.sh
Labels: Changed

#19413 [CHIA-1161] Migrate `test_nft_1_offers.py` to `WalletTestFramework`
  chia/_tests/wallet/cat_wallet/test_trades.py
  chia/_tests/wallet/nft_wallet/test_nft_1_offers.py
  chia/wallet/trading/offer.py
Labels: Changed, Tests

#19507 catchup: into long_lived/datalayer_merkle_blob from main @ 485d8889032600937571a47b2d41bf01670023d4
  .github/workflows/benchmarks.yml
  .github/workflows/build-windows-installer.yml
  .github/workflows/test-single.yml
  PRETTY_GOOD_PRACTICES.md
  build_scripts/build_macos-2-installer.sh
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/blockchain/test_build_chains.py
  chia/_tests/conftest.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/full_node/test_generator_tools.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  chia/_tests/core/util/test_streamable.py
  chia/_tests/fee_estimation/test_fee_estimation_integration.py
  chia/_tests/generator/test_rom.py
  chia/_tests/util/blockchain.py
  chia/_tests/util/test_condition_tools.py
  chia/_tests/wallet/cat_wallet/test_trades.py
  chia/_tests/wallet/db_wallet/test_dl_offers.py
  chia/_tests/wallet/nft_wallet/test_nft_1_offers.py
  chia/consensus/block_creation.py
  chia/consensus/blockchain.py
  chia/consensus/cost_calculator.py
  chia/consensus/default_constants.py
  chia/data_layer/download_data.py
  chia/full_node/coin_store.py
  chia/full_node/mempool.py
  chia/full_node/mempool_check_conditions.py
  chia/full_node/mempool_manager.py
  chia/full_node/subscriptions.py
  chia/pools/pool_wallet.py
  chia/rpc/full_node_rpc_api.py
  chia/server/address_manager.py
  chia/server/server.py
  chia/simulator/block_tools.py
  chia/types/blockchain_format/program.py
  chia/types/eligible_coin_spends.py
  chia/types/internal_mempool_item.py
  chia/types/mempool_item.py
  chia/types/spend_bundle_conditions.py
  chia/util/condition_tools.py
  chia/util/generator_tools.py
  chia/util/virtual_project_analysis.py
  chia/wallet/trading/offer.py
  poetry.lock
  tools/analyze-chain.py
  tools/chialispp.py
Labels: checkpoint_merge, Changed, coverage-diff

#19293 chore: fix some comments
  chia/full_node/full_node_api.py
Labels: Changed, community-pr

#19442 [CHIA-1162] Port `test_nft_bulk_mint.py` to `WalletTestFramework`
  chia/_tests/wallet/nft_wallet/test_nft_bulk_mint.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_protocol.py
Labels: Changed, Tests

#19492 Refactor `BlockTools`
  .github/workflows/benchmarks.yml
  .github/workflows/test-single.yml
  chia/_tests/blockchain/test_build_chains.py
  chia/_tests/core/full_node/test_full_node.py
  chia/simulator/block_tools.py
Labels: ready_to_merge, Changed

#19509 Remove the manual keychain delete step
  .github/workflows/build-macos-installers.yml
Labels: Fixed, CI

#19508 chia rs 0 22 0
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/util/test_replace_str_to_bytes.py
  chia/_tests/util/test_testnet_overrides.py
  chia/cmds/sim_funcs.py
  chia/consensus/default_constants.py
  chia/simulator/block_tools.py
  chia/types/blockchain_format/program.py
  chia/util/initial-config.yaml
  poetry.lock
  tools/analyze-chain.py
Labels: Changed

#19316 fixup colliding `-o` options on `chia dev gh test`
  chia/cmds/dev/gh.py
Labels: Fixed, Tests

#18566 Set AGG_SIG_ME_ADDITIONAL_DATA in config.yaml for simulator
  chia/cmds/sim_funcs.py
Labels: Fixed

#19437 add `chia dev data sync-time` for doing datalayer sync time tests
  chia/cmds/dev/data.py
  chia/cmds/dev/main.py
  chia/data_layer/data_layer.py
Labels: Added, Exclude_Notes

#19512 catchup: into long_lived/datalayer_merkle_blob from main @ 2449e0c06d7b6d32dbbe1515a76f853d907ae69e
  .github/workflows/benchmarks.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/test-single.yml
  chia/_tests/blockchain/test_build_chains.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/util/test_replace_str_to_bytes.py
  chia/_tests/util/test_testnet_overrides.py
  chia/_tests/wallet/nft_wallet/test_nft_bulk_mint.py
  chia/cmds/dev/gh.py
  chia/cmds/sim_funcs.py
  chia/consensus/default_constants.py
  chia/full_node/full_node_api.py
  chia/rpc/wallet_rpc_api.py
  chia/simulator/block_tools.py
  chia/types/blockchain_format/program.py
  chia/util/initial-config.yaml
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_protocol.py
  poetry.lock
  tools/analyze-chain.py
Labels: checkpoint_merge, Changed, coverage-diff

#19517 catchup: into long_lived/datalayer_merkle_blob from main @ c97f0a1777d455d9a1d26a028362425e634ee066
  .github/dependabot.yml
  chia/cmds/dev/data.py
  chia/cmds/dev/main.py
  chia/cmds/sim_funcs.py
  chia/data_layer/data_layer.py
Labels: checkpoint_merge, Changed

#19511 CHIA-2749 Annotate test_full_node_rpc.py
  chia/_tests/core/test_full_node_rpc.py
  mypy-exclusions.txt
Labels: ready_to_merge, Changed

#19519 validate block generator created by the debug RPC
  chia/full_node/full_node_api.py
  chia/full_node/mempool.py
  chia/rpc/full_node_rpc_api.py
Labels: Added

#19525 update chia_rs datalayer again
  poetry.lock
Labels: Changed, Exclude_Notes

#19505 CHIA-2743 Synchronous block generator creation
  benchmarks/mempool-long-lived.py
  benchmarks/mempool.py
  chia/_tests/blockchain/test_blockchain_transactions.py
  chia/_tests/core/full_node/stores/test_coin_store.py
  chia/_tests/core/full_node/test_performance.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  chia/_tests/util/misc.py
  chia/_tests/util/spend_sim.py
  chia/full_node/coin_store.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/rpc/full_node_rpc_api.py
  chia/simulator/full_node_simulator.py
  chia/types/eligible_coin_spends.py
  chia/types/mempool_item.py
Labels: Changed

#19527 use index when fetching SP
  chia/_tests/core/full_node/stores/test_full_node_store.py
  chia/_tests/core/full_node/test_full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/full_node_store.py
Labels: full_node, Fixed

#19528 store merkle, key, and value blobs in files
  chia/_tests/core/data_layer/conftest.py
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/core/data_layer/test_data_store.py
  chia/cmds/dev/data.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_store.py
  chia/data_layer/util/benchmark.py
  chia/util/initial-config.yaml
Labels: Changed, Exclude_Notes, coverage-diff

#19491 force use of index for `MAX(generation)`
  chia/data_layer/data_store.py
Labels: Fixed, Exclude_Notes

#19524 log an error if we fail to compute the block cost
  chia/full_node/mempool.py
Labels: Added

#19538 log how long it took to call peak_post_processing_2()
  chia/full_node/full_node.py
  chia/full_node/mempool_manager.py
Labels: Changed

#19535 move `chia.types.aliases` to `chia.server.aliases`
  chia/_tests/cmds/test_farm_cmd.py
  chia/_tests/conftest.py
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/core/test_crawler.py
  chia/_tests/farmer_harvester/test_farmer.py
  chia/_tests/farmer_harvester/test_farmer_harvester.py
  chia/_tests/farmer_harvester/test_filter_prefix_bits.py
  chia/_tests/farmer_harvester/test_third_party_harvesters.py
  chia/_tests/fee_estimation/test_fee_estimation_rpc.py
  chia/_tests/plot_sync/test_plot_sync.py
  chia/_tests/plot_sync/test_sync_simulated.py
  chia/_tests/plot_sync/util.py
  chia/_tests/pools/test_pool_rpc.py
  chia/_tests/timelord/test_new_peak.py
  chia/_tests/timelord/test_timelord.py
  chia/_tests/util/setup_nodes.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/test_new_wallet_protocol.py
  chia/seeder/start_crawler.py
  chia/server/aliases.py
  chia/server/start_data_layer.py
  chia/server/start_farmer.py
  chia/server/start_full_node.py
  chia/server/start_harvester.py
  chia/server/start_introducer.py
  chia/server/start_timelord.py
  chia/server/start_wallet.py
  chia/simulator/setup_services.py
Labels: Changed

#19536 move tx processing queue entry classes
  chia/_tests/core/full_node/test_tx_processing_queue.py
  chia/_tests/util/test_misc.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/tx_processing_queue.py
  chia/types/transaction_queue_entry.py
Labels: Changed

#18822 Add some checks when trying to join the same pool already joined
  chia/_tests/pools/test_pool_cmdline.py
  chia/_tests/pools/test_pool_rpc.py
  chia/cmds/plotnft_funcs.py
  chia/rpc/wallet_rpc_api.py
Labels: Changed

#19537 CHIA-2593 Add a unit test to cover an aspect of singleton fast forward dynamics
  chia/_tests/core/mempool/test_mempool_manager.py
Labels: Added

#19544 remove `DataStore.process_merkle_blob_queries()`
  chia/data_layer/data_store.py
Labels: Changed

#19561 release 2 5 4 windows build
  .github/workflows/build-windows-installer.yml
  build_scripts/build_linux_deb-2-installer.sh
  build_scripts/build_windows-2-installer.ps1
Labels: Changed, Exclude_Notes

#19562 Fix double slashes in s3 urls (#19443)
  .github/workflows/reflow-publish-installer.yml
Labels: Changed, Exclude_Notes
