Repository Chia-Network/chia-blockchain, pull requests merged in 2025-01, with the labels that each got.

#19100 Updated License
  LICENSE
Labels: Changed, Exclude_Notes

#18914 task referencer
  benchmarks/mempool.py
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/core/farmer/test_farmer_api.py
  chia/_tests/core/full_node/stores/test_block_store.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/full_node/test_tx_processing_queue.py
  chia/_tests/core/server/flood.py
  chia/_tests/core/server/serve.py
  chia/_tests/core/server/test_loop.py
  chia/_tests/db/test_db_wrapper.py
  chia/_tests/util/test_limited_semaphore.py
  chia/_tests/util/test_priority_mutex.py
  chia/daemon/client.py
  chia/daemon/keychain_proxy.py
  chia/daemon/server.py
  chia/data_layer/data_layer.py
  chia/farmer/farmer.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/weight_proof.py
  chia/introducer/introducer.py
  chia/plot_sync/sender.py
  chia/plotters/plotters_util.py
  chia/rpc/rpc_client.py
  chia/rpc/rpc_server.py
  chia/seeder/crawler.py
  chia/seeder/dns_server.py
  chia/server/node_discovery.py
  chia/server/server.py
  chia/server/signal_handlers.py
  chia/server/start_service.py
  chia/server/ws_connection.py
  chia/simulator/setup_services.py
  chia/timelord/timelord.py
  chia/util/async_pool.py
  chia/util/beta_metrics.py
  chia/util/network.py
  chia/util/task_referencer.py
  chia/wallet/util/wallet_sync_utils.py
  chia/wallet/wallet_node.py
  ruff.toml
Labels: Changed, Exclude_Notes

#19064 Update Managed Files
  .github/dependabot.yml
Labels: Changed, CI, Exclude_Notes

#18716 add use of rust datalayer merkle blob
  .github/actions/install/action.yml
  .github/workflows/check_wheel_availability.yaml
  .github/workflows/test-install-scripts.yml
  chia/_tests/core/data_layer/test_data_store.py
  chia/_tests/core/data_layer/test_merkle_blob.py
  chia/data_layer/data_store.py
  poetry.lock
  pyproject.toml
Labels: Added, Tests

#19103 Update requirements-poetry.txt to use poetry 1.8.5 like dependabot
  requirements-poetry.txt
Labels: Changed, CI

#18930 remove redundant block record conversion CHIA-1286
  chia/consensus/blockchain.py
  chia/full_node/full_node.py
Labels: full_node, sync, Fixed

#19032 Fix TL log spam.
  chia/timelord/timelord.py
Labels: Fixed

#19076 CHIA-2108 Cover computing transactions filter for transaction blocks with only reward coins
  chia/_tests/wallet/sync/test_wallet_sync.py
Labels: Changed, Cleanup

#19112 bump chia_rs to the latest version
  poetry.lock
  pyproject.toml
Labels: ready_to_merge, Changed

#19113 Fix peak_post_processing w/priority_mutex
  chia/full_node/full_node.py
Labels: Fixed

#19114 sqlite cached_statements workaround
  chia/util/db_wrapper.py
Labels: Changed

#19080 go back to <4 as the python version upper limit
  poetry.lock
  pyproject.toml
Labels: Changed

#19121 avoid a traceback on failure
  chia/cmds/data_funcs.py
Labels: Fixed

#19106 clean overflow blocks moved to unfinished block cache on reset chain
  chia/timelord/timelord.py
Labels: timelord, Fixed

#19125 Add seeder.xchseeder.com to dns_servers in config.yaml
  chia/util/initial-config.yaml
Labels: ready_to_merge, Added, community-pr

#19129 Fixed an issue where cancelling NFT offer did not cancel other offers…
  chia/rpc/wallet_rpc_api.py
  chia/wallet/trade_manager.py
  chia/wallet/wallet_state_manager.py
Labels: Fixed, coverage-diff

#19128 CHIA-2215 Annotate run_block.py
  mypy-exclusions.txt
  tools/run_block.py
Labels: Changed, Cleanup

#19127 CHIA-2210 Remove no longer needed TestFullNodeBlockCompression and TestFullNodeProtocol classes
  chia/_tests/core/full_node/test_full_node.py
Labels: Changed, Cleanup

#19126 Optimize missing hashes lookup.
  chia/data_layer/data_store.py
Labels: Changed, DataLayer

#19134 add a time-out of adding more transactions to blocks
  chia/full_node/full_node_api.py
  chia/full_node/mempool.py
Labels: Changed

#19133 bump chia_rs to 0.18.0
  chia/_tests/blockchain/blockchain_test_utils.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/full_node/test_generator_tools.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/fee_estimation/test_fee_estimation_integration.py
  chia/_tests/util/test_condition_tools.py
  chia/simulator/block_tools.py
  chia/types/blockchain_format/program.py
  poetry.lock
  pyproject.toml
Labels: ready_to_merge, Changed

#19120 [CHIA-2198] Don't create zero amount royalty payments
  chia/wallet/nft_wallet/nft_wallet.py
Labels: ready_to_merge, Fixed

#19132 Name wallet protocol subscription messages consistently
  CHANGELOG.md
  chia/_tests/wallet/simple_sync/test_simple_sync_protocol.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/_tests/wallet/test_wallet_node.py
  chia/full_node/full_node_api.py
  chia/protocols/protocol_message_types.py
  chia/protocols/protocol_state_machine.py
  chia/server/rate_limit_numbers.py
  chia/wallet/util/wallet_sync_utils.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_node_api.py
Labels: full_node, Changed

#19155 check resolution of example.net more loosely
  chia/_tests/util/test_network.py
Labels: ready_to_merge, Fixed, Tests

#19159 catchup: into long_lived/datalayer_merkle_blob from main @ 27c34ec92c25b724827b6b1030d0a96e947a57e2
  CHANGELOG.md
  chia/_tests/blockchain/blockchain_test_utils.py
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/core/data_layer/test_merkle_blob.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/full_node/test_generator_tools.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/fee_estimation/test_fee_estimation_integration.py
  chia/_tests/util/test_condition_tools.py
  chia/_tests/util/test_network.py
  chia/_tests/wallet/simple_sync/test_simple_sync_protocol.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/_tests/wallet/test_wallet_node.py
  chia/cmds/data_funcs.py
  chia/consensus/blockchain.py
  chia/consensus/multiprocess_validation.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool.py
  chia/protocols/protocol_message_types.py
  chia/protocols/protocol_state_machine.py
  chia/rpc/util.py
  chia/rpc/wallet_rpc_api.py
  chia/server/rate_limit_numbers.py
  chia/simulator/block_tools.py
  chia/timelord/timelord.py
  chia/types/blockchain_format/program.py
  chia/util/db_wrapper.py
  chia/util/generator_tools.py
  chia/util/initial-config.yaml
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
  chia/wallet/util/wallet_sync_utils.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_node_api.py
  chia/wallet/wallet_state_manager.py
  mypy-exclusions.txt
  poetry.lock
  pyproject.toml
  ruff.toml
  tools/run_block.py
Labels: checkpoint_merge, Changed, coverage-diff

#19156 correct test to avoid shared blob bytes
  chia/_tests/core/data_layer/test_merkle_blob.py
Labels: Fixed, Exclude_Notes

#19163 fix new actionlint/shellcheck complaint
  .github/workflows/build-windows-installer.yml
  .github/workflows/upload-pypi-source.yml
Labels: Added, CI

#19178 narrow to `bytes32` hinting in `DataStore.insert_batch()`
  chia/_tests/core/data_layer/test_merkle_blob.py
  chia/data_layer/data_store.py
  chia/data_layer/util/merkle_blob.py
Labels: Changed, Exclude_Notes

#19177 make `ProofOfInclusion.root_hash` a method, from a property
  chia/data_layer/data_layer_util.py
  chia/data_layer/data_layer_wallet.py
Labels: Changed, Exclude_Notes

#19180 separate `KvID` to `KeyId` and `ValueId`
  chia/_tests/core/data_layer/test_merkle_blob.py
  chia/data_layer/data_store.py
  chia/data_layer/util/merkle_blob.py
Labels: Changed, Exclude_Notes, coverage-diff

#19137 CHIA-2218 Remove no longer needed get_block_path
  chia/_tests/core/full_node/test_full_node.py
Labels: Changed, Cleanup

#19141 CHIA-2220 Fix a typo when picking the best unfinished block in test_request_unfinished_block2
  chia/_tests/core/full_node/test_full_node.py
Labels: Changed, Cleanup

#19142 CHIA-2221 Remove no longer needed has_peers_with_peak
  chia/_tests/core/full_node/full_sync/test_full_sync.py
Labels: Changed, Cleanup

#19143 CHIA-2222 Annotate analyze-chain.py
  mypy-exclusions.txt
  tools/analyze-chain.py
Labels: Changed, Cleanup

#19162 [CHIA-1219] Allow coin selection of 0 value coins
  chia/_tests/wallet/test_coin_selection.py
  chia/wallet/coin_selection.py
Labels: ready_to_merge, Fixed

#19167 Remove old offer guards
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/rpc/wallet_rpc_api.py
Labels: ready_to_merge, Changed

#19153 [CHIA-2224] Add some extra safety into `create_message_spend`
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/did_wallet/did_wallet_puzzles.py
Labels: ready_to_merge, Fixed

#19161 move augmented to caller
  chia/_tests/util/full_sync.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/full_node/full_node.py
  chia/simulator/add_blocks_in_batches.py
  tools/test_full_sync.py
Labels: full_node, sync, Fixed

#19174 fix new actionlint/shellcheck complaint (#19163)
  .github/workflows/build-windows-installer.yml
  .github/workflows/upload-pypi-source.yml
Labels: Changed, Cleanup

#19139 CHIA-2219 Fix a plot ID calculation typo in test_unfinished_block_with_replaced_generator
  chia/_tests/core/full_node/test_full_node.py
Labels: Changed, Cleanup

#19154 streamable for merkle blob serialization
  chia/_tests/core/data_layer/test_merkle_blob.py
  chia/data_layer/util/merkle_blob.py
Labels: Changed

#19182 [CHIA-2264] Add config constant support to `chia db validate`
  chia/_tests/core/test_db_validation.py
  chia/cmds/db_validate_func.py
Labels: ready_to_merge, Added

#19173 check resolution of example.net more loosely (#19155)
  chia/_tests/util/test_network.py
Labels: Changed, Cleanup

#19193 Move `check_fork_next_block.py` to `chia.full_node`
  chia/full_node/check_fork_next_block.py
  chia/full_node/full_node.py
Labels: Fixed, Cleanup

#19037 delete `chia/simulator/simulator_constants.py`
  chia/simulator/simulator_constants.py
Labels: Changed

#19054 semantic newlines in `PRETTY_GOOD_PRACTICES.md`
  PRETTY_GOOD_PRACTICES.md
Labels: Changed, Exclude_Notes

#19176 updated chia_rs to latest version (0.19.1)
  poetry.lock
  pyproject.toml
Labels: Changed

#19175 Change delta format
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/data_layer_util.py
  chia/data_layer/data_store.py
Labels: Changed, DataLayer
