Repository Chia-Network/chia-blockchain, pull requests merged in 2025-03, with the labels that each got.

#19332 use chia_rs directly for pool target
  benchmarks/block_store.py
  chia/_tests/util/benchmarks.py
  chia/_tests/util/network_protocol_data.py
  chia/_tests/util/test_full_block_utils.py
  chia/_tests/wallet/wallet_block_tools.py
  chia/consensus/block_creation.py
  chia/farmer/farmer_api.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/protocols/farmer_protocol.py
  chia/simulator/block_tools.py
  chia/types/blockchain_format/pool_target.py
Labels: Changed, Exclude_Notes

#19337 bump chia_rs to 0.21.0
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  poetry.lock
  pyproject.toml
Labels: Changed

#19336 use chia_rs directly for reward chain block
  benchmarks/block_store.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/util/benchmarks.py
  chia/_tests/util/network_protocol_data.py
  chia/_tests/util/test_full_block_utils.py
  chia/_tests/wallet/wallet_block_tools.py
  chia/consensus/block_creation.py
  chia/full_node/full_node_api.py
  chia/protocols/farmer_protocol.py
  chia/protocols/harvester_protocol.py
  chia/protocols/timelord_protocol.py
  chia/timelord/iters_from_block.py
  chia/timelord/timelord.py
  chia/types/blockchain_format/reward_chain_block.py
  chia/types/unfinished_header_block.py
  chia/types/weight_proof.py
Labels: Changed, Exclude_Notes

#19335 cache `get_unspent_lineage_info()`
  benchmarks/mempool.py
  chia/_tests/blockchain/test_blockchain_transactions.py
  chia/_tests/core/full_node/test_performance.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  chia/_tests/util/spend_sim.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool_manager.py
  chia/simulator/full_node_simulator.py
Labels: ready_to_merge, Added

#19340 fix `MerkleBlob.get_min_height_leaf()`
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/data_layer/util/merkle_blob.py
Labels: Fixed, Exclude_Notes

#19356 bump chia_rs to 0.21.1
  poetry.lock
  pyproject.toml
Labels: ready_to_merge, Changed

#19352 [CHIA-2503] make the super set rule stricter
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/full_node/mempool_manager.py
Labels: ready_to_merge, Changed

#19333 Add fallback for introducer.
  chia/_tests/simulation/test_simulation.py
  chia/_tests/util/setup_nodes.py
  chia/introducer/introducer.py
  chia/introducer/introducer_api.py
  chia/server/start_introducer.py
  chia/util/initial-config.yaml
Labels: Fixed

#19354 datalayer: use rust
  chia/_tests/core/data_layer/test_data_store.py
  chia/_tests/core/data_layer/test_merkle_blob.py
  chia/data_layer/data_store.py
  chia/data_layer/util/merkle_blob.py
  poetry.lock
Labels: Changed, Exclude_Notes

#19286 Add increment to skipped_items if we hit an Exception in mempool
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/full_node/mempool.py
  chia/types/eligible_coin_spends.py
Labels: ready_to_merge, Changed

#19355 [CHIA-2383] improve FF mempool eviction
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/util/misc.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/types/mempool_item.py
Labels: ready_to_merge, Fixed

#19361 checkpoint: into main from release/2.5.2 @ 7eb79c18941c40435e61a59fd5b2c1500bbbedc3
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#19353 remove coin cache
  chia/full_node/coin_store.py
Labels: Changed

#19368 just use latest chia_rs for datalayer
  poetry.lock
Labels: Changed, Exclude_Notes

#19376 use `.execute_insert()` in `DataStore.add_kvid()`
  chia/data_layer/data_store.py
Labels: Changed, Exclude_Notes

#19379 Add benchmark test.
  chia/_tests/core/data_layer/test_data_store.py
Labels: Added, Tests, DataLayer

#19382 use `.writer_maybe_transaction()` in `DataStore.add_kvid()`
  chia/data_layer/data_store.py
Labels: Changed, Exclude_Notes

#19367 CHIA-2538 Remove no longer needed item_inclusion_filter in the mempool
  chia/_tests/fee_estimation/test_mempoolitem_height_added.py
  chia/_tests/util/spend_sim.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
Labels: Changed

#19267 CHIA-2375 Remove no longer needed TestDIDWallet class
  chia/_tests/wallet/did_wallet/test_did.py
Labels: Changed, Cleanup

#19386 checkpoint: into main from release/2.5.3 @ 4ae44855b12922df6bf9524e4c2bd431f9dcf54c
  chia/_tests/core/mempool/test_mempool.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
Labels: ready_to_merge, checkpoint_merge, Changed

#19387 bypass error while uninstalling gui on amazonlinux:2023
  .github/workflows/build-linux-installer-rpm.yml
Labels: ready_to_merge, Fixed, CI

#19262 CHIA-2367 Separate height to hash and sub epoch summaries files by networks
  chia/consensus/blockchain.py
  chia/full_node/block_height_map.py
  chia/full_node/full_node.py
Labels: Changed, Cleanup

#19395 remove use of ppa provided git in `test-install-scripts.yml`
  .github/workflows/test-install-scripts.yml
Labels: Fixed, CI

#18527 validate cached blockchains
  .github/workflows/benchmarks.yml
  .github/workflows/test-single.yml
  chia/_tests/util/blockchain.py
Labels: ready_to_merge, Added, Tests

#19399 checkpoint: into main from release/2.5.3 @ 1b75fbdaf4bd0a30e0e2a7e8ff5d02b72581f27e
  .github/workflows/test-install-scripts.yml
Labels: checkpoint_merge, Changed

#19396 stop forcing pyenv usage on macos intel in `check_wheel_availability.yaml`
  .github/workflows/check_wheel_availability.yaml
Labels: Fixed, CI

#19271 CHIA-2378: Add CLI commands to import, export, and benchmark the mempool
  chia/cmds/dev.py
  chia/cmds/mempool.py
  chia/cmds/mempool_funcs.py
  chia/rpc/full_node_rpc_api.py
  chia/rpc/full_node_rpc_client.py
Labels: CLI, ready_to_merge, Added

#19400 checkpoint: into main from release/2.5.3 @ c9050689ed35ad159f9523cd4d9d7a8b31ef4379
  .github/workflows/check_wheel_availability.yaml
Labels: checkpoint_merge, Changed

#19409 breakdown `DataStore.insert_into_data_store_from_file()`
  chia/data_layer/data_store.py
Labels: Changed, Exclude_Notes, coverage-diff

#19390 NewBlockGenerator as an extension of BlockGenerator
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/consensus/block_creation.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/rpc/full_node_rpc_api.py
  chia/simulator/block_tools.py
  chia/types/generator_types.py
Labels: ready_to_merge, Changed, Exclude_Notes

#19411 catchup: into long_lived/datalayer_merkle_blob from main @ 885107b78761b38beef94427eca51d062c289645
  .github/workflows/benchmarks.yml
  .github/workflows/build-linux-installer-rpm.yml
  .github/workflows/check_wheel_availability.yaml
  .github/workflows/test-install-scripts.yml
  .github/workflows/test-single.yml
  CHANGELOG.md
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/fee_estimation/test_mempoolitem_height_added.py
  chia/_tests/simulation/test_simulation.py
  chia/_tests/timelord/test_new_peak.py
  chia/_tests/util/blockchain.py
  chia/_tests/util/misc.py
  chia/_tests/util/setup_nodes.py
  chia/_tests/util/spend_sim.py
  chia/_tests/wallet/did_wallet/test_did.py
  chia/cmds/cmds_util.py
  chia/cmds/dev.py
  chia/cmds/mempool.py
  chia/cmds/mempool_funcs.py
  chia/consensus/blockchain.py
  chia/full_node/block_height_map.py
  chia/full_node/coin_store.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/introducer/introducer.py
  chia/introducer/introducer_api.py
  chia/rpc/full_node_rpc_api.py
  chia/rpc/full_node_rpc_client.py
  chia/server/start_introducer.py
  chia/timelord/timelord_api.py
  chia/types/eligible_coin_spends.py
  chia/types/mempool_item.py
  chia/util/initial-config.yaml
  chia/util/task_timing.py
  tools/analyze_memory_profile.py
Labels: checkpoint_merge, Changed, coverage-diff

#19408 combine adding node hashes into single `.executemany()` call
  chia/data_layer/data_store.py
Labels: Changed, Exclude_Notes

#19410 less unneeded `bytes32`ing
  chia/data_layer/data_store.py
Labels: Changed, Exclude_Notes

#19407 correct sql limit to match batch length
  chia/data_layer/data_store.py
Labels: Fixed, Exclude_Notes

#19398 CHIA-2570 Adapt to requiring the same amount across singleton fast forward versions
  chia/_tests/core/full_node/stores/test_coin_store.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  chia/full_node/coin_store.py
  chia/types/eligible_coin_spends.py
Labels: Changed

#19392 Check full node state in tl tests
  chia/_tests/timelord/test_new_peak.py
Labels: full_node, timelord, Fixed, Tests

#19416 log exceptions while inserting from delta file
  chia/data_layer/download_data.py
Labels: Changed, Exclude_Notes

#19417 add `CHIA_DATA_LAYER_STOP_AFTER_GENERATION` env var for timing tests
  chia/data_layer/download_data.py
Labels: Changed, Exclude_Notes

#19415 pass around some connections
  chia/data_layer/data_store.py
Labels: Changed, Exclude_Notes

#19419 simplify chia command key root path handling
  chia/cmds/chia.py
Labels: Changed, Exclude_Notes

#19418 subdirectory for chia dev commands
  chia/_tests/cmds/test_dev_gh.py
  chia/cmds/chia.py
  chia/cmds/dev/__init__.py
  chia/cmds/dev/gh.py
  chia/cmds/dev/installers.py
  chia/cmds/dev/main.py
  chia/cmds/dev/mempool.py
  chia/cmds/dev/mempool_funcs.py
  chia/cmds/dev/sim.py
Labels: Changed, Exclude_Notes

#19421 datalayer compress for db
  chia/data_layer/data_store.py
Labels: Changed, Exclude_Notes

#19422 avoid unneeded conversion to bytearray
  chia/data_layer/data_store.py
Labels: Changed, Exclude_Notes

#19414 CHIA-2580 Significantly speedup mempool manager tests by not forcing them to request unneeded fixtures
  chia/_tests/core/mempool/test_mempool_manager.py
Labels: Changed

#19420 add the keys root path to `ChiaCliContext`
  chia/cmds/chia.py
  chia/cmds/cmd_classes.py
Labels: Changed, Exclude_Notes

#19426 catchup: into long_lived/datalayer_merkle_blob from main @ 99448387ada5dd492d06261ab823c59c2a55b231
  chia/_tests/cmds/test_dev_gh.py
  chia/_tests/core/full_node/stores/test_coin_store.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  chia/_tests/timelord/test_new_peak.py
  chia/cmds/chia.py
  chia/cmds/cmd_classes.py
  chia/cmds/dev/__init__.py
  chia/cmds/dev/gh.py
  chia/cmds/dev/installers.py
  chia/cmds/dev/main.py
  chia/cmds/dev/mempool.py
  chia/cmds/dev/mempool_funcs.py
  chia/cmds/dev/sim.py
  chia/consensus/block_creation.py
  chia/full_node/coin_store.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/rpc/full_node_rpc_api.py
  chia/simulator/block_tools.py
  chia/types/eligible_coin_spends.py
  chia/types/generator_types.py
Labels: checkpoint_merge, Changed

#19424 2.5.3 changelog
  CHANGELOG.md
Labels: Changed

#19429 Fix changelog typo
  CHANGELOG.md
Labels: Fixed, Exclude_Notes

#19385 [CHIA-2546] Refactor and add test for WSM puzzle hash endpoints
  chia/_tests/environments/wallet.py
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/conftest.py
  chia/_tests/wallet/test_wallet_state_manager.py
  chia/util/db_wrapper.py
  chia/wallet/wallet_node.py
  chia/wallet/wallet_puzzle_store.py
  chia/wallet/wallet_state_manager.py
  chia/wallet/wsm_apis.py
Labels: ready_to_merge, Changed

#19375 CHIA-2545 Annotate test_wallet_rpc.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  mypy-exclusions.txt
Labels: Changed

#19412 CHIA-2577 Remove no longer needed TestFullSync class
  chia/_tests/core/full_node/full_sync/test_full_sync.py
Labels: Changed, Cleanup

#19435 CHIA-2596 Simplify latest_singleton_coin checking in invariant_check_mempool
  chia/_tests/util/misc.py
Labels: Changed, Cleanup

#19438 checkpoint: into main from release/2.5.3 @ 51fff62b1ea26786aaf34c2084a5ff80b116a5b9
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#19434 bump chia_rs to 0.21.2
  poetry.lock
  pyproject.toml
Labels: ready_to_merge, Changed

#19270 [CHIA-2052] Compressed blocks
  benchmarks/mempool.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/rpc/full_node_rpc_api.py
Labels: ready_to_merge, Changed

#19369 ensure poetry version via install scripts
  Install.ps1
  Setup-poetry.ps1
  install.sh
  setup-poetry.sh
Labels: Changed, Exclude_Notes

#19436 add `CHIA_DATA_LAYER_STOP_AFTER_GENERATION` env var for timing tests (#19417)
  chia/data_layer/download_data.py
Labels: Added, Exclude_Notes
