Repository Chia-Network/chia-blockchain, pull requests merged in 2025-09, with the labels that each got.

#20018 CHIA-3718 Handle building chiavdf for MacOS when CMake is already installed
  install-timelord.sh
Labels: Changed

#19990 Rate limits cleanup
  chia/_tests/core/server/test_rate_limits.py
  chia/server/rate_limit_numbers.py
  chia/server/rate_limits.py
Labels: Changed, Cleanup

#20009 Swap to self hosted mac intel runners for installer build
  .github/workflows/build-macos-installers.yml
  .github/workflows/check_wheel_availability.yaml
  .github/workflows/pre-commit.yml
  .github/workflows/test-install-scripts.yml
  .github/workflows/test.yml
  .github/workflows/upload-pypi-source.yml
Labels: Changed, CI, Exclude_Notes

#19969 [CHIA-3654] [CHIA-3537] [CHIA-3673] stub chiapos2 API
  chia/_tests/core/custom_types/test_proof_of_space.py
  chia/_tests/plotting/test_prover.py
  chia/consensus/pos_quality.py
  chia/harvester/harvester_api.py
  chia/plotting/prover.py
  chia/simulator/block_tools.py
  chia/solver/solver.py
  chia/types/blockchain_format/proof_of_space.py
Labels: ready_to_merge, Added, Exclude_Notes

#20012 checkpoint: into main from release/2.5.6 @ ecb54a5874681326b9ba0d0f33e68c8d718c8639
  chia/_tests/harvester/test_harvester_api.py
  chia/_tests/util/build_network_protocol_files.py
  chia/_tests/util/network_protocol_data.py
  chia/_tests/util/protocol_messages_bytes-v1.0
  chia/_tests/util/protocol_messages_json.py
  chia/_tests/util/test_network_protocol_files.py
  chia/_tests/util/test_network_protocol_json.py
  chia/_tests/util/test_network_protocol_test.py
  chia/farmer/farmer_api.py
  chia/harvester/harvester_api.py
  chia/protocols/harvester_protocol.py
Labels: checkpoint_merge, Changed

#20026 fixup coverage handling with conditional macos-intel execution
  .github/workflows/test.yml
Labels: Fixed, Exclude_Notes

#20022 remove unnecessary NPCResult in mempool_manager
  chia/full_node/mempool_manager.py
  chia/types/internal_mempool_item.py
Labels: ready_to_merge, Changed, Exclude_Notes

#20023 bump chia_rs dependency
  chia/_tests/blockchain/blockchain_test_utils.py
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/core/custom_types/test_proof_of_space.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/full_node/test_generator_tools.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/fee_estimation/test_fee_estimation_integration.py
  chia/_tests/util/test_condition_tools.py
  chia/_tests/util/test_replace_str_to_bytes.py
  chia/consensus/default_constants.py
  chia/full_node/eligible_coin_spends.py
  chia/full_node/mempool_manager.py
  chia/types/blockchain_format/proof_of_space.py
  poetry.lock
  pyproject.toml
Labels: ready_to_merge, Changed

#20004 add another case to `test_get_rate_limits_to_use()`
  chia/_tests/core/server/test_rate_limits.py
Labels: Added, Tests

#19982 [CHIA-3701] Check plots v2
  chia/plotting/check_plots.py
Labels: ready_to_merge, Added

#20010 test on linux arm :penguin: :muscle: :boom:
  .github/workflows/test.yml
Labels: Changed, CI

#20044 CHIA-3731 Cover peak post processing w.r.t. added transactions as a result of retrying potential transactions
  chia/_tests/core/full_node/test_full_node.py
Labels: Added

#20031 [CHIA-3729] Fix clvm streamable type analysis
  chia/util/streamable.py
  chia/wallet/util/clvm_streamable.py
Labels: Fixed

#20063 [CHIA-3712] simplify add_transaction()
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/mempool/test_mempool.py
  chia/full_node/full_node.py
  chia/server/server.py
Labels: Changed, Exclude_Notes

#20090 catchup: into long_lived/datalayer_merkle_blob from main @ 3652e609bdcdb199ece68bcfd60665d19594e5f0
  .github/workflows/test-install-scripts.yml
  build_scripts/npm_global/__init__.py
  build_scripts/npm_global/package-lock.json
  build_scripts/npm_global/package.json
  install-gui.sh
  start-gui.sh
Labels: checkpoint_merge, Changed

#19987 [CHIA-3603] Port `send_notifications` to `@marshal`
  chia/_tests/cmds/wallet/test_notifications.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/cmds/wallet_funcs.py
  chia/wallet/wallet_request_types.py
  chia/wallet/wallet_rpc_api.py
  chia/wallet/wallet_rpc_client.py
Labels: Changed

#20083 update clvm to 0.9.15
  poetry.lock
Labels: Changed, Exclude_Notes

#20089 use bash for test install scripts, except the ps1 step
  .github/workflows/test-install-scripts.yml
Labels: Changed, CI

#20079 back to full binary wheel checks etc
  .github/actions/install/action.yml
  .github/workflows/check_wheel_availability.yaml
  .github/workflows/test-install-scripts.yml
Labels: Changed, Exclude_Notes

#20097 CHIA-3758 Avoid recomputing mempool removals' transaction IDs in FullNode's broadcast_removed_tx
  chia/full_node/full_node.py
  chia/full_node/mempool.py
Labels: Changed

#20098 [LABS-126] Add label support to `/add_key`
  chia/wallet/wallet_request_types.py
  chia/wallet/wallet_rpc_api.py
Labels: Added

#20092 Update chiavdf to 1.1.13
  poetry.lock
Labels: Changed

#20121 Install latest boost instead of boost@1.85 on macos in `install-timelord.sh`
  install-timelord.sh
Labels: Fixed
