Repository Chia-Network/chia-blockchain, pull requests merged in 2025-10, with the labels that each got.

#20120 MacOS intel tests on macos-15-intel
  .github/workflows/test-single.yml
  .github/workflows/test.yml
Labels: Changed, CI, Exclude_Notes

#20132 stop installing sudo for testing install scripts
  .github/workflows/test-install-scripts.yml
Labels: Changed, CI

#20123 CHIA-2515 Simplify MempoolItem by constructing SpendBundle on demand from its components
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_item_queries.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  chia/_tests/fee_estimation/test_fee_estimation_integration.py
  chia/full_node/eligible_coin_spends.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/types/internal_mempool_item.py
  chia/types/mempool_item.py
Labels: Changed
