Repository Chia-Network/chia-blockchain, pull requests merged in 2025-02, with the labels that each got.

#19200 [CHIA-689] Port `test_dl_wallet.py` to `WalletTestFramework`
  chia/_tests/wallet/db_wallet/test_dl_wallet.py
Labels: Changed

#19215 chia.types no longer depends upon chia.protocols
  chia/types/coin_record.py
Labels: Changed

#19217 CHIA-2301 Cover maintaining correct mempool item's height added to mempool value on mempool update or rebuild
  chia/_tests/core/mempool/test_mempool_manager.py
Labels: Added, Cleanup

#19222 fixup `test_db_validate_default_1000_blocks()`
  chia/_tests/core/test_db_validation.py
Labels: Fixed, Tests

#19208 check on import that assertions are working
  chia/__init__.py
Labels: Fixed

#19227 catchup: into long_lived/datalayer_merkle_blob from main @ 1d9ab3cf0a1231d318a8d971c8296f4f82555553
  chia/_tests/core/full_node/test_transactions.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/test_db_validation.py
  chia/_tests/util/test_full_block_utils.py
  chia/_tests/util/time_out_assert.py
  chia/_tests/wallet/db_wallet/test_dl_wallet.py
  chia/types/coin_record.py
  mypy-exclusions.txt
Labels: checkpoint_merge, Changed

#19220 use undelying height_to_hash to check main chain
  chia/full_node/full_node.py
Labels: Fixed

#19233 bump chiapos to 2.0.9rc1, with Earle's fix
  poetry.lock
  pyproject.toml
Labels: ready_to_merge, Fixed

#19209 Standardize the `Wallet` API for `generate_signed_transaction`
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/full_node/test_transactions.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/mempool/test_mempool_performance.py
  chia/_tests/simulation/test_simulation.py
  chia/_tests/simulation/test_simulator.py
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/did_wallet/test_did.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/simple_sync/test_simple_sync_protocol.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/_tests/wallet/test_wallet.py
  chia/_tests/wallet/test_wallet_node.py
  chia/_tests/wallet/test_wallet_retry.py
  chia/_tests/wallet/test_wallet_state_manager.py
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/simulator/full_node_simulator.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/notification_manager.py
  chia/wallet/puzzles/tails.py
  chia/wallet/trade_manager.py
  chia/wallet/wallet.py
Labels: Changed

#19225 avoid asyncio bug in 3.12.8
  .github/workflows/test-single.yml
Labels: Fixed, CI

#19235 Comment out arch linux install test
  .github/workflows/test-install-scripts.yml
Labels: Fixed, CI, Exclude_Notes

#19206 CHIA-2282 Improve some coins checks in test_select_coins_rpc
  chia/_tests/wallet/rpc/test_wallet_rpc.py
Labels: Changed, Cleanup

#19214 use chia_rs provided `KeyId`, `ValueId`, `TreeIndex`
  chia/_tests/core/data_layer/test_data_store.py
  chia/_tests/core/data_layer/test_merkle_blob.py
  chia/data_layer/data_store.py
  chia/data_layer/util/merkle_blob.py
  poetry.lock
Labels: Changed, CI

#19238 drop `MerkleBlob.get_lineage_by_key_id()`
  chia/_tests/core/data_layer/test_merkle_blob.py
  chia/data_layer/data_store.py
  chia/data_layer/util/merkle_blob.py
Labels: Changed, Exclude_Notes

#19240 bump chiapos to 2.0.9
  poetry.lock
  pyproject.toml
Labels: Fixed

#19237 checkpoint: into main from release/2.5.1 @ 6ad68961e9f0a07cf6668a93d13116c5f5b5bde6
  poetry.lock
  pyproject.toml
Labels: checkpoint_merge, Changed

#19179 create `MerkleTypes` testing compatibility interface
  chia/_tests/core/data_layer/test_merkle_blob.py
Labels: Changed, Exclude_Notes

#19246 Comment out arch linux install test (#19235)
  .github/workflows/test-install-scripts.yml
Labels: Changed, Tests

#19247 checkpoint: into main from release/2.5.1 @ bbc8d253d3a663d0cd4b829348f66177e9002d27
  .github/workflows/test-single.yml
Labels: checkpoint_merge, Changed

#19190 chore: fix some typos
  chia/_tests/wallet/test_wallet_test_framework.py
  chia/full_node/full_node.py
  chia/full_node/weight_proof.py
  chia/wallet/vc_wallet/vc_wallet.py
Labels: Fixed, community-pr

#19096 chore: fix 404 status URL
  chia/_tests/core/util/test_keychain.py
Labels: Fixed, community-pr

#19234 Bring `VCWallet.generate_signed_transaction` into conformity
  chia/_tests/wallet/vc_wallet/test_vc_wallet.py
  chia/rpc/wallet_rpc_api.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet_protocol.py
Labels: Changed, coverage-diff

#19253 Deprecate n-weso.
  chia/timelord/timelord.py
  chia/util/initial-config.yaml
Labels: timelord, Changed

#19255 checkpoint: into main from release/2.5.1 @ db2776570efd439cf410f40661e5ac0beaeeca72
  poetry.lock
  pyproject.toml
Labels: checkpoint_merge, Changed

#19257 checkpoint: into main from release/2.5.1 @ 76e877f5d3647639be65a2b39090984f27ece7e9
  poetry.lock
  pyproject.toml
Labels: checkpoint_merge, Changed

#19244 Add `generate_signed_transaction` to `WalletProtocol`
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/wallet/cat_wallet/dao_cat_wallet.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_protocol.py
Labels: Changed

#19207 `create_block_generator` refactor
  benchmarks/mempool.py
  chia/_tests/core/mempool/test_mempool.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/types/generator_types.py
Labels: ready_to_merge, Changed

#19228 Remove DL hashes table
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/data_store.py
  chia/data_layer/util/merkle_blob.py
Labels: Changed, DataLayer

#19269 more datalayer python/rust parametrization
  chia/_tests/core/data_layer/test_merkle_blob.py
  chia/data_layer/util/merkle_blob.py
  poetry.lock
Labels: Changed, Tests

#19268 import ENABLE_KECCAK and ENABLE_KECCAK_OPS_OUTSIDE_GUARD from chia_rs
  chia/_tests/core/mempool/test_mempool.py
Labels: Fixed, Tests, Cleanup

#19276 [CHIA-2380] harden mempool fast-forward feature
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
Labels: ready_to_merge, Fixed

#19273 CHIA-2382 Create a mempool item out of a copy of the input one when processing fast forward spends
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  chia/full_node/mempool.py
  chia/types/eligible_coin_spends.py
  chia/types/internal_mempool_item.py
Labels: Changed

#19272 CHIA-2381 Validate fast forward spends before adding their spend bundle to the mempool
  benchmarks/mempool-long-lived.py
  benchmarks/mempool.py
  chia/_tests/core/mempool/test_mempool_fee_estimator.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  chia/_tests/util/spend_sim.py
  chia/full_node/full_node.py
  chia/full_node/mempool_manager.py
  chia/types/eligible_coin_spends.py
Labels: ready_to_merge, Changed

#19285 checkpoint: into main from release/2.5.2 @ 6e542f051ef6ad2aca5f16c76c5c0e97a6616e29
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
Labels: checkpoint_merge, Changed

#19284 Syncstorewjb
  chia/full_node/full_node.py
Labels: Fixed

#19281 parametrize datalayer proof of inclusion for rust as well
  chia/_tests/core/data_layer/test_merkle_blob.py
  chia/data_layer/util/merkle_blob.py
  poetry.lock
Labels: Changed, Tests

#19288 checkpoint: into main from release/2.5.2 @ ad755916ab664abb207421e042328ca1603658ab
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  chia/full_node/mempool.py
  chia/types/eligible_coin_spends.py
  chia/types/internal_mempool_item.py
Labels: checkpoint_merge, Changed

#19289 EL.changelog-2.5.2
  CHANGELOG.md
Labels: Changed, Exclude_Notes

#19226 CHIA-2320 Annotate test_full_node.py
  chia/_tests/core/full_node/test_full_node.py
  mypy-exclusions.txt
Labels: Changed, Cleanup

#19266 [CHIA-2369] Legacy-ify DAOs
  chia/_tests/cmds/wallet/test_dao.py
  chia/_tests/wallet/dao_wallet/__init__.py
  chia/_tests/wallet/dao_wallet/config.py
  chia/_tests/wallet/dao_wallet/test_dao_clvm.py
  chia/_tests/wallet/dao_wallet/test_dao_wallets.py
  chia/_tests/wallet/test_singleton_store.py
  chia/cmds/chia.py
  chia/cmds/dao.py
  chia/cmds/dao_funcs.py
  chia/cmds/wallet_funcs.py
  chia/rpc/wallet_request_types.py
  chia/rpc/wallet_rpc_api.py
  chia/rpc/wallet_rpc_client.py
  chia/wallet/cat_wallet/dao_cat_info.py
  chia/wallet/cat_wallet/dao_cat_wallet.py
  chia/wallet/dao_wallet/__init__.py
  chia/wallet/dao_wallet/dao_info.py
  chia/wallet/dao_wallet/dao_utils.py
  chia/wallet/dao_wallet/dao_wallet.py
  chia/wallet/puzzles/deployed_puzzle_hashes.json
  chia/wallet/puzzles/tails.py
  chia/wallet/util/wallet_types.py
  chia/wallet/wallet_state_manager.py
Labels: Changed

#19298 checkpoint: into main from release/2.5.2 @ 683d0ac2897412b0f971857d7571d70742c7799d
  chia/full_node/full_node.py
Labels: checkpoint_merge, Changed

#19223 update arch testing to python 3.12.7
  .github/workflows/test-install-scripts.yml
Labels: Changed, Tests

#19305 remove `ProofOfInclusion.as_program()`
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/data_layer_util.py
Labels: Changed, Exclude_Notes

#19036 mypy annotation for `test_dos.py`
  chia/_tests/core/full_node/test_performance.py
  chia/_tests/core/server/test_dos.py
  mypy-exclusions.txt
Labels: Changed, Tests

#19308 use chia_rs directly for foliage
  benchmarks/block_store.py
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/cmds/test_show.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/farmer_harvester/test_third_party_harvesters.py
  chia/_tests/util/benchmarks.py
  chia/_tests/util/network_protocol_data.py
  chia/_tests/util/test_full_block_utils.py
  chia/_tests/wallet/wallet_block_tools.py
  chia/consensus/block_creation.py
  chia/full_node/full_node_api.py
  chia/protocols/farmer_protocol.py
  chia/protocols/timelord_protocol.py
  chia/types/blockchain_format/foliage.py
  chia/types/unfinished_header_block.py
  chia/util/full_block_utils.py
Labels: Changed, Exclude_Notes

#19306 more datalayer rust transition prep
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_util.py
  chia/data_layer/data_store.py
Labels: Changed, CI

#19324 extract sibling hash and side methods as functions
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_util.py
Labels: Changed, Exclude_Notes

#19315 use chia_rs directly for weight proof
  chia/_tests/core/util/test_streamable.py
  chia/_tests/util/blockchain_mock.py
  chia/_tests/util/network_protocol_data.py
  chia/consensus/blockchain.py
  chia/consensus/blockchain_interface.py
  chia/full_node/block_store.py
  chia/full_node/weight_proof.py
  chia/types/weight_proof.py
Labels: Changed, Exclude_Notes

#19325 tweak datalayer test consistency
  chia/_tests/core/data_layer/test_data_rpc.py
Labels: Changed, Exclude_Notes

#19327 use chia_rs proof of inclusion for datalayer
  chia/_tests/core/data_layer/test_data_layer_util.py
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_util.py
  chia/data_layer/data_layer_wallet.py
  chia/data_layer/data_store.py
  chia/data_layer/util/merkle_blob.py
  poetry.lock
Labels: Changed, Exclude_Notes
