Repository Chia-Network/chia-blockchain, pull requests merged in 2025-06, with the labels that each got.

#19545 promote block-creation setting to user-facing
  benchmarks/mempool.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool_manager.py
  chia/rpc/full_node_rpc_api.py
  chia/util/initial-config.yaml
Labels: Changed

#19660 checkpoint: into main from release/2.5.4 @ 3901126c3d4b12cf7567f9ff33081d1ae99f626c
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/full_node/mempool_manager.py
Labels: checkpoint_merge, Changed

#19665 The `chia.consensus` module no longer depends upon `chia.wallet`.
  chia/_tests/core/test_farmer_harvester_rpc.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/cmds/init_funcs.py
  chia/cmds/keys_funcs.py
  chia/cmds/sim_funcs.py
  chia/consensus/coinbase.py
  chia/daemon/server.py
  chia/simulator/block_tools.py
  chia/simulator/simulator_test_tools.py
  chia/wallet/derive_keys.py
Labels: Changed, Exclude_Notes

#19667 Improve migration logging.
  chia/data_layer/data_store.py
Labels: Added, coverage-diff, DataLayer

#19668 [CHIA-2911] fix `test_db_graftroot` after chia_rs update
  chia/_tests/wallet/db_wallet/test_db_graftroot.py
Labels: ready_to_merge, Fixed, Tests

#19662 CHIA-2989 Insert DB values in CoinStore's new_block without creating coin records for them
  chia/full_node/coin_store.py
Labels: Changed

#19680 checkpoint: into main from release/2.5.4 @ 27bfa7e2a31af5736c84ecadf7954adc18eb086c
  chia/full_node/mempool_manager.py
Labels: checkpoint_merge, Changed

#19687 catchup: into long_lived/datalayer_merkle_blob from main @ 082f0592d879ff6e784e4ad9d4f7a9f0442206ca
  .github/workflows/build-windows-installer.yml
  benchmarks/mempool.py
  chia/_tests/core/full_node/stores/test_coin_store.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/mempool/test_mempool_fee_estimator.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/test_farmer_harvester_rpc.py
  chia/_tests/timelord/test_new_peak.py
  chia/_tests/wallet/cat_wallet/test_trades.py
  chia/_tests/wallet/db_wallet/test_db_graftroot.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/test_signer_protocol.py
  chia/_tests/wallet/test_wallet.py
  chia/_tests/wallet/vc_wallet/test_vc_wallet.py
  chia/cmds/init_funcs.py
  chia/cmds/keys_funcs.py
  chia/cmds/sim_funcs.py
  chia/consensus/coinbase.py
  chia/daemon/server.py
  chia/full_node/bitcoin_fee_estimator.py
  chia/full_node/coin_store.py
  chia/full_node/fee_tracker.py
  chia/full_node/full_node_api.py
  chia/full_node/mempool_manager.py
  chia/protocols/fee_estimate_store.py
  chia/rpc/full_node_rpc_api.py
  chia/simulator/block_tools.py
  chia/simulator/simulator_test_tools.py
  chia/util/initial-config.yaml
  chia/wallet/derive_keys.py
  chia/wallet/trade_manager.py
  chia/wallet/wallet_action_scope.py
  chia/wallet/wallet_state_manager.py
Labels: checkpoint_merge, Changed

#19681 fix(full_node): use f-string for log message when adding blocks
  chia/full_node/full_node.py
Labels: Changed, Exclude_Notes

#19685 Bump chia rs >=0.25, <0.26
  chia/_tests/weight_proof/test_weight_proof.py
  chia/cmds/show_funcs.py
  chia/consensus/block_header_validation.py
  chia/consensus/multiprocess_validation.py
  chia/farmer/farmer_api.py
  chia/full_node/full_node.py
  chia/full_node/full_node_api.py
  chia/full_node/weight_proof.py
  chia/simulator/block_tools.py
  chia/timelord/iters_from_block.py
  chia/types/blockchain_format/proof_of_space.py
  poetry.lock
  pyproject.toml
Labels: ready_to_merge, Changed

#19690 checkpoint: into main from release/2.5.4 @ 813370b49eab16d614ca3fc2062acc114a3944e3
  CHANGELOG.md
Labels: checkpoint_merge, Changed

#19663 Also log the VDF field being compacted
  chia/timelord/timelord.py
Labels: Changed, community-pr

#19630 Optimize add missing files
  chia/data_layer/data_store.py
  poetry.lock
Labels: Fixed, DataLayer

#19696 CHIA-3086 Simplify test_rollback
  chia/_tests/core/full_node/stores/test_coin_store.py
Labels: Changed

#19710 CHIA-3113 Simplify test_num_unspent
  chia/_tests/core/full_node/stores/test_coin_store.py
Labels: Changed

#19707 Extract time lock validation and move to `chia.consensus`.
  chia/_tests/clvm/coin_store.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/consensus/block_body_validation.py
  chia/consensus/check_time_locks.py
  chia/full_node/mempool_check_conditions.py
  chia/full_node/mempool_manager.py
Labels: Changed, Exclude_Notes

#19722 remove 'or descriptor' from `chia --passphrase-file` help
  chia/cmds/chia.py
Labels: Changed, Exclude_Notes

#19711 Refactor `BlockHeightMap` Creation to Decouple It from `Blockchain`
  benchmarks/block_ref.py
  chia/_tests/core/full_node/ram_db.py
  chia/_tests/core/full_node/stores/test_block_store.py
  chia/_tests/core/full_node/stores/test_coin_store.py
  chia/_tests/core/test_db_conversion.py
  chia/_tests/core/test_db_validation.py
  chia/_tests/util/blockchain.py
  chia/consensus/blockchain.py
  chia/full_node/full_node.py
Labels: Changed, Exclude_Notes

#19720 tach pre-commit
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  tach.toml
Labels: Changed, Exclude_Notes

#19716 [CHIA-2859] add ConsensusMode in tests to cover the new hard fork
  chia/_tests/conftest.py
  chia/_tests/core/full_node/test_conditions.py
  chia/consensus/condition_costs.py
  chia/simulator/block_tools.py
Labels: ready_to_merge, Changed, Tests

#19728 update requests to 2.32.4
  poetry.lock
Labels: Changed, Exclude_Notes

#19282 less response failure error consumption
  chia/cmds/plotnft_funcs.py
Labels: Fixed

#19759 more memoryview
  tools/analyze-chain.py
Labels: Changed, Exclude_Notes

#19760 CHIA-3217 Simplify SpendSim's farm_block
  chia/_tests/util/spend_sim.py
Labels: ready_to_merge, Changed

#19746 bump chia_rs to 0.26.0
  chia/_tests/conftest.py
  chia/_tests/core/consensus/test_pot_iterations.py
  chia/_tests/core/custom_types/test_proof_of_space.py
  chia/_tests/simulation/test_simulation.py
  chia/_tests/tools/test_run_block.py
  chia/_tests/util/constants.py
  chia/_tests/util/test_replace_str_to_bytes.py
  chia/consensus/default_constants.py
  chia/consensus/pot_iterations.py
  chia/simulator/block_tools.py
  chia/types/blockchain_format/proof_of_space.py
  poetry.lock
  pyproject.toml
Labels: ready_to_merge, Changed

#19714 require block generators to use canonical CLVM serialization after 3.0-hard fork
  chia/_tests/blockchain/test_blockchain.py
  chia/consensus/block_body_validation.py
  chia/util/errors.py
Labels: ready_to_merge, Changed

#19762 use poetry sync in install scripts
  Install.ps1
  install.sh
Labels: Changed, Exclude_Notes

#19749 CHIA-3207 Pass coin IDs from Blockchain's _reconsider_peak to CoinStore's new_block to avoid recomputing them
  benchmarks/coin_store.py
  chia/_tests/core/full_node/stores/test_coin_store.py
  chia/_tests/util/spend_sim.py
  chia/_tests/wallet/test_new_wallet_protocol.py
  chia/consensus/blockchain.py
  chia/full_node/coin_store.py
Labels: Changed

#19771 Fix plot size override
  chia/_tests/util/test_testnet_overrides.py
  chia/consensus/default_constants.py
  chia/server/start_harvester.py
  chia/util/initial-config.yaml
Labels: Fixed, Exclude_Notes

#19689 [CHIA-1315] Port (wallet) DataLayer endpoints to `@marshal`
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/wallet/db_wallet/test_dl_wallet.py
  chia/_tests/wallet/rpc/test_dl_wallet_rpc.py
  chia/cmds/dev/data.py
  chia/data_layer/data_layer.py
  chia/data_layer/data_layer_util.py
  chia/data_layer/data_layer_wallet.py
  chia/data_layer/dl_wallet_store.py
  chia/wallet/wallet_request_types.py
  chia/wallet/wallet_rpc_api.py
  chia/wallet/wallet_rpc_client.py
Labels: Changed

#19694 nft wallet job timeout reduced to 25 minutes
  chia/_tests/wallet/nft_wallet/config.py
Labels: Changed, Exclude_Notes
