Repository Chia-Network/chia-blockchain, pull requests merged in 2025-05, with the labels that each got.

#19523 log if computing cost fails during block creation
  chia/consensus/block_creation.py
Labels: Added

#19445 fix tl node peak sync (#19389)
  chia/_tests/timelord/test_new_peak.py
  chia/timelord/timelord_api.py
Labels: Fixed

#19546 back-port improved logging of timing in block validation
  chia/full_node/full_node.py
  chia/full_node/mempool_manager.py
Labels: Added

#19560 Optimize mempool's removals checking
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/full_node/mempool_manager.py
Labels: ready_to_merge, Changed

#19565 Improve dedup
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/full_node/mempool_manager.py
Labels: Changed

#19563 Enable Keccak for 2.5.4
  chia/simulator/block_tools.py
  chia/types/blockchain_format/program.py
  tools/analyze-chain.py
Labels: Added

#19567 use monotonic clock when timing functions in harvester
  chia/harvester/harvester_api.py
Labels: ready_to_merge, Fixed

#19569 amendment to Dedup patch #19565
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/full_node/mempool_manager.py
Labels: ready_to_merge, Changed

#19467 Improve the serialisation of AddressManager
  benchmarks/address_manager_store.py
  chia/_tests/core/full_node/test_address_manager.py
  chia/server/address_manager.py
  chia/server/address_manager_store.py
  chia/server/node_discovery.py
Labels: Changed

#19570 CHIA-1655: add test_add_unfinished_block_with_generator_refs
  chia/_tests/core/full_node/test_full_node.py
Labels: ready_to_merge, full_node, Fixed, Tests

#19586 checkpoint: into main from release/2.5.4 @ 5e0a0df94a261b84b6b940fd661c7be4b49f01a6
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/full_node/mempool_manager.py
Labels: ready_to_merge, checkpoint_merge, Changed

#19587 Move `augmented_chain.py` and `prev_transaction_block.py` to `chia/consensus`
  chia/_tests/blockchain/blockchain_test_utils.py
  chia/_tests/blockchain/test_augmented_chain.py
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/farmer_harvester/test_third_party_harvesters.py
  chia/_tests/util/full_sync.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/consensus/augmented_chain.py
  chia/consensus/block_creation.py
  chia/consensus/multiprocess_validation.py
  chia/consensus/prev_transaction_block.py
  chia/full_node/full_node.py
  chia/simulator/add_blocks_in_batches.py
  chia/simulator/full_node_simulator.py
  tools/test_full_sync.py
Labels: Changed, Cleanup

#19592 Update CODEOWNERS
  .github/CODEOWNERS
Labels: Changed, Exclude_Notes

#19595 additional test for is_clvm_canonical()
  chia/_tests/core/mempool/test_mempool_manager.py
Labels: ready_to_merge, Added

#19590 Remove the dependency of `chia.consensus` on the module `chia.types`
  chia/_tests/blockchain/test_blockchain_transactions.py
  chia/_tests/clvm/test_spend_sim.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  chia/_tests/core/test_full_node_rpc.py
  chia/_tests/pools/test_wallet_pool_store.py
  chia/_tests/util/spend_sim.py
  chia/_tests/wallet/test_singleton_lifecycle_fast.py
  chia/_tests/wallet/test_wallet.py
  chia/data_layer/data_layer_wallet.py
  chia/full_node/eligible_coin_spends.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/pools/pool_puzzles.py
  chia/pools/pool_wallet.py
  chia/types/coin_spend.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/estimate_fees.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/singleton.py
  chia/wallet/trade_manager.py
  chia/wallet/util/compute_additions.py
  chia/wallet/vc_wallet/vc_drivers.py
  chia/wallet/wallet_spend_bundle.py
  chia/wallet/wallet_state_manager.py
Labels: Changed

#19598 checkpoint: into main from release/2.5.4 @ baceeb841754e5079df58257c2b3d1ba25c4d4c0
  chia/full_node/full_node.py
Labels: ready_to_merge, checkpoint_merge, Changed

#19593 Tighten chia_rs version spec to `>=0.22, <0.23`
  poetry.lock
  pyproject.toml
Labels: Changed

#19585 CHIA-2862 Adapt test_check_removals_with_block_creation to cover both block generator creation versions
  chia/_tests/core/mempool/test_mempool_manager.py
Labels: Changed

#19588 Optimize add_missing_files
  chia/data_layer/data_store.py
Labels: Changed, DataLayer

#19601 checkpoint: into main from release/2.5.4 @ 78ccd6988581a387e943e67e88dea68e471838bf
  chia/harvester/harvester_api.py
Labels: ready_to_merge, checkpoint_merge, Changed

#19591 Tighten chia_rs version to `>=0.21, <0.22`
  poetry.lock
  pyproject.toml
Labels: Changed

#19611 reject transactions from the mempool, that take too long to validate
  chia/full_node/mempool_manager.py
Labels: Changed

#19608 More significant digits in `block_rate`
  chia/full_node/full_node.py
Labels: Changed, Exclude_Notes

#19582 Fix delta file to use new format in duplicate hash.
  chia/data_layer/download_data.py
Labels: Fixed, DataLayer

#19614 catchup: into long_lived/datalayer_merkle_blob from main @ e81b213b9a7bb2a46539d2ef5ed1ed1cd9271345
  .github/CODEOWNERS
  chia/_tests/blockchain/blockchain_test_utils.py
  chia/_tests/blockchain/test_augmented_chain.py
  chia/_tests/blockchain/test_blockchain.py
  chia/_tests/blockchain/test_blockchain_transactions.py
  chia/_tests/clvm/test_spend_sim.py
  chia/_tests/core/full_node/test_full_node.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  chia/_tests/core/test_full_node_rpc.py
  chia/_tests/farmer_harvester/test_third_party_harvesters.py
  chia/_tests/pools/test_wallet_pool_store.py
  chia/_tests/util/full_sync.py
  chia/_tests/util/spend_sim.py
  chia/_tests/util/test_ssl_check.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/_tests/wallet/test_singleton_lifecycle_fast.py
  chia/_tests/wallet/test_wallet.py
  chia/cmds/chia.py
  chia/cmds/dev/data.py
  chia/cmds/init_funcs.py
  chia/consensus/augmented_chain.py
  chia/consensus/block_creation.py
  chia/consensus/multiprocess_validation.py
  chia/consensus/prev_transaction_block.py
  chia/data_layer/data_layer_wallet.py
  chia/full_node/eligible_coin_spends.py
  chia/full_node/full_node.py
  chia/full_node/mempool.py
  chia/full_node/mempool_manager.py
  chia/harvester/harvester_api.py
  chia/pools/pool_puzzles.py
  chia/pools/pool_wallet.py
  chia/server/server.py
  chia/simulator/add_blocks_in_batches.py
  chia/simulator/block_tools.py
  chia/simulator/full_node_simulator.py
  chia/ssl/create_ssl.py
  chia/ssl/ssl_check.py
  chia/types/coin_spend.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/estimate_fees.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/singleton.py
  chia/wallet/trade_manager.py
  chia/wallet/util/compute_additions.py
  chia/wallet/vc_wallet/vc_drivers.py
  chia/wallet/wallet_spend_bundle.py
  chia/wallet/wallet_state_manager.py
  poetry.lock
  tools/test_full_sync.py
Labels: checkpoint_merge, Changed

#19600 Move `dump_keyring.py` to remove dep `chia.util` => `chia.cmds`
  chia/_tests/util/test_dump_keyring.py
  chia/cmds/dump_keyring.py
Labels: Fixed, Exclude_Notes

#19626 dont skip same peak if in unfinished cache
  chia/_tests/timelord/test_new_peak.py
  chia/timelord/timelord_api.py
Labels: timelord, Changed

#18013 CHIA-364 use upstream miniupnpc
  poetry.lock
  pyproject.toml
Labels: Changed

#19594 chore: fix some typos in comment
  chia/_tests/clvm/test_message_conditions.py
  chia/wallet/conditions.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
  chia/wallet/wsm_apis.py
Labels: Changed, community-pr

#19656 use `apt-get` instead of `apt`
  .github/workflows/test-install-scripts.yml
  build_scripts/build_linux_deb-2-installer.sh
Labels: Changed, CI, Cleanup

#19653 use `pyproject.toml` `[project]` section (again)
  poetry.lock
  pyproject.toml
Labels: Changed
