Repository Chia-Network/chia-blockchain, pull requests merged in 2025-08, with the labels that each got.

#19880 Simplify `BlockStore`
  chia/_tests/blockchain/blockchain_test_utils.py
  chia/_tests/blockchain/test_blockchain.py
  chia/consensus/blockchain.py
  chia/full_node/block_store.py
  chia/full_node/full_node_api.py
  chia/simulator/full_node_simulator.py
Labels: Changed

#19889 fast-forward spends can be treated as regular spends
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  chia/full_node/mempool_manager.py
Labels: Fixed

#19887 miniupnpc 3.13 files in lock
  poetry.lock
Labels: Changed, Exclude_Notes

#19891 Bump chia rs 0.28
  chia/_tests/clvm/coin_store.py
  chia/_tests/core/full_node/test_generator_tools.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/generator/test_rom.py
  chia/cmds/show_funcs.py
  chia/consensus/block_body_validation.py
  chia/consensus/generator_tools.py
  chia/full_node/full_node_rpc_api.py
  chia/full_node/mempool_manager.py
  chia/full_node/subscriptions.py
  poetry.lock
  pyproject.toml
Labels: Changed

#19898 update nodeenv to 1.9.1
  poetry.lock
Labels: Changed, Exclude_Notes

#19897 update pywin32 to 311
  poetry.lock
Labels: Changed, Exclude_Notes

#19860 [CHIA-3419] Remove `TransactionRecord.*_json_dict_convenience`
  chia/_tests/cmds/cmd_test_utils.py
  chia/_tests/cmds/wallet/test_consts.py
  chia/_tests/cmds/wallet/test_did.py
  chia/_tests/cmds/wallet/test_wallet.py
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/test_transaction_store.py
  chia/_tests/wallet/test_wallet.py
  chia/cmds/wallet_funcs.py
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
  chia/wallet/transaction_record.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_request_types.py
  chia/wallet/wallet_rpc_api.py
  chia/wallet/wallet_rpc_client.py
  chia/wallet/wallet_state_manager.py
  chia/wallet/wallet_transaction_store.py
Labels: Changed

#19774 [CHIA-3294] Port `get_wallet_balance(s)` to `@marshal`
  chia/_tests/cmds/wallet/test_wallet.py
  chia/_tests/environments/wallet.py
  chia/_tests/pools/test_pool_rpc.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/cmds/plotnft_funcs.py
  chia/cmds/wallet_funcs.py
  chia/wallet/wallet_request_types.py
  chia/wallet/wallet_rpc_api.py
  chia/wallet/wallet_rpc_client.py
Labels: Changed

#19896 Set the correct commit author for mozilla cert workflow
  .github/workflows/update-mozilla-ca-cert.yaml
Labels: Changed, CI, Exclude_Notes

#19895 Simplify dependencies wrt `chia.server`
  build_scripts/pyinstaller.spec
  chia/_tests/cmds/test_farm_cmd.py
  chia/_tests/conftest.py
  chia/_tests/core/data_layer/test_data_rpc.py
  chia/_tests/core/server/test_server.py
  chia/_tests/core/services/test_services.py
  chia/_tests/core/test_crawler.py
  chia/_tests/farmer_harvester/test_farmer.py
  chia/_tests/farmer_harvester/test_farmer_harvester.py
  chia/_tests/farmer_harvester/test_filter_prefix_bits.py
  chia/_tests/farmer_harvester/test_third_party_harvesters.py
  chia/_tests/fee_estimation/test_fee_estimation_rpc.py
  chia/_tests/plot_sync/test_plot_sync.py
  chia/_tests/plot_sync/test_sync_simulated.py
  chia/_tests/plot_sync/util.py
  chia/_tests/pools/test_pool_rpc.py
  chia/_tests/timelord/test_new_peak.py
  chia/_tests/timelord/test_timelord.py
  chia/_tests/util/setup_nodes.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/test_new_wallet_protocol.py
  chia/data_layer/data_layer_service.py
  chia/data_layer/start_data_layer.py
  chia/farmer/farmer_service.py
  chia/farmer/start_farmer.py
  chia/full_node/full_node_service.py
  chia/full_node/start_full_node.py
  chia/harvester/harvester_service.py
  chia/harvester/start_harvester.py
  chia/introducer/introducer_service.py
  chia/introducer/start_introducer.py
  chia/seeder/crawler_service.py
  chia/seeder/start_crawler.py
  chia/server/aliases.py
  chia/simulator/setup_services.py
  chia/timelord/start_timelord.py
  chia/timelord/timelord_service.py
  chia/wallet/start_wallet.py
  chia/wallet/wallet_service.py
  pyproject.toml
  tach.toml
Labels: Changed, Exclude_Notes

#19842 [CHIA-3391] Port `test_nft*offers.py` to be parametrized with R-CATs
  chia/_tests/wallet/nft_wallet/test_nft_1_offers.py
  chia/_tests/wallet/nft_wallet/test_nft_offers.py
Labels: Changed, Tests

#19893 Update Managed Files
  .github/dependabot.yml
Labels: Changed, Exclude_Notes

#19937 use github hosted linux arm runners
  .github/workflows/build-linux-installer-deb.yml
  .github/workflows/check_wheel_availability.yaml
  .github/workflows/pre-commit.yml
  .github/workflows/test-install-scripts.yml
  .github/workflows/upload-pypi-source.yml
Labels: Changed, Exclude_Notes

#19935 update precommit shfmt
  .pre-commit-config.yaml
Labels: Changed, Exclude_Notes

#19936 update precommit pre-commit-hooks
  .pre-commit-config.yaml
Labels: Changed, Exclude_Notes

#19943 Update Managed Files
  .github/workflows/check-commit-signing.yml
  .github/workflows/dependency-review.yml
Labels: Changed, CI, Exclude_Notes

#19807 Make CI workflows fork-friendly
  .github/workflows/benchmarks.yml
  .github/workflows/build-macos-installers.yml
  .github/workflows/check_wheel_availability.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependency-review.yml
  .github/workflows/pre-commit.yml
  .github/workflows/reflow-publish-installer.yml
  .github/workflows/require-labels.yml
  .github/workflows/stale-issue.yml
  .github/workflows/start-release.yml
  .github/workflows/start-sync-test.yml
  .github/workflows/test-install-scripts.yml
  .github/workflows/test.yml
  .github/workflows/trigger-docker-dev.yml
  .github/workflows/trigger-docker-main.yml
  .github/workflows/upload-pypi-source.yml
Labels: Changed, Exclude_Notes, community-pr

#19965 [CHIA-3601] Port `spend_clawback_coins` to `@marshal`
  chia/_tests/cmds/wallet/test_wallet.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/test_wallet.py
  chia/cmds/wallet_funcs.py
  chia/wallet/wallet_request_types.py
  chia/wallet/wallet_rpc_api.py
  chia/wallet/wallet_rpc_client.py
Labels: ready_to_merge, Changed

#19962 [CHIA-3654] previous transaction block height in BlockTools
  chia/simulator/block_tools.py
Labels: ready_to_merge, Changed, Tests, Exclude_Notes

#19938 [CHIA-3593] New solver service
  chia/_tests/conftest.py
  chia/_tests/farmer_harvester/test_farmer_harvester.py
  chia/_tests/harvester/__init__.py
  chia/_tests/harvester/config.py
  chia/_tests/harvester/test_harvester_api.py
  chia/_tests/plotting/test_prover.py
  chia/_tests/solver/__init__.py
  chia/_tests/solver/config.py
  chia/_tests/solver/test_solver_service.py
  chia/_tests/util/build_network_protocol_files.py
  chia/_tests/util/network_protocol_data.py
  chia/_tests/util/protocol_messages_bytes-v1.0
  chia/_tests/util/protocol_messages_json.py
  chia/_tests/util/setup_nodes.py
  chia/_tests/util/test_network_protocol_files.py
  chia/_tests/util/test_network_protocol_json.py
  chia/_tests/util/test_network_protocol_test.py
  chia/apis.py
  chia/cmds/chia.py
  chia/cmds/cmds_util.py
  chia/cmds/rpc.py
  chia/cmds/solver.py
  chia/cmds/solver_funcs.py
  chia/consensus/pos_quality.py
  chia/farmer/farmer.py
  chia/farmer/farmer_api.py
  chia/harvester/harvester_api.py
  chia/plotting/check_plots.py
  chia/plotting/prover.py
  chia/protocols/harvester_protocol.py
  chia/protocols/outbound_message.py
  chia/protocols/protocol_message_types.py
  chia/protocols/shared_protocol.py
  chia/protocols/solver_protocol.py
  chia/server/server.py
  chia/simulator/setup_services.py
  chia/solver/__init__.py
  chia/solver/solver.py
  chia/solver/solver_api.py
  chia/solver/solver_rpc_api.py
  chia/solver/solver_rpc_client.py
  chia/solver/solver_service.py
  chia/solver/start_solver.py
  chia/ssl/create_ssl.py
  chia/util/initial-config.yaml
  chia/util/service_groups.py
  pyproject.toml
Labels: Blockchain team, ready_to_merge, harvester, Changed

#19984 [CHIA-3659] ignore unreasonably small v2 plots
  chia/plotting/manager.py
Labels: ready_to_merge, Added

#19955 checkpoint: into main from release/2.5.5 @ b1cc0a5b84a9c517ad55da2ce87e5378dcdccb32
  chia/_tests/core/mempool/test_singleton_fast_forward.py
  chia/full_node/mempool_manager.py
Labels: checkpoint_merge, Changed

#19983 [CHIA-3703] Add Enum support to streamable
  chia/_tests/core/util/test_streamable.py
  chia/util/streamable.py
Labels: Added, coverage-diff
