Repository Chia-Network/chia-blockchain, pull requests merged in 2025-07, with the labels that each got.

#19768 [CHIA-3205] unify test constants on the ones used by `BlockTools`
  chia/_tests/util/constants.py
Labels: Changed, Tests

#19769 Plot v2 quality string
  chia/_tests/core/custom_types/test_proof_of_space.py
  chia/_tests/weight_proof/test_weight_proof.py
  chia/consensus/default_constants.py
  chia/full_node/full_node_rpc_api.py
  chia/harvester/harvester_api.py
  chia/simulator/block_tools.py
  chia/types/blockchain_format/proof_of_space.py
Labels: ready_to_merge, Changed, Tests

#19773 [CHIA-2639] drop spends we can't serialize rather than the whole request
  chia/_tests/core/full_node/test_generator_tools.py
  chia/full_node/mempool_check_conditions.py
  poetry.lock
  pyproject.toml
Labels: Fixed

#19708 [CHIA-1311] Port DID RPCs to `@marshal` decorator
  chia/_tests/cmds/wallet/test_did.py
  chia/_tests/wallet/did_wallet/test_did.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/cmds/wallet_funcs.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/wallet_request_types.py
  chia/wallet/wallet_rpc_api.py
  chia/wallet/wallet_rpc_client.py
Labels: ready_to_merge, Changed

#19796 update testnet overrides in wallet
  chia/server/start_wallet.py
Labels: Fixed, Exclude_Notes

#19798 `BlockHeightMapProtocol`
  benchmarks/block_ref.py
  chia/_tests/core/full_node/ram_db.py
  chia/_tests/core/full_node/stores/test_block_store.py
  chia/_tests/core/full_node/stores/test_coin_store.py
  chia/_tests/core/full_node/test_block_height_map.py
  chia/_tests/core/test_db_conversion.py
  chia/_tests/core/test_db_validation.py
  chia/_tests/util/blockchain.py
  chia/consensus/block_height_map.py
  chia/consensus/block_height_map_protocol.py
  chia/consensus/blockchain.py
  chia/full_node/full_node.py
Labels: Changed, Exclude_Notes

#19782 DL Code Cleanup
  chia/_tests/core/data_layer/test_data_store.py
  chia/data_layer/data_layer_util.py
  chia/data_layer/data_store.py
Labels: Fixed, Cleanup, DataLayer

#19803 Use chia_rs in API instead of clvm
  chia/_tests/core/full_node/test_generator_tools.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/test_cost_calculation.py
  chia/_tests/core/test_full_node_rpc.py
  chia/_tests/util/spend_sim.py
  chia/full_node/full_node_api.py
  chia/full_node/full_node_rpc_api.py
  chia/full_node/full_node_rpc_client.py
  chia/full_node/mempool_check_conditions.py
  chia/types/coin_spend.py
Labels: ready_to_merge, Changed

#19797 DL Check root hash in missing hashes.
  chia/data_layer/data_store.py
  poetry.lock
Labels: Fixed, DataLayer

#19806 recover chiabip tgz in poetry lock
  poetry.lock
Labels: Fixed, Exclude_Notes

#19818 [CHIA-3388] Port `test_cat_endpoints` in `test_wallet_rpc.py` to `WalletTestFramework` and R-CATs
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/wallet/cat_wallet/r_cat_wallet.py
Labels: Fixed

#19819 checkpoint: into main from release/2.5.5 @ 96aeaf3e685f51a3ef9901228005109fc97687ed
  poetry.lock
  pyproject.toml
Labels: checkpoint_merge, Changed

#19770 [CHIA-3293] Port `get_wallets` to `@marshal` decorator
  chia/_tests/cmds/cmd_test_utils.py
  chia/_tests/cmds/wallet/test_vcs.py
  chia/_tests/cmds/wallet/test_wallet.py
  chia/_tests/pools/test_pool_cmdline.py
  chia/_tests/pools/test_pool_rpc.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/vc_wallet/test_vc_wallet.py
  chia/cmds/plotnft_funcs.py
  chia/cmds/wallet_funcs.py
  chia/wallet/wallet_request_types.py
  chia/wallet/wallet_rpc_api.py
  chia/wallet/wallet_rpc_client.py
Labels: Changed

#19834 use logical core count for batch size when lazy building dl cache
  chia/data_layer/data_store.py
Labels: Changed, Exclude_Notes

#19833 tidy
  chia/_tests/conftest.py
  chia/_tests/core/data_layer/test_data_store.py
Labels: Changed, Exclude_Notes

#19767 [CHIA-3251] Delete DID recovery endpoints
  chia/_tests/wallet/did_wallet/test_did.py
  chia/_tests/wallet/nft_wallet/test_nft_wallet.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/vc_wallet/test_vc_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet_request_types.py
  chia/wallet/wallet_rpc_api.py
  chia/wallet/wallet_rpc_client.py
Labels: Changed

#19844 Revert "update zstd to 1.5.7.2"
  poetry.lock
Labels: Changed, Exclude_Notes

#19838 use now allowed randbytes and other helpers
  benchmarks/address_manager_store.py
  benchmarks/block_store.py
  benchmarks/streamable.py
  chia/_tests/core/custom_types/test_spend_bundle.py
  chia/_tests/core/data_layer/test_data_layer_util.py
  chia/_tests/core/data_layer/test_data_store.py
  chia/_tests/core/full_node/stores/test_block_store.py
  chia/_tests/core/mempool/test_mempool.py
  chia/_tests/core/test_db_conversion.py
  chia/_tests/core/test_db_validation.py
  chia/_tests/core/test_merkle_set.py
  chia/_tests/util/benchmarks.py
  chia/_tests/util/test_full_block_utils.py
Labels: Changed, Exclude_Notes

#19820 integrate `PLOT_V1_PHASE_OUT` constant
  chia/_tests/core/consensus/test_pot_iterations.py
  chia/_tests/wallet/sync/test_wallet_sync.py
  chia/consensus/pot_iterations.py
  chia/full_node/full_node.py
Labels: Changed

#19858 checkpoint: into main from release/2.5.5 @ 96d1356b6579c0a4dd78273928b55dfa1e10725d
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/wallet/cat_wallet/r_cat_wallet.py
Labels: checkpoint_merge, Changed

#19846 [CHIA-3418] Change `TransactionRecord` to use dict instead of list of tuples for memos
  chia/_tests/cmds/cmd_test_utils.py
  chia/_tests/cmds/wallet/test_consts.py
  chia/_tests/cmds/wallet/test_wallet.py
  chia/_tests/wallet/cat_wallet/test_cat_wallet.py
  chia/_tests/wallet/rpc/test_wallet_rpc.py
  chia/_tests/wallet/test_transaction_store.py
  chia/_tests/wallet/test_wallet.py
  chia/data_layer/data_layer_wallet.py
  chia/pools/pool_wallet.py
  chia/util/streamable.py
  chia/wallet/cat_wallet/cat_wallet.py
  chia/wallet/did_wallet/did_wallet.py
  chia/wallet/nft_wallet/nft_wallet.py
  chia/wallet/trade_manager.py
  chia/wallet/transaction_record.py
  chia/wallet/vc_wallet/cr_cat_wallet.py
  chia/wallet/vc_wallet/vc_wallet.py
  chia/wallet/wallet.py
  chia/wallet/wallet_rpc_api.py
  chia/wallet/wallet_state_manager.py
Labels: Changed

#19830 [CHIA-3389] Port `test_offer_endpoints` in to `WalletTestFramework` and parametrize for R-CATs
  chia/_tests/wallet/rpc/test_wallet_rpc.py
Labels: Changed, Tests

#19865 CHIA-3484 Handle items that spend an older ff version when newer lineage exists
  chia/_tests/core/mempool/test_mempool_manager.py
  chia/full_node/mempool_manager.py
Labels: Changed

#19885 update cryptography to 45.0.5
  poetry.lock
  pyproject.toml
Labels: Changed

#19879 chiapos 2.0.11
  poetry.lock
Labels: Changed, Exclude_Notes
